### ISSUE TITLE
rows.Close(): panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by monkey92t** [ClickHouse/clickhouse-go#1019]
code:

```go
// table does not exist
query := "select * from xxxxxxx where id = ?"
rows, err := conn.Query(ctx, query, args...)
defer func() {
	if rows != nil {
		_ = rows.Close()
	}
}()
```

log:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x19419af]

goroutine 4036 [running]:
github.com/ClickHouse/clickhouse-go/v2.(*rows).Close(0x0)
        /data/gopath/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.9.3/clickhouse_rows.go:101 +0x2f
db.(*ClickHouse).query.func1()
        /data/ver/db/clickhouse.go:83 +0x2b

* Client version: v2.9.3
* Language version: go 1.20
* OS: linux centos 7

**Comment by jkaflik** [comment]
Fixed in recent versions
