### ISSUE TITLE
I have 4 nodes,but most of client's connector is in the first node

### ISSUE THREAD

**Issue by lichehuo** [ClickHouse/clickhouse-go#1027]
### Describe the bug
this is my config
urls= ["ip1:9000","ip2:9000","ip3:9000","ip4:9000"]
There is 200M data writen into clickhouse cluster every second .
most of connector is in ip1
a little connector is in other 3 ip
### Expected behaviour
4 node has the same connector
### Code example
```
conn := clickhouse.OpenDB(&clickhouse.Options{
		Addr: ["ip1:9000","ip2:9000","ip3:9000","ip4:9000"],
		Auth: clickhouse.Auth{
			Database: db,
			Username: user,
			Password: pwd,
		},
		Settings: clickhouse.Settings{
			"max_execution_time": 60,
		},
		DialTimeout: 5 * time.Second,
		Compression: &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		},
		Debug: debug,
	})
	conn.SetMaxIdleConns(50)
	conn.SetMaxOpenConns(100)
	conn.SetConnMaxLifetime(time.Hour * time.Duration(1))
```
#### Environment
* Client version:
v2.10.1
* Language version: 
go 1.18
* OS: 
Linux sirius 4.18.20-041820-generic #201812030624 SMP Mon Dec 3 11:25:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Interface: ClickHouse API / database/sql compatible driver

#### ClickHouse server
* ClickHouse Server version:
22.11.6.44
* ClickHouse Server non-default settings, if any:
`CREATE TABLE db.tb on cluster1
(
    `timestamp` DateTime,
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/db/tb', '{replica}')
PARTITION BY toYYYYMMDD(timestamp)
TTL timestamp + toIntervalDay(30)
SETTINGS enable_mixed_granularity_parts = 1, use_minimalistic_part_header_in_zookeeper = 1, index_granularity = 8192

CREATE TABLE db.tb_dist on cluster1
(
    `timestamp` DateTime,
)
ENGINE = Distributed('cluster_1', 'db', 'tb', rand())
` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by jkaflik** [comment]
Hi @lichehuo 

By default, clickhouse-go chooses first live server. There is no connection sequence in a DB connector lifetime. 

Please see docs:

> connection_open_strategy - round_robin/in_order (default in_order).
> - round_robin - choose a round-robin server from the set
> - in_order - first live server is chosen in specified order

https://github.com/ClickHouse/clickhouse-go/blob/da1c1d302f928a231e54b7b292897c2ad169b06e/README.md#L152

I recommend you use `round_robin` option so your connections are more balanced. In case of any further questions, feel free to comment.
