### ISSUE TITLE
v2  Memory usage is twice that of v1

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/clickhouse-go#1030]
version: v2.10.1
v2  Memory usage is twice that of v1
Can memory usage be optimized?

**Comment by jkaflik** [comment]
Currently we don't plan to optimise memory usage in clickhouse-go. If you want to get more performance optimised client, I advise to use https://github.com/ClickHouse/ch-go

**Comment by intfish123** [comment]
Ok
