### ISSUE TITLE
Impelement Query Server Time Callback in Progress Callback

### ISSUE THREAD

**Issue by Zalgo2462** [ClickHouse/clickhouse-go#1038]
**Is your feature request related to a problem? Please describe.**

I need to run benchmarks for the queries used by my application.
I am determining whether to go forward with Clickhouse or another database for the backend of my Go application. 
I am frustrated that I cannot obtain the execution time of queries using the Go driver.

**Describe the solution you'd like**

I would have liked to use the built in server execution time info provided in the query progress packets. 
The cpp code over at https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/Progress.cpp#L25 shows how this could be accomplished. 

**Describe alternatives you've considered**

 I am currently planning on extracting the queries along with their parameters and running them through clickhouse-benchmark.

**Comment by jkaflik** [comment]
Hi @Zalgo2462 

There is an example how to use progress tracking feature in Go driver:
https://github.com/ClickHouse/clickhouse-go/blob/b3a51de65e8303852e4350b262185b95e3ad47dc/examples/clickhouse_api/progress.go#L35

Elapsed time was just recently added into ClickHouse. We have to implement it into the driver as well: https://github.com/ClickHouse/clickhouse-go/pull/1039
