### ISSUE TITLE
Can't handle NaN value

### ISSUE THREAD

**Issue by frkntplglu** [ClickHouse/clickhouse-go#1043]
### Describe the bug
A float64 type field breaks json when it comes from database as NaN.

`json: unsupported value: NaN`

I tried creating a custom type like this but it did not work. It is said that NullableFloat is not supported.
`func (nf NullableFloat64) MarshalJSON() ([]byte, error) {
	if math.IsNaN(float64(nf)) {
		return []byte("null"), nil
	}
	return json.Marshal(float64(nf))
}`
### Steps to reproduce
1.
2.
3.

### Expected behaviour
I am expecting that if any field is NaN it should be interpreted as null like it is in HTTP Interface of clickhouse.

### Code example
```go
```
#### Environment
* Client version: v2
* Language version: v1.18
* OS: Macos
* Interface: ClickHouse API 

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by jkaflik** [comment]
Hi @frkntplglu 

Can you provide code that reproduces this issue? Thanks

**Comment by frkntplglu** [comment]
> Hi @frkntplglu
> 
> Can you provide code that reproduces this issue? Thanks

Hi, when I use avg in my query, if the result of the avg is zero, it returns NaN however I am expecting for returning zero or interpret this as Nil in Go. Is it clear now?

**Comment by jkaflik** [comment]
Ok. Basically, `encoding/json` cannot handle Go float NaN representation.
The work-around could be implementing custom float type for this use case:

```go
package issues

import (
	"context"
	"fmt"
	"github.com/ClickHouse/clickhouse-go/v2"
	clickhouse_tests "github.com/ClickHouse/clickhouse-go/v2/tests"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"math"
	"testing"
)

type nAnFloat64 float64

func (f *nAnFloat64) Scan(src any) error {
	if t, ok := src.(float64); ok {
		if math.IsNaN(t) {
			t = 0
		}

		*f = nAnFloat64(t)
		return nil
	}
	return fmt.Errorf("cannot scan %T into nAnFloat64", src)
}

type customFloat64 float64

func Test1043(t *testing.T) {
	var (
		conn, err = clickhouse_tests.GetConnection("issues", clickhouse.Settings{
			"max_execution_time": 60,
		}, nil, &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		})
	)
	ctx := context.Background()
	require.NoError(t, err)
	const ddl = `
		CREATE TABLE test_1043 (
			Col1 Float64
		) Engine MergeTree() ORDER BY tuple()
		`
	defer func() {
		conn.Exec(ctx, "DROP TABLE IF EXISTS test_1043")
	}()
	require.NoError(t, conn.Exec(ctx, ddl))

	row := conn.QueryRow(ctx, "SELECT avg(Col1) FROM test_1043")
	require.NoError(t, row.Err())

	var avg nAnFloat64
	err = row.Scan(&avg)

	assert.Zero(t, avg)
}
```

In this case, `nAnFloat64` will fall back to zero in the case of NaN value.
