### ISSUE TITLE
Acquire connection in batch only when needed

### ISSUE THREAD

**Issue by EpicStep** [ClickHouse/clickhouse-go#1047]
Hi, now batch requires an acquired connection at the all time before `Send()`, but I think for `Append()` operation we doesn't need to keep connection. It would be good to have a function that would return the connection to the pool (in order not to break backward compatibility, in v3 it would be nice to see option in batch constructor). Also when calling `Send()` or first `Flush()` a connection from pool need to be acquired.

If you accept this feature request I can take and develop it.

**Comment by jkaflik** [comment]
Hi @EpicStep 

Thanks for raising this idea. Naturally, all contributions are welcomed.
