### ISSUE TITLE
clickhouse execution SQL is wrong, but sdk returns empty data

### ISSUE THREAD

**Issue by zsdyx** [ClickHouse/clickhouse-go#1064]
### Describe the bug
Use a native interface for requests，clickhouse execution SQL is wrong, but sdk returns empty data.If you can see some error and warn logs when you open debug in sdk.

### Expected behaviour
Should return errors

### Code example
```go
startTime := time.Now()
	var cancel context.CancelFunc
	ctx, cancel = context.WithTimeout(ctx, time.Duration(chc.maxExeTime)*time.Second)
	defer cancel()
	rows, err := chc.conn.Query(clickhouse.Context(ctx, clickhouse.WithSpan(
		trace.NewSpanContext(trace.SpanContextConfig{
			SpanID:  trace.SpanContextFromContext(ctx).SpanID(),
			TraceID: trace.SpanContextFromContext(ctx).TraceID(),
		}),
	)), sql)
	elapsed := time.Since(startTime)
	tracer.GetLogger(ctx).Infof("Query clickhouse, cost time: %s", elapsed.String())
	if err != nil {
		if ctx.Err() == context.DeadlineExceeded {
			log.Panic("Query Clickhouse client timeout")
			return nil
		}
		log.Panicf("Query Clickhouse client err, err: %s", err.Error())
		return nil
	}
	if rows.Err() != nil {
		log.Panicf("Query Clickhouse client rows err: %s", rows.Err().Error())
		return nil
	}
```
#### Environment
* Client version:
* Language version:
* OS:
* Interface: ClickHouse API 

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by jkaflik** [comment]
Hi @zsdyx 

Can you share (it can be anonymized) SQL query you execute? I cannot reproduce your issue. With obvious wrong SQL, the client returns an error back from the `Query` function.
