### ISSUE TITLE
date32 is bigger when using clickhouse-go

### ISSUE THREAD

**Issue by Inasayang** [ClickHouse/clickhouse-go#1067]
ddl
```sql
CREATE TABLE test
(
    `a` String,
    `b` Date32
)
ENGINE = MergeTree
ORDER BY a
SETTINGS index_granularity = 8192;
```

```go
func TestDate32(t *testing.T) {
	conn := NewConn()
	batch, err := conn.PrepareBatch(context.Background(), fmt.Sprintf("%s%s", `INSERT INTO `, `test`))
	if err != nil {
		t.Fatal(err)
	}
	if err := batch.Append(
		`aaa`,
		`2000-01-01`,
	); err != nil {
		t.Fatal(err)
	}
	if err := batch.Send(); err != nil {
		t.Fatal(err)
	}
}
```

result
![image](https://github.com/ClickHouse/ClickHouse/assets/30060632/97a5ca5b-5b7b-465b-9a0a-8053a5c333a8)
There's a 45-year difference. I'm not sure what the problem is? I don't think it's the time zone.

But when executed in the terminal, it works fine
![image](https://github.com/ClickHouse/ClickHouse/assets/30060632/80d9f6b8-db96-47aa-8d39-38effe3f511f)

**Comment by jkaflik** [comment]
Hi @Inasayang
Thanks for reporting this. Let's continue in https://github.com/ClickHouse/clickhouse-go/issues/1066 - it's related to native format handling.

**Comment by jkaflik** [comment]
This will be fixed by https://github.com/ClickHouse/ch-go/pull/320
