### ISSUE TITLE
batch.Append with boolean fields in map representing JSON column fails

### ISSUE THREAD

**Issue by ilyabreev** [ClickHouse/clickhouse-go#1072]
### Steps to reproduce
1. Call `batch.Append` or `batch.AppendStructure` passing json map with boolean field
2. Call it one more time with same data
3. Fail with error "type mismatch in column expected Bool but got Boolean"

### Expected behaviour

Data appended to batch

It seems like error is in this line: 
https://github.com/ClickHouse/clickhouse-go/blob/main/lib/column/json.go#L43

If I replace `Bool` with `Boolean` it works like a charm.

**Comment by jkaflik** [comment]
@ilyabreev, thanks for reporting this. This is an odd bug. Thanks for your investigation. The fix is on the way!
