### ISSUE TITLE
More control over connection's buffers

### ISSUE THREAD

**Issue by cergxx** [ClickHouse/clickhouse-go#1086]
In my project I have a pool of long-living connections to ClickHouse.
Each of them holds a buffer `clickhouse.connect.buffer`, which leads to overall big memory usage

I would like to have more control over these buffers – to be able to drop them without closing the connection

Possible solutions:
Add an option to `clickhouse.Options` like `FreeBuffersOnRelease`, which would trigger drop of the `buffer` on every connection release
(Replace `b.Buf = b.Buf[:0]` with `b.Buf = nil`)

**Comment by jkaflik** [comment]
Hi @cergxx 

Would you like to submit a PR with change?

**Comment by cergxx** [comment]
> Would you like to submit a PR with change?

Yes, I would
