### ISSUE TITLE
Is streaming query result supported?

### ISSUE THREAD

**Issue by thilak009** [ClickHouse/clickhouse-go#1088]
related issue https://github.com/ClickHouse/clickhouse-go/issues/533 which was closed by author but i haven't been able to find anything around streaming query result instead of getting entire result at once as the data is huge in size and i can't load all of that into my application memory

So wanted to know if streaming is supported in any interface type (http or native)

I see that http streaming is in plan for v3 https://github.com/ClickHouse/clickhouse-go/issues/652, not sure about the native interface

Pardon if it is already supported and i haven't been able to figure out, haven't found anything related to streaming result in docs

**Comment by jkaflik** [comment]
@thilak009 for ClickHouse native protocol streams data chunks in [blocks](https://clickhouse.com/docs/en/development/architecture#block) and this is how `clickhouse-go` implements it.
Also, it has an abstraction that allows you to iterate over rows on top of [ClickHouse columnar](https://clickhouse.com/docs/en/faq/general/columnar-database) native format. If you want to optimise it, either you lower blocks size or switch to driver that does not have this overhead: https://github.com/ClickHouse/ch-go

There are two ways you can influence memory sizing:
- tweak around https://clickhouse.com/docs/en/operations/settings/settings#setting-max_block_size setting. You can lower it, so the client receives less data.
- in `clickhouse-go` change default `clickhouse.Options.BlockBufferSize` to 1. Default it's 2. This value is the number of blocks buffered per query.
