### ISSUE TITLE
The timeout exception did not return

### ISSUE THREAD

**Issue by zsdyx** [ClickHouse/clickhouse-go#1097]
### Describe the bug
clickhouse has been out of time, but sdk does not return timeout error information

### Expected behaviour
the timeout exception did not return

### Code example
```go
func (chc CHClient) Query(ctx context.Context, sql string, columnMapping map[string]string, withTotal bool) []byte {
	startTime := time.Now()
	rows, err := chc.conn.Query(clickhouse.Context(ctx, clickhouse.WithSpan(
		trace.NewSpanContext(trace.SpanContextConfig{
			SpanID:  trace.SpanContextFromContext(ctx).SpanID(),
			TraceID: trace.SpanContextFromContext(ctx).TraceID(),
		}),
	)), sql)
	elapsed := time.Since(startTime)
	tracer.GetLogger(ctx).Infof("Query clickhouse, cost time: %s", elapsed.String())
	if err != nil {
		log.Panicf("Query Clickhouse client err, err: %s", err.Error())
		return nil
	}
	var (
		columnNames = rows.Columns()
		columnTypes = rows.ColumnTypes()
		initVars    = make([]reflect.Type, len(columnTypes))
	)
	for i := range columnTypes {
		initVars[i] = columnTypes[i].ScanType()
	}
	rst := make([]map[string]interface{}, 0)
	for rows.Next() {
		if rows.Err() != nil {
			log.Panicf("Query Clickhouse client rows err: %s", rows.Err().Error())
			return nil
		}
		vars := make([]interface{}, len(columnTypes))
		for i := range initVars {
			vars[i] = reflect.New(initVars[i]).Interface()
		}

		if err := rows.Scan(vars...); err != nil {
			log.Panicf("Scan Clickhouse client err, err: %s", err.Error())
			return nil
		}
		tmp := make(map[string]interface{}, 1)
		for i, val := range vars {
			tmp[columnNames[i]] = val
		}
		rst = append(rst, tmp)
	}
	json := jsoniter.ConfigCompatibleWithStandardLibrary
	rst = chc.formatColumn(rst, columnMapping)
	formatRst := &CHResponse{}
	formatRst.Data = rst
	formatRst.Page = 1
	formatRst.PageSize = len(rst)

	if withTotal {
		totals := make([]interface{}, len(columnTypes))
		for i := range initVars {
			totals[i] = reflect.New(initVars[i]).Interface()
		}
		err = rows.Totals(totals...)
		if err != nil {
			log.Panicf("Scan Clickhouse client err, err: %s", err.Error())
			return nil
		}
		totalsMap := make(map[string]interface{}, 1)
		for i, val := range totals {
			totalsMap[columnNames[i]] = val
		}
		totalRst := make([]map[string]interface{}, 0)
		totalRst = append(totalRst, totalsMap)
		totalRst = chc.formatColumn(totalRst, columnMapping)
		formatRst.Totals = totalRst[0]
	}
	jsRst, marshalErr := json.Marshal(&formatRst)
	if marshalErr != nil {
		log.Panicf("query err, json err: %s", marshalErr.Error())
		return nil
	}
	return jsRst
}
```
### Error log
`
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.17862ms
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.17862ms
[clickhouse][conn=1][10.64.0.160:9000][read data] compression="none". block: columns=6, rows=5
[clickhouse][conn=1][10.64.0.160:9000][profile events] rows=5
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.167625ms
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.167625ms
[clickhouse][conn=1][10.64.0.160:9000][read data] compression="none". block: columns=6, rows=5
[clickhouse][conn=1][10.64.0.160:9000][profile events] rows=5
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.188335ms
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.188335ms
[clickhouse][conn=1][10.64.0.160:9000][read data] compression="none". block: columns=6, rows=17
[clickhouse][conn=1][10.64.0.160:9000][profile events] rows=17
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.214949ms
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.214949ms
[clickhouse][conn=1][10.64.0.160:9000][read data] compression="none". block: columns=6, rows=6
[clickhouse][conn=1][10.64.0.160:9000][profile events] rows=6
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.193506ms
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.193506ms
[clickhouse][conn=1][10.64.0.160:9000][read data] compression="none". block: columns=6, rows=7
[clickhouse][conn=1][10.64.0.160:9000][profile events] rows=7
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.218374ms
[clickhouse][conn=1][10.64.0.160:9000][progress] rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0 elapsed=100.218374ms
[clickhouse][conn=1][10.64.0.160:9000][read data] compression="none". block: columns=6, rows=11
[clickhouse][conn=1][10.64.0.160:9000][profile events] rows=11
[clickhouse][conn=1][10.64.0.160:9000][exception] code: 159, message: Timeout exceeded: elapsed 123.766516903 seconds, maximum: 120
[clickhouse][conn=1][10.64.0.160:9000][query] process error: code: 159, message: Timeout exceeded: elapsed 123.766516903 seconds, maximum: 120
{"level":"info","ts":1695192043.2855418,"caller":"application/query.go:242","msg":"Result: {\"data\":[],\"totals\":null,\"page\":1,\"pageSize\":0} CostTime: 2m6.436337569s","service":"mario-core","tenant":"aa","trace_id":"00000000000000000000000000000000"}`

**Comment by jkaflik** [comment]
Hi @zsdyx 
Initialising a query is non-blocking operation:

```go
	rows, err := chc.conn.Query(clickhouse.Context(ctx, clickhouse.WithSpan(
		trace.NewSpanContext(trace.SpanContextConfig{
			SpanID:  trace.SpanContextFromContext(ctx).SpanID(),
			TraceID: trace.SpanContextFromContext(ctx).TraceID(),
		}),
	)), SQL)
	```
	
This has no chance of returning an error. What happens is your code never gets into the for-loop statement. What you can do here is to add an extra:

```go
if err := rows.Err(); err != nil {
   ... handle err
}
```
After your loop statement.

**Comment by zsdyx** [comment]
Hi @jkaflik 
I'm doing this now. The error information is available
```go
rows, err := chc.conn.Query(clickhouse.Context(ctx, clickhouse.WithSpan(
		trace.NewSpanContext(trace.SpanContextConfig{
			SpanID:  trace.SpanContextFromContext(ctx).SpanID(),
			TraceID: trace.SpanContextFromContext(ctx).TraceID(),
		}),
	)), sql)
	elapsed := time.Since(startTime)
	tracer.GetLogger(ctx).Infof("Query clickhouse, cost time: %s", elapsed.String())
	if err != nil {
		log.Panicf("Query Clickhouse client err, err: %s", err.Error())
		return nil
	}
	var (
		columnNames = rows.Columns()
		columnTypes = rows.ColumnTypes()
		initVars    = make([]reflect.Type, len(columnTypes))
	)
	for i := range columnTypes {
		initVars[i] = columnTypes[i].ScanType()
	}
	rst := make([]map[string]interface{}, 0)

	if !rows.Next() {
		if rows.Err() != nil {
			log.Panicf("Query Clickhouse client rows err: %s", rows.Err().Error())
			return nil
		}
	}
```

**Comment by jkaflik** [comment]
@zsdyx good it works for you know. My advise would be to not call:

```go
if !rows.Next() {
```

but do your usual for-loop and later double-check for `rows.Err()`.

**Comment by zsdyx** [comment]
@jkaflik 
Do you think it should be placed outside for an error judgment? 
rows.Next() returns true or false, is it possible to appear true and false after the appearance of the case
```go
	for rows.Next() {
		vars := make([]interface{}, len(columnTypes))
		for i := range initVars {
			vars[i] = reflect.New(initVars[i]).Interface()
		}

		if err := rows.Scan(vars...); err != nil {
			log.Panicf("Scan Clickhouse client err, err: %s", err.Error())
			return nil
		}
		tmp := make(map[string]interface{}, 1)
		for i, val := range vars {
			tmp[columnNames[i]] = val
		}
		rst = append(rst, tmp)
	}
	if rows.Err() != nil {
			log.Panicf("Query Clickhouse client rows err: %s", rows.Err().Error())
			return nil
		}
```

**Comment by jkaflik** [comment]
@zsdyx your code snippet looks alright.
