### ISSUE TITLE
Am I able to Get the result from "Show Create Table <table_name>" from Clickhouse using sqlx?

### ISSUE THREAD

**Issue by whitehatbuds** [ClickHouse/clickhouse-go#1099]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jkaflik** [comment]
@whitehatbuds

If we are talking about https://github.com/jmoiron/sqlx - it's just a wrapper for `database/sql` interface. 

[`SHOW CREATE TABLE`](https://clickhouse.com/docs/en/sql-reference/statements/show) is the usual query that returns a one row result:

```
click.local :) CREATE TABLE test_table (id Int) ENGINE=Memory

CREATE TABLE test_table
(
    `id` Int
)
ENGINE = Memory

Query id: a8664b2b-ee3b-4ff1-9193-83af9075f4ad

Ok.

0 rows in set. Elapsed: 0.002 sec.

click.local :) SHOW CREATE TABLE test_table

SHOW CREATE TABLE test_table

Query id: 553b4702-d504-4438-8083-4711c883f8e8

┌─statement─────────────────────────────────────────────────────┐
│ CREATE TABLE _local.test_table
(
    `id` Int32
)
ENGINE = Memory │
└───────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.003 sec.
```

You can query it using `Query` function. Please let me know if you have any further questions.
