### ISSUE TITLE
Support canceling batch send operation

### ISSUE THREAD

**Issue by cergxx** [ClickHouse/clickhouse-go#1102]
**Is your feature request related to a problem? Please describe.**
I experienced this bug: #1101.
So I wanted to do a workaround: run separate goroutine which would listen to `context.Done()` and call `batch.Abort()` in it.
However, it won't work:
1. `Abort()` won't cancel already started `sendData()` operation.
2. It is actually unsafe right now to call `Abort()` and `Send()` in separate goroutines since there is no synchronization in the library.

Also the `batch.Send()` won't be interrupted if the context passed to `PrepareBatch()` is canceled.

**Describe the solution you'd like**
The best option would be if `batch.Send()` listened to `ctx.Done()` and stopped if the context was canceled.

**Comment by jkaflik** [comment]
The "easiest" option I can see right now is to close the TCP connection on context cancellation. However, this does not sound like a convenient solution.
