### ISSUE TITLE
Panic if IPv6 address is `nil` or empty `net.IP{}`

### ISSUE THREAD

**Issue by grantstephens** [ClickHouse/clickhouse-go#1106]
### Describe the bug
When trying to insert the library will panic if the IPv6 address is `nil` or empty `net.IP`
### Steps to reproduce
1. Create a table with an IPv6 column
2. Insert a row using a struct where the IP field is `nil` or `net.IP{}`
3. See the following panic:
```
github.com/ClickHouse/clickhouse-go/v2/lib/column.IPv6ToBytes({0x0?, 0xc0001c4000?, 0xc000012030?})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.14.0/lib/column/ipv6.go:339 +0x2cf
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*IPv6).AppendRow(0xc000114870, {0xbaa4e0?, 0xc000386e28?})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.14.0/lib/column/ipv6.go:280 +0x685
github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Block).Append(0xc0002cc080, {0xc000367680?, 0x14, 0xa5b869?})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.14.0/lib/proto/block.go:62 +0x18a
github.com/ClickHouse/clickhouse-go/v2.(*batch).Append(0xc000480360, {0xc000367680?, 0xc?, 0xc000366640?})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.14.0/conn_batch.go:134 +0x45
github.com/ClickHouse/clickhouse-go/v2.(*batch).AppendStruct(0xc000480360, {0xb6a500?, 0xc00027de40?})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.14.0/conn_batch.go:150 +0x89
```

### Expected behaviour
An empty value should be inserted
### Code example
[Made a minimal example that show the error](https://gist.github.com/grantstephens/610e6951751a5498c0337624158cf617)

#### Environment
* Client version:  v0.58.2
* Language version: 1.21
* OS: Linux
* Interface: ClickHouse API 

#### ClickHouse server
* ClickHouse Server version:  22.10

**Comment by grantstephens** [comment]
I'm happy to make do a fix here- seems like a simple check in the `IPv6ToBytes` for nil or `net.IP{}` would fix it.

**Comment by jkaflik** [comment]
Hi @grantstephens 
Yes, please submit a PR if you have anything already

**Comment by grantstephens** [comment]
Thanks you @jkaflik 
Very much appreciated!
