### ISSUE TITLE
Inserting a map[string]any{} containing an int into a JSON type column leads to conversion error (int -> Int64)

### ISSUE THREAD

**Issue by leodido** [ClickHouse/clickhouse-go#1119]
### Describe the bug

Assume a column with type JSON (setting on),
when inserting/appending a Go `map[string]any{}` containing an `int` value
clickhouse-go returns a conversion error.

After investigating the code, I do believe the error is due to `rv.Kind()` being different than `col.ScanType().Kind()` in the `func (col *Int64) AppendRow(v any) error` method.

https://github.com/ClickHouse/clickhouse-go/blob/e38243734a7b937e023ba629c6de5715d66f769d/lib/column/column_gen.go#L1075

This happens because the input `v any` is actually an `int` while the (sub-)column is an `Int64` column due to the `kindMappings` mapping happened in the `parsePrimitive()` function.

https://github.com/ClickHouse/clickhouse-go/blob/fd05bb564afcbc7995802ccbd64c7d83f9fa5c55/lib/column/json.go#L111

https://github.com/ClickHouse/clickhouse-go/blob/fd05bb564afcbc7995802ccbd64c7d83f9fa5c55/lib/column/json.go#L31

### Steps to reproduce

1. Enable the experimental JSON type (eg., `SET allow_experimental_object_type = 1`)
2. Give to a column the experimental `JSON` type
3. Insert a map containing an `int` value (ie., `map[string]any{}{"name": "leo", "age": 22}`)

### Expected behavior

I expect it to work but this may be intended behavior. Feel free to close the issue if that's the case.

When using an `int64(22)` value, it works as expected.

### Code example

Here's a reproducer:

```go
package main

import (
	"context"
	"fmt"

	"github.com/ClickHouse/clickhouse-go/v2"
)

func InsertReadJSON() error {
	opts := &clickhouse.Options{
		Settings: clickhouse.Settings{
			"allow_experimental_object_type": 1,
		},
	}

	conn, err := clickhouse.Open(opts)
	if err != nil {
		return err
	}
	ctx := context.Background()

	conn.Exec(ctx, "DROP TABLE IF EXISTS example")

	if err = conn.Exec(ctx, `
		CREATE TABLE example (
				Col1 JSON,
				Col2 JSON,
				Col3 JSON,
				Col4 JSON
			)
			Engine Memory
		`); err != nil {
		return err
	}

	type User struct {
		Name     string `json:"name"`
		Age      int    `json:"age"`
		Password string `ch:"-"`
	}

	defer func() {
		conn.Exec(ctx, "DROP TABLE example")
	}()
	batch, err := conn.PrepareBatch(ctx, "INSERT INTO example")
	if err != nil {
		return err
	}
	// we can insert JSON as either a string, struct or map
	col1Data := `{"name": "Clicky McClickHouse", "age": 40, "password": "password"}`
	col2Data := `{}`
	col3Data := map[string]any{
		"name":     "leodido",
		"age":      22,
		"password": "clicky",
	}
	col4Data := map[string]interface{}{} // Notice that `{}` works resulting in an output of `map[_dummy:0]`

	// both named and unnamed can be added with slices
	if err = batch.Append(col1Data, col2Data, col3Data, col4Data); err != nil {
		return err
	}

	if err = batch.Send(); err != nil {
		return err
	}
	// we can scan JSON into either a map or struct
	var (
		col1 map[string]any
		col2 map[string]any
		col3 User
		col4 map[string]any
	)
	// named tuples can be retrieved into a map or slices, unnamed just slices
	if err = conn.QueryRow(ctx, "SELECT * FROM example").Scan(&col1, &col2, &col3, &col4); err != nil {
		return err
	}
	fmt.Printf("row: col1=%v, col2=%v, col3=%v\n, col4=%v\n", col1, col2, col3, col4)

	return nil
}

func main() {
	if err := InsertReadJSON(); err != nil {
		fmt.Println(err)
	}
}
```

### Error log

```
clickhouse [AppendRow]: Col3 clickhouse [AppendRow]: converting int to Int64 is unsupported
```

#### Environment
* Client version: 23.9.1.1854 (official build)
* Language version: github.com/ClickHouse/clickhouse-go/v2 v2.14.3
* OS: Darwin 23.0.0 arm64
* Interface: ClickHouse API

#### ClickHouse server
* ClickHouse Server version: 23.9.1 revision 54466
* ClickHouse Server non-default settings, if any: NONE
* `CREATE TABLE` statements for tables involved: NONE

**Comment by DimaOne** [comment]
There was also an error like `clickhouse [AppendRow]: converting int64 to UInt64 is unsupported`.

As far as I understand, you need change all the conditions from
`if rv := reflect.ValueOf(v); rv.Kind() == col.ScanType().Kind() && rv.CanConvert(col.ScanType())`

to
`if rv := reflect.ValueOf(v); rv.Kind() == col.ScanType().Kind() || rv.CanConvert(col.ScanType()) {`

does this make sense?

**Comment by leodido** [comment]
Yup, the problem is at that line (column_gen.go:1075).

**Comment by DimaOne** [comment]
This condition wrong for all types.

**Comment by jkaflik** [comment]
Thanks for finding this out. 🎖️ I haven't had time to look at this. Indeed fix looks simple.
