### ISSUE TITLE
weird behavior of WriteBuffer

### ISSUE THREAD

**Issue by paruru48** [ClickHouse/clickhouse-go#112]
My program is encountering memory leak issue. When profiling program  with `pprof`, I notice that `(*WriteBuffer).addChunk` inuse heap is increasing along with running time of program.
 
` 398MB 32.38% 32.38%      398MB 32.38%  github.com/kshvakov/clickhouse/lib/writebuffer.(*WriteBuffer).addChunk`
...
`614.61MB 41.16% 41.16%   614.61MB 41.16%  github.com/kshvakov/clickhouse/lib/writebuffer.(*WriteBuffer).addChunk`

Generally, the program has multi routine that push data to clickhouse in batch.
I had tried to create a brand new connection on each transaction but issue still remains.

**Comment by kshvakov** [comment]
Make an example to reproduce this problem. We don't have this issue on our production servers.

**Comment by mnach** [comment]
@paruru48
Hi! I have the same issue, but in production only. Can you share some sample of code which triggers this memory leak?

**Comment by kshvakov** [comment]
We have a better memory usage in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
