### ISSUE TITLE
clickhouse [AppendRow]: converting map[string]interface {} to Map(String, Nullable(String)) is unsupported. try using map[string]*string"

### ISSUE THREAD

**Issue by studyhuang1996** [ClickHouse/clickhouse-go#1123]
### Describe the bug
clickhouse datatype Map(String, Nullable(String)) 
go map[string]interface {}   batch.Append  error 

### Expected behaviour
 support Map(String, Nullable(String))
### Code example
```go
	// }

	batch, err := conn.PrepareBatch(ctx, "INSERT INTO default.AUDIT_TEST(TIMESTAMP,EVENT_ID,CLASS,ACCOUNT,CONNECTION_DATA,CREATE_TIME) values")
	if err != nil {
		return err
	}
	for i := 0; i < 10; i++ {
		err := batch.Append(
			"2023-08-22 09:06:58",
			uint16(23),
			"Inc",
			map[string]string{"a": "232", "b": "1"}, 
			map[string]string{"a": "232", "b": "1"},
			nil)
		if err != nil {
			return err
		}
	}
	fmt.Printf("23222")
	return batch.Send()
```
### Error log
clickhouse [AppendRow]: ACCOUNT clickhouse [AppendRow]: converting map[string]string to Map(String, Nullable(String)) is unsupported. try using map[string]*string",
#### Environment
* Client version: 2.14
* Language version: 1.21
* OS: window
* Interface: ClickHouse API / database/sql compatible driver

#### ClickHouse server
* ClickHouse Server version: 8.22
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* 
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by jkaflik** [comment]
@studyhuang1996 this works as expected. It's due to the fact your schema expects `String` to be eventually `Nullable`: `Nullable(String)`. You should append a `map[string]*string` instead, so a nil value can be handled.
