### ISSUE TITLE
HTTP: data streaming is impossible

### ISSUE THREAD

**Issue by vitalyisaev2** [ClickHouse/clickhouse-go#1124]
Currently HTTP driver [buffers full HTTP response](https://github.com/ClickHouse/clickhouse-go/blob/main/conn_http.go#L117)  from the database before delivering data to the caller. This approach may cause performance issues and OOM failures for the applications using `clickhouse-go`. In fact, the size of the response is limited by the memory available for the application, therefore, full scans of large tables are impossible now.

Are there any plans to refactor client to make it more suitable for data streaming? Thank you.

**Comment by jkaflik** [comment]
I agree there are better options here. The underlying native format implementation can read out of `io.Reader`, so refactoring should be pretty straightforward.

I can spend some time on it later next week.
