### ISSUE TITLE
please release v1 with tag v1.5.5

### ISSUE THREAD

**Issue by ioito** [ClickHouse/clickhouse-go#1137]
**Is your feature request related to a problem? Please describe.**

tag with v1.5.4 not contain commit https://github.com/ClickHouse/clickhouse-go/commit/d212b31a558acb3b1d42bb106310812186c98868

**Describe the solution you'd like**

please release new tag v1.5.5 with v1

**Comment by rolinh** [comment]
v1 is no longer maintained, you should consider migrating to v2.
