### ISSUE TITLE
converting []uint8 to FixedString is unsupported

### ISSUE THREAD

**Issue by romaincointepas** [ClickHouse/clickhouse-go#1155]
Would it be possible to accept `[]byte` and `[n]byte` for the `FixedString(n)` type?

It is already accepting a `encoding.BinaryMarshaler` which returns `[]byte`, like this:

```go
type binBytes []byte

func (b binBytes) MarshalBinary() ([]byte, error) {
	return b, nil
}
```

**Comment by jkaflik** [comment]
@romaincointepas yes. Woud you like to submit a PR change?
