### ISSUE TITLE
Sending time as a parameter, some time zones are changing

### ISSUE THREAD

**Issue by Eyup-Devop** [ClickHouse/clickhouse-go#1169]
### Describe the bug
When the time variable is used as a parameter to the query sentence, some time zones such as GMT-2, GMT-3 are formatted in different time zones with the formatTime function toDateTime(time, timezone) in the bind.go file. 

### Steps to reproduce
1. location, err := time.LoadLocation(timeZone)
2.startDate, err = time.ParseInLocation("2006-01-02", "2024-01-03", location)
3. use is as a parameter for DateTime field

bind.go -> line number 267
### Code example
```go
		preFormat := value.Format("toDateTime('2006-01-02 15:04:05',")
		return preFormat + "'" + value.Location().String() + "')", nil
		//		return value.Format(fmt.Sprintf("toDateTime('2006-01-02 15:04:05', '%s')", value.Location().String())), nil

```
#### Environment
* Client version: 2.17.1

**Comment by jkaflik** [comment]
Hi @Eyup-Devop

Could you provide more details on how you build `time.Time` data on your side? I have done following:

```go
package issues

import (
	"context"
	"testing"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
	clickhouse_tests "github.com/ClickHouse/clickhouse-go/v2/tests"
	"github.com/stretchr/testify/require"
)

func Test1169(t *testing.T) {
	var (
		conn, err = clickhouse_tests.GetConnection("issues", clickhouse.Settings{
			"max_execution_time":             60,
			"allow_experimental_object_type": true,
		}, nil, &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		})
	)
	ctx := context.Background()
	require.NoError(t, err)
	const ddl = "CREATE TABLE test_1169 (Col1 DateTime) Engine MergeTree() ORDER BY tuple()"
	require.NoError(t, conn.Exec(ctx, ddl))
	defer func() {
		conn.Exec(ctx, "DROP TABLE IF EXISTS test_1169")
	}()

	location := time.FixedZone("Etc/GMT+2", 0)
	date, err := time.ParseInLocation("2006-01-02", "2024-01-03", location)
	require.NoError(t, err)

	err = conn.Exec(ctx, "INSERT INTO test_1169 (Col1) VALUES (?)", date)
	require.NoError(t, err)
}
```

This is related to ClickHouse `toDateTime` function expect timezone and parse it. Please note it depends on `tzdata`: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
`Etc/GMT+2` is something ClickHouse is able to pick up.

**Comment by Eyup-Devop** [comment]
I changed and added some line to code
the result shows the problem.

import (
"context"
"testing"
"time"

"github.com/ClickHouse/clickhouse-go/v2"
clickhouse_tests "github.com/ClickHouse/clickhouse-go/v2/tests"
"github.com/stretchr/testify/require"
)

func Test1169(t *testing.T) {
conn, err := clickhouse_tests.GetConnection("issues", clickhouse.Settings{
"max_execution_time": 60,
"allow_experimental_object_type": true,
}, nil, &clickhouse.Compression{
Method: clickhouse.CompressionLZ4,
})
ctx := context.Background()
require.NoError(t, err)
const ddl = "CREATE TABLE test_1169 (Col1 DateTime) Engine MergeTree()
ORDER BY tuple()"
require.NoError(t, conn.Exec(ctx, ddl))
defer func() {
conn.Exec(ctx, "DROP TABLE IF EXISTS test_1169")
}()

location := time.FixedZone("Etc/GMT-3", 0)
date, err := time.ParseInLocation("2006-01-02 15:04:05", "2024-01-03
11:22:33", location)
require.NoError(t, err)

err = conn.Exec(ctx, "INSERT INTO test_1169 (Col1) VALUES (?)", date)

var result []time.Time
conn.Select(ctx, &result, "SELECT Col1 FROM test1169 WHERE toDateTime(Col1,
'Etc/GMT-3') <= ?", date)
require.NoError(t, err)
}

/*
in system.query_log table this last query like this:
SELECT Col1 FROM test1169 WHERE toDateTime(Col1, 'Etc/GMT-3') <=
toDateTime('2024-01-03 11:22:33', 'Etc/GMT-11')

'Etc/GMT-11' is wrong
*/




Kuba Kaflik ***@***.***>, 4 Oca 2024 Per, 10:38 tarihinde
şunu yazdı:

**Comment by jkaflik** [comment]
@Eyup-Devop so the issue is:

```go
location := time.FixedZone("Etc/GMT-3", 0)
date, err := time.ParseInLocation("2006-01-02 15:04:05", "2024-01-03
11:22:33", location)
```

has became 

```sql
toDateTime('2024-01-03 11:22:33', 'Etc/GMT-11')
```

using parameter bind? Something has offset the location. Weird.

Please use code block formatting and formulate the problem next time. Thanks!

**Comment by Eyup-Devop** [comment]
I found what is the problem. It is related with go format function. If Etc/GMT-3 not using in the layout there is no complication. EYÜP SARALKuba Kaflik ***@***.***> şunları yazdı (9 Oca 2024 11:18):﻿
@Eyup-Devop so the issue is:
location := time.FixedZone("Etc/GMT-3", 0)
date, err := time.ParseInLocation("2006-01-02 15:04:05", "2024-01-03
11:22:33", location)
has became
toDateTime('2024-01-03 11:22:33', 'Etc/GMT-11')
using parameter bind? Something has offset the location. Weird.
Please use code block formatting and formulate the problem next time. Thanks!

**Comment by jkaflik** [comment]
@Eyup-Devop is this still an issue for you?

**Comment by Eyup-Devop** [comment]
yes it is because it is not related with clickhouse-go. it is related with go formatting string with timezone string. it will change automatically when see Etc/GMT-3 change into Etc/GMT-11. So in bind.go line 267 needs to be change or will use sprintf without timezone like 
```
preFormat := value.Format("toDateTime('2006-01-02 15:04:05',")
		return preFormat + "'" + value.Location().String() + "')", nil
		//		return value.Format(fmt.Sprintf("toDateTime('2006-01-02 15:04:05', '%s')", value.Location().String())), nil
```

**Comment by jkaflik** [comment]
@Eyup-Devop would you like to provide a PR?

**Comment by Eyup-Devop** [comment]
I already sent PR,

Eyup SARAL

Kuba Kaflik ***@***.***>, 23 Oca 2024 Sal, 10:32 tarihinde
şunu yazdı:
