### ISSUE TITLE
How to set timezone when using clickhouse.OpenDB method

### ISSUE THREAD

**Issue by tianshimoyi** [ClickHouse/clickhouse-go#1186]
### Describe the bug
how to set timezone?
### Code example
```go
s.ckClient = clickhouse.OpenDB(&clickhouse.Options{
		Addr: strings.Split(hosts, ","),
		Auth: clickhouse.Auth{
			Database: database,
			Username: user,
			Password: password,
		},
		Settings: clickhouse.Settings{
			"max_execution_time": 60,
		},
		DialTimeout: time.Second * 30,
		Compression: &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		},
		Debug:                true,
		BlockBufferSize:      10,
		MaxCompressionBuffer: 10240,
		ClientInfo: clickhouse.ClientInfo{
			Products: []struct {
				Name    string
				Version string
			}{
				{Name: "xxx-" + hostName, Version: "0.1"},
			},
		},
	})
```
### Error log
[clickhouse][conn=1][10.58.226.20:9000][handshake] <- ClickHouse (xxxxx) server version 22.3.20 revision 54455 (timezone UTC)
[clickhouse][conn=1][10.58.226.20:9000][ping] -> ping
[clickhouse][conn=1][10.58.226.20:9000][ping] <- pong

#### Environment
* Client version: github.com/ClickHouse/clickhouse-go/v2 v2.13.4
* Language version: 1.21
* Interface: database/sql compatible driver

**Comment by jkaflik** [comment]
Hi @tianshimoyi
can you tell me what is your use case? What problem you want to resolve? Do you want to set server timezone?

**Comment by tianshimoyi** [comment]
@jkaflik When I use the clickhouse golang client to connect, it uses UTC by default, which causes the data time I insert to be wrong. I want to use a different time zone, but can't find where to set it

**Comment by tianshimoyi** [comment]
@jkaflik 
![截屏2024-01-30 17 44 10](https://github.com/ClickHouse/clickhouse-go/assets/68532999/32c23380-0f7d-4a03-8e55-62af56176419)

How to set up if you want to use Asia/Shanghai time zone?

**Comment by jkaflik** [comment]
@tianshimoyi 
there are two ways of doing that:
- make sure `time.Time` you provide to insert has correct `Location` set
- make sure you set https://clickhouse.com/docs/en/operations/settings/settings#session_timezone when initializing connection

**Comment by tianshimoyi** [comment]
@jkaflik thank you for your help
