### ISSUE TITLE
[read meta] unexpected packet [5] from server

### ISSUE THREAD

**Issue by AlekSi** [ClickHouse/clickhouse-go#122]
Tagged version `v1.3.4`. ClickHouse `yandex/clickhouse-server:18.12.17`.

```go
db.SetConnMaxLifetime(0)
db.SetMaxOpenConns(2)
db.SetMaxIdleConns(2)
```

First connection is opened:
```
[clickhouse]host(s)=127.0.0.1:9001, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=true, strategy=random, ident=1, server=0 -> 127.0.0.1:9001
[clickhouse][connect=1][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=1][hello] <- ClickHouse 18.12.54407 (UTC)
[clickhouse][connect=1]-> ping
[clickhouse][connect=1][process] <- pong
```

We use for INSERTs (nevermind zero rows):
```
[clickhouse][connect=1][begin] tx=false, data=false
[clickhouse][connect=1][prepare] INSERT INTO audit_messages …
[clickhouse][connect=1][send query] INSERT INTO audit_messages …
[clickhouse][connect=1][read meta] <- data: packet=1, columns=7, rows=0
[clickhouse][connect=1][stmt] close
[clickhouse][connect=1][commit] tx=true, data=true
[clickhouse][connect=1][process] <- end of stream
```

Concurrently we use the same connection of SELECTs:
```
[clickhouse][connect=1][prepare] SELECT …
[clickhouse][connect=1][send query] SELECT …
[clickhouse][connect=1][stmt] close
```

Then this connection is suddenly closed:
```
[clickhouse][connect=1][prepare] SELECT …
[clickhouse][connect=1][AlekSi][prepare] ch.conn.closed
```

This custom log message is added before `return` there: https://github.com/kshvakov/clickhouse/blob/aeedb7b9d0584f393905447021238b5c6e9c5154/clickhouse.go#L56-L60

Then second connection is opened:
```
[clickhouse]host(s)=127.0.0.1:9001, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=true, strategy=random, ident=2, server=0 -> 127.0.0.1:9001
[clickhouse][connect=2][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=2][hello] <- ClickHouse 18.12.54407 (UTC)
```

SELECT works:
```
[clickhouse][connect=2][prepare] SELECT …
[clickhouse][connect=2][send query] SELECT …
[clickhouse][connect=2][stmt] close
```

But then INSERT fails:
```
[clickhouse][connect=2][begin] tx=false, data=false
[clickhouse][connect=2][prepare] INSERT INTO audit_messages
[clickhouse][connect=2][send query] INSERT INTO audit_messages
Failed to prepare statement: [read meta] unexpected packet [5] from server
Failed to commit transaction: driver: bad connection
```

I assume that `[read meta] unexpected packet [5] from server` actually happened at prepare when the connection is suddenly closed. And, for some reason, this error jumps to the next connection.

**Comment by kshvakov** [comment]
Sorry, I can't reproduce

```go
func Test_Issue122(t *testing.T) {

	const DDL = `
		CREATE TABLE IF NOT EXISTS audit_messages (
			id    UInt64
		) Engine=Memory
	`

	if connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?debug=true"); assert.NoError(t, err) && assert.NoError(t, connect.Ping()) {
		connect.SetConnMaxLifetime(0)
		connect.SetMaxOpenConns(2)
		connect.SetMaxIdleConns(2)
		{
			connect.Exec(DDL)
		}
		if tx, err := connect.Begin(); assert.NoError(t, err) {
			if stmt, err := tx.Prepare("INSERT INTO audit_messages VALUES (?)"); assert.NoError(t, err) {
				if _, err := stmt.Exec(1); assert.NoError(t, err) {
					assert.NoError(t, tx.Commit())
				}
			}
		}
		if rows, err := connect.Query("SELECT id FROM audit_messages"); assert.NoError(t, err) {
			var id int64
			for rows.Next() {
				if assert.NoError(t, rows.Scan(&id)) {
					t.Logf("id=%d", id)
				}
			}
		}
		if tx, err := connect.Begin(); assert.NoError(t, err) {
			if stmt, err := tx.Prepare("INSERT INTO audit_messages VALUES (?)"); assert.NoError(t, err) {
				if _, err := stmt.Exec(1); assert.NoError(t, err) {
					assert.NoError(t, tx.Commit())
				}
			}
		}
	}
}

```

```
=== RUN   Test_Issue122
[clickhouse]host(s)=127.0.0.1:9000, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=true, strategy=random, ident=1, server=0 -> 127.0.0.1:9000
[clickhouse][connect=1][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=1][hello] <- ClickHouse 18.12.54407 (UTC)
[clickhouse][connect=1]-> ping
[clickhouse][connect=1][process] <- pong
[clickhouse][connect=1][prepare] 
		CREATE TABLE IF NOT EXISTS audit_messages (
			id    UInt64
		) Engine=Memory
	
[clickhouse][connect=1][send query] 
		CREATE TABLE IF NOT EXISTS audit_messages (
			id    UInt64
		) Engine=Memory
	
[clickhouse][connect=1][process] <- end of stream
[clickhouse][connect=1][stmt] close
[clickhouse][connect=1][begin] tx=false, data=false
[clickhouse][connect=1][prepare] INSERT INTO audit_messages VALUES (?)
[clickhouse][connect=1][send query] INSERT INTO audit_messages VALUES 
[clickhouse][connect=1][read meta] <- data: packet=1, columns=1, rows=0
[clickhouse][connect=1][commit] tx=true, data=true
[clickhouse][connect=1][process] <- end of stream
[clickhouse][connect=1][stmt] close
[clickhouse][connect=1][prepare] SELECT id FROM audit_messages
[clickhouse][connect=1][send query] SELECT id FROM audit_messages
[clickhouse][connect=1][read meta] <- data: packet=1, columns=1, rows=0
[clickhouse][connect=1][rows] <- data: packet=1, columns=1, rows=1, elapsed=14.257µs
[clickhouse][connect=1][rows] <- data: packet=1, columns=1, rows=1, elapsed=1.825µs
[clickhouse][connect=1][rows] <- data: packet=1, columns=1, rows=1, elapsed=1.23µs
[clickhouse][connect=1][rows] <- data: packet=1, columns=1, rows=1, elapsed=1.777µs
[clickhouse][connect=1][rows] <- data: packet=1, columns=1, rows=1, elapsed=1.723µs
[clickhouse][connect=1][rows] <- profiling: rows=5, bytes=40, blocks=5
[clickhouse][connect=1][rows] <- progress: rows=5, bytes=40, total rows=0
[clickhouse][connect=1][rows] <- data: packet=1, columns=0, rows=0, elapsed=1.588µs
[clickhouse][connect=1][rows] <- end of stream
[clickhouse][connect=1][rows] close
[clickhouse][connect=1][stmt] close
[clickhouse][connect=1][begin] tx=false, data=false
[clickhouse][connect=1][prepare] INSERT INTO audit_messages VALUES (?)
[clickhouse][connect=1][send query] INSERT INTO audit_messages VALUES 
[clickhouse][connect=1][read meta] <- data: packet=1, columns=1, rows=0
[clickhouse][connect=1][commit] tx=true, data=true
[clickhouse][connect=1][process] <- end of stream
[clickhouse][connect=1][stmt] close
--- PASS: Test_Issue122 (0.00s)
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:263: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:263: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:263: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:263: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:263: id=1
PASS
ok  	github.com/kshvakov/clickhouse	0.007s
Success: Tests passed.```

**Comment by kshvakov** [comment]
AND 

```go
func Test_Issue122(t *testing.T) {

	const DDL = `
		CREATE TABLE IF NOT EXISTS audit_messages (
			id    UInt64
		) Engine=Memory
	`

	if connect, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?debug=true"); assert.NoError(t, err) && assert.NoError(t, connect.Ping()) {
		connect.SetConnMaxLifetime(0)
		connect.SetMaxOpenConns(2)
		connect.SetMaxIdleConns(2)
		{
			connect.Exec(DDL)
		}
		if tx, err := connect.Begin(); assert.NoError(t, err) {
			if stmt, err := tx.Prepare("INSERT INTO audit_messages VALUES (?)"); assert.NoError(t, err) {
				if _, err := stmt.Exec(1); assert.NoError(t, err) {
					assert.NoError(t, tx.Commit())
				}
			}
		}

		if tx, err := connect.Begin(); assert.NoError(t, err) {

			if rows, err := connect.Query("SELECT id FROM audit_messages"); assert.NoError(t, err) {
				var id int64
				for rows.Next() {
					if assert.NoError(t, rows.Scan(&id)) {
						t.Logf("id=%d", id)
					}
				}
			}

			if stmt, err := tx.Prepare("INSERT INTO audit_messages VALUES (?)"); assert.NoError(t, err) {
				if _, err := stmt.Exec(1); assert.NoError(t, err) {
					assert.NoError(t, tx.Commit())
				}
			}
		}
	}
}```

```

=== RUN   Test_Issue122
[clickhouse]host(s)=127.0.0.1:9000, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=true, strategy=random, ident=1, server=0 -> 127.0.0.1:9000
[clickhouse][connect=1][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=1][hello] <- ClickHouse 18.12.54407 (UTC)
[clickhouse][connect=1]-> ping
[clickhouse][connect=1][process] <- pong
[clickhouse][connect=1][prepare] 
		CREATE TABLE IF NOT EXISTS audit_messages (
			id    UInt64
		) Engine=Memory
	
[clickhouse][connect=1][send query] 
		CREATE TABLE IF NOT EXISTS audit_messages (
			id    UInt64
		) Engine=Memory
	
[clickhouse][connect=1][process] <- end of stream
[clickhouse][connect=1][stmt] close
[clickhouse][connect=1][begin] tx=false, data=false
[clickhouse][connect=1][prepare] INSERT INTO audit_messages VALUES (?)
[clickhouse][connect=1][send query] INSERT INTO audit_messages VALUES 
[clickhouse][connect=1][read meta] <- data: packet=1, columns=1, rows=0
[clickhouse][connect=1][commit] tx=true, data=true
[clickhouse][connect=1][process] <- end of stream
[clickhouse][connect=1][stmt] close
[clickhouse][connect=1][begin] tx=false, data=false
[clickhouse]host(s)=127.0.0.1:9000, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=true, strategy=random, ident=2, server=0 -> 127.0.0.1:9000
[clickhouse][connect=2][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=2][hello] <- ClickHouse 18.12.54407 (UTC)
[clickhouse][connect=2][prepare] SELECT id FROM audit_messages
[clickhouse][connect=2][send query] SELECT id FROM audit_messages
[clickhouse][connect=2][read meta] <- data: packet=1, columns=1, rows=0
[clickhouse][connect=2][rows] <- data: packet=1, columns=1, rows=1, elapsed=23.926µs
[clickhouse][connect=2][rows] <- data: packet=1, columns=1, rows=1, elapsed=4.339µs
[clickhouse][connect=2][rows] <- data: packet=1, columns=1, rows=1, elapsed=3.345µs
[clickhouse][connect=2][rows] <- data: packet=1, columns=1, rows=1, elapsed=3.119µs
[clickhouse][connect=2][rows] <- data: packet=1, columns=1, rows=1, elapsed=3.285µs
[clickhouse][connect=2][rows] <- data: packet=1, columns=1, rows=1, elapsed=2.568µs
[clickhouse][connect=2][rows] <- data: packet=1, columns=1, rows=1, elapsed=5.965µs
[clickhouse][connect=2][rows] <- profiling: rows=7, bytes=56, blocks=7
[clickhouse][connect=2][rows] <- progress: rows=7, bytes=56, total rows=0
[clickhouse][connect=2][rows] <- data: packet=1, columns=0, rows=0, elapsed=1.379µs
[clickhouse][connect=2][rows] <- end of stream
[clickhouse][connect=2][rows] close
[clickhouse][connect=2][stmt] close
[clickhouse][connect=1][prepare] INSERT INTO audit_messages VALUES (?)
[clickhouse][connect=1][send query] INSERT INTO audit_messages VALUES 
[clickhouse][connect=1][read meta] <- data: packet=1, columns=1, rows=0
[clickhouse][connect=1][commit] tx=true, data=true
[clickhouse][connect=1][process] <- end of stream
[clickhouse][connect=1][stmt] close
--- PASS: Test_Issue122 (0.01s)
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:266: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:266: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:266: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:266: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:266: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:266: id=1
    /home/kshvakov/GOPATH/src/github.com/kshvakov/clickhouse/issues_test.go:266: id=1
PASS
ok  	github.com/kshvakov/clickhouse	0.011s
Success: Tests passed.
```
