### ISSUE TITLE
Append to a batch transactionally

### ISSUE THREAD

**Issue by yujiarista** [ClickHouse/clickhouse-go#1225]
Currently if I append a row with bad data to a batch, the batch is basically ruined. 
Can we add a transactional semantic to Batch.Append so no data is appended to any column if there is an error?

**Comment by threadedstream** [comment]
I think it can be resolved by following the template below 
```go
func append() error {
   batch := conn.PrepareBatch(...)
   defer func() {
     if err != nil {
        return batch.Abort()
     }
     return batch.Send()
   }
   .....
}
```

Maybe you have a different case where template above doesn't work

**Comment by yujiarista** [comment]
My suggestion is basically the same as https://github.com/ClickHouse/clickhouse-go/issues/1223. Closing this one.
