### ISSUE TITLE
Create table failing when engine parameter is present in query

### ISSUE THREAD

**Issue by luk3skyw4lker** [ClickHouse/clickhouse-go#1238]
### Describe the bug
When trying to create a table programatically the query substitution is not working for the engine parameter

### Steps to reproduce
1. Try to create a table with an engine parameter in the query

### Expected behaviour
The code should create the table programatically successfully

### Code example
```go
conn, err := driver.Open(&driver.Options{
	Addr:  []string{fmt.Sprintf("127.0.0.1:9000")},
	Debug: true,
	Debugf: func(format string, v ...any) {
		log.Printf(format, v...)
	},
})
if err != nil {
	return err
}

const createTableString = `
  CREATE TABLE IF NOT EXISTS {table:Identifier} (
  		key String
  	, value String
  	, expiration DateTime
  ) ENGINE={engine:Identifier}
`

if err := conn.Exec(ctx, createTableString); err != nil {
	return  err
}
```
### Error log
![image](https://github.com/ClickHouse/clickhouse-go/assets/48929501/fbc4a793-b0c5-4ec9-93d3-08795cd37d10)

#### Environment
* Client version: v2.20.0
* Language version:
* OS: Manjaro Linux
* Interface: ClickHouse API

#### ClickHouse server
* ClickHouse Server version: 24.2.2.71
* ClickHouse Server non-default settings, if any: none
* `CREATE TABLE` statements for tables involved: provided in the code above

**Comment by jkaflik** [comment]
Hi @luk3skyw4lker 

Thanks for filling in this issue. Unfortunately, it's not implemented in ClickHouse itself: https://github.com/ClickHouse/ClickHouse/issues/61865

As a workaround I suggest pass engine name inline into SQL statement.
