### ISSUE TITLE
Can you please comment your library so its actually usable

### ISSUE THREAD

**Issue by kvtx** [ClickHouse/clickhouse-go#1246]
It is almost impossible to use your go library because there is no documentation except the examples in your code base which is absolutely unacceptable. Comment your code.

**Comment by jkaflik** [comment]
@kvtx did you had a chance to take a look on https://clickhouse.com/docs/en/integrations/go ? It's linked directly in README. Is there anything missing you would like to include in the doc?

**Comment by kvtx** [comment]
My apologies for being a tad prickish on friday, i was frustrated by the following....

It is very unclear what the preferred methodology for query parameters is:

there is one example here: https://github.com/ClickHouse/clickhouse-go/blob/main/examples/clickhouse_api/query_parameters.go

another here: 
https://clickhouse.com/docs/en/integrations/go#parameter-binding

The links in the github documentation take you to [this](https://github.com/ClickHouse/clickhouse-go/blob/main/examples/clickhouse_api/query_parameters.go)

Now... given that was the first example ill walk you through what it was like to figure out how to use this properly from within Go.

In the screenshot below you can see the on hover for clickhouse `query` within my implemention:
![Screenshot 2024-03-25 at 9 11 49 AM](https://github.com/ClickHouse/clickhouse-go/assets/7979707/8d56e663-7ddc-456e-bb33-dad1f0e3c13c)

this function accepts `...args any` as its 3rd parameter, so you might assume that it actually takes a distribution of `any` (strings, ints etc) in all cases. However, it only takes `any` if you use the old "deprecated" bindings of `?` or `$` and not the qualified types bindings suggested for use by your docs/examples: `{str:String}`

In order to know that it doesn't actually take `any` but it instead takes a very specific `driver.NamedValue` type masked as `any` you either have to look directly at examples and make assumptions based on those examples, or you have to use the function without that correct input and get the error message, or trace the web of interfaces in the IDE until you find the real implementation where the error is thrown if the `any` cannot be parsed into the `NamedValue`.

The trace is not simple because of your interface pattern, trying to trace on `query` gets you here: 
![Screenshot 2024-03-25 at 9 12 00 AM](https://github.com/ClickHouse/clickhouse-go/assets/7979707/40465bcf-d25b-4b73-bd12-3cb8a87d1ed3)

so instead, you must trace from the implementer of the interface which is the client... now this is a journey:

1. ![Screenshot 2024-03-25 at 9 24 19 AM](https://github.com/ClickHouse/clickhouse-go/assets/7979707/52685af7-b159-4525-bfa2-1ce2e58dbac0)

2. ![Screenshot 2024-03-25 at 9 24 29 AM](https://github.com/ClickHouse/clickhouse-go/assets/7979707/35fd74f2-4f2a-45da-bccc-e47309730e64)

3. ![Screenshot 2024-03-25 at 9 25 10 AM](https://github.com/ClickHouse/clickhouse-go/assets/7979707/e9f7420a-74c8-4e58-8944-b4dc2667dbe7)

4. ![Screenshot 2024-03-25 at 9 25 19 AM](https://github.com/ClickHouse/clickhouse-go/assets/7979707/6eefdf08-c95f-4d20-9adb-0ff559a3b1eb)

5. ![Screenshot 2024-03-25 at 9 25 27 AM](https://github.com/ClickHouse/clickhouse-go/assets/7979707/34df6ea2-21d2-4cf1-9330-eb4c49cc97ae)


5 function traces later we finally have ONE single tiny comment that tells us how to use this thing:

```
	// validate if query contains a {<name>:<data type>} syntax, so it's intentional use of query parameters
	// parameter values will be loaded from `args ...any` for compatibility
```

this should be on the description of the interface method `query` at the very least. 

AND we finally see that, without a comment or anything, this new `NamedValue` struct of `string, any` actually is, yet again, not actually allowed to be `any` but instead must actually be a `string`



Ok but better yet, it appears that this may actually be the _deprecated_ method for implementing query parameters.

your documentations says this: [query parameters](https://github.com/ClickHouse/clickhouse-go/blob/main/examples/clickhouse_api/query_parameters.go) (deprecated in favour of native query parameters)

but then gives no qualification for what a native query parameter is.

If you Google ![Screenshot 2024-03-25 at 10 24 19 AM](https://github.com/ClickHouse/clickhouse-go/assets/7979707/5d0321d6-2a5b-4906-a1e3-181711663be4), the first thing that comes up is the reference example that appears to possible be the deprecated version.

but all of this is very unclear,

if you could just add a few comments in the code on the interface it would make integrating with your go library much more straight forward and not require cross referencing a bunch of docs. Of which, it is not particularly clear which are new and favored and which are old and out of favor.

All you would have to do to add go docs is copy paste into your go code in a comment... Im also making assumptions about which method is deprecated because i have not found anywhere that makes that fully clear except the if statement in the code that appears to short circuit on suggestion that we are preferring the new method.


Here is all you would need to at a minimum make this usable:
```
// Query accepts multiple bindvar options `?`, `@named`, `$`  and the deprecated `{param: type}` binding method.
/ /in order to use named parameters, you must pass the argument as type `NamedVar`
Query(ctx context.Context, query string, args ...any) (Rows, error)

//repeat for each of the follow `Select`, `Query Row`
```

In fact, if you can clear all this up for me I will make a PR and document the code for you!

**Comment by jkaflik** [comment]
@kvtx 

Thanks for describing the problem you are facing in depth! I agree that the query parameters feature is specifically badly documented. I will follow up on this week. 

Query parameters is a way to go: https://github.com/ClickHouse/clickhouse-go/blob/main/examples/clickhouse_api/query_parameters.go

Here is ClickHouse documentation on query parameters: https://clickhouse.com/docs/en/sql-reference/syntax#defining-and-using-query-parameters
You can also watch a recording explaining this: https://clickhouse.com/videos/how-to-use-query-parameters-in-clickhouse

[Besides aligning on query parameters documentation](https://github.com/ClickHouse/clickhouse-go/issues/1253), I think it's worth to invest in exported types comments. This library doesn't have it at all, but it's really worth to expose how is the logic handled with this! You can follow [this issue](https://github.com/ClickHouse/clickhouse-go/issues/1254).

**Comment by jkaflik** [comment]
@kvtx using ClickHouse query parameters

**Comment by kvtx** [comment]
thats these: `{key:type}`?

**Comment by kanekv** [comment]
@jkaflik how to pass array of strings as a native parameter? Do we need to do our own escaping?

**Comment by kvtx** [comment]
i figured this out recently, you have to pass any array as a string representation of the array in square brackets like so

"['value1','value2','value3']"

then in the query you parameterize by type correctly

`{my_array_param:Array(String)}`

if they were uuids you would do the same then do

`{my_array_param:Array(UUID)}`

so the value of the parameter is a "stringified" array which then gets automatically parsed by the clickhouse type system to the correct array type via the parameter definition in the query.
