### ISSUE TITLE
connect::prepareBatch parsed INSERT query incorrectly

### ISSUE THREAD

**Issue by timmyb32r** [ClickHouse/clickhouse-go#1247]
In trunk now function prepareBatch trying to parse INSERT statement by regexp:

```golang
var splitInsertRe = regexp.MustCompile(`(?i)\sVALUES\s*\(`)
var columnMatch = regexp.MustCompile(`.*\((?P<Columns>.+)\)$`)

func (c *connect) prepareBatch(...)
    query = splitInsertRe.Split(query, -1)[0]
    colMatch := columnMatch.FindStringSubmatch(query)
```

so, the problem is - user can create any columnName into backticks, which also makes possible to match part of regexp.

Example (any column_name with parentheses as part of name):

```sql
INSERT INTO `my_schema`.`my_table` (`__primary_key`,`ColumnNameWithParentheses(something)`) VALUES (1,1);
```

I see good solution here - at least use tokenizer from Clickhouse antlr grammar instead of regexp.

I have PR with fix & test

**Comment by timmyb32r** [comment]
damn, don't know how to allocate issue number, and link PR into issue.
So, the PR is into #1248
can anybody link that PR into this issue?)

**Comment by jkaflik** [comment]
@timmyb32r you already referenced it. GitHub does it automatically when you post a link/issue number.
