### ISSUE TITLE
can not scan Nullable column into sql.NullString

### ISSUE THREAD

**Issue by shory152** [ClickHouse/clickhouse-go#1257]
### Describe the bug

select a nullable column, scan into sql.NullString, report not support error.

### Steps to reproduce
1.
2.
3.

### Code example
```go
```
#### Environment
* Client version:
* Language version:
* OS:
* Interface: ClickHouse API / database/sql compatible driver

#### ClickHouse server
* ClickHouse Server version: 22.9
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by jkaflik** [comment]
@shory152 please update issue body with minimum information:
- clickhouse-go version
- code example/steps to reproduce

**Comment by perekalov** [comment]
Hi!

I'm experiencing the same issue. This is my way of reproducing:
1. Run clickhouse-server on standard port 9000
2. Execute following code

```
package main

import (
	"database/sql"
	"time"

	_ "github.com/ClickHouse/clickhouse-go/v2"
)

func main() {
	conn, err := sql.Open("clickhouse", "clickhouse://localhost:9000")
	if err != nil {
		panic(err)
	}
	const ddl = `
		CREATE TABLE test_scan (
			  Str String,
			  NStr Nullable(String),
			  Dt DateTime,
			  NDt Nullable(DateTime)
		) Engine MergeTree() ORDER BY tuple()
`
	defer func() {
		conn.Exec("DROP TABLE test_scan")
	}()
	_, err = conn.Exec(ddl)
	if err != nil {
		panic(err)
	}
	scope, err := conn.Begin()
	if err != nil {
		panic(err)
	}
	batch, err := scope.Prepare("INSERT INTO test_scan")
	if err != nil {
		panic(err)
	}
	_, err = batch.Exec(
		"str",
		"str",
		time.Now(),
		time.Now(),
	)
	if err != nil {
		panic(err)
	}
	if err := scope.Commit(); err != nil {
		panic(err)
	}

	var (
		col1string     string
		col2NullString sql.NullString
		col3Time       time.Time
		col4NullTime   sql.NullTime
	)

	row := conn.QueryRow("SELECT Str, NStr, Dt, NDt FROM test_scan", map[string]interface{}{})
	if row.Err() != nil {
		panic(err)
	}
	if err := row.Scan(&col1string, &col2NullString, &col3Time, &col4NullTime); err != nil {
		panic(err)
	}

	return
}
```


I expect successful scan into sql.NullString from source Nullable(String) column. But error appears:
```
panic: sql: Scan error on column index 1, name "NStr": unsupported Scan, storing driver.Value type *string into type *string

goroutine 1 [running]:
main.main()
	/Users/pperekalov/Desktop/chtest/main.go:67 +0x39c
exit status 2
```

Also, there is no test that checks scan of existing value of nullable column into sql.NullString: https://github.com/ClickHouse/clickhouse-go/blob/v2.23.2/tests/string_test.go#L127
It only checks two cases of scanning into sql.NullString empty values (Null) of nullable column.

Environment
- Language version: go1.22.1 darwin/arm64
- OS: mac os 13.6.3
- Interface: github.com/ClickHouse/clickhouse-go/v2 v2.23.2
- ClickHouse Server version: 24.2.1.2248

**Comment by Wang** [comment]
> Hi!
> 
> I'm experiencing the same issue. This is my way of reproducing:
> 
> 1. Run clickhouse-server on standard port 9000
> 2. Execute following code
> 
> ```
> package main
> 
> import (
> 	"database/sql"
> 	"time"
> 
> 	_ "github.com/ClickHouse/clickhouse-go/v2"
> )
> 
> func main() {
> 	conn, err := sql.Open("clickhouse", "clickhouse://localhost:9000")
> 	if err != nil {
> 		panic(err)
> 	}
> 	const ddl = `
> 		CREATE TABLE test_scan (
> 			  Str String,
> 			  NStr Nullable(String),
> 			  Dt DateTime,
> 			  NDt Nullable(DateTime)
> 		) Engine MergeTree() ORDER BY tuple()
> `
> 	defer func() {
> 		conn.Exec("DROP TABLE test_scan")
> 	}()
> 	_, err = conn.Exec(ddl)
> 	if err != nil {
> 		panic(err)
> 	}
> 	scope, err := conn.Begin()
> 	if err != nil {
> 		panic(err)
> 	}
> 	batch, err := scope.Prepare("INSERT INTO test_scan")
> 	if err != nil {
> 		panic(err)
> 	}
> 	_, err = batch.Exec(
> 		"str",
> 		"str",
> 		time.Now(),
> 		time.Now(),
> 	)
> 	if err != nil {
> 		panic(err)
> 	}
> 	if err := scope.Commit(); err != nil {
> 		panic(err)
> 	}
> 
> 	var (
> 		col1string     string
> 		col2NullString sql.NullString
> 		col3Time       time.Time
> 		col4NullTime   sql.NullTime
> 	)
> 
> 	row := conn.QueryRow("SELECT Str, NStr, Dt, NDt FROM test_scan", map[string]interface{}{})
> 	if row.Err() != nil {
> 		panic(err)
> 	}
> 	if err := row.Scan(&col1string, &col2NullString, &col3Time, &col4NullTime); err != nil {
> 		panic(err)
> 	}
> 
> 	return
> }
> ```
> 
> I expect successful scan into sql.NullString from source Nullable(String) column. But error appears:
> 
> ```
> panic: sql: Scan error on column index 1, name "NStr": unsupported Scan, storing driver.Value type *string into type *string
> 
> goroutine 1 [running]:
> main.main()
> 	/Users/pperekalov/Desktop/chtest/main.go:67 +0x39c
> exit status 2
> ```
> 
> Also, there is no test that checks scan of existing value of nullable column into sql.NullString: https://github.com/ClickHouse/clickhouse-go/blob/v2.23.2/tests/string_test.go#L127 It only checks two cases of scanning into sql.NullString empty values (Null) of nullable column.
> 
> Environment
> 
> * Language version: go1.22.1 darwin/arm64
> * OS: mac os 13.6.3
> * Interface: github.com/ClickHouse/clickhouse-go/v2 v2.23.2
> * ClickHouse Server version: 24.2.1.2248

It uses "database/sql" driver not clickhouse-go from the above examples.

**Comment by perekalov** [comment]
> It uses "database/sql" driver not clickhouse-go from the above examples.

Sorry. I don't get it.
database/sql is not a driver, it is an interface. And clickhouse-go allows to use it https://github.com/ClickHouse/clickhouse-go?tab=readme-ov-file#databasesql-interface
