### ISSUE TITLE
Set the query_id

### ISSUE THREAD

**Issue by jackconley** [ClickHouse/clickhouse-go#126]
I'm looking for a way to set the query_id when executing a new query.  I can do this with the HTTP interface but I have not be able to with this interface.

`http://localhost:8123/?query=SELECT * FROM system.processes&query_id=example`

**Comment by kshvakov** [comment]
Hi, I'll think about it.

**Comment by jackconley** [comment]
Problem solved.
In clickhouse_send_query.go there is a misplaced comment for initial_query_id.  That value actually gets encoded as the first string after ClientQuery.  I'm not sure of a good way to pass query_id through the golang sql layer.  I did a quick hack to pull it out of a query comment to solve my issue.

**Comment by Kenneth-Kuo** [comment]
Here is what [go-clickhouse](https://github.com/mailru/go-clickhouse) implemented to pass down the query_id.

```
ctx := context.Background()
rows, err := connect.QueryContext(context.WithValue(ctx, clickhouse.QueryID, "dummy-query-id"), `
	SELECT
		country_code,
		os_id,
		browser_id,
		categories,
		action_day,
		action_time
	FROM
		example`
)

```

**Comment by Zhile** [comment]
Hi @jackconley, Can you help to explain more about your hacky method? I tried to put the query_id into that field, but it doesn't work. Do I still need to change something else? 
```	
        { // client info
		ch.encoder.Uvarint(1)
		ch.encoder.String("")
		ch.encoder.String("") //initial_query_id //put the query_id here???
		ch.encoder.String("[::ffff:127.0.0.1]:0")
		ch.encoder.Uvarint(1) // iface type TCP
		ch.encoder.String(hostname)
		ch.encoder.String(hostname)
	}
```
I also changed the setting `replace_running_query=1` in clickhouse-server side, it doesn't work either.

**Comment by Zhile** [comment]
I do some tests on this, and found @jackconley is right. 
please see the PR here: https://github.com/ClickHouse/clickhouse-go/pull/338

**Comment by John-belt** [comment]
Hi, is this issue resolved??

**Comment by kshvakov** [comment]
@John-belt Yes, you can use [Context](https://github.com/ClickHouse/clickhouse-go/blob/v2/context.go#L40)
