### ISSUE TITLE
Nullable(T): column: unhandled type Nothing

### ISSUE THREAD

**Issue by AlekSi** [ClickHouse/clickhouse-go#127]
https://clickhouse.yandex/docs/en/data_types/special_data_types/nothing/

As simple as
```go
db.Exec(`SELECT NULL`)
```

See also https://github.com/mymarilyn/clickhouse-driver/issues/21.

**Comment by kshvakov** [comment]
ОК, I'll add this type

**Comment by nianglao** [comment]
any update on this?
