### ISSUE TITLE
sql.Open() is fine but Ping fails

### ISSUE THREAD

**Issue by mhechthz** [ClickHouse/clickhouse-go#1270]
I'm using this kind of connect:
```
func ConnectDSN() error {
	env, err := GetStdTestEnvironment()
	if err != nil {
		return err
	}
	conn, err := sql.Open("clickhouse", fmt.Sprintf("clickhouse://%s:%d?username=%s&password=%s", env.Host, env.Port, env.Username, env.Password))
	if err != nil {
		return err
	}
	return conn.Ping()
}
```
The string is finally  `"clickhouse://myserver:8123?username=myuser&password=mypass"`

Host, port, user and pass are checked using python clickhouse access. On ping I get: `driver: bad connection`.

What's wrong here?

**Comment by mhechthz** [comment]
Here  is the full test code:
```
package main

import (
	"database/sql"
	"fmt"
	"os"

	_ "github.com/ClickHouse/clickhouse-go"
)

func main() {

	connString := fmt.Sprintf("clickhouse://%s:8123?username=%s&password=%s", os.Getenv("CLKSERVER"), os.Getenv("CLKUSER"), os.Getenv("CLKPASS"))
	fmt.Println("CONNECT TO CLICKHOUSE:\n" + connString)
	conn, err := sql.Open("clickhouse", connString)
	if err != nil {
		fmt.Println("ERROR on connect: " + err.Error())
	} else {
		fmt.Println("SUCCESS on connect ...")
	}

	if err := conn.Ping(); err != nil {
		fmt.Println("ERROR on ping: failed to ping database - " + err.Error())
	}
}

```

and this the output after a minute or so
```
go run dbtest.go
CONNECT TO CLICKHOUSE:
    'clickhouse://...:8123?username=...&password=...'
SUCCESS on connect ...
ERROR on ping: failed to ping database - driver: bad connection
```

With Python i do with the same parameters
```
import clickhouse_connect as chc # pip install clickhouse-connect
...
client =  chc.get_client(host='...', 
                        port=8123, 
                        username=username, 
                        password=password)
    
result = client.query(query)
```
and all is fine.

**Comment by Slach** [comment]
try to use 9000 port instead of 8123

**Comment by mhechthz** [comment]
Hmmm ... works. But I'dont understand why there are so many ports to connect to clickhouse, e.g. 8123, 8443, 9000, ...

Nevertheless, thank you very much!

**Comment by mhechthz** [comment]
Maybe there could be a better error message ...

**Comment by jkaflik** [comment]
@mhechthz ClickHouse provides a doc explaining each TCP port: https://clickhouse.com/docs/en/guides/sre/network-ports

> Maybe there could be a better error message instead of "driver: bad connection".

That would be great, however: (besides `driver: bad connection` is way too generic)
- how do you know it's a wrong protocol port chosen vs bug vs network hiccup
- each ClickHouse server can be configured differently on ports
