### ISSUE TITLE
connect success，but ping failed

### ISSUE THREAD

**Issue by FailedNamed** [ClickHouse/clickhouse-go#1275]
## Observed
connect success，but ping failed
error msg: clickhouse [execute]:: 404 code: Code: 46, e.displayText() = DB::Exception: Unknown function timeZone. Maybe you meant: ['timezone','toTimeZone']: While processing timeZone() (version 21.3.9.83 (official build))
but when I connect another clickhouse(version 22.2.2.1)，it is success！
and then I try to use github.com/mailru/go-clickhouse, it can work as well (on the clickhouse with version  21.3.9.83)!

## Expected behaviour
what's wrong with this?

## Code example
```go
package code

import (
	"database/sql"
	"log"
	"testing"

	_ "github.com/ClickHouse/clickhouse-go/v2"
)

func TestClickHouse1(t *testing.T) {
	connect, err := sql.Open("clickhouse", "http://name:pwd@host:port?database=default")
	// connect, err := sql.Open("clickhouse", "http://name2:pwd2@host2:port2?database=default")
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("connect success\n")
	if err := connect.Ping(); err != nil {
		log.Fatalf("err: %v\n", err)
	}
	log.Printf("ping success\n")
}
```

## Error log

error msg: clickhouse [execute]:: 404 code: Code: 46, e.displayText() = DB::Exception: Unknown function timeZone. Maybe you meant: ['timezone','toTimeZone']: While processing timeZone() (version 21.3.9.83 (official build))

### Environment
* [ ] `clickhouse-go` version: 2.3.0
* [ ] Go version: 1.18.3
* [ ] ClickHouse version: 21.3.9.83

**Comment by jkaflik** [comment]
@FailedNamed any reason to use old `2.3.0` version? It is fixed in [`2.4.0`](https://github.com/ClickHouse/clickhouse-go/releases/tag/v2.4.0). Current version is 2.23.
