### ISSUE TITLE
How to use it in version 1.18 of go

### ISSUE THREAD

**Issue by maidivh** [ClickHouse/clickhouse-go#1321]
The version I am using is g1.18, which means I can only use it v2@v2.2.0 Version, when I started using it, it prompted me that I needed the CMP and Slices packages. However, at this time, G.1.18 did not have these two packages

**Comment by dedisuryadi** [comment]
Hi, I have the same issue, it seems some transitive dependency is requiring slice and cmp std lib that did not exist on go@1.18, for the time being I am using v1.5.4 ```go get -u github.com/ClickHouse/clickhouse-go@v1.5.4```

**Comment by jkaflik** [comment]
Any reason to use Go 1.18? It's out of support.
