### ISSUE TITLE
Query parameter not working for LIMIT and OFFSET

### ISSUE THREAD

**Issue by darshan-lukhi** [ClickHouse/clickhouse-go#1335]
When I try to pass the query parameters in offset and limit, I'm getting below error
`code: 26, message: Cannot parse quoted string: expected opening quote ''', got '1'`

Code snippest
```go
rows, err := conn.Query(
	context.Background(),
	"SELECT {column:Identifier} v, {str:String} s, {array:Array(String)} a FROM {database:Identifier}.{table:Identifier} LIMIT {limit:String} OFFSET 100",
	clickhouse.Named("num", "42"),
	clickhouse.Named("str", "hello"),
	clickhouse.Named("array", "['a', 'b', 'c']"),
	clickhouse.Named("column", "number"),
	clickhouse.Named("database", "system"),
	clickhouse.Named("table", "numbers"),
	clickhouse.Named("limit", "10"),
)
```

Is this the issue with library or am I doing wrong anything?

**Comment by jkaflik** [comment]
@darshan-lukhi `LIMIT ...` clause expects an integer value. You need to cast it properly:

```
SELECT * FROM system.numbers LIMIT {limit:Int}
```

Error message is messy. Parser fails due to unexpected string.

**Comment by darshan-lukhi** [comment]
@jkaflik  When I try to provide an uint8 value as a query parameter in ClickHouse, which states: "expected string value in NamedValue for query parameter." This is consistent with the validation logic that enforces NamedValue's Value to be a string only.

Reference: [ClickHouse Go - query_parameters.go#L47](https://github.com/ClickHouse/clickhouse-go/blob/9e269fafb0ff1944c7c72c06afe9cb7b0ad1d184/query_parameters.go#L47)

Here is my code reference:
```go
q := "SELECT {col1:Uint8}"
var col1 uint8 = 1
params := []any{
    clickhouse.Named("col1", col1),
}
```

Is this an intentional limitation? If it’s an oversight, I would be happy to fix it and submit a pull request.

**Comment by jkaflik** [comment]
@darshan-lukhi ClickHouse query parameters support multiple data types, but the client hasn't implemented them yet. It's not required to work with multiple data types as soon they are castable from a string.


```go
q := "SELECT {col1:Uint8}"
var col1 string = "1"
params := []any{
    clickhouse.Named("col1", col1),
}
```

will work.

**Comment by shubham-100ms** [comment]
@darshan-lukhi did you get a solution to this issue? I'm still not able to pass LIMIT dynamically.

**Comment by darshan-lukhi** [comment]
@shubham-100ms Yes, It seems issue with parameterized variable name. I just changed the parameter name `limit` to `size` and works for me.

**Comment by jkaflik** [comment]
@shubham-100ms, what is the error you get? Does the solution from https://github.com/ClickHouse/clickhouse-go/issues/1335#issuecomment-2202477082 help?

**Comment by shubham-100ms** [comment]
@darshan-lukhi changing the parameter name from `limit` to `size` worked.  Thanks a lot!

**Comment by shubham-100ms** [comment]
@jkaflik the error was the same as in the issue description:-

`code: 26, message: Cannot parse quoted string: expected opening quote ''', got '1'`.

I was able to make it work by changing the parameter name from `limit` to `size`. Is the `limit` parameter name a special name?

**Comment by jkaflik** [comment]
@shubham-100ms It's interesting. I can't reproduce it with ClickHouse directly, but I guess it might be a case for HTTP protocol.

What is the protocol you use?

**Comment by shubham-100ms** [comment]
@jkaflik I'm using the `clickhouse.Native` protocol; 

clickhouse-go version: `github.com/ClickHouse/clickhouse-go/v2 v2.28.0`
