### ISSUE TITLE
When deactivating a clickhouse cluster node, it is not possible to automatically connect to the normal node

### ISSUE THREAD

**Issue by Ri0nGo** [ClickHouse/clickhouse-go#1336]
## Observed

I have built a clickhouse cluster with 2 nodes, using http protocol to connect to the cluster, when I stop a node, querying the data will report an error.

detail descption:

1. Use clickhouse-go to connect clickhouse cluster, cluster have 2 node(node1, node2)
2. When I stop clickhouse node1, The go program won't connect, it lasts for a minute and then it still won't connect
3. When I restart clickhouse node1, The go program recovery connect

## Expected behaviour

**It is possible to switch to the normal clickhouse node**

## Code example

```go
// use http connect
func InitClickHouseClusterWithHttp(hosts []string, username, password, database string) (*sql.DB, error) {
	sqlDb := clickhouse.OpenDB(&clickhouse.Options{
		Addr: hosts,
		Auth: clickhouse.Auth{
			Database: database,
			Username: username,
			Password: password,
		},
		Protocol: clickhouse.HTTP,
	})
	return sqlDb, sqlDb.Ping()
}

// query data
func TestInitClickHouseClusterWithHttp(t *testing.T) {
	hosts := []string{
		"192.168.1.230:8128",
		"192.168.1.231:8129",
	}
	db, err := InitClickHouseClusterWithHttp(hosts, "username", "password", "tmp_db")
	if err != nil {
		fmt.Println(err)
	}

	for {
		rows, err := db.Query("SELECT uuid, ts, value FROM history_data order by ts limit 1")
		if err != nil {
			fmt.Println(err)
		}
		for rows.Next() {
			var (
				uuid  string
				ts    time.Time
				value float64
			)
			err = rows.Scan(&uuid, &ts, &value)
			if err != nil {
				fmt.Println(err)
			}
			fmt.Println(uuid, ts, value)
		}
		time.Sleep(1 * time.Second)
	}
}
```

## Error log

```log
Post "http://admin:***@192.168.1.230:8128?database=tmp_db&default_format=Native": dial tcp 192.168.1.230:8128: connectex: No connection could be made because the target machine actively refused it.
```

### Environment

* [x] `clickhouse-go`: github.com/ClickHouse/clickhouse-go/v2 v2.26.0 

* [x] Interface: `database/sql`

* [x] Go version:  go1.21.6 windows/amd64

* [x] Operating system: Windows11 23H2

* [x] ClickHouse version:  24.3.2.23

* [x] Is it a ClickHouse Cloud? no, build clickhouse cluster in local

* [x] ClickHouse Server non-default settings, if any: use defualt setting

* [x] `CREATE TABLE` statements for tables involved:

    ```sql
    CREATE TABLE tmp_db.history_data
    (
        `uuid` LowCardinality(String),
        `ts` DateTime CODEC(Delta(4),
     ZSTD(1)),
        `value` Float64 CODEC(Gorilla,
     ZSTD(1))
    )
    ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/tmp_history_data',
     '{replica}')
    PARTITION BY toDate(ts)
    ORDER BY (uuid,
     ts)
    SETTINGS index_granularity = 8192;
    ```

    

* [ ] Sample data for all these tables, use [[clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80)](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by jkaflik** [comment]
Hi @Ri0nGo

The client does not implement a failover mechanism for a broken nodes. (This can be implemented as an additional feature.)

I think about two approaches you can take to make it work as you expect:
1.  use a load-balancer in front of your nodes. It will take care of the failover switch.
2. implement a custom `DialStrategy logic`. It's a undocumented feature. Explanation in a PR: https://github.com/ClickHouse/clickhouse-go/pull/855

I would go with the first option as the most robust and resilient solution.
