### ISSUE TITLE
inserted time not correct

### ISSUE THREAD

**Issue by github1youlc** [ClickHouse/clickhouse-go#135]
I insert '2018-09-30 **00**:00:00' but got '2018-09-30 **08**:00:00' in database. There is 8 hours gap. My local timezone is UTC+8.

Here is my test code

```
func TestClickHouseLib(t *testing.T) {
	conn, _ := sqlx.Open("clickhouse", "tcp://localhost:9000")

	// insert data
	tx, err := conn.Begin()
	if err != nil {
		t.Error(err)
	}
	stmt, err := tx.Prepare("INSERT INTO locked_request (id, lock_id, process_time) VALUES (?, ?, ?)")
	if err != nil {
		t.Error(err)
	}
	idx := []uint32{1, 2, 3}
	for _, i := range idx {
		if _, err := stmt.Exec(i, uint64(4), "2018-09-30 00:00:00"); err != nil {
			t.Error(err)
		}
	}
	if err = tx.Commit(); err != nil {
		t.Error(err)
	}

	// get data
	var date []string
	if err := conn.Select(&date, `SELECT process_time from locked_request WHERE lock_id=4`); err != nil {
		t.Error(err)
	}

	t.Log(date)
}
```

And the result is 
`
	clickhouse_test.go:57: [2018-09-30T08:00:00+08:00 2018-09-30T08:00:00+08:00 2018-09-30T08:00:00+08:00 2018-09-30T08:00:00+08:00 2018-09-30T08:00:00+08:00 2018-09-30T08:00:00+08:00]
`

Result from clickhouse-client:

┌─id─┬─lock_id─┬────────process_time─┐
│  1 │       4 │ 2018-09-30 08:00:00 │
│  2 │       4 │ 2018-09-30 08:00:00 │
│  3 │       4 │ 2018-09-30 08:00:00 │
│  1 │       4 │ 2018-09-30 08:00:00 │
│  2 │       4 │ 2018-09-30 08:00:00 │
│  3 │       4 │ 2018-09-30 08:00:00 │
└────┴─────────┴─────────

go verison: 1.9.2
kshvakov/clickhouse commit version: 3414b6002bd44e72f96fe378b3103fec3248b8d6

**Comment by Yullin** [comment]
Yeah, default is time.UTC, you can change like #291

**Comment by kshvakov** [comment]
Done
