### ISSUE TITLE
Support to 9440 connections on Clickhouse Cloud using usql

### ISSUE THREAD

**Issue by calebeaires** [ClickHouse/clickhouse-go#1368]
## Observed

usql uses this library to create clickhouse connections ([github.com/ClickHouse/clickhouse-go/v2](https://github.com/ClickHouse/clickhouse-go)). 

Clickhouse Cloud permissions let you access only by SSL connection. The default `clickhouse-client` works with the credentials I've set, but when I tried to connect using `clickhouse-go` and `usql` with a connection string, the connection is closed.

## Expected behaviour
Connect using port 9440 like `clickhouse-client` does

## Code example

```bash
usql ch://user:pass@some-id.privatelink.azure.clickhouse.cloud:9440/my_database
```

The code above doesn't create a connection. I've tried with the port 9000 and 8443, it dosen't work either

## Error log

```bash
error: clickhouse: read: read tcp 172.172.172:59618->172.172.172:9440: read: connection reset by peer

```

### Environment
* [x] `clickhouse-go` version: 2.27
* [x] Interface: ClickHouse API / `database/sql` compatible driver: usql
* [x] Go version: 1.22
* [x] Operating system: linux
* [x] Is it a ClickHouse Cloud?

**Comment by jkaflik** [comment]
Hi @calebeaires 

I am not familiar with the `usql` tool; however, from their [ClickHouse driver ClickHouse implementation](https://github.com/xo/usql/blob/master/drivers/clickhouse/clickhouse.go), I understand they register `database/SQL` drivers.

My guess is DSN passed to `usql` is passed straight away to the ClickHouse client stdlib driver. Enabling TLS connection can be achieved by adding `secure=true` query parameter: https://clickhouse.com/docs/en/integrations/go#using-tls-1

Your command should be:

```
usql ch://user:pass@some-id.privatelink.azure.clickhouse.cloud:9440/my_database?secure=true
```

BTW next time please post such questions in repository discussions.
