### ISSUE TITLE
Incorrect column list parsing for multiline INSERT statements

### ISSUE THREAD

**Issue by Fiery-Fenix** [ClickHouse/clickhouse-go#1375]
## Observed
If in Batch operation INSERT statement defined as multiline go string - insert will failed with error `clickhouse [Append]:  clickhouse: expected N arguments, got M`
This happened because of incorrect Regex used in `extractNormalizedInsertQueryAndColumns` which not honor newlines in statement. Because of that Batch operation uses list of columns from ClickHouse table instead of list of columns in INSERT statement and batch fails with error
Fix: #1373

## Expected behavior
Correct insert without errors

## Code example
```go
package code

package main

import (
	"context"
	"database/sql"
	"fmt"

	_ "github.com/ClickHouse/clickhouse-go/v2"
)

func main() {
	dsn := "http://127.0.0.1:8123?dial_timeout=10s"

	conn, err := sql.Open("clickhouse", dsn)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer conn.Close()

	ctx := context.Background()
	if _, err := conn.ExecContext(ctx, "CREATE TABLE IF NOT EXISTS test (col1 String, col2 String, col3 String) ENGINE = MergeTree() ORDER BY tuple()"); err != nil {
		fmt.Println(err)
		return
	}

	tx, err := conn.BeginTx(ctx, nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer tx.Rollback()

	sql := `INSERT INTO test (
		col1,
		col2
	) VALUES (
	 	?,
		?
	)`
	stmt, err := tx.PrepareContext(ctx, sql)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer stmt.Close()

	_, err = stmt.ExecContext(ctx, "test", "test")
	if err != nil {
		fmt.Println(err)
		return
	}

	err = tx.Commit()
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

## Error log
```log
clickhouse [Append]:  clickhouse: expected 3 arguments, got 2
```

### Environment
* [x] `clickhouse-go` version: v2.27.1
* [x] Interface: `database/sql` compatible driver
* [x] Go version: 1.22.6
* [x] Operating system: Ubuntu 22.04
* [x] ClickHouse version: 24.6.2.17
* [x] Is it a ClickHouse Cloud? No

**Comment by SpencerTorres** [comment]
Fixed in #1373, available now in [v2.27.2](https://github.com/ClickHouse/clickhouse-go/releases/tag/v2.27.2)

Thanks!
