### ISSUE TITLE
LowCardinality support?

### ISSUE THREAD

**Issue by sundy-li** [ClickHouse/clickhouse-go#139]
Hi, will this awesome driver support  LowCardinality ?

**Comment by kshvakov** [comment]
Hi, no yet.

**Comment by agaurav** [comment]
@kshvakov It seems most of the bugs with `LowCardinality` have been fixed and the experimental feature label has also been removed. I will be great to have support for it in the most popular ch driver.

Have you started working on this ?
I will very much like to help out, in case you haven't.

**Comment by kshvakov** [comment]
@agaurav Yes, at the moment `LowCardinality` is production ready feature, I think I'll add this feature within a couple of weeks.

**Comment by agaurav** [comment]
@kshvakov It seems to be working fine for both `inserts` and `select` queries with `LowCardinality(String)` data type. 
I don't know the internals of the drivers so might be missing a case which needs to be taken care of.

sample code to test `insert` and `select`.

``` golang
package main

import (
	"github.com/jmoiron/sqlx"
	_ "github.com/kshvakov/clickhouse"
	"log"
	"time"
)

func main() {
	connect, err := sqlx.Open("clickhouse", "tcp://127.0.0.1:9000?debug=true")
	if err != nil {
		log.Fatal(err)
	}

        _, err = connect.Exec(`
                    CREATE TABLE IF NOT EXISTS test.low_cardinality (
                           d Date,
                           x UInt32,
                           s LowCardinality(String)
                      ) ENGINE = MergeTree
                      ORDER BY (d,x,s)
                 `)

	var (
		tx, errtx   = connect.Begin()
		stmt, errst = tx.Prepare("INSERT INTO test.low_cardinality (d,x,s) VALUES (?, ?, ?)")
	)

	if errtx != nil {
		log.Fatal(errtx)
	}

	if errst != nil {
		log.Fatal(errst)
	}

	defer stmt.Close()

	for i := 0; i < 100; i++ {
		if _, err := stmt.Exec(
			time.Now(),
			i,
			"s",
		); err != nil {
			log.Fatal(err)
		}
	}

	if err := tx.Commit(); err != nil {
		log.Fatal(err)
	}

	rows, err := connect.Query("SELECT d,x,s FROM test.low_cardinality")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	for rows.Next() {
		var (
			d time.Time
			x uint32
			s string
		)
		if err := rows.Scan(&d, &x, &s); err != nil {
			log.Fatal(err)
		}
		log.Println(d, x, s)
	}
}
```

**Comment by kshvakov** [comment]
@agaurav It's a compatibility mode, ClickHouse server convert `LowCardinality` types on its side (see https://github.com/yandex/ClickHouse/pull/3879). It's no good for read/write performance.

**Comment by negbie** [comment]
+1

**Comment by John-belt** [comment]
Hi this seems like a wonderful feature to have. Is it available yet??

**Comment by John-belt** [comment]
> @agaurav It's a compatibility mode, ClickHouse server convert `LowCardinality` types on its side (see [ClickHouse/ClickHouse#3879](https://github.com/ClickHouse/ClickHouse/pull/3879)). It's no good for read/write performance.

So does it work atleast as good as before without low cardinality??

**Comment by sundy-li** [comment]
I think this issue could be closed. The compatibility mode is by default.
We are using `LowCardinality` with `clickhouse-go` on the production for 2 years, it works well.
