### ISSUE TITLE
when inserting NULL empty value is inserted instead of DEFAULT

### ISSUE THREAD

**Issue by kanekv** [ClickHouse/clickhouse-go#1439]
## Observed

1. When inserting `nil` into a table with DEFAULT clause it inserts empty value, not DEFAULT, column is not nullable and insert_null_as_default=1

## Expected behavior
DEFAULT to be inserted

## Code example

```sql
CREATE TABLE A (
    foo String DEFAULT 'bar'
) ENGINE = MergeTree() ORDER BY foo;
```
```go
	stmt, err := r.chConn.PrepareBatch(context.Background(),
		"INSERT INTO A (foo) VALUES",
		driver.WithReleaseConnection())
	if err != nil {
		return err
	}
	err = stmt.Append(nil)
	if err != nil {
		return err
	}
	return stmt.Send()
```
After running the insert - empty string '' is inserted.
Running query in clickhouse inserts DEFAULT value:
```
83994477e1ae :) insert into A(foo) VALUES(null);
```

### Environment
* [x] `clickhouse-go` version: v2.30.0
* [x] Interface: ClickHouse API
* [x] ClickHouse version: 24.8.4.13
* [x] Is it a ClickHouse Cloud? NO

**Comment by Slach** [comment]
you need to use Nullable type in CREATE TABLE

` foo Nullable(String) DEFAULT 'bar'`

better to avoid Nullable field type

**Comment by kanekv** [comment]
@Slach I want to avoid using Nullable field type. How do I insert default value then? Clickhouse-client supports this type of query.

**Comment by Slach** [comment]
Default value inserted when you just skip column
```
CREATE TABLE A (
    id UInt64
    foo String DEFAULT 'bar'
) ENGINE = MergeTree() ORDER BY id;
```

then `INSERT INTO A(id)`
in this case for `foo` column will inserted DEFAULT expression

**Comment by kanekv** [comment]
@Slach In my case I can't skip columns (or it will be very cumbersome). Is it clickhouse limitation or something in the library?

**Comment by kanekv** [comment]
It seems this implementation is incorrect: https://github.com/ClickHouse/clickhouse-go/blob/main/lib/column/string.go#L98, is it possible at all to send NULL values in the protocol?

**Comment by Slach** [comment]
yes aggree library is incorrect ;(
standard clickhouse-client works good here
https://fiddle.clickhouse.com/62cd7254-81a4-41fd-8d09-56bdf5a6e32c

@jkaflik could you look?

**Comment by kanekv** [comment]
It seems library doesn't take into account `insert_null_as_default` which is on by default. If it was off then library still would be incorrect - probably better would be to return an error as clickhouse's docs say:
When this setting is off, then attempt to insert null would cause an exception and imo it's better to propagate it. Otherwise if this setting is on then default value would be used and if no default value, exception again.
So to me it makes sense to make all types Nullable* when determining column type here:
https://github.com/ClickHouse/clickhouse-go/blob/main/lib/column/column_gen.go#L38

**Comment by jkaflik** [comment]
@kanekv @Slach 

ClickHouse native format (used in batch insert) does not support defaults. It works if you put your values inline SQL query.

This is known limitation in ClickHouse. You can see more in the issue: https://github.com/ClickHouse/ClickHouse/issues/58662 (Ingestions team is working on prioritising this internally)

Mentioned setting has nothing to do with this.

cc @SpencerTorres

**Comment by jkaflik** [comment]
Let me close this issue. It can be found in search for a further reference.
