### ISSUE TITLE
Incorrect midnight time conversion for non UTC time

### ISSUE THREAD

**Issue by altush1983** [ClickHouse/clickhouse-go#150]
Time conversion in module https://github.com/kshvakov/clickhouse/blob/master/helpers.go returns wrong result for non UTC midnight time.
Sample code:
```
	n := time.Date(2018, 2, 6, 0, 0, 0, 0, time.Local)
	fmt.Println("EXPECTED:", n)
	rows := ch.Query("select * from (select toDate(17567) as d) where d=?", n)
	var t time.Time
	rows.Next()
	if err := rows.Scan(&t); err == nil {
		fmt.Println("CLICKHOUSE:", t)
	}
```

now returns:
EXPECTED: 2018-02-06 00:00:00 +0300 MSK
CLICKHOUSE: 2018-02-05 03:00:00 +0300 MSK

Possible fix is remove toDate part from formatTime:
```
func formatTime(value time.Time) string {
	/*	if (value.Hour() + value.Minute() + value.Second() + value.Nanosecond()) == 0 {
		return fmt.Sprintf("toDate(%d)", int(int16(value.Unix()/24/3600)))
	}*/
	return fmt.Sprintf("toDateTime(%d)", int(uint32(value.Unix())))
}
```

**Comment by kshvakov** [comment]
It's old bug, I'll try to fix it in next week.

**Comment by kshvakov** [comment]
ClickHouse have a bug https://github.com/yandex/ClickHouse/issues/2011. I'm working on a problem in the driver :)

**Comment by yuyutime** [comment]
Date/DateTime logic for midnight seems to be broken somewhere not only for non_UTC time (or needs better documentation/examples).

In my code I have:
`var Timestamp time.Time`
where Timestamp value is derived from filenames like `190412_0000_UTC.pln`, `190412_0015_UTC.pln`
For these sample filenames with query:

`ch.conn.QueryRow(queryStr, clickhouse.Date(Timestamp), clickhouse.DateTime(Timestamp))`

for the first file I see incorrect query sent:

```
clickhouse][connect=1][prepare] SELECT count() FROM NodeTraffic WHERE d=? and dt=?
[clickhouse][connect=1][send query] SELECT count() FROM NodeTraffic WHERE d=toDate(17998) and dt=toDate(17998)
```

while for the second file sent query works as expected:

```
[clickhouse][connect=1][prepare] SELECT count() FROM NodeTraffic WHERE d=? and dt=?
[clickhouse][connect=1][send query] SELECT count() FROM NodeTraffic WHERE d=toDate(17998) and dt=toDateTime(1555028100)
```

**Comment by kshvakov** [comment]
@yuyutime You can try master branch

**Comment by TrueCarry** [comment]
![image](https://user-images.githubusercontent.com/5431520/73225670-86b64b80-417e-11ea-87e5-34055561a342.png)
Caught very tricky issue today, because of automatic toDate conversion. I wanted to compare datetime column with value and it always breaking on midnight, because for some reason driver uses toDate func. Is there a reason why it cannot be disabled?

**Comment by GithubUser5462** [comment]
Just stumbled on this problem today.
Any news regarding this issue?

**Comment by valiantx** [comment]
Two years later,  this issue still is opened. what happened?

**Comment by tsingsun** [comment]
I PR in #440

**Comment by kshvakov** [comment]
Fixed in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
