### ISSUE TITLE
dose clickhouse support tcp keepalive setting on linux?

### ISSUE THREAD

**Issue by YZerui** [ClickHouse/clickhouse-go#156]
I found a issue that my server(ubuntu 14.04) leave many ESTABLISHED tcp connections on port 9000，which is clickhouse-server listening on，I try to use lsof -i:9000 on my server to print message,the following is what i see:

```
clickhous 30830 root 6150u  IPv4 707178178      0t0  TCP s83:9000->s135:23136 (ESTABLISHED)
clickhous 30830 root 6151u  IPv4 707172048      0t0  TCP s83:9000->s135:23147 (ESTABLISHED)
clickhous 30830 root 6159u  IPv4 708880791      0t0  TCP s83:9000->s135:53031 (ESTABLISHED)
clickhous 30830 root 6164u  IPv4 708882809      0t0  TCP s83:9000->s135:52984 (ESTABLISHED)
clickhous 30830 root 6207u  IPv4 708882135      0t0  TCP s83:9000->s135:53109 (ESTABLISHED)
clickhous 30830 root 6324u  IPv4 708880829      0t0  TCP s83:9000->s135:53137 (ESTABLISHED)
clickhous 30830 root 6333u  IPv4 708882161      0t0  TCP s83:9000->s135:53128 (ESTABLISHED)
clickhous 30830 root 6446u  IPv4 742904993      0t0  TCP s83:9000->s135:10316 (ESTABLISHED)
clickhous 30830 root 6453u  IPv4 742902389      0t0  TCP s83:9000->s135:10027 (ESTABLISHED)
clickhous 30830 root 6537u  IPv4 746585601      0t0  TCP s83:9000->s135:23001 (ESTABLISHED)
clickhous 30830 root 6563u  IPv4 746286725      0t0  TCP s83:9000->s135:22075 (ESTABLISHED)
clickhous 30830 root 6898u  IPv4 722455529      0t0  TCP s83:9000->s135:12458 (ESTABLISHED)
clickhous 30830 root 6906u  IPv4 733445906      0t0  TCP s83:9000->s135:31813 (ESTABLISHED)
clickhous 30830 root 6931u  IPv4 742912799      0t0  TCP s83:9000->s135:12678 (ESTABLISHED)
clickhous 30830 root 6975u  IPv4 744398592      0t0  TCP s83:9000->s135:31891 (ESTABLISHED)
clickhous 30830 root 6984u  IPv4 722456808      0t0  TCP s83:9000->s135:12490 (ESTABLISHED)
clickhous 30830 root 7126u  IPv4 722455530      0t0  TCP s83:9000->s135:12463 (ESTABLISHED) 
..........
..........
..........
```
the server s83 make many connections with s135，but i only have one script on s135，and the script only make a connection with s83 at one time. so i guess if the above port on s135 is existing, I run lsof -i:23136 on s135 and not found anything. the connection:

> clickhous 30830 root 6150u  IPv4 707178178      0t0  TCP s83:9000->s135:23136 (ESTABLISHED)

maybe is dead but still exist on s83 ，it exist when I am back in a few days to see，how can i  release the connection on s83?

**Comment by kshvakov** [comment]
At the moment driver doesn't support keep alive, I'll investigate it and add in the future.

**Comment by YZerui** [comment]
> At the moment driver doesn't support keep alive, I'll investigate it and add in the future.

i don't know how to solve the proplem that exist many idle ESTABLISHED tcp connections on server except for keep alive setting，can you make some suggest for me?

**Comment by kshvakov** [comment]
@YZerui You can set max_open/max_idle and  connection life time 

https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns  
https://golang.org/pkg/database/sql/#DB.SetMaxIdleConns
https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime

Example

```go 
conn,_:=sql.Open("clickhouse", dsn)
conn.SetMaxOpenConns(10)
conn.SetMaxIdleConns(5)
conn.SetConnMaxLifetime(time.Hour)
```

**Comment by forward32** [comment]
@YZerui Using version 1.3.7 I don't have such problems.

I have single tcp connection which is alive for a long time and all transactions are done via this connection:
```
IPv4 5056900      0t0      TCP dell:59606->172.25.0.100:9000 (ESTABLISHED)
```
