### ISSUE TITLE
could not load time location on windows

### ISSUE THREAD

**Issue by rekby** [ClickHouse/clickhouse-go#162]
When start compiled binary on windows computer without installed golang the library can't work with server with error:
could not load time location...

Is it possible ignore server timezone and work with local timezone?

Or set name of local time zone and use local timezone instead load it by name if local zone name equal to server timezone?

**Comment by BlenderRUS** [comment]
Yep. The same issue in Windows. And no problems in Linux.

**Comment by tmathews** [comment]
Has anyone found a workaround for this?

**Comment by tmathews** [comment]
Quick hack to get up and running:
```
diff --git a/lib/data/server_info.go b/lib/data/server_info.go
index a6c90be..927b8dd 100644
--- a/lib/data/server_info.go
+++ b/lib/data/server_info.go
@@ -2,7 +2,7 @@ package data

 import (
        "fmt"
-       //"io"
+       "runtime"
        "time"

        "github.com/ClickHouse/clickhouse-go/lib/binary"
@@ -35,13 +35,21 @@ func (srv *ServerInfo) Read(decoder *binary.Decoder) (err error) {
                if err != nil {
                        return fmt.Errorf("could not read server timezone: %v", err)
                }
-               if srv.Timezone, err = time.LoadLocation(timezone); err != nil {
+               // TODO fix this! time.LoadLocationFromTZData(timezone, )
+               if srv.Timezone, err = getTimezone(timezone); err != nil {
                        return fmt.Errorf("could not load time location: %v", err)
                }
        }
        return nil
 }

+func getTimezone(timezone string) (*time.Location, error) {
+       if runtime.GOOS == "windows" && timezone == "posixrules" {
+               timezone = "Local"
+       }
+       return time.LoadLocation(timezone)
+}
+
 func (srv ServerInfo) String() string {
        return fmt.Sprintf("%s %d.%d.%d (%s)", srv.Name, srv.MajorVersion, srv.MinorVersion, srv.Revision, srv.Timezone)
 }
```

**Comment by Tokumicn** [comment]
I encountered the situation  was under windows server and not installed golang.

main.go  main func ：

// ZONEINFOPATH ==> zoneinfo.zip
err := syscall.Setenv("ZONEINFO", ZONEINFOPATH)
	if err != nil {
		log.Fatal(err)
	}


go/src/time/zoneinfo.go：

// The time zone database needed by LoadLocation may not be
// present on all systems, especially non-Unix systems.
// LoadLocation looks in the directory or uncompressed zip file
// named by the ZONEINFO environment variable, if any, then looks in
// known installation locations on Unix systems,
// and finally looks in $GOROOT/lib/time/zoneinfo.zip.

**Comment by rekby** [comment]
Now it has workaround on application side:
```
import _ "time/tzdata" 
```

https://golang.org/pkg/time/tzdata/

**Comment by Hakob** [comment]
Approving. The solution above is working
