### ISSUE TITLE
Reading mode for decimal type

### ISSUE THREAD

**Issue by neverlee** [ClickHouse/clickhouse-go#169]
When 'select' decimal type data with "github.com/go-sql-driver/mysql", it was treated as a 'float'.
When 'select' decimal type data with "github.com/kshvakov/clickhouse", it was treated as a "int" with enlarged.
This is inconvenient for some case.
So, could you agree this solution?
Add a option, then we can choose the reading mode for decimal type.
If you agree, I will pull a request for this.

**Comment by kshvakov** [comment]
In [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2) we use `shopspring/decimal` for Decimal types.
