### ISSUE TITLE
Trouble inserting time "0000-00-00 00:00:00"

### ISSUE THREAD

**Issue by bsadryland** [ClickHouse/clickhouse-go#177]
Trying to insert a zero date, I'm having trouble:
`stmt, err := tx.Prepare("INSERT INTO my_table (my_date_time_col) values (?)")`
`_, err := stmt.Exec("0000-00-00 00:00:00")`

I get the following error from Exec:
`parsing time "0000-00-00 00:00:00": month out of range`

If I convert the date string to the "zero" time like this "0000-01-01 00:00:00", the datetime inserted in DB is "2041-07-13 01:04:00".
Any idea how we can insert a zero datetime ?

**Comment by finnan444** [comment]
@CyrilleLilas is my_date_time_col of type `Nullable(DateTime)`?
If so, try to pass pointer to variable:
```golang
var a *time.Time
if _, err := stmt.Exec(a); err != nil {
	log.Fatal(32, err)
}
b := time.Now()
a = &b
if _, err := stmt.Exec(a); err != nil {
	log.Fatal(32, err)
}
```
In the example above first row will be null in DB, second current time

**Comment by CyrilleLilas** [comment]
@finnan444 Thanks for your reply ; no, it's not a nullable column.
That would probably be a solution, but I didn't want to use Nullable to avoid affecting negatively the performances.

**Comment by finnan444** [comment]
@CyrilleLilas if it is not nullable, you can use pointer, database will insert null without error

**Comment by tetafro** [comment]
Same for the `Date`-type column: I get `1974-10-01`, when trying to insert `time.Time{}`. Also query execution just hangs forever when I use empty pointer value.

Here's minimal example:
```sql
CREATE TABLE tbl (dt Date) ENGINE = MergeTree() ORDER BY dt
```
```go
package main

import (
    "database/sql"
    "time"

    _ "github.com/kshvakov/clickhouse"
)

func main() {
	db, err := sql.Open("clickhouse", "tcp://localhost:9000")
	if err != nil {
		panic(err)
	}
	tx, err := db.Begin()
	defer tx.Commit()

	stmt, err := tx.Prepare("INSERT INTO tbl (dt) VALUES (?)")
	if err != nil {
		panic(err)
	}

	var t time.Time
	if _, err := stmt.Exec(t); err != nil {
		panic(err)
	}
}
```
```
SELECT * FROM tbl

┌─────────dt─┐
│ 1974-10-01 │
└────────────┘
```

For pointer value `var t time.Time` as I said - nothing happening, program hangs on `stmt.Exec`

**Comment by tetafro** [comment]
Just discovered that `time.Unix(0, 0)` is converting to `0000-00-00` (instead of `1970-01-01`). So looks like a a workaround, though a bit not obvious.

**Comment by finnan444** [comment]
> Just discovered that `time.Unix(0, 0)` is converting to `0000-00-00` (instead of `1970-01-01`). So looks like a a workaround, though a bit not obvious.

Yeah, nice solution, works both for Date and Datetime

**Comment by tetafro** [comment]
Apparently this is the source of the problem: https://github.com/yandex/ClickHouse/issues/3470

**Comment by finnan444** [comment]
> Just discovered that `time.Unix(0, 0)` is converting to `0000-00-00` (instead of `1970-01-01`). So looks like a a workaround, though a bit not obvious.

@tetafro I think it is a proper way of getting zero date, because standard time golang package defines isZero method which checks sec and nanosec as in your example
```go
func (t Time) IsZero() bool {
	return t.sec() == 0 && t.nsec() == 0
}
```

**Comment by tetafro** [comment]
> standard time golang package defines isZero method which checks sec and nanosec

Standard time golang package checks sec and nanosec since `0001-01-01 00:00:00`, not since `1970-01-01 00:00`.

```
// IsZero reports whether t represents the zero time instant,
// January 1, year 1, 00:00:00 UTC.
func (t Time) IsZero() bool {
	return t.sec() == 0 && t.nsec() == 0
}
```

https://play.golang.org/p/JlmIyQzItD5
