### ISSUE TITLE
Is date time handled with a 32bit code ?

### ISSUE THREAD

**Issue by Stephane-Thales** [ClickHouse/clickhouse-go#191]
I'm inserting in Clickhouse from Go some datetime that have the value 1900-01-01 00:00:00 
In Clickhouse the value end-up being : 2036-02-07 06:28:16

That look like a 32bit limitation. 
Go field is defined as time.time that is 64bit, so it should manage the datetime properly.

Internal clickhouse test show that Clickhouse should store it as 0000-00-00 00:00:00.

I just want to get a clarification of the exact behavior of this librairy in that case, as I can workaround it.
==> Can you confirm that the transformation to  2036-02-07 06:28:16 come from here ?
==> What is the max-min datetime that can be managed, and what is the behavior when out of range ?

Thanks

**Comment by kshvakov** [comment]
Hi, yes it's a 32bit limitation. ClickHouse can store dates between 1970 and 2105 years.
That transformation is a bug, the driver must checks dates.
