### ISSUE TITLE
How do I set up session parameter values, from a go client

### ISSUE THREAD

**Issue by amchakra789** [ClickHouse/clickhouse-go#205]
Hi,

We are using views on top of tables and querying the view with the partitioning column in the predicate clause.

To optimize the view from a local session, we are using 

set enable_optimize_predicate_expression=1;

How do we set this parameter in a session, when we are querying from inside a go client.

**Comment by forward32** [comment]
You can specify it in DSN, e.g. my dns look like:
```
"tcp://172.25.0.100:9000?database=test&debug=true&max_memory_usage=1000000000&max_execution_speed=500000&max_execution_time=5"
```

Check this file https://github.com/kshvakov/clickhouse/blob/master/query_settings.go to find you option.
