### ISSUE TITLE
Question on block WriteXXX error handling

### ISSUE THREAD

**Issue by cw9** [ClickHouse/clickhouse-go#210]
Hi,

I'm using the `block.WriteXXX` functions to insert data to CH, and I have a question on error handling. 

In the [example](https://github.com/kshvakov/clickhouse/blob/aeedb7b9d0584f393905447021238b5c6e9c5154/examples/columnar.go#L114) the errors are ignored from those write functions. When would errors occur in these `WriteXXX` functions? 

If I'm writing a batch of 10K rows and `row100` failed on `column3`, how do I skip `row100` and write the rest of the batch? For example can I rollback the data from `row100` on `column1` and `column2` and write the rest of data?

Thanks

**Comment by vahid-sohrabloo** [comment]
block.WriteXXX  Only Write to bufio.Writer (and offset in Array).
Only after commit, all buffer will be sent to the server.
