### ISSUE TITLE
driver: bad connection when no query for hours

### ISSUE THREAD

**Issue by tlightsky** [ClickHouse/clickhouse-go#214]
all our etl service which dong insert into table once per hours will got 
this `bad connection` error
driver version is `1.3.11`

**Comment by forward32** [comment]
CH has `idle_connection_timeout` option with default value 1 hour. If you do nothing within this time CH closes your connection.

Solutions:
1) just increase this value
2) use separate goroutine with some activity (e.g. ping)

**Comment by tlightsky** [comment]
@forward32 
we suspect that too, 
and we tried a db.Ping() every 30 second,
still got the bad connection error

**Comment by forward32** [comment]
Hm, I use second approach (ping once in minute) and it works fine for me.

Try to:
1) check your value of `idle_connection_timeout`
2) check error logs in CH
3) capture traffic between your app and CH and investigate it for some anomalies

**Comment by tlightsky** [comment]
@forward32 
for now, we try to reconnect if it failed for the first time insertion,
will try to investigate the reason later, 
thanks for reply

**Comment by awskii** [comment]
Previously, db.Ping did not return error at all (driver bug), so you needed to `SELECT 1;` in a for loop, and reconnect, if select fails. 
Looks like something never changes, and that's why I'm here.

**Comment by kshvakov** [comment]
ResetSession added in [V2](https://github.com/ClickHouse/clickhouse-go/blob/v2/clickhouse_std.go#L49)
