### ISSUE TITLE
arguments count error with toStartOfInterval

### ISSUE THREAD

**Issue by wormcc** [ClickHouse/clickhouse-go#218]
When i use this lib with sqlx, it gives the error: expected 3 arguments, got 4
SQL:
`SELECT avg(data) AS data, toStartOfInterval(time, INTERVAL ?) AS timeInterval FROM iotdata WHERE sensor=? AND time>=? AND time<=? GROUP BY timeInterval ORDER BY timeInterval DESC` 

Bind:
`db.Select(&data, query, timeInterval, sensor, startTime, endTime)`

Does this cause by the keyword INTERVAL? 
Thanks.

**Comment by d5n** [comment]
As described in the error there is an additional argument (timeInterval) being passed in your db.Select(...)

**Comment by Felixoid** [comment]
@d5n it shouldn't be "additional". There are 4 `?` in the query.

**Comment by d5n** [comment]
@Felixoid you are right missed the first '?' in the function. This seems related to #158

**Comment by pierrre** [comment]
I figured out it's related to `toStartOfInterval(time, INTERVAL ?)`.
It "works" with `toStartOfInterval(time, ?)`, but then the driver complains about invalid type:
```
Illegal type String of argument of function toStartOfInterval. Should be an interval of time
```

**Comment by pierrre** [comment]
Try something like this:
```
toStartOfInterval(time, toIntervalSecond(?))
```
and give a number of seconds

You can use functions from https://clickhouse.tech/docs/en/sql-reference/functions/type-conversion-functions/#function-tointerval
