### ISSUE TITLE
Support selecting Array(Array(T)) column

### ISSUE THREAD

**Issue by cw9** [ClickHouse/clickhouse-go#224]
Hi,

Is `Array(Array(T))` column supported in select queries? 

I saw [this](https://github.com/kshvakov/clickhouse/blob/4ca0da588f7f562145a0bca218f4d89d174d5ac9/clickhouse_test.go#L1247) test has been commented out and it seems to be failing when I uncomment it.

Thanks,
Chao

**Comment by kshvakov** [comment]
Yes, see [V2](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/array_test.go#L75)
