### ISSUE TITLE
currency (String): unexpected type currency.Currency

### ISSUE THREAD

**Issue by dangerousvasil** [ClickHouse/clickhouse-go#232]
Возникает проблема с кастомными типами.
Мы делаем по инструкции (к пакету database/sql)объявляем к объекту метод

func (s *Currency) Value() (driver.Value, error)

по идее этот метод должен вернуть значение для колонки в БД
но не получается конвертировать автоматически,
через метод!

приходится делать структуру со строками (с типами строк вместо кастомных)
переводить структуру в(через json) структуру(с типами строк вместо кастомных) и её писать в базу почему в структуру, а не в мапу ответ:
разные типы дат автоматом матчатся уже легче.

какой метод нам нужно объявить чтобы нормально структура с кастомными типами писалась в бд????

P.S. у нас много разных баз и у объекта есть методы для них: кассандра (MarshalCQL,UnmarshalCQL), pg&mysql (Value,Scan), json (MarshalJSON/UnmarshalJSON), String() string 
и все работает

**Comment by kshvakov** [comment]
Привет, сделай пример для воспроизведения проблемы со структурой таблицы и кодом на Го

**Comment by dangerousvasil** [comment]
https://github.com/dangerousvasil/clickhouse-newfunc

вот тут 
склонировать запустить

```
main.go:44: save start 
[clickhouse]host(s)=127.0.0.1:9000, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=1, server=0 -> 127.0.0.1:9000
[clickhouse][connect=1][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=1][hello] <- ClickHouse 19.16.54427 (Europe/Moscow)
[clickhouse][connect=1][begin] tx=false, data=false
[clickhouse]host(s)=127.0.0.1:9000, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=2, server=0 -> 127.0.0.1:9000
[clickhouse][connect=2][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=2][hello] <- ClickHouse 19.16.54427 (Europe/Moscow)
[clickhouse][connect=2][prepare] CREATE TABLE IF NOT EXISTS test_currency
(
    id       Nullable(Int32),
    currency Nullable(FixedString(3))
)
    engine = Memory;
[clickhouse][connect=2][send query] CREATE TABLE IF NOT EXISTS test_currency
(
    id       Nullable(Int32),
    currency Nullable(FixedString(3))
)
    engine = Memory;
[clickhouse][connect=2][process] <- end of stream
[clickhouse][connect=2][stmt] close
[clickhouse][connect=1][prepare] INSERT INTO test_currency (id,currency) VALUES (?,?);
[clickhouse][connect=1][send query] INSERT INTO test_currency (id,currency) VALUES 
[clickhouse][connect=1][read meta] <- data: packet=1, columns=2, rows=0
Custom unmarshall
main.go:66: {11501818 RUR}
main.go:69: currency (FixedString(3)): unexpected type currency.Currency

```

**Comment by dangerousvasil** [comment]
изначально мы создаём модели через протобаф 
потом обогащаем методами для работами с бд

**Comment by dangerousvasil** [comment]
разобрался

https://golang.org/pkg/database/sql/#NullBool.Value

ненужна звездочка.
