### ISSUE TITLE
leakypool occupy too much memory 

### ISSUE THREAD

**Issue by loloxiaoz** [ClickHouse/clickhouse-go#233]
Hi, I profiled memory usage for my program, as shown below
<img width="956" alt="leakpool" src="https://user-images.githubusercontent.com/6119077/69206956-31abf700-0b89-11ea-8409-91a6336eab75.png">
I almost insert 2,000,000,000 rows, used WriteBlock Function , and leakypool occupied almost 1G memory, and it would not release memory any more
How can I optimize memory usage ?

**Comment by ersivv** [comment]
How can I optimize memory usage ?

**Comment by kshvakov** [comment]
Hi, set `pool_size` https://github.com/ClickHouse/clickhouse-go#dsn

**Comment by zifter** [comment]
I faced with the same problem and `pool_size` can't help here - leakypool allocates too much memory and this memory is not returning back to leakypool:
1. We allocate chunk from leaky pool (internally in `WriteBuffer.New`) for each column:
```
func (block *Block) Reserve() {
	if len(block.buffers) == 0 {
		block.buffers = make([]*buffer, len(block.Columns))
		block.offsets = make([]offset, len(block.Columns))
		for i := 0; i < len(block.Columns); i++ {
			var (
				offsetBuffer = wb.New(wb.InitialSize)
				columnBuffer = wb.New(wb.InitialSize)
			)
			block.buffers[i] = &buffer{
				Offset:       binary.NewEncoder(offsetBuffer),
				Column:       binary.NewEncoder(columnBuffer),
				offsetBuffer: offsetBuffer,
				columnBuffer: columnBuffer,
			}
		}
	}
}
```
2. On commit, we are resetting block and delete them all. So, we don't reuse them:
```
func (block *Block) Reset() {
	block.NumRows = 0
	block.NumColumns = 0
	for _, buffer := range block.buffers {
		buffer.reset()
	}
	{
		block.offsets = nil
		block.buffers = nil
	}
}
```
3. So, if we have a look at `reset` method in `WriteBuffer`, we will see that last chunk is not recycling:
```
func (wb *WriteBuffer) Reset() {
	if len(wb.chunks) == 0 {
		return
	}
	// Recycle all chunks except the last one
	chunkSizeThreshold := cap(wb.chunks[0])
	for _, chunk := range wb.chunks[:len(wb.chunks)-1] {
		// Drain chunks smaller than the initial size
		if cap(chunk) >= chunkSizeThreshold {
			leakypool.PutBytes(chunk[:0])
		} else {
			chunkSizeThreshold = cap(chunk)
		}
	}
	// Keep the largest chunk
	wb.chunks[0] = wb.chunks[len(wb.chunks)-1][:0]
	wb.chunks = wb.chunks[:1]
}
```
4. So, as a result allocated chunk we will be freed only by GC.

So, this behavior of block leads to lots of allocation without any re-usage of allocated chunk.
And, unfortunately, it became dramatically worse for insert request with lots of columns.

**Comment by kshvakov** [comment]
@zifter This is easy task, I'll fix it when I have time)

**Comment by zifter** [comment]
@kshvakov agree)
If you wish, I can do it

**Comment by kshvakov** [comment]
@zifter OK )

**Comment by zifter** [comment]
done, will be waiting for you review!

**Comment by kshvakov** [comment]
@zifter OK, let's try it)
