### ISSUE TITLE
How initialize the result of groupArray function of the ClickHouse to the array in Golang?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [ClickHouse/clickhouse-go#237]
First of all, thank you for this wonderful project! :)

In my Golang application, I make a request to the **ClickHouse** database via this package. This query which I make return always only one record and it's an array of integers. Is there any way to initialize that result to the array in Golang?

```
var ids []int

ids, err := database.ClickHouse.Exec("SELECT groupArray(ID) FROM layers;")
if err != nil {
    fmt.Println(err)
}
```

I tried such code but it raises an error: `cannot assign Result to ids (type []int) in multiple assignment.`

**Comment by kshvakov** [comment]
Use the `Query*` methods https://golang.org/pkg/database/sql/#Conn.QueryRowContext
