### ISSUE TITLE
Mac: Stuck while connecting

### ISSUE THREAD

**Issue by iambudi** [ClickHouse/clickhouse-go#245]
Hi,

I try to connect to yandex insinde docker container with port configured to 8123. It failed due to connection time out when finding yandex server.

> [clickhouse]host(s)=localhost:8123, database=default, username=default
> [clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=1, server=0 -> [::1]:8123
> [clickhouse][connect=1][hello] -> Golang SQLDriver 1.1.54213
> [clickhouse][connect=1][connect] read error: read tcp [::1]:61510->[::1]:8123: i/o timeout
> [clickhouse]host(s)=localhost:8123, database=default, username=default
> [clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=2, server=0 -> [::1]:8123
> [clickhouse][connect=2][hello] -> Golang SQLDriver 1.1.54213
> [clickhouse][connect=2][connect] read error: read tcp [::1]:61521->[::1]:8123: i/o timeout
> [clickhouse]host(s)=localhost:8123, database=default, username=default
> [clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=3, server=0 -> [::1]:8123
> [clickhouse][connect=3][hello] -> Golang SQLDriver 1.1.54213

I try using another [golang driver](https://github.com/leprosus/golang-clickhouse), it works fine. Any clue on how to fix my connection problem?

Thank you.
 `

**Comment by kshvakov** [comment]
You must use the `9000` port for this driver
