### ISSUE TITLE
golang database/sql scan has some performace problems

### ISSUE THREAD

**Issue by ZonghaoWang** [ClickHouse/clickhouse-go#251]
https://github.com/lib/pq/issues/771

**Comment by ZonghaoWang** [comment]
scan to a int32 may cost 300us

**Comment by kshvakov** [comment]
Hi, I know https://github.com/golang/go/issues/22544. The only solution is to create a driver that can work without a `database/sql` package

**Comment by kshvakov** [comment]
Fixed in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2#benchmark)
