### ISSUE TITLE
Is it possible to use 8123 http port?

### ISSUE THREAD

**Issue by stepanselyuk** [ClickHouse/clickhouse-go#261]
Hello,
is it possible to use 8123 (http) port instead of 9000 (tcp) ? 
I'm asking because I want to use https://github.com/nikepan/clickhouse-bulk in conjunction with this driver.

**Comment by kshvakov** [comment]
No, this driver uses native protocol

**Comment by Slach** [comment]
try look to other libraries https://clickhouse.tech/docs/en/interfaces/third-party/client_libraries/
