### ISSUE TITLE
Error in parsing a query

### ISSUE THREAD

**Issue by runicelf** [ClickHouse/clickhouse-go#269]
Branch: v1.4.0

When I am executing this code, I am got a error below:
Look like a bug in parsing query.
```
query := `select * from db.table where hasAny(status, ['\"\'\\|/<>?']);`
db.QueryContext(ctx, query)
```
Error: sql: expected 1 arguments, got 0

**Comment by coraxster** [comment]
looks like no need to escape `"`
`select '"\'\\|/<>?';` works fine

**Comment by runicelf** [comment]
`select '\'>?';`
Does this request work for you? I get a mistake with it.
