### ISSUE TITLE
A big performace problems

### ISSUE THREAD

**Issue by ayaya118** [ClickHouse/clickhouse-go#273]
with : /debug/pprof/heap

D:\>go tool pprof -inuse_space heap
File: kafka
Build ID: a50f74f51a2233714862ca83d368b0a68d75c07b
Type: inuse_space
Time: May 13, 2020 at 11:45am (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 3801.82MB, 99.35% of 3826.67MB total
Dropped 103 nodes (cum <= 19.13MB)
Showing top 10 nodes out of 18
      flat  flat%   sum%        cum   cum%
 1911.09MB 49.94% 49.94%  1911.09MB 49.94%  github.com/ClickHouse/clickhouse-go/
lib/binary.NewCompressReader (inline)
 1890.23MB 49.40% 99.34%  1890.23MB 49.40%  github.com/ClickHouse/clickhouse-go/
lib/binary.NewCompressWriter (inline)
    0.50MB 0.013% 99.35%  1911.59MB 49.95%  github.com/ClickHouse/clickhouse-go/
lib/binary.NewDecoderWithCompress (inline)
         0     0% 99.35%  3812.86MB 99.64%  database/sql.(*DB).Begin
         0     0% 99.35%  3812.86MB 99.64%  database/sql.(*DB).BeginTx
         0     0% 99.35%  3812.86MB 99.64%  database/sql.(*DB).begin
         0     0% 99.35%  3812.86MB 99.64%  database/sql.(*DB).conn
         0     0% 99.35%  3811.86MB 99.61%  database/sql.dsnConnector.Connect
         0     0% 99.35%  3811.86MB 99.61%  github.com/ClickHouse/clickhouse-go.
(*bootstrap).Open
         0     0% 99.35%  3811.86MB 99.61%  github.com/ClickHouse/clickhouse-go.
Open (inline)
(pprof)

**Comment by ayaya118** [comment]
![112323](https://user-images.githubusercontent.com/4150721/81769723-f0314e80-9510-11ea-9435-682a9ba63e24.png)

**Comment by Slach** [comment]
@ayaya118 could you also add minimal reproducible golang code what exactly you doing?

**Comment by kshvakov** [comment]
Sorry, but I don't see the problem. What do you mean?

**Comment by ayaya118** [comment]
this is the code:

![1](https://user-images.githubusercontent.com/4150721/81800473-79fb0f00-9545-11ea-8ad8-d0c0561ffc1e.png)

**Comment by ayaya118** [comment]
and with high concurrency!

![2](https://user-images.githubusercontent.com/4150721/81800628-b3cc1580-9545-11ea-95ac-2341aac0944d.png)

**Comment by ayaya118** [comment]
"tail -n 100 /var/log/messages" show:
May 13 15:19:04 faceverifi-online-248 kernel: Out of memory: Kill process 31774 (kafka) score 776 or sacrifice child
May 13 15:19:04 faceverifi-online-248 kernel: Killed process 31774 (kafka) total-vm:8790520kB, anon-rss:6397300kB, file-rss:4kB, shmem-rss:0kB

**Comment by kshvakov** [comment]
> and with high concurrency!

OK, you must use a small number of connections to insert.

**Comment by ayaya118** [comment]
> > and with high concurrency!
> 
> OK, you must use a small number of connections to insert.

yes,it`s work
