### ISSUE TITLE
DateTime parse timezone not right when inserting

### ISSUE THREAD

**Issue by magicgdc** [ClickHouse/clickhouse-go#278]
Hello,

My timezone is UTC+8, and i found something wrong when inserting. I read the source code, and found the following function. 

Why did you parse datetime sting using "time.UTC" instead of "dt.TimeZone" ? Is that a bug or there is something I did not recognize? 

Thank you !

![image](https://user-images.githubusercontent.com/7950701/83237462-89c25680-a1c7-11ea-8f15-096225f40546.png)

**Comment by kshvakov** [comment]
Fixed In [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
