### ISSUE TITLE
Connect to a clickhouse server hosted in kubernetes behind an ingress

### ISSUE THREAD

**Issue by DrissiReda** [ClickHouse/clickhouse-go#281]
I'm trying to connect to my clickhouse instance that's behind an ingress, I can't seem to figure out how:
Things I've tried:

```
CLICKHOUSE_HOST="example.host.com/clickhouse/:443" #Error: Missing port in address
CLICKHOUSE_HOST="https://example.host.com/clickhouse/" #Error: no such host

```

Any suggestions on how use this driver with an ingress?

**Comment by blinkov** [comment]
@DrissiReda this library works over ClickHouse's custom TCP protocol, not HTTP(S), so you'll likely need to find another way to proxy the connection to a ClickHouse server.

**Comment by Slach** [comment]
@DrissiReda try https://github.com/mailru/go-clickhouse/
