### ISSUE TITLE
NumInput() return wrong number

### ISSUE THREAD

**Issue by 2hangchen** [ClickHouse/clickhouse-go#283]
when I execute this statement, 
` **SELECT * FROM `xxx`.xxxx  WHERE (a_id IN(?)) AND (unix_time>?) AND (unix_time<?) LIMIT ? OFFSET ?**
`
there are 5 '?' marks in the statement, but I debug find that numInput() converts the statement to byte, with 5 byte values of 63, but only returns the number 4

so finally an error is got 

`**sql: expected 4 arguments, got 5**`

**Comment by pierrre** [comment]
I figured out it's the `LIMIT ? OFFSET ?` syntax.
Use `LIMIT ?, ?` instead.
See https://clickhouse.tech/docs/en/sql-reference/statements/select/limit/
Be careful, the order is reversed.
