### ISSUE TITLE
Does this library support bulk exports

### ISSUE THREAD

**Issue by gane5hvarma** [ClickHouse/clickhouse-go#290]
Hi, is it possible to load into Clickhouse from a csv file, json file etc using this library.

**Comment by gane5hvarma** [comment]
Also is their support for ( COPY FROM stdin ) support in this library
ex: https://godoc.org/github.com/lib/pq#hdr-Bulk_imports

**Comment by kshvakov** [comment]
Hi, COPY is a specific PostgreSQL command and is not supported for other databases.

**Comment by gane5hvarma** [comment]
okay, Can i know is it possible to load to tables from csv files?

**Comment by kshvakov** [comment]
sure, you can use https://golang.org/pkg/encoding/csv/#Reader

**Comment by gane5hvarma** [comment]
@kshvakov, i tried to implement this but facing some issues

i have used csv reader like this
```
var gzipReader *gzip.Reader
gzipReader, err = gzip.NewReader(gzipFile)
csvReader := csv.NewReader(gzipReader)
var record [][]string
record, _ = csvReader.ReadAll()
 ```
Now the problem is how do i pass this record value into this query
```
stmt, _ = tx.Prepare("INSERT INTO example (country_code, os_id, browser_id, categories, action_day, action_time) FORMAT CSV ")
```
