### ISSUE TITLE
Batch insert missing 

### ISSUE THREAD

**Issue by ParvizBoymurodov** [ClickHouse/clickhouse-go#296]
I want to query batch insert but I  can't find any solution.

**Comment by zifter** [comment]
Have you seen example?
Batch insert is implemented like sql transaction - you need to begin transaction and then commit.

**Comment by mvu-tk** [comment]
sorry but how to do batch insert using this driver? 
Thanks

-M

**Comment by zxc111** [comment]
@mvu-tk 
https://github.com/ClickHouse/clickhouse-go/blob/master/clickhouse_test.go#L253

**Comment by payam-int** [comment]
@zxc111 does it have the same performance as multiple insert query (`INSERT INTO x (a, b) VALUES (1, 2), (2, 3)`)?

**Comment by a-dot** [comment]
> @zxc111 does it have the same performance as multiple insert query (`INSERT INTO x (a, b) VALUES (1, 2), (2, 3)`)?

@kshvakov Can you confirm that this way of inserting data (multiple values) is unsupported by clickhouse-go? thanks!

**Comment by kshvakov** [comment]
@a-dot You can send multiple values in a batch mode. 
See example 
https://github.com/ClickHouse/clickhouse-go/blob/master/examples/simple.go#L36 
https://github.com/ClickHouse/clickhouse-go/blob/v2/examples/native/simple.go#L56
