### ISSUE TITLE
Decimal data type support?

### ISSUE THREAD

**Issue by zifter** [ClickHouse/clickhouse-go#297]
https://clickhouse.tech/docs/en/sql-reference/data-types/decimal/

At that moment driver does not work properly with this type as expected.

**Comment by zr-hebo** [comment]
I have the same demand, help!

**Comment by alifpay** [comment]
I use float64 for insert, string for select 
when there is sum() in select, throws  error if I use float64 so change to string
but no problem without sum()
```
CREATE TABLE IF NOT EXISTS table2
(
 ID                      UInt64,
 Amount             Decimal64(2), 
 Country             String,
 Regdate            DateTime DEFAULT now()
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(Regdate)
ORDER BY (ID)
SETTINGS index_granularity = 8192


SELECT Country,  toString(SUM(Amount)) FROM table2 GROUP BY Country

```

**Comment by alifpay** [comment]
It will be very good if it supports

https://github.com/shopspring/decimal

**Comment by veqryn** [comment]
I found this out the hard way by reading the source code, but you can read in Decimals as integers and write them out as integers. The scaling factor determines how they turn into Decimals.

So, if you have a `Decimal32(4)`, and you write the integer `123456789`, you will end up with this decimal in clickhouse: `12345.6789`

**Comment by kshvakov** [comment]
`shopspring/decimal` was added in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
