### ISSUE TITLE
could not load time location: unknown time zone Asia/Shanghai

### ISSUE THREAD

**Issue by unidbaas** [ClickHouse/clickhouse-go#301]
This error is reported when I build a Docker container to run

**Comment by unidbaas** [comment]
![image](https://user-images.githubusercontent.com/31329928/90353381-9f357700-e078-11ea-96ed-16b0a88d9b3e.png)

**Comment by kshvakov** [comment]
Hi, you need to install the `tzdata` package

**Comment by unidbaas** [comment]
> Hi, you need to install the `tzdata` package

Tzdata is already installed

**Comment by 18601673727** [comment]
> > Hi, you need to install the `tzdata` package
> 
> Tzdata is already installed,but problems remain

It actually works if you `docker exec` into the container and `apk add tzdata` then restart the container.
