### ISSUE TITLE
bulk write is slow

### ISSUE THREAD

**Issue by on99** [ClickHouse/clickhouse-go#307]
Writing 150k rows of data to single node clickhouse:
1. clickhouse sql driver, begin->prepare->loop insert->commit, takes around 15s
2. mysql sql driver, batch insert, 4096 rows of data per batch, takes around 1s

I can paste my code here if needed, it's very straightforward.

**Comment by cppla** [comment]
you should insert by this command：
```
INSERT INTO table_name(column, column, ) VALUES (xxx, xxx),(xxx, xxx).....
```

**Comment by kshvakov** [comment]
> Writing 150k rows of data to single node clickhouse:
> 
> 1. clickhouse sql driver, begin->prepare->loop insert->commit, takes around 15s
> 2. mysql sql driver, batch insert, 4096 rows of data per batch, takes around 1s
> 
> I can paste my code here if needed, it's very straightforward.

Hi, could you please provide some sample code?

**Comment by FourSpaces** [comment]
@on99 How many columns do you have? I found that the more columns, the slower the insertion speed. In production, we can speed up the insertion of more than 1600 columns by adjusting the concurrency of single row data.
