### ISSUE TITLE
[help wanted]how to use clickhouse function in clickhouse-go

### ISSUE THREAD

**Issue by kansz** [ClickHouse/clickhouse-go#308]
Hi guys,

I have a table like:
CREATE TABLE IF NOT EXISTS sfb_monitor.basic_metric ON CLUSTER 'chi-s1-r1'
(
  timestamp DateTime DEFAULT now(),
  date Date DEFAULT toYYYYMMDD(timestamp),
  ip UInt32,
  count UInt32 DEFAULT 1,
  product String
) ENGINE = MergeTree()
PARTITION BY date
ORDER BY timestamp
TTL date + INTERVAl 1 DAY;

When I use clickhouse client, I can insert a record with cmd: insert into basic_metric (ip, product) values (IPv4StringToNum('127.0.0.1'), 'TEST DRIVER')

When I use clickhouse-go, I don't know how to use the clickhouse function like 'IPv4StringToNum'. Must I convert a IP to a UInt32 by myself, and then insert the UInt32?

**Comment by kshvakov** [comment]
Use Go net.IP type. See [example](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/ipv4_test.go#L37)
