### ISSUE TITLE
Retrieving with totals result

### ISSUE THREAD

**Issue by ivishnevs** [ClickHouse/clickhouse-go#309]
Is it possible to get "with totals" result via golang sql interface?
e.g. I want to perform such query
`SELECT hour, country, uniq(uuid) AS visitors FROM country_aggs_dist GROUP BY country, hour WITH TOTALS ORDER BY country, hour`

and with totals allows me to see total number of uniq visitors.
Thanks!

**Comment by kshvakov** [comment]
Yes, With Totals is supported in version [V1](https://github.com/ClickHouse/clickhouse-go/blob/master/clickhouse_test.go#L794), and [V2 std](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/std/totals_test.go) and [V2 native](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/totals_test.go#L11)

**Comment by calebeaires** [comment]
@kshvakov is there some example that make this happen:


By using the clickhouse-client command line interface and specifying the format as JSON, we can retrieve both the query result and accompanying statistics. In a query SELECT using some aggregation and grouped, when using the verb `with totals` the result comes with the totals aggregated

When using `clickhouse-client` and setting the attribute `--format=JSON` we get a json with others important values, the same is present in the oficial clickhouse-go Javascript library. Here is the result in the terminal after running the following query

Query
```bash
clickhouse-client --password=test --user=default --format=JSON --query="select 1 + 1"

```

```json

{
    "meta":
    [
        {
            "name": "plus(1, 1)",
            "type": "UInt16"
        }
    ],

    "data":
    [
        {
            "plus(1, 1)": 2
        }
    ],

    "rows": 1,

    "statistics":
    {
        "elapsed": 0.001043427,
        "rows_read": 1,
        "bytes_read": 1
    }
}
```

Result props in JSON

1. Meta 
2. Data
3. Rows
4. Statistics
5. Totals: (when using with totals verb)

Could you please assist me in achieving the same JSON result through an API with the `﻿go-clickhouse` library in Go, similar to what can be accomplished with the `official clickhouse-go library` in JavaScript? Your guidance would be greatly appreciated.

The goal is to delivery the result with totals and stats directly to the API Request Endpoint.

**Comment by jkaflik** [comment]
@calebeaires `clickhouse-go` does not support formats other than `native`, so format `JSON` will not work. API does not expose any control over it.

@kshvakov referenced to a code examples how to use `WITH TOTALS` statement:

> Totals is supported in version [V1](https://github.com/ClickHouse/clickhouse-go/blob/master/clickhouse_test.go#L794), and [V2 std](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/std/totals_test.go) and [V2 native](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/totals_test.go#L11)

 Is there anything you miss for this implementation?
