### ISSUE TITLE
Can't find the file when using INTO OUTFILE?

### ISSUE THREAD

**Issue by bzon** [ClickHouse/clickhouse-go#313]
I'm trying to use the INTO OUTFILE and after successfully executing the below code, the file is nowhere to be found. I also tried using absolute file paths. I'm expecting the file to be written like how it is when used with the clickhouse-client.

```golang
// Where ch is &sql.DB
_, err := ch.ExecContext(context.Background(), "SELECT 'a' as c1, 'b' as c2 INTO OUTFILE 'exports.csv' FORMAT CSVWithNames")
```

```
[clickhouse][connect=1][prepare] SELECT 'a' as c1, 'b' as c2 INTO OUTFILE 'exports.csv' FORMAT CSVWithNames
[clickhouse][connect=1][send query] SELECT 'a' as c1, 'b' as c2 INTO OUTFILE 'exports.csv' FORMAT CSVWithNames
[clickhouse][connect=1][process] <- data: packet=1, columns=2, rows=0
[clickhouse][connect=1][process] <- data: packet=1, columns=2, rows=1
[clickhouse][connect=1][process] <- profiling: rows=1, bytes=36, blocks=1
[clickhouse][connect=1][process] <- progress: rows=1, bytes=1, total rows=0
[clickhouse][connect=1][process] <- data: packet=1, columns=0, rows=0
[clickhouse][connect=1][process] <- progress: rows=0, bytes=0, total rows=0
[clickhouse][connect=1][process] <- end of stream
```

No errors are returned in Go code.

**Comment by jakesyl** [comment]
I'm having the same issue

**Comment by Slach** [comment]
This functionality is available in the command-line client and clickhouse-local. 

clickhouse-go doesn't implements INTO OUTFILE now

fell free to make PR

**Comment by jakesyl** [comment]
@Slach any advice on where to implement a test for this? It requires mock inserts and I don't see any examples of the insert->select worfklow (beyond, say copying and pasting `Test_DirectInsert` before the test minus the drop)
