### ISSUE TITLE
Array, what is that for?

### ISSUE THREAD

**Issue by iqDF** [ClickHouse/clickhouse-go#315]
Hi, 

Just minor question about the code sanity here. I wonder what is the `array.go` for? I causes confusion and it does nothing in the end. Here is the code snipet:

```
func Array(v interface{}) interface{} {
	return v
}

func ArrayFixedString(len int, v interface{}) interface{} {
	return v
}

func ArrayDate(v []time.Time) interface{} {
	return v
}

func ArrayDateTime(v []time.Time) interface{} {
	return v
}
```

In my view, especially the `Array()`  causes many confusion and can be misused as well. I can put non-slice/array into the argument and still won't give me any array or string. Just an indentity input output function. The `ArrayFixedString` is the worst, is doesn't do any fixed length or anything. I recommend to clean up the usage of this array. It vagues the new comers just to discover it's a dummy function. It don't think it has any usecase either.

But this is non-priority. I can handle refactoring and ensure the test cases works with backward compatibility if necessary.

**Comment by linrl3** [comment]
It looks like unfinished type conversion things.
