### ISSUE TITLE
Support for uint type in golang

### ISSUE THREAD

**Issue by iqDF** [ClickHouse/clickhouse-go#318]
I have an issue where I got this error:

```
`column_uint` (UInt64): unexpected type uint
```

This is the result of logging when I print the result. 
```
INSERT INTO `members` (`column_uint`,`name`) VALUES (1, 'foreign_key_constraints')
```

so what happened in my experimentation is that my column type is UInt64 but I used `uint`. I'm aware that there is no such thing as `UInt` in the clickhouse server database itself, but for Golang, can we map uint to a certain type? like `UInt32` or `UInt64` rather than throwing this error?

The error above came from this file I suppose: `lib/column/common.go::ErrUnexpectedType`. I looked into the source code and there is no mapping for `uint(0)`.

First, can I confirm that this is indeed the current situation that clickhouse-go doesn't support uint type?
If so, is it possible to consistently map `uint` to `UInt64` for safe?

**Comment by kshvakov** [comment]
No, since [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2) the driver requires strict compliance for all types
