### ISSUE TITLE
Getting Unexpected packet Data received from client while running the query

### ISSUE THREAD

**Issue by John-belt** [ClickHouse/clickhouse-go#322]
HI,
I am getting "DB::Exception: Unexpected packet Data received from client" while executing the query. 
Got only few instances of those but hoping to find the reason behind it??
Clickhouse-go version: 1.3.7
Clickhouse-version: 20.1

Went through the clickhouse code and found out, that packet type received by clickhouse is " Protocol::Client::Scalar" whereas i think it should have been "Protocol::Client::Query". I am not sure what is this "Protocol::Client::Scalar" Protocol? From the clickhouse code it is written that it is "A block of Data sent(Compressed or not)", but why is client send something like this in between the select query??

**Comment by Slach** [comment]
@John-belt could you share minimal reproducible golang code?

**Comment by Slach** [comment]
@John-belt did you try latest clickhouse-go 1.4.3 version?

**Comment by John-belt** [comment]
Hi, This is the only occurrence of issue we have and does not seem to be reproducible. I am sure it is not impacting anything but customer wants to know the reason behind it. Yes, we will update the to latest version in the coming release but not possible as of now. 
FYI the exception came while running the insertion query.
Any possible reasons would work.

**Comment by JinWuZhao** [comment]
I get similar error "code: 101, message: Unexpected packet Data received from client" with clickhouse-go 1.4.3.

**Comment by achettyiitr** [comment]
I am getting this error on version 1.4.8 also.

**Comment by lyj2871** [comment]
This problem may be caused by multi-threaded operations. The write operation in one thread has not yet been completed, and another thread initiates a read and write operation.

**Comment by makeavish** [comment]
@JinWuZhao Where you able to fix this issue?
I am facing similar issue: https://github.com/ClickHouse/clickhouse-go/issues/485

**Comment by JinWuZhao** [comment]
@makeavish No，I didn't fix it. It happens sometimes. I don't know how to recurrent it.

**Comment by makeavish** [comment]
@JinWuZhao Similar issue which I faced is fixed now.
Maybe you can have a look: https://github.com/ClickHouse/clickhouse-go/issues/485
