### ISSUE TITLE
how can i create request with file(which use like temp table)

### ISSUE THREAD

**Issue by NineStems** [ClickHouse/clickhouse-go#323]
I need to select data with long list of  ids (more that 1kk elements).
How can i use this https://clickhouse.tech/docs/en/engines/table-engines/special/external-data/ with yours lib?

**Comment by alvarotuso** [comment]
@NineStems pretty old but I went ahead and built this into the driver if you want to test it: https://github.com/ClickHouse/clickhouse-go/pull/341

**Comment by NineStems** [comment]
@alvarotuso, thank you very much, I will definitely try it soon
