### ISSUE TITLE
Support for UInt256

### ISSUE THREAD

**Issue by filippetroviccc** [ClickHouse/clickhouse-go#324]
Hi guys,

I saw recently that clickhouse supports big int types (UInt256, Int256, etc.) and I would like to use them for some complex big value aggregation.

I'm totally willing to open PR on myself and add support for UInt256. I would just like it if some of you could give me any direction for implementation or what I need to change, both would be really helpful. 

There are a couple of issues that I encountered with my own implementation, first is that other int types are using go native types but UInt256 will need to use byte array of fixed length, I tried to tickle a bit with `MaxVariantLen64`->`MaxVariantLen256` but I'm not sure if that is way to go. Another issue that got myself entangled with is when I try to insert byte array to uint256 field in clickhouse I either get `bad connection` or `bad query`

Here is the repo where I added my dummy implementation of UInt256: [here]( https://github.com/Tenderly/clickhouse-go/tree/feature/support-uint256)

Also, note that I still didn't change any tests, only one `clickhouse_test.go:76 - Test_Insert()` in order for me to try implementation you can do the same there.

Filip

**Comment by GooSatoru** [comment]
@filippetroviccc your code does't work yet, i can we makey it possible.

**Comment by filippetroviccc** [comment]
@GooSatoru Yes, indeed it doesn't work. I described the issue that I've encountered when trying to add support for `UInt256`. I'm quite sure that my approach is wrong or at least not optimal and wanted to see if somebody else has a better (and working) approach, ideally from clickhouse team but everybody is welcome to help.

**Comment by GooSatoru** [comment]
> @GooSatoru Yes, indeed it doesn't work. I described the issue that I've encountered when trying to add support for `UInt256`. I'm quite sure that my approach is wrong or at least not optimal and wanted to see if somebody else has a better (and working) approach, ideally from clickhouse team but everybody is welcome to help.

I think i known the data format, It seems UInt256 column read write as little edian like [32]byte in golang, i store UInt256 value and use clickhouse-go query it, it returns  little edian of [32]byte.

Query Result bellow
```
10000 -> [16 39 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
11111111111111111111111111111111111111111 -> [199 113 28 199 113 22 45 178 247 212 40 245 17 41 18 167 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```

BigInt Bytes bellow
```
10000 -> [39 16]
11111111111111111111111111111111111111111 -> [32 167 18 41 17 245 40 212 247 178 45 22 113 199 28 113 199]
```

you can look at the [clickhouse-driver of python ](https://github.com/mymarilyn/clickhouse-driver/blob/336f0efc1ea539b6841c675b319c56335ccea093/clickhouse_driver/columns/intcolumn.py#L151)

**Comment by filippetroviccc** [comment]
Cool, thank you @GooSatoru

I'll use python implementation as a reference and try to come up with a working PR over a weekend.

**Comment by filippetroviccc** [comment]
Hey @GooSatoru 

I've added support for UInt256 and fixed a single test to work with the new type.

Here is the [repo](https://github.com/Tenderly/clickhouse-go/tree/feature/support-uint256)
And the [test](https://github.com/Tenderly/clickhouse-go/blob/master/clickhouse_test.go#L75-L251)

I'll open PR once I implement all big int types and add the tests. (I suppose next week/weekend)

**Comment by GooSatoru** [comment]
@filippetroviccc Good Job

I have also add support and  test success, the code is [here](https://github.com/GooSatoru/clickhouse-go/commits/master), but have no time to come up with a working PR , and there are still some boundary checks that need to be done.

Next, I may hope to support Decimal128 Decimal256, big decimal storage is more complicated than big integer, I want to study later, If you have time, you can take a look

Do you also want to store blockchain data with clickhouse?

**Comment by markandrus** [comment]
UInt256 and related types can be implemented similar to how Decimal128 was implemented in #411.

**Comment by kshvakov** [comment]
Done

**Comment by kshvakov** [comment]
See [example](https://github.com/ClickHouse/clickhouse-go/blob/master/tests/bigint_test.go)
