### ISSUE TITLE
query log settings is not reflected in client side

### ISSUE THREAD

**Issue by John-belt** [ClickHouse/clickhouse-go#325]
Hi,
Running clickhouse client Clickhouse-go version: 1.3.7.
I manually changed the query_log settings(disabling it, setting value to 0 ) in users.xml in clickhouse(Clickhouse says no restart required for users related settings). The values in the server side is changed, i can confirm that, but when any query is being run from the driver(same session) it is still logged into the query_log table with the older setting(value 1).
Question: Does the changes in server side users.xml is not taken by the driver on the same session.
I had to reconnect the client for the new changes to take place. Is there something i can do use the same session and avoid reconnect. Is that something that has been fixed in the latest version?? i know i am using quite older client version.
Thanks

**Comment by Slach** [comment]
clickhouse-server doesn't notify client about any changes in `users.xml`, your issue isn't related to `clickhouse-go` itself
so, I think you should create an issue on https://github.com/ClickHouse/ClickHouse/issues

**Comment by John-belt** [comment]
Okay, but does the client (clickhouse-go ) has somekind of listner so if clickhouse does sent the config change, the client will be notified??

**Comment by Slach** [comment]
no clickhouse-go doesn't have any listener
it's a CLIENT library which make TCP connections to `clickhouse-server`
and as I said, clickhouse doesn't notify any clients when any settings reload from XML files

so, only one way I see to achieve your behavior
- implements OS signal handling in your golang code which will close connection in clickhouse-go, and re-init it
- change XML file on server, wait when settings will applied (just sleep 1 is enough)
- send kill SIGHUP (or any other signal for your choice) to your client application

**Comment by John-belt** [comment]
@Slach thanks for the advise, that will surely help.
