### ISSUE TITLE
Add multiquery support

### ISSUE THREAD

**Issue by ybogo** [ClickHouse/clickhouse-go#351]
As I know clickhouse-client has beta multiquery support (https://clickhouse.tech/docs/en/interfaces/cli/#command-line-options)
Is it possible to add this feature to the go driver?

It will be very useful for setting up migration system in clickhouse.

**Comment by kshvakov** [comment]
Hi, I think this is not a good idea for a CH driver. If you need support for multiquery requests, you can do it on the side of your app.
