### ISSUE TITLE
Ping fails with "driver: bad connection"

### ISSUE THREAD

**Issue by peterjasc** [ClickHouse/clickhouse-go#353]
If I use 
`import _ "github.com/ClickHouse/clickhouse-go"`

db, err := sql.Open("clickhouse", "tcp://127.0.0.1:8123?debug=true")
if err := db.Ping(); err != nil {
	logger.Fatal(err.Error())
}

I get an error:

`[clickhouse]host(s)=127.0.0.1:8123, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=1, server=0 -> 127.0.0.1:8123
[clickhouse][connect=1][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=1][connect] read error: read tcp 127.0.0.1:51337->127.0.0.1:8123: i/o timeout
[clickhouse]host(s)=127.0.0.1:8123, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=2, server=0 -> 127.0.0.1:8123
[clickhouse][connect=2][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=2][connect] read error: read tcp 127.0.0.1:51433->127.0.0.1:8123: i/o timeout
[clickhouse]host(s)=127.0.0.1:8123, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=3, server=0 -> 127.0.0.1:8123
[clickhouse][connect=3][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=3][connect] read error: read tcp 127.0.0.1:51554->127.0.0.1:8123: i/o timeout
1.61392464805231e+09	fatal	logger/logger.go:62	driver: bad connection`

While, this does not produce an error (using http):
`import "github.com/mailru/go-clickhouse"`
`db, err := sql.Open("clickhouse", "http://127.0.0.1:8123?debug=true")`
if err := db.Ping(); err != nil {
	logger.Fatal(err.Error())
}

**Comment by zxc111** [comment]
@peterjasc clickhouse-go does not support http(8123 default) protocol, it support tcp (9000 default) only.
Try https://github.com/mailru/go-clickhouse for http

**Comment by peterjasc** [comment]
Thanks, I mixed up the ports.

> Container exposes 8123 port for HTTP interface and 9000 port for native client.
https://hub.docker.com/r/yandex/clickhouse-server/
