### ISSUE TITLE
It's very slowly when insert 400000 datas, and it will take 130 seconds

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/clickhouse-go#354]
It's very slowly when insert 400000 datas, and it will take 130 seconds. we have 1040 columns....
`stmt.Exec duration: 111.531020116s
commit duration: 20.588932168s
`

**Comment by FourSpaces** [comment]
@intfish123  We have more than 1600 columns. Through concurrent processing of single row data, we can insert 20W data for 20 ~ 30s.

**Comment by kshvakov** [comment]
@intfish123 We have released [V2 alpha ](https://github.com/ClickHouse/clickhouse-go/tree/v2)with improved performance.
