### ISSUE TITLE
Batch insert silently fails

### ISSUE THREAD

**Issue by danncoba** [ClickHouse/clickhouse-go#355]
Hi guys,

I use ReplicatedSummingMergeTree on Replicated shard. For batch inserting i use size of 20k. I use exactly the same way of batch insert as described in the docs (so i don't paste it here unnecessarily). This works normally, but periodically, inserted data just isn't entered. When i 
`SELECT SUM(data1), SUM(data2) FROM table;`
i see that exactly insert failed. No error in, Prepare in Exec in Commit
No errors on server.
It just silently fails.

**Comment by Slach** [comment]
Look like you try to insert to same data multiple times
as desctibed here
https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/
```
Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application doesn’t know if the data was written to the DB, so the INSERT query can simply be repeated. It doesn’t matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by merge_tree server settings.
```

**Comment by Zhile** [comment]
Use this setting when you create the ReplicatedMergeTreeTable
`
SETTINGS index_granularity = 8192, **replicated_deduplication_window** = 0
`
