### ISSUE TITLE
Check for timeout params overflow

### ISSUE THREAD

**Issue by forward32** [ClickHouse/clickhouse-go#361]
Driver [parses](https://github.com/ClickHouse/clickhouse-go/blob/51ccb554c2fb9c734c65f7b962f0be279793de67/bootstrap.go#L128) such values as `read_timeout / write_timeout` to Float64 which is enough to hold such values as 60000000000.
But passing such value to ClickHouse leads to overflow and as result you get `bad connection` error.

**Comment by jalavosus** [comment]
@forward32 What's the maximum timeout Clickhouse supports? It probably makes sense to have a sanity check in the code that parses timeout parameters, which sets the read/write timeouts to max (or just under it) if user-passed arguments are too large.

**Comment by forward32** [comment]
I suppose it's 4 bytes integer but maybe I'm wrong since there is no documentation about native tcp protocol.

**Comment by kshvakov** [comment]
In [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2) we have removed read/write timeout settings. You can use `context.WithTimeout`
