### ISSUE TITLE
Authentication failed if password contains specific symbols

### ISSUE THREAD

**Issue by forward32** [ClickHouse/clickhouse-go#362]
Suppose you have user with password=`RSzqnN+n`.

When you try to connect to ClickHouse with such credentials you got the following error:
```
code: 516, message: test: Authentication failed: password is incorrect or there is no user with such name
```
I investigated payload with `tcpdump` and found interesting moment - encoded password doesn't have `+` symbol.

`clickhouse-client` works correctly in this case and encodes data properly.

**Comment by forward32** [comment]
Using `url.QueryEscape` on password field helped.

Is it obvious for everyone that url values should be query escaped and that's only my mistake?
Should we add exta information about it to DSN section in README?

@kshvakov what do u think?

**Comment by jalavosus** [comment]
@forward32 I've opened up a PR (#368) which should fix this issue.

**Comment by jakesyl** [comment]
+1 on @jalavosus solution here, I've gotten bit by this a few times

**Comment by kshvakov** [comment]
In [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2#dsn) we switched to a new DSN format
