### ISSUE TITLE
CityHash64 results not consistent with Clickhouse output

### ISSUE THREAD

**Issue by maciej** [ClickHouse/clickhouse-go#363]
```go
h = cityhash102.New64()
_ = binary.Write(h, binary.LittleEndian, uint64(1))
fmt.Printf("%d\n", h.Sum64())
```
prints 10143279697293281662

```sql
SELECT cityHash64(1);
```
returns 10577349846663553072

What I expected to see:
same value.

I understand the reason behind it is that Clickhouse does not compute a city hash at all in that case
https://github.com/ClickHouse/ClickHouse/blob/bd81f43ecb33dfd160f54b97cebf533156d9565e/src/Functions/FunctionsHashing.h#L754-L764

That said I don't think it's unreasonable to believe a `clickhouse-go` CityHash64 implementation returns the same result as a `ClickHouse` one.

**Comment by sundy-li** [comment]
Well，the `cityHash` in clickhouse-go is just for protocol. 
https://github.com/ClickHouse/clickhouse-go/blob/master/lib/binary/compress_writer.go#L68-L73

We did tests with CPP implemantation in `https://github.com/ClickHouse/clickhouse-go/blob/master/lib/cityhash102/testdata/cityhash.cpp#L356-L362`, the results are same.

**Comment by Slach** [comment]
@maciej cityhash102 is not standart CityHash implementation
you can use https://github.com/zentures/cityhash or https://github.com/tenfyzhong/cityhash

**Comment by RO-29** [comment]
Hello @maciej @sundy-li @Slach 

Did you find some solution to it? I want to calculate the cithash64 which matches the exact output of ch server and the go implementation does not work for me


>you can use https://github.com/zentures/cityhash or https://github.com/tenfyzhong/cityhash
Even this doesn't give the same output

**Comment by ernado** [comment]
Hey, please take a look at https://github.com/go-faster/city

Also see https://go-faster.org/docs/clickhouse/hash
