### ISSUE TITLE
Is it possible to set string settings 

### ISSUE THREAD

**Issue by minaevmike** [ClickHouse/clickhouse-go#365]
It's quite easy to set some int or bool settings using input DSN. Is there any way to pass some string settings like `load_balancing` and others? Of course, I can set these values if I run a query like `SET load_balancing='blablabla'`. But it would be more convenient if I can set them on the whole connection.

**Comment by forward32** [comment]
it should work. Described behavior is implemented in code - check ([it](https://github.com/ClickHouse/clickhouse-go/blob/51ccb554c2fb9c734c65f7b962f0be279793de67/bootstrap.go#L159) out.

**Comment by kshvakov** [comment]
You can use `Context` or global settings in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
