### ISSUE TITLE
how to build connection to clickhouse cluster

### ISSUE THREAD

**Issue by SE2AI** [ClickHouse/clickhouse-go#370]
when using clickhouse cluster mode, how to build connection to more than one DSN?

**Comment by SE2AI** [comment]
could anybody help to answer the question?

**Comment by kshvakov** [comment]
Hi, use alt hosts https://github.com/ClickHouse/clickhouse-go#dsn

**Comment by SE2AI** [comment]
@kshvakov many thanks, 

How does clients determine which host should operate, using some round-robin algorithms inside?

I build 3 local tables and 3 distribute tables on 3 dockers (1 table for 1 docker), and read distribute tables while write local tables. When perform DML, I want to choose the target host manually. So If I use alt-hosts, could it support my application?
