### ISSUE TITLE
Unknown codec

### ISSUE THREAD

**Issue by larry-cdn77** [ClickHouse/clickhouse-go#376]
Against version 21.3 ClickHouse server I get 'Unknown code family code':

```
[clickhouse][connect=1][begin] tx=false, data=false
[clickhouse][connect=1][prepare] INSERT INTO default.metrics_buffer2 VALUES
[clickhouse][connect=1][send query] INSERT INTO default.metrics_buffer2 VALUES VALUES 
[clickhouse][connect=1][send external tables] count 0
[clickhouse][connect=1][read meta] <- data: packet=1, columns=20, rows=0
[clickhouse][connect=1][commit] tx=true, data=true
[clickhouse][connect=1][process] <- exception
ClickHouse Commit: code: 432, message: Unknown codec family code: 226
```

I am doing a minimal insert transaction, in pseudo code:

```
conn := clickhouse.Open("tcp://127.0.0.1:9000?compress=true&debug=true")
transaction := conn.Begin()
statement := conn.Prepare("INSERT INTO t VALUES")
statement.Exec([]driver.Value{ ... })
transaction.Commit()
```

When this last worked I had the same kind of client code and an older ClickHouse server version 20.x

Tried out-of-box LZ4 as well as Cloudflare's Cgo implementation. Without compression the commit function times out with 'bad connection' (I am not sure uncompressed worked before).

**Comment by kshvakov** [comment]
Fixed in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
