### ISSUE TITLE
Feature Req: allow DSN as username:password@host/database

### ISSUE THREAD

**Issue by ukolovda** [ClickHouse/clickhouse-go#377]
Hello!

Most DB drivers use DSN with username and password before hostname:

`clickhouse://username:password@host/database`

Please, allow this format also.

**Comment by akamensky** [comment]
2nd that. DSN while does not have official standard, has a "community standard" which many tools follow (with some variations).

Most commonly accepted DSN format is using URL standard:

```
scheme://username:password@host:port/path?query
```

which would make DSN for Clickhouse look like:

```
clickhouse://username:password@host:port/db_name?config=options
```

alternatively there is MySQL variation of this which is:

```
scheme://username:password@proto(path)/path?query
translated to Clickhouse native would be
clickhouse://username:password@tcp(host:port)/db_name?config=options
```

**Comment by kshvakov** [comment]
@ukolovda DSN has been changed in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2#dsn)
