### ISSUE TITLE
expected 1 arguments, got 3

### ISSUE THREAD

**Issue by AleXzpm** [ClickHouse/clickhouse-go#378]
`	query := ` ` SELECT * FROM ? LIMIT ? OFFSET ?  ` `

       params := []interface{"sometable", "1", "2" }

	stmt, err := db.Prepare(query)

	if err != nil {

		return nil, err

	}

	rows, err := stmt.Query(params...)

`
will result in error `"ERROR=sql: expected 1 arguments, got 3`
Is this not the way to do selects for clickhouse with mutilple params?

**Comment by vxxvvxxv** [comment]
+1, I have the same problem, I think it's because `OFFSET` don't catch at parsing SQL (like `LIMIT`).

**Comment by vxxvvxxv** [comment]
@kshvakov Can you create a new tag from latest commit?

**Comment by kshvakov** [comment]
done
