### ISSUE TITLE
golang fetch Decimal(18,2) miss the point(golang读取带小数点的数据，会丢失小数点)

### ISSUE THREAD

**Issue by imysm** [ClickHouse/clickhouse-go#379]
clickhouse-go 读取clickhouse里面带小数点的数据，在取值的时候会把小数据点丢掉 ，比如 clickhouse里面存的是88.88 ，读出来后会变成8888

for example :
88.88 in clickhouse ，but   the result  golang fetched is 8888 .the point missed

**Comment by kshvakov** [comment]
You can try [V2](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/decimal_test.go)
