### ISSUE TITLE
Map(String,String) supported

### ISSUE THREAD

**Issue by fengde** [ClickHouse/clickhouse-go#380]
have any plans to support Map Type? :)

**Comment by iprobeyang** [comment]
i used Map(String, String), got error：
unhandled type Map(String,String)

**Comment by saintech** [comment]
Temporary workaround:
```SQL
SELECT arrayMap(key -> tuple(key, map_col[key]), map_col.keys) FROM table_with_map_col;
```

**Comment by khamin** [comment]
Seems like related to #400

**Comment by Kugelschieber** [comment]
Would be great if we could select `cast((keys, values), 'Map(String, String)')` into `map[string]string` for table
```sql
CREATE TABLE kv (
    `keys` Array(String),
    `values` Array(String),
    -- ...
```

**Comment by Kugelschieber** [comment]
Awesome! Thanks a lot!
