### ISSUE TITLE
how to exec  insert into select by clickhouse-go?

### ISSUE THREAD

**Issue by NewHongjayGitHub** [ClickHouse/clickhouse-go#385]
i have a  insert sql like this:   `INSERT INTO my_table SELECT '2021-06-27 00:00:00', ‘colum1', 'colum1', 11, quantileState(toInt64(200)) `   

i need batch insert this data, i use clickhouse-go like this: 
`stmr, err := tx.Prepare("INSERT INTO my_table SELECT ?, ?, ?, ?, ?")
stmt.Exec(time.Now(), ‘colum1', 'colum1', 11, 'quantileState(toInt64(200))' )`

it doesn't works, got err: 
sql: expected 4 arguments, got 5

Thanks for answering

**Comment by yanghuijava** [comment]
I have the same problem. Have you solved it

**Comment by doroshenkoam** [comment]
same problem

`INSERT INTO example (id, name, version) SELECT 1, 'Bill', (SELECT max(version) FROM example WHERE name='Bill')`
