### ISSUE TITLE
It is recommended to support batch insert

### ISSUE THREAD

**Issue by springrain** [ClickHouse/clickhouse-go#386]
It is recommended to support batch insert:
```sql
insert into tablename(name) values(?),(?);
```

**Comment by busgo** [comment]
the same

**Comment by kshvakov** [comment]
See example https://github.com/ClickHouse/clickhouse-go/blob/master/examples/simple.go#L38

**Comment by springrain** [comment]
> See example https://github.com/ClickHouse/clickhouse-go/blob/master/examples/simple.go#L38

Not a single insert, but a batch insert
