### ISSUE TITLE
usual select with filters

### ISSUE THREAD

**Issue by ip75** [ClickHouse/clickhouse-go#387]
![image](https://user-images.githubusercontent.com/3886308/124005339-9ffda000-d9e1-11eb-9c6f-66ae72768e40.png)
![image](https://user-images.githubusercontent.com/3886308/124005512-d4715c00-d9e1-11eb-9074-5ffbf63c7925.png)

**Comment by ip75** [comment]
this error won't occur only if use `(?)` instead of `?`

**Comment by kshvakov** [comment]
Try to use [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2) with numeric placeholders or named params

**Comment by ip75** [comment]
это у вас так в яндексе баги фиксят?   ахахаха.....
