### ISSUE TITLE
Wrong DateTime64 value after insert

### ISSUE THREAD

**Issue by nskforward** [ClickHouse/clickhouse-go#389]
I hava a table:
```
CREATE TABLE md.trades
(
    `timestamp` DateTime64(3, "America/New_York"),
    `price` Float64
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)
```
When I execute the following statement via command line interface:
```
INSERT INTO md.trades (timestamp, price) VALUES (1625128291293, 2.2)
```
I have the following correct values:
```
:) SELECT * FROM md.trades
2021-07-01 11:31:31.293 │ 2.2 │
```
But if I use github.com/ClickHouse/clickhouse-go for the same purpose:
```
tx, err := clickhouse.Begin()
if err != nil {
    panic(err)
}
stmt, err := tx.Prepare("INSERT INTO md.trades (timestamp, price) VALUES (?, ?)")
if err != nil {
    panic(err)
}
if _, err := stmt.Exec(1625128291293, 2.2); err != nil {
	panic(err)
    }
}
if err := tx.Commit(); err != nil {
    panic(err)
}
stmt.Close()
```
I have the following incorrect values:
```
:) SELECT * FROM md.trades
1970-01-01 03:27:05.129 │ 2.2 │
```
Why timestamp 1625128291293 transforms to '1970-01-01 03:27:05.129' via clickhouse-go?

**Comment by edwvee** [comment]
Same thing and can't insert as float64 when microseconds are after the point.

**Comment by kshvakov** [comment]
Fixed in [V2](https://github.com/ClickHouse/clickhouse-go/commit/79aa13ea799328ad1d82aae0351837caff7b5fb8)
