### ISSUE TITLE
How to handle decimal numbers?

### ISSUE THREAD

**Issue by itzikiusa** [ClickHouse/clickhouse-go#392]
Hi, i was trying to fetch decimal numbers from clickouse, as far as i can see, the conversion is being made to Integer, i even trying to fetch values as string and handle them afterwards
is there any easier workaround?
I'm willing  to help if needed
thanks, Itzik

**Comment by alexey-milovidov** [comment]
How do you fetch data from ClickHouse, what protocol and client driver do you use?

In binary formats, Decimals are represented as integers (little endian) with the value of decimal multiplied by power of 10 corresponding to the number of digits after point (scale).

**Comment by itzikiusa** [comment]
@alexey-milovidov 
thanks for the response

regarding fetch, i'm using clickhouse-go driver, with sqlx as he access layer (native protocol connection)
is there any automatic way to tell what was the scale? or should i modify my query to use the same scale for all values?
i.e if i'm doing some avg calculation on some fields

**Comment by alifpay** [comment]
github.com/shopspring/decimal

**Comment by kshvakov** [comment]
I have a plan to add `github.com/shopspring/decimal` as the default `Decimal` type in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)

**Comment by kshvakov** [comment]
@itzikiusa  
>> automatic way to tell what was the scale

We [provide info](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/std/decimal_test.go#L52) for the `database/sql`, and also support `shopspring/decimal` as default Decimal type for Go in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
