### ISSUE TITLE
failed to exec insert: name (String): unexpected type *interface {}

### ISSUE THREAD

**Issue by calebeaires** [ClickHouse/clickhouse-go#398]
This amazing lib USQL makes it possible to connect to various drivers, including clickhouse through clickhouse-go lib.  One of its features is the possibility to migrate data by using the \copy command. I've been using it on a series of drivers, but when I came up to clickhouse go I get this error:

`failed to exec insert: name (String): unexpected type *interface {}`

Maybe someone of clickhouse-go community could help us overcame this issue: https://github.com/xo/usql/issues/280

**Comment by kshvakov** [comment]
Sorry, but we can't help with MySQL driver and other external libraries.
