### ISSUE TITLE
slice not replace correctly in update stmt

### ISSUE THREAD

**Issue by dkishere** [ClickHouse/clickhouse-go#399]
args [test [6 0] 1]
[clickhouse][connect=1][prepare] ALTER TABLE `admin_role` UPDATE `name` = ?, `permission` = ?, `active` = ? WHERE `id` = ?;
[clickhouse][connect=1][process] <- exception
failed code: 62, message: Syntax error: failed at position 68 ('0'): 0, `active` = 1 WHERE `id` = 2;. Expected one of: identifier, column assignment

**Comment by kshvakov** [comment]
Can you try [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2) with the new placeholder syntax?
