### ISSUE TITLE
map is not insertable even I use raw sql

### ISSUE THREAD

**Issue by dkishere** [ClickHouse/clickhouse-go#400]
I can select out with map_column.keys & map_column.values. However I am not able to write data, it always return column: unhandled type Map(String,String)

INSERT INTO `data_source` (`id`,`map_column`) VALUES (?,map(?,?,?,?)), (?,map(?,?,?,?));

or even

INSERT INTO `data_source` (`id`,`map_column`) VALUES (123,map("a","b","c","d")), (456,map("a","b","c","d"));

**Comment by saintech** [comment]
Temporary workaround:
```SQL
INSERT INTO table_with_map_col (map_col) SELECT map('key1', 'val1', 'key2', 'val2');
```

**Comment by kshvakov** [comment]
Native Map support was added in [V2](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/map_test.go#L28)
