### ISSUE TITLE
clickhouse memory leak

### ISSUE THREAD

**Issue by Sudio** [ClickHouse/clickhouse-go#408]
code: 241, message: Memory limit (for query) exceeded: would use 10.69 GiB (attempt to allocate chunk of 2147516592 bytes), maximum: 9.31 GiB

```
go tool pprof http://localhost:6060/debug/pprof/allocs
Fetching profile over HTTP from http://localhost:6060/debug/pprof/allocs
Saved profile in /root/pprof/pprof.main.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz
File: main
Type: alloc_space
Time: Aug 26, 2021 at 10:29am (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 5129.73MB, 99.47% of 5156.85MB total
Dropped 74 nodes (cum <= 25.78MB)
Showing top 10 nodes out of 33
      flat  flat%   sum%        cum   cum%
 3870.59MB 75.06% 75.06%  3870.59MB 75.06%  github.com/ClickHouse/clickhouse-go/lib/data.newValue (inline)
  670.01MB 12.99% 88.05%   670.01MB 12.99%  reflect.packEface
  301.98MB  5.86% 93.91%   301.98MB  5.86%  github.com/ClickHouse/clickhouse-go/lib/leakypool.GetBytes
  186.60MB  3.62% 97.52%   186.60MB  3.62%  reflect.mapassign
      45MB  0.87% 98.40%   276.11MB  5.35%  encoding/json.(*decodeState).object
   33.50MB  0.65% 99.05%    33.50MB  0.65%  reflect.New
   13.04MB  0.25% 99.30%  5155.47MB   100%  main.sync
    8.50MB  0.16% 99.46%       42MB  0.81%  reflect.cvtBytesString
    0.50MB 0.0097% 99.47%  4843.08MB 93.92%  github.com/ClickHouse/clickhouse-go.(*stmt).ExecContext
         0     0% 99.47%  4845.08MB 93.95%  database/sql.(*Stmt).Exec (inline)
```

```go	
       conn, err := sql.Open("clickhouse", "tcp://127.0.0.1:9000?debug=true")
	conn.SetMaxOpenConns(10)
	conn.SetMaxIdleConns(20)
	if err != nil {
		log.Fatalf("connect clickhouse failed: %v", err)
	}
	defer conn.Close()
	if err != nil {
		log.Fatal(err)
	}
	for i, meta := range all {
		tx, _ := conn.Begin()
		stmt, _ := tx.Prepare(...)
		for k, v := range meta.Files {
			if _, err := stmt.Exec(...); err != nil {
				log.Fatal(err)
			}
		}
		if err := tx.Commit(); err != nil {
			log.Fatal(err)
		}
		stmt.Close()
	}
```

**Comment by Sudio** [comment]
> The `begin->prepare->exec->commit` is used by the clickhouse-go driver to enable batching of inserts. If you have such big insertions you may want to commit the batches after 1k or 10k Exec(). This way you will not fill up your local memory and still take advantage of the faster insertions when using batching.

in fact, i have already commit after 1k+ Exec() . it seems the memory did not decrease after a transaction commit or a statement closing.

**Comment by eqinox76** [comment]
Strange. I just rechecked our application that uploads around 1gb of data (5_000_000 rows) and it stays within 50mb of rss. So something in your use case seems to be different. Most likely only further digging to figure out where the memory is still used will help. Like [here](https://yuriktech.com/2020/11/07/Golang-Memory-Leaks/).

**Comment by lulufeiacount** [comment]
Has the problem been solved? I seem to have encountered the same problem in production

**Comment by Sudio** [comment]
> Has the problem been solved? I seem to have encountered the same problem in production

not solved yet.

**Comment by lulufeiacount** [comment]
> > Has the problem been solved? I seem to have encountered the same problem in production
> 
> not solved yet.

How did you deal with it? Restart?
