### ISSUE TITLE
Nullable support for writing data in blocks seems broken

### ISSUE THREAD

**Issue by markandrus** [ClickHouse/clickhouse-go#410]
Nullable support for writing data in blocks was added in https://github.com/ClickHouse/clickhouse-go/pull/367, but, when testing, I cannot confirm the correct values are written.

First of all, if I just run [clickhouse_columnar_test.go](https://github.com/ClickHouse/clickhouse-go/blob/master/clickhouse_columnar_test.go) against a local ClickHouse instance (21.10.1.7908) and test the results with the ClickHouse client, selecting columns which should be null returns unexpected values instead:

* All columns `uint8_null`, `uint16_null`, `uint32_null`, `uint64_null`, `float32_null` and `float64_null` come back as `0` instead of `ᴺᵁᴸᴸ`.
* `string_null` comes back as the empty string instead of `ᴺᵁᴸᴸ`. By luck, `fString_null` comes back as `ᴺᵁᴸᴸ`.
* `date_null` and `datetime_null` come back as `1970-01-01 01:00:00` and `1970-01-01 01:00:00` instead of `ᴺᵁᴸᴸ`.
* Selecting `enum8_null` and `enum16_null` raises "Unexpected value 0 in enum," presumably because the columns store `0` and have not been marked `ᴺᵁᴸᴸ`.

If I update the test to write non-null values instead, it inserts junk or causes the `INSERT` to hang or fail. For example, writing a non-null string fails with

```
    clickhouse_columnar_test.go:181: 
        	Error Trace:	clickhouse_columnar_test.go:181
        	Error:      	Received unexpected error:
        	            	code: 62, message: Empty query
        	Test:       	Test_ColumnarInsert
```

```diff
diff --git a/clickhouse_columnar_test.go b/clickhouse_columnar_test.go
index d17ddf2..fed5555 100644
--- a/clickhouse_columnar_test.go
+++ b/clickhouse_columnar_test.go
@@ -151,8 +151,9 @@ func Test_ColumnarInsert(t *testing.T) {
                                                block.WriteFloat64(10, float64(i))
                                                block.WriteFloat64Nullable(11, nil)
 
-                                               block.WriteString(12, "string")
-                                               block.WriteStringNullable(13, nil)
+                                               str := "string"
+                                               block.WriteString(12, str)
+                                               block.WriteStringNullable(13, &str)
                                                block.WriteFixedString(14, []byte("CH"))
                                                block.WriteFixedStringNullable(15, nil)
                                                block.WriteDate(16, time.Now())
```

Writing a non-null `uint64` ultimately writes `ᴺᵁᴸᴸ`:

```
marks-air.local :) select uint64_null from clickhouse_test_columnar_insert limit 1;

SELECT uint64_null
FROM clickhouse_test_columnar_insert
LIMIT 1

Query id: 9e2917c0-c989-4f82-b6c5-f5f1a61bde52

┌─uint64_null─┐
│        ᴺᵁᴸᴸ │
└─────────────┘
```

```diff
diff --git a/clickhouse_columnar_test.go b/clickhouse_columnar_test.go
index d17ddf2..1934c06 100644
--- a/clickhouse_columnar_test.go
+++ b/clickhouse_columnar_test.go
@@ -5,6 +5,7 @@ import (
        "github.com/ClickHouse/clickhouse-go"
        "github.com/ClickHouse/clickhouse-go/lib/data"
        "github.com/stretchr/testify/assert"
+       "math"
        "net"
        "reflect"
        "testing"
@@ -143,8 +144,9 @@ func Test_ColumnarInsert(t *testing.T) {
                                                block.WriteUInt16Nullable(3, nil)
                                                block.WriteUInt32(4, uint32(i))
                                                block.WriteUInt32Nullable(5, nil)
-                                               block.WriteUInt64(6, uint64(i))
-                                               block.WriteUInt64Nullable(7, nil)
+                                               uint64val := uint64(math.MaxUint64)
+                                               block.WriteUInt64(6, uint64val)
+                                               block.WriteUInt64Nullable(7, &uint64val)
 
                                                block.WriteFloat32(8, float32(i))
                                                block.WriteFloat32Nullable(9, nil)
```

**Comment by markandrus** [comment]
On first glance, Encoder's [Nullable](https://github.com/ClickHouse/clickhouse-go/blob/master/lib/binary/encoder.go#L48-L57) function looks wrong:

```go
func (enc *Encoder) Nullable(isNull bool) error {
	nullablePrefix := uint8(0)
	if !isNull {
		nullablePrefix = uint8(1)
	}
	if _, err := enc.Get().Write([]byte{nullablePrefix}); err != nil {
		return err
	}
	return nil
}
```

Compare this to [the C++ version](https://github.com/ClickHouse/clickhouse-cpp/blob/master/clickhouse/columns/nullable.cpp#L18-L21):

```cpp
void ColumnNullable::Append(bool isnull)
{
    nulls_->Append(isnull ? 1 : 0);
}
```

In the Go version, doesn't it look like we have an unnecessary `!` in the if-statement? Removing it seems to fix writing nullable `uint8`, `uint16`, etc. But I have issues still with strings (and perhaps other types — still need to test).

**Comment by markandrus** [comment]
I used Wireshark to check how clickhouse-go writes out columns, versus clickhouse-cpp. Here we are writing two non-null values ("hello") to a column `id` with type `Nullable(String)`:

**C++**

```hex
0000   1e 00 00 00 60 08 0c 00 00 69 06 40 00 00 00 00   ....`....i.@....
0010   00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00   ................
0020   00 00 00 00 00 00 00 00 00 00 00 01 e6 2b 23 28   .............+#(
0030   c4 75 d8 cd 34 19 fe ba 80 18 18 e2 00 71 00 00   .u..4........q..
0040   01 01 08 0a 2e 0e 93 6c 2e 0e 93 6c 02 00 4d 1a   .......l...l..M.
0050   c2 bd 60 52 bf df 0d 0d 53 50 13 5f 9a 6f 82 37   ..`R....SP._.o.7
0060   00 00 00 2c 00 00 00 f0 1d 01 00 02 ff ff ff ff   ...,............
0070   00 01 02 02 69 64 10 4e 75 6c 6c 61 62 6c 65 28   ....id.Nullable(
0080   53 74 72 69 6e 67 29 00 00 05 68 65 6c 6c 6f 05   String)...hello.
0090   68 65 6c 6c 6f                                    hello
```

1. Two `isNull` values written out (`00` and `00`),
2. Then two strings written out — first their length (`05`), then their bytes (`68 65 6c 6c 6f`).

**Go**

```hex
0000   02 00 00 00 45 00 00 6e 00 00 40 00 40 06 00 00   ....E..n..@.@...
0010   7f 00 00 01 7f 00 00 01 e6 27 23 28 f7 45 90 1f   .........'#(.E..
0020   5f ed cf 99 80 18 18 ea fe 62 00 00 01 01 08 0a   _........b......
0030   2e 0e 02 7d 2e 0e 02 7d 02 00 01 00 02 ff ff ff   ...}...}........
0040   ff 00 01 02 02 69 64 10 4e 75 6c 6c 61 62 6c 65   .....id.Nullable
0050   28 53 74 72 69 6e 67 29 00 05 68 65 6c 6c 6f 00   (String)..hello.
0060   05 68 65 6c 6c 6f 02 00 01 00 02 ff ff ff ff 00   .hello..........
0070   00 00                                             ..
```

1. One `isNull` value written out (`00`),
2. Then a string written out — first its length (`05`), then its bytes (`68 65 6c 6c 6f`).
3. Another `isNull` value written out (`00`),
4. Then the second string written out — first its length (`05`), then its bytes (`68 65 6c 6c 6f`).
5. Some garbage at the end?

The interleaving of nulls and values in clickhouse-go looks wrong. The two are interleaved rather than treated as separate columns.

**Comment by shinny-chengzhi** [comment]
The layout for nullable column should be  ```... isnull,  isnull,  isnull, value, value, value, ...```

```AppendRow``` is calling ```column.WriteNull``` which correctly write isnull to ```nulls *binary.Encoder``` and values to ```encoder *binary.Encoder``` separately

```WriteXXXNullable``` write both ```isnull``` and ```value``` to ```encoder *binary.Encoder```, thus the resulting layout is ``` ... isnull, value, isnull, value, isnull, value, ...``` which is wrong.
