### ISSUE TITLE
Failed to parse Column type: SimpleAggregateFunction(max, DateTime64(3, 'UTC'))

### ISSUE THREAD

**Issue by utkarsh-sib** [ClickHouse/clickhouse-go#412]
When reading from a table with column type `SimpleAggregateFunction(max, DateTime64(3, 'UTC'))` the following code tries to split `max, DateTime64(3, 'UTC')` by `,`. Which results in an array of length 3. With parts `max`,  `DateTime64(3`, `UTC')`.

https://github.com/ClickHouse/clickhouse-go/blob/1ae00d34c574d8706a8fa2f9277865fb3c41617f/lib/column/column.go#L189-L200

This function returns an error if the length of the splitted array is not equal to 2. 
Please check.
Thanks.

**Comment by kshvakov** [comment]
Fixed in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
