### ISSUE TITLE
how to Disable log

### ISSUE THREAD

**Issue by praisethejack** [ClickHouse/clickhouse-go#417]
when use go-clickhouse, it will output amount of log like those:
[clickhouse][connect=1][begin] tx=false, data=false
[clickhouse][connect=1][prepare] INSERT INTO ...
[clickhouse][connect=1][send query] INSERT INTO ...
[clickhouse][connect=1][send external tables] count 0
[clickhouse][connect=1][read meta] <- data: packet=1, columns=6, rows=0
[clickhouse][connect=1][commit] tx=true, data=true
[clickhouse][connect=1][process] <- end of stream
[clickhouse][connect=1][stmt] close

I don't hope to see that, is there a function to disable those log?

**Comment by argakon** [comment]
Set debug=false in connection string

**Comment by praisethejack** [comment]
@argakon thanks
