### ISSUE TITLE
Incorrect error returned when context is canceled during query or when handling resulting rows

### ISSUE THREAD

**Issue by sidh** [ClickHouse/clickhouse-go#426]
If context passed to query methods is canceled while query is being executed or while handling resulting Rows, sql.ErrBadConn is returned instead of context.Canceled. This breaks error handling and requires separate context check after each sql.ErrBadConn error.

I suppose similar thing happens when context' deadline is exceeded.

Solution - driver should return ctx.Err() instead of sql.ErrBadConn when context is canceled.

**Comment by kshvakov** [comment]
Done https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/std/context_timeout_test.go#L13
