### ISSUE TITLE
[question] How do I insert arrays of nested data? 

### ISSUE THREAD

**Issue by akamensky** [ClickHouse/clickhouse-go#428]
The documentation about this use case is non-existent...

I have a set of data that looks similar to:

```go
type Obj struct {
  Field1 string
  Field2 uint64
  Field3 []*SubObj
}

type SubObj struct {
  Field1 string
  Field2 uint64
  Field4 []*T1
  Field5 []*T2
}

type T1 struct {
  F1 string
  F2 uint64
}

type T1 struct {
  F1 string
  F2 uint64
}
```

This needs to be inserted into Clickhouse, so I am looking at arrays of nested data. I created a table that looks like:

```sql
create table tbl_name (
  Field1 String,
  Field2 UInt64,
  Field3 Array(
    Nested(
      Field1 string,
      Field2 uint64,
      Field4 Array(
        Nested(
          F1 String,
          F2 UInt64,
        )
      ),
      Field5 Array(
        Nested(
          F1 String,
          F2 UInt64,
        )
      )
    )
  )
)
engine = MergeTree
partition by Field2
order by Field2
```

But I don't seem to find a way to insert this data into Clickhouse using this library. Everything ends up with `Field3` being `[]` (empty array).

**Comment by kshvakov** [comment]
Nested type  is [Array](https://clickhouse.com/docs/en/operations/settings/settings/#flatten-nested). But your schema looks it's no good to CH, maybe PostgreSQL or MongoDB will be better for you
