### ISSUE TITLE
[bug] inserts only supported in batch mode

### ISSUE THREAD

**Issue by akamensky** [ClickHouse/clickhouse-go#430]
This is definitely a bug, not code bug, but logical. There are cases where this causes issues and require clunky implementations with singular inserts wrapped into begin...end. And transactions don't even exist in Clickhouse. All other attempts to `.Exec("insert into ...")` fails with: `insert statement supported only in the batch mode (use begin/commit)`.

There is no logical reason why it needs to be required by this driver. So I think this implementation needs to be reconsidered.

**Comment by kshvakov** [comment]
Hi, if you want to use ClickHouse - use batch queries;)

**Comment by akamensky** [comment]
@kshvakov have you read the post before closing this issue? There is no logical reason to force "batching" to everyone.

Anyway. Thanks for showing where your priorities are. I am changing my project to Postgres.

**Comment by sjsdfg** [comment]
i can't agree more with you @akamensky

this deign sucks

**Comment by labulakalia** [comment]
@akamensky you can use github.com/mailru/go-clickhouse
