### ISSUE TITLE
[bug] Unable Parse string column into byte slice

### ISSUE THREAD

**Issue by akamensky** [ClickHouse/clickhouse-go#431]
I am using this driver via sql package (as in `sql.Open("clickhouse", ...)`).

It is a common pattern to Parse string column into `[]byte`. This works perfectly fine with MySQL and Postgres drivers, but not here. The returned error is "interface not a pointer", which in case of slice should not be a pointer.

Assume the code as:

```go
var strCol []byte

d, _ := sql.Open("clickhouse", "...")
err := d.QueryRow("select str_col from tbl_name limit 1").Scan(strCol)
if err != nil {
    panic(err)
}
fmt.Println(string(strCol))
```

**Comment by kshvakov** [comment]
Yes, the driver does not cast the string to bytes. You can convert string to bytes in your code

**Comment by akamensky** [comment]
@kshvakov have you read the post? That is opposite of how sql interface should behave. Hence that's a bug.
