### ISSUE TITLE
Return real errors from user-facing methods and implement `ResetSession`

### ISSUE THREAD

**Issue by joewreschnig** [ClickHouse/clickhouse-go#433]
The `connect` `Read` and `Write` methods return `driver.ErrBadConn` if any error occurs during reading or writing. However, this masks the real error, which can only be seen if you enable the debug log. However, as noted in several other issue reports `ErrBadConn` must be returned as part of the `driver.Conn` interface to invalidate the connection rather than return it to the pool.

To deal with this Go supports [a `ResetSession` method](https://pkg.go.dev/database/sql/driver#SessionResetter). If the `driver.Conn` implements it, it's called any time a connection will be reused and it can return `ErrBadConn` to the same effect, allowing e.g. the `Commit` method to instead return a more informative error to the user.

A `ResetSession` implemented on `clickhouse` may also be a better place for some of the cleanup logic currently implemented in `Commit` and `Rollback`.

**Comment by joewreschnig** [comment]
If there's no objection to this design I'd be willing to work on it.

**Comment by Slach** [comment]
Great, please feel free to make PR

**Comment by joewreschnig** [comment]
I've put a draft PR for review up at #436. There are three tests I'm having trouble with (also before my changes) and would appreciate help from someone more familiar with the test suite.

**Comment by williamfeng323** [comment]
@joewreschnig are you still working on this PR? It is a good fix because if the ResetSession can throw the ErrBadConn, the BeginTx method could create another tx with a new connection which might resolve the #336

**Comment by joewreschnig** [comment]
As far as I know the PR is ready but I had two test failures that I could not trace to anything in my changes, and one failure related to my changes that also failed on master. I've taken the PR out of draft state to hopefully attract more attention, as well as raise one other minor issue I found. If you're more familiar with the code you could look at #436.

**Comment by kshvakov** [comment]
Added in [V2](https://github.com/ClickHouse/clickhouse-go/blob/v2/clickhouse_std.go#L49)
