### ISSUE TITLE
Inconsistent logic in implementation

### ISSUE THREAD

**Issue by akamensky** [ClickHouse/clickhouse-go#435]
In [here](https://github.com/ClickHouse/clickhouse-go/issues/33#issuecomment-300072595) you say that:

> Hi, it's not possible, Clickhouse do not support transactions

But in [here](https://github.com/ClickHouse/clickhouse-go/issues/430#issuecomment-964416026) you say:

> Hi, if you want to use ClickHouse - use batch queries;)

**Before someone rush to close this ticket -- I am WELL aware that ClickHouse doesn't support transactions, the point of this ticket is THIS LIBRARY flawed logic.**

You either allow `db.Exec("INSERT ...")` without requiring using "fake transactions", or you allow fully effing working "transaction" functionality, that is different types of inserts with one "transaction". You can't have both at the same time otherwise this library is unusable in most cases.

I.e. my example -- I am reading data from another source and inserting it into 5 different tables. I cannot do it with just `db.Exec("INSERT...")` because of #430 and I cannot do it with single "transaction" and "prepare" because of #33.

**The limitation is not in ClickHouse, the limitation is artificially imposed by this library.**

**Comment by Slach** [comment]
@akamensky look to https://github.com/vahid-sohrabloo/chconn, maybe it will better choice for you?

And please, could you be little less toxic, if you want to change something, let's make a pull request

**Comment by akamensky** [comment]
> maybe it will better choice for you?
34 commits as of today, no documentation and readme with notice that "It's on heavy development. Don't use it until the first release". It well may come out to be a good low level lib for CH in the future, but looks like not there yet. In my project I need to use Golangs' built-in `sql` interface (for replaceable databases) and I need a stable enough library for at least basic operations. So for this library seemed to be the one, but (see below)

> And please, could you be little less toxic

Apologies if that came out this way, I feel very frustrated dealing with this library. I need to support CH, and I have been using it for some time already with Python and Java. Those libraries there don't have similar weird implementations somehow. But the "straw that broke the camels back" is that I see plenty of valid issues reported here and being closed  without due consideration and with a comment a-la "we know better than you (winky face)".

> let's make a pull request

Would love to once I have free time (perhaps next year).

**Comment by Slach** [comment]
> Would love to once I have free time (perhaps next year).
Community will wait you, always!
And thanks a lot for your efforts

**Comment by sjsdfg** [comment]
i can't agree more with you @akamensky 

this deign sucks

**Comment by kshvakov** [comment]
We have 2 interfaces in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
