### ISSUE TITLE
Use the HTTP interface so that we can enable async inserts

### ISSUE THREAD

**Issue by tonyhb** [ClickHouse/clickhouse-go#443]
This driver uses the TCP interface which has so far been great for us.  That said, the newer releases of clickhouse support async inserts without buffer tables via the HTTP interface.  It would be great to enable this within the official go driver.

**Comment by ramazanpolat** [comment]
Ok, need clarification.

Can we use async_insert while connected to `native interface`?

https://github.com/ClickHouse/clickhouse-go#native-interface
![image](https://user-images.githubusercontent.com/3527695/153781437-a308d26f-5197-4fb5-80f0-ed9c73392564.png)

**Comment by kshvakov** [comment]
@ramazanpolat Hi, you can
