### ISSUE TITLE
is it possible to load parquet file with this library?

### ISSUE THREAD

**Issue by saartamir** [ClickHouse/clickhouse-go#446]
Hello,
I have a service that consume message from kafka and save it into Parquet files.
I want to know if it's possible to use this library to load the parquet files into Clickhouse.
It's possible with the clickhouse-client in command line:
`$ cat {filename} | clickhouse-client --query="INSERT INTO {some_table} FORMAT Parquet"`

**Comment by kshvakov** [comment]
Hi, the driver does not support the `FORMAT` functionality this is only a ClickHouse Client and Server feature
