### ISSUE TITLE
seq_time

### ISSUE THREAD

**Issue by dlvkin** [ClickHouse/clickhouse-go#448]
insertSql ="INSERT INTO activity_user_track(cell_id,imsi,tac,other_tac,other_eci,city,procedure_end_time,seq_num,seq_time)VALUES(?,?,?,?,?,?,?,?,?)"

var stmt, er = tx.Prepare(insertSql)
	if er != nil {
		log.Printf("Prepare error: %v \n", err)
		return
	}
when connect  transaction Prepare,but error is happed, the error is fellow as:

cannot parse expression of type String here: ?,?,?,?,?,?,?,?,?) VALUES : While executing ValuesBlockInputFormat

i reference official document guide,i don't know why, and how to solve this problem

**Comment by kshvakov** [comment]
It is a driver bug. You can send insert request without placeholders, like: 
```INSERT INTO activity_user_track(cell_id,imsi,tac,other_tac,other_eci,city,procedure_end_time,seq_num,seq_time)VALUES```
