### ISSUE TITLE
CompressReader and CompressWriter keep creating new buff in goroutine

### ISSUE THREAD

**Issue by FingerLiu** [ClickHouse/clickhouse-go#449]
![image](https://user-images.githubusercontent.com/3981064/147525908-6261a612-d47c-4e8b-82f0-37fb844e016f.png)

I have a cron logic which create goroutine and connect to clickhouse repeatedly. Through heap flameGraph I can see CompressReader and CompressWriter keep creating new buff. I know this is not a memory leak but creating objects perhaps means a lot of gc. Can we use `sync.Pool` to reuse buffer across different connections?

**Comment by PaulHindenberg** [comment]
Had the same problem after doing some testing. Had a big loop and every loop did a select statement.  As a Result I had 46gb for NewCompressReader and  46gb for NewCompressWriter.

I found an easy solution here: https://github.com/ClickHouse/clickhouse-go/issues/316

This helped me a lot to avoid the huge memory usage + another boost in performance:
```
    connect.SetMaxOpenConns(5)
    connect.SetMaxIdleConns(1)
    connect.SetConnMaxLifetime(1 * time.Minute)
```

**Comment by kshvakov** [comment]
Hi, @PaulHindenberg. I fixed this issue in [V2 ](https://github.com/ClickHouse/clickhouse-go/tree/v2). I think in a couple of weeks we will release the first v2 version
