### ISSUE TITLE
connections leak on errors in insert()

### ISSUE THREAD

**Issue by dobergerator** [ClickHouse/clickhouse-go#451]
I'm having an issue
tx.Prepare() raise exception and leaks connection in process
sql.Open() being called only once during app init and SetMaxOpenConns and SetMaxIdleConns are set

```
        db, err := sql.Open(config.ClickhouseDriverName, client.ConnectionString)
        if err != nil {
           return err
        }
        
        db.SetMaxOpenConns(25)
        db.SetMaxIdleConns(25)
        db.SetConnMaxLifetime(time.Duration(300 * time.Second)        

        table := "wrong_table_name"
        clickFields := []string{"field1", "field2"}
	questions := []string{"?", "?"}

 	query := fmt.Sprintf(
		`INSERT INTO %v (%v) VALUES (%v)`,
		table,
		strings.Join(clickFields, ","),
		questions)

	tx, err := db.Begin()
	if err != nil {
		return err
	}

	stmt, err := tx.Prepare(query)
	if err != nil {
		return err
	}
```

tx.Prepare() then returns stmt = nil and err = ""code: 60, message: Table wrong_table_name doesn't exist.
And keeps the connection in use
SetConnMaxLifetime doesn't affect it

This way app may raise error only 25 times, call 26 locks thread

**Comment by kshvakov** [comment]
Fixed in V2, see[ stress.go ](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/stress/stress.go)
