### ISSUE TITLE
Truncate time to day by Unix Time

### ISSUE THREAD

**Issue by dandans-dan** [ClickHouse/clickhouse-go#456]
https://github.com/ClickHouse/clickhouse-go/blob/5e59844a8ec407dd194e0f34dac9eb2b1f3b6342/helpers.go#L145

I used module at non UTC time zone, like Asia/Shanghai.
So I got wrong SQL used module like this:
```go
stmt.Query(time.Date(2022, 1, 17, 0, 0, 0, 0, time.Local))
// got sql like toDate(19008)
```

**Comment by kshvakov** [comment]
Fixed in [v1.5.2](https://github.com/ClickHouse/clickhouse-go/releases/tag/v1.5.2)
