### ISSUE TITLE
go-faster ch

### ISSUE THREAD

**Issue by alifpay** [ClickHouse/clickhouse-go#457]
Hi,

https://github.com/go-faster/ch

what do you think about go-faster/ch?

**Comment by cnmade** [comment]
Good question, you may want to ask if they can donate the project into merge into clickhouse-go project.
This is the real official support project.

Or else, may be the clickhouse-go native protocol support is on the way...

**Comment by kshvakov** [comment]
@cnmade Hi, we supported tcp protocol in both version (V1 and [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)). 

@alifpay We have the same performance for the write and a little slower at reading as go-fast in real applications.  go-faster assumes that you will work with raw data, while clickhouse-go does this work for you and provides a simple and familiar interface.

**Comment by cnmade** [comment]
@kshvakov Thanks for tip me that . i missed the real feature of clickhouse-go. I am really write Java instead Golang, sorry for any inconvence
