### ISSUE TITLE
possible performance issue on stmt

### ISSUE THREAD

**Issue by nianglao** [ClickHouse/clickhouse-go#458]
Hi,

I found a possible performance issue but don't know if it's caused by Golang sql package or clickhouse-go driver. 

I built up an App which queries Clickhouse Cluster with Golang sql/driver + clickhouse-go. My App logs the db execution time of db.QueryContext() and rows.Close(). I can also find the query execution time in Clickhouse system.query_log.
For 10 out of 4000 queries in production environment, I found they executed very fast in Clikchouse but cost too much in driver.
Take one query as example: it run 100ms in Clickhouse and resulted 0 rows, but App cost 10s to finish this query.

After some investigation, I found the Golang sql stmt.Close() take most of the time.

Has anyone meet this issue ever?

**Comment by kshvakov** [comment]
Can you reproduce this in [v2](https://github.com/ClickHouse/clickhouse-go/tree/v2)?

**Comment by nianglao** [comment]
Oh, we still use v1. I will adopt v2 and keep on watching this.

**Comment by nianglao** [comment]
@kshvakov Do your have any plan about when the major version v2 will be released officially.
Looking forward to v2.0.0

**Comment by kshvakov** [comment]
@nianglao Early next week

**Comment by kshvakov** [comment]
Done
