### ISSUE TITLE
implementation QueryerContext interface in Golang sql/driver for Conn 

### ISSUE THREAD

**Issue by nianglao** [ClickHouse/clickhouse-go#459]
As described in http://go-database-sql.org/prepared.html, _Sometimes a prepared statement is not what you want_

Do you have any plan to implement QueryerContext interface in Golang sql/driver for Conn to avoid using prepared stmt in some scenarios.

**Comment by kshvakov** [comment]
Done, will be added in the next [v2](https://github.com/ClickHouse/clickhouse-go/tree/v2) release

**Comment by nianglao** [comment]
@kshvakov 
thanks for this quick response.

One comment for your implemetation:
refer https://pkg.go.dev/database/sql/driver#QueryerContext, 
`QueryerContext must honor the context timeout and return when the context is canceled.`
Please help confirm if your implementation should honor this.

**Comment by kshvakov** [comment]
@nianglao Sometimes we get a `net.Error` on macOS when passing ContextWithTimeout  https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/std/context_timeout_test.go#L18. I think I can fix it
