### ISSUE TITLE
 Code: 113, e.displayText() = DB::Exception: There is no session or session context has expired (version vSClickhouse-21.8.4.1-008)\n, sql: set max_memory_usage = 30000000000

### ISSUE THREAD

**Issue by AlpJQ** [ClickHouse/clickhouse-go#461]
code:
sess := clickhouse.Connection.NewSessionContext(ctx, nil)
_, err := sess.Exec(sql)

my sql:set max_memory_usage = 30000000000

error: There is no session or session context has expired

**Comment by kshvakov** [comment]
Hello, I think the problem is in https://github.com/mailru/dbr ;)
