### ISSUE TITLE
I cant use RegisterTLSConfig() in v2

### ISSUE THREAD

**Issue by uptutu** [ClickHouse/clickhouse-go#463]
I try to upgrade my SDK, no RegisterTLSConfig function now, how should I config this?

**Comment by uptutu** [comment]
Is there a std compatible method?

**Comment by kshvakov** [comment]
Not right now. I will add the `RegisterTLSConfig` method for `database/sql`

**Comment by kshvakov** [comment]
I added `OpenDB`, it's better then `RegisterTLSConfig`. See example https://github.com/ClickHouse/clickhouse-go/blob/master/examples/std/open_db.go. I'm going to check how it works and add it I'll make a new release

**Comment by kshvakov** [comment]
@uptutu done https://github.com/ClickHouse/clickhouse-go/releases/tag/v2.0.0-beta.4
