### ISSUE TITLE
Why do u force your users to some default settings?

### ISSUE THREAD

**Issue by sinkyminky** [ClickHouse/clickhouse-go#464]
hey, i checked your new v2 codes. one part is confused me. i am talking about this part :

```go 

func (o *Options) setDefaults() {
	if len(o.Auth.Database) == 0 {
		o.Auth.Database = "default"
	}
	if len(o.Auth.Username) == 0 {
		o.Auth.Username = "default"
	}
	if o.DialTimeout == 0 {
		o.DialTimeout = time.Second
	}
	if o.MaxIdleConns <= 0 {
		o.MaxIdleConns = 5
	}
	if o.MaxOpenConns <= 0 {
		o.MaxOpenConns = o.MaxIdleConns + 5
	}
	if o.ConnMaxLifetime == 0 {
		o.ConnMaxLifetime = time.Hour
	}
}
```

as i asked at title i am repeating. Why do u force your users to some default settings? maybe i do not wanna set idle connections or i wanna use clickhouse max connection count which is 4096 so i do not need to set it or i wanna use endless connection life time. why?

**Comment by kshvakov** [comment]
This fixes common mistakes that were made when working with `database/sql`. If you need others, you can change them as you like.

**Comment by sinkyminky** [comment]
thanks for reply. At your [benchmarks](https://github.com/ClickHouse/clickhouse-go#benchmark) you benchmarked standard lib with 0(zero) idle connection vs native lib with 5 idle connection. Isn't it usual for the native one to be faster in this case?

**Comment by kshvakov** [comment]
It doesn't matter. Only one connection is used in the benchmark. The native interface is faster because it has less overhead for reflection
