### ISSUE TITLE
Inserting into a UUID column swaps bytes of underlying array [2]

### ISSUE THREAD

**Issue by simonenkoav** [ClickHouse/clickhouse-go#477]
### Issue description
Seems that bug reported in https://github.com/ClickHouse/clickhouse-go/issues/168 is still present for driver version 2. Saving values like that:
```go
import (
	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/google/uuid"
)

type Value struct {
	ID        uuid.UUID `ch:"id"`
	Name      string    `ch:"name"`
	CreatedAt time.Time `ch:"created_at"`
}

...
	batch, err := s.conn.PrepareBatch(ctx, "insert into my_table (id, name, created_at)")
	for i, v := range values {
		if err = batch.Append(v.ID, v.Name, v.CreatedAt); err != nil {
			return err
		}
	}
	batch.Send()
...
```
leads to uuid `3d6a2c88-dc64-4c7c-89df-7e9ef19abbf6` saved in database as `7c4c64dc-882c-6a3d-f6bb-9af19e7edf89`.

### Configuration
*OS:*
```
╰─λ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

*Go version:*
```
╰─λ go version
go version go1.17.2 linux/amd64
```

*ClickHouse Server version:*
```
SELECT version()

┌─version()─┐
│ 21.8.3.44 │
└───────────┘
````

*Interface:* `native`

**Comment by kshvakov** [comment]
Fixed https://github.com/ClickHouse/clickhouse-go/commit/129754155b1d70a45415fdb9291a96e522408ca8. 

Update the driver to the latest version

```
go get -u github.com/ClickHouse/clickhouse-go/v2
```
