### ISSUE TITLE
Allow scanning rows to interface{} type

### ISSUE THREAD

**Issue by usrlocl** [ClickHouse/clickhouse-go#478]
I would like to be able to specify interface{} types for Scan as so,

    var col1 interface{}
    conn.QueryRow(ctx, "SELECT foo FROM bar").Scan(&col1)

However, it throws the following error

    converting String to *interface {} is unsupported

Doing this can allow for some generic behaviour when the column types are not known in the application.

It should be a straight forward change. Wondering if it was a conscious choice to not allow this or would you be open for a pull request?

**Comment by usrlocl** [comment]
Is this available only on the standard interface? Is there an equivalent on the native interface as well, or any plans to introduce?

**Comment by kshvakov** [comment]
I'll add `ColumnTypes` to native interface

**Comment by usrlocl** [comment]
Great! Btw, what are the plans with respect to standard vs native interfaces? Will they be maintained in conjunction going forward or is one likely to be deprecated?
Also interested to know if it's mainly performance reason to prefer native one or are there other limitations with standard one?

**Comment by kshvakov** [comment]
We will support both interfaces, since in some cases users are more accustomed to using the standard interface. In the native interface, we can choose the names of methods and their meaning is clear, while in the standard one everything may not be so obvious. For example, we use "transactions" to prepare a block with data, while the native interface has a method called `PrepareBatch`, the same with asynchronous requests, and so on

**Comment by kshvakov** [comment]
Done https://github.com/ClickHouse/clickhouse-go/commit/d214e35e9a09babc97a04dec86b7a057d5d1659c

**Comment by usrlocl** [comment]
I tried this on HEAD. I can use ColumnTypes() now but getting the same error as before with native interface.

     [ScanRow]: (type) converting Enum8 to *interface {} is unsupported

I think the issue is that ScanRow still sees the type as *interface{} which has no handling. I modified the code you shared to use native interface.

**Comment by kshvakov** [comment]
I have added an example https://github.com/ClickHouse/clickhouse-go/commit/9b480b54a0175e63ca51ba93002b4d83ae622c32

**Comment by usrlocl** [comment]
Ah, it works with reflect.Value instead of pointer type. This should be good as well.

Thank you very much for the change and all the help!
