### ISSUE TITLE
Cannot parse expression of type Int64 on insert

### ISSUE THREAD

**Issue by Kugelschieber** [ClickHouse/clickhouse-go#481]
### Issue description

I'm testing v2 with github.com/golang-migrate/migrate/v4. Starting with an empty database, it does create the schema_migrations table, but fails to insert migration steps with the error `panic: code: 62, message: Cannot parse expression of type Int64 here: ?, ?, ?): While executing ValuesBlockInputFormat in line 0: INSERT INTO schema_migrations (version, dirty, sequence) VALUES (?, ?, ?)`.

### Example code

From [the library](https://github.com/golang-migrate/migrate/blob/master/database/clickhouse/clickhouse.go#L182):

```go
query := "INSERT INTO " + ch.config.MigrationsTable + " (version, dirty, sequence) VALUES (?, ?, ?)"
if _, err := tx.Exec(query, version, bool(dirty), time.Now().UnixNano()); err != nil {
    return &database.Error{OrigErr: err, Query: []byte(query)}
}
```

tx is a regular `*sql.Tx`. I've tried casting the `version` variable to int64, but it still returns the error. The table looks like this:

```sql
CREATE TABLE schema_migrations
(
    `version` Int64,
    `dirty` UInt8,
    `sequence` UInt64
)
ENGINE = TinyLog
```

### Configuration
*OS:* Manjaro

*Interface:* `database/sql`

*Driver version:* 2.0.3

*Go version:* go1.17.6 linux/amd64

*ClickHouse Server version:* 21.11

**Comment by kshvakov** [comment]
Hi, first of all ClickHouse does not support transactions, so it's a mistake to treat it as a transactional database. Second, you must use prepared statements to insert data for both the [database/sql](https://github.com/ClickHouse/clickhouse-go/blob/v2/examples/std/batch/main.go#L57) and [native](https://github.com/ClickHouse/clickhouse-go/blob/v2/examples/native/batch/main.go#L69) interfaces or you can use AsyncInsert see examples: [native](https://github.com/ClickHouse/clickhouse-go/blob/v2/examples/native/write-async/main.go), [std](https://github.com/ClickHouse/clickhouse-go/blob/v2/examples/std/write-async/main.go)

**Comment by Kugelschieber** [comment]
Thanks for pointing it out! Did this behavior change from v1? I'm not a contributor to github.com/golang-migrate/migrate, but it works with v1.

I think this has to be changed on their end then :)

**Comment by kshvakov** [comment]
I don't know how it works) golang-migrate uses clickhouse-go 1.4. Can you provide full code and I'll try to investigate?

**Comment by Kugelschieber** [comment]
You can clone our repo: https://github.com/pirsch-analytics/pirsch and checkout the branch `clickhouse-driver`. This will migrate the database for the schema `pirschtest` using a local ClickHouse installation (using `default` as a user and no password).

Alternatively, here is the migration function: https://github.com/pirsch-analytics/pirsch/blob/clickhouse-driver/migrate.go

**Comment by kshvakov** [comment]
I'll prepare a PR for the golang-migrate

**Comment by Kugelschieber** [comment]
Incredible, thank you so much for your help!

**Comment by kshvakov** [comment]
@Kugelschieber https://github.com/golang-migrate/migrate/pull/697

**Comment by Kugelschieber** [comment]
I might just use your fork for testing. They're really taking their time for the PR (which is fine, but I would like to move on :D).

**Comment by gingerwizard** [comment]
Closing this as not relevant to the driver.
