### ISSUE TITLE
'DateTime' column out of range issue.

### ISSUE THREAD

**Issue by kholo89** [ClickHouse/clickhouse-go#482]
### Issue description

Hello.
Thank you for your contribution.
I'm using this repository very well for my project.

My issue is related to DateTime value.

The origin DB DateTime value is '2061-02-01 00:00:00', but parsed value is '1924-12-27 02:31:44 +0900 KST' in Go.
So, I tried to debug this repository code. then I figured out parsed timestamp is -1328628496.

I guess this issue related to out of range data type Int32.
Because this value('2061-02-01 00:00:00')'s timestamp is 2874441600.
It's out of range the max value of Int32. But it's just my guess.

So, I tried this code.
```
select toDateTime64(toUnixTimestamp(toDateTime('2064-01-01 00:00:00')), 3)
```

Then, This is working.

I attached my test code.

Thank you.

### Example code
```go
func main() {
	setDB()

	query := `
select
	toDateTime('2020-02-01 00:00:00'), -- Not issued date
	toDateTime('2061-02-01 00:00:00'), -- Issued date
	toDateTime64(toUnixTimestamp(toDateTime('2064-01-01 00:00:00')), 3), -- Depend code
	toDateTime(2147483647), -- Int 32 max value to timestamp
	toDateTime(2147483648) -- Test for range over int32
`
	var (
		notIssueDate    time.Time
		myIssueDate     time.Time
		myIssueDateTo64 time.Time
		int32MaxDate    time.Time
		int32OverDate   time.Time
	)

	row := db.QueryRow(context.Background(), query)

	if err := row.Scan(&notIssueDate, &myIssueDate, &myIssueDateTo64, &int32MaxDate, &int32OverDate); err != nil {
		panic(err)
	}

	fmt.Println(notIssueDate) // 2020-02-01 09:00:00 +0900 KST
	fmt.Println(myIssueDate) // 1924-12-27 02:31:44 +0900 KST
	fmt.Println(myIssueDateTo64) // 2064-01-01 09:00:00 +0900 KST
	fmt.Println(int32MaxDate) // 2038-01-19 12:14:07 +0900 KST
	fmt.Println(int32OverDate) // 1901-12-14 05:45:52 +0900 KST
}
```

### Configuration
*OS:* Windows 10

*Interface:* native

*Driver version:* 2.0.5 (Same occur error in 2.0.4)

*Go version:* go version go1.17.2 windows/amd64

*ClickHouse Server version:*  yandex/clickhouse-server:21.3.8.76 (From docker-hub)

**Comment by kshvakov** [comment]
Fixed

**Comment by kholo89** [comment]
I checked this working. Thank you :)
