### ISSUE TITLE
Example for opentelemetry integration

### ISSUE THREAD

**Issue by itzikiusa** [ClickHouse/clickhouse-go#493]
Hi, is it possible to add an example how to use otel with the driver?
both for native and std

(we moved from version 1.5.2 to 2.0.10)
we so a performance improvement of more than 400% (2k records: avg of bulk insert before: 1200ms, new version: 270ms, without using async inserts, and server is remote, so there is this latency)
very much appriciated the latest changes (though we are not working that intesnly with CH, we do see an improvement)

**Comment by kshvakov** [comment]
You can set the `SpanContext` with the `Context` for the queries https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/opentelemetry_test.go#L43

For integration with monitoring systems you should use [system.opentelemetry_span_log](https://clickhouse.com/docs/en/operations/system-tables/opentelemetry_span_log/) table
See https://clickhouse.com/docs/en/operations/opentelemetry/
