### ISSUE TITLE
Query on different partitions

### ISSUE THREAD

**Issue by itzikiusa** [ClickHouse/clickhouse-go#502]
Hi, when i try to query different partitions and try to retrieve all data, when results coming from different partitions only single result is being returned, is there a way to overcome it(using select to scan struct)? currently using order by does the trick, but is there another way?

thanks!

**Comment by kshvakov** [comment]
Can't reproduce. Try v2.0.11

**Comment by itzikiusa** [comment]
@kshvakov yeah, seems like it is working on the new version
was using v2.0.9

will upgrade, thanks!
