### ISSUE TITLE
How to use grouping set in the where syntax?

### ISSUE THREAD

**Issue by kholo89** [ClickHouse/clickhouse-go#504]
### Issue description
Hi,

I need to use grouping set pattern in the query.
But, it's not working my expected.
ex: WHERE (a,b) IN $1 => WHERE (a, b) IN (('a', 1), ('b', 2))

I attach my partial code.
Thank you.

### Example code
```go
		var keys [][]interface{}

		for _, key := range shopKeys {
			keys = append(keys, []interface{}{key.ShopId, key.ShopNo})
		}

		query := `
SELECT 
  shop_id, shop_no, shop_name
FROM
  shop
WHERE
  (shop_id, shop_no) IN $1
`
		rows, err := database.DB.Query(context.Background(), query, keys)
```

### Error log
```
[clickhouse][conn=1][...][handshake] -> Golang SQLDriver 1.1.54453
[clickhouse][conn=1][...][handshake] downgrade client proto
[clickhouse][conn=1][...][handshake] <- ClickHouse (...) server version 20.6.4 revision 54436 (timezone UTC)
[clickhouse][conn=1][...][send query] compression=true 
SELECT 
  shop_id, shop_no, shop_name
FROM
  shop
WHERE
  (shop_id, shop_no) IN 'a', 1, 'b', 1, 'c', 1, 'd'
[clickhouse][conn=1][...][send data] compression=true
[clickhouse][conn=1][...][exception] code: 62, message: Syntax error: failed at position 135 (line 8, col 38): , 1, 'b', 1, 'c', 1, 'd', 1'. Expected one of: LIMIT, LIKE, GLOBAL NOT IN, AS, HAVING, IS, GROUP BY, INTO OUTFILE, OR, QuestionMark, OFFSET, BETWEEN, NOT LIKE, AND, alias, ORDER BY, SETTINGS, UNION ALL, IN, ILIKE, FORMAT, NOT ILIKE, WITH, NOT, token, NOT IN, GLOBAL IN
2022/02/18 17:04:15 [Recovery] 2022/02/18 - 17:04:15 panic recovered:
```

### Configuration
*OS:* Linux(k8s)

*Interface:* Native

*Driver version:* 2.0.11

*Go version:* 1.16.7

*ClickHouse Server version:* 21.3.8.76

**Comment by kshvakov** [comment]
Added in v2.0.12. See example https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/issues/504_test.go#L46

**Comment by kholo89** [comment]
It's working. Thank you :)

**Comment by gingerwizard** [comment]
@kholo89 this behavior will change in 2.11. The previous implementation of using []interface{} was fragile and prevented users from using maps with slices. We added support for grouping sets https://github.com/ClickHouse/clickhouse-go/pull/620. Updated the issue test and example [here](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/issues/504_test.go#L48)

Apologies for this breaking change. We're cognizant this isn't ideal but unavoidable in this case.
