### ISSUE TITLE
Socket timeout or read time out setting parameter

### ISSUE THREAD

**Issue by akhalifeh79** [ClickHouse/clickhouse-go#509]
I need to set a time out for query execution + reading data time, I tried the parameters  "query_timeout" and "connect_timeout" with no success.  Any solution for this please?

@Test
	void testDriverTimeout(){
		Properties clickhouseProperties = new Properties();
		clickhouseProperties.setProperty("user", "**");
		clickhouseProperties.setProperty("password", "**");
		clickhouseProperties.setProperty("query_timeout", "1");
		clickhouseProperties.setProperty("connect_timeout", "3");

		DataSource balancedCkDs = new BalancedClickhouseDataSource("**", clickhouseProperties);
		List<String> result = new ArrayList<>();

		try (Connection conn1 = balancedCkDs.getConnection()) {
			PreparedStatement ps = conn1.prepareStatement("blab blab);
			long start1 = System.currentTimeMillis();
			ResultSet rs = ps.executeQuery();
			long end1 = System.currentTimeMillis();
			System.out.println("Elapsed Time in seconds: "+ (end1-start1)/1000);

			start1 = System.currentTimeMillis();
			while(rs.next()){
				result.add(rs.getString("external_id"));
			}
			end1 = System.currentTimeMillis();
			System.out.println("Elapsed Time for reading data in seconds: "+ (end1-start1)/1000);
		}catch (Exception ex){
			System.out.println(ex);
		}

		System.out.println(result);

	}
Elapsed Time for query execution in seconds: 0
Elapsed Time for reading data in seconds: 73

**Comment by kshvakov** [comment]
Hi, try to create an issue in [JDBC repo](https://github.com/ClickHouse/clickhouse-jdbc)
