### ISSUE TITLE
AppendStruct  missing destination name  *main.row

### ISSUE THREAD

**Issue by roccia** [ClickHouse/clickhouse-go#513]
I'm testing batch write struct, but got  missing destination name  *main.row , I'v checked `block.names`, it does contain all clomuns, not sure what cause this problem
code :
 <img width="786" alt="image" src="https://user-images.githubusercontent.com/5943684/156005023-deacf5f4-1ddc-41cb-a2cb-d608928563b1.png">
 
 antoher question: in my table column names are : metric_name,ts,value... all are low case, when constructing a struct, I cant use camel case right? I did not see any convertion code from camel to lower

**Comment by kshvakov** [comment]
The fields must be public. If you want to map column names to fields, you should use the `ch` tag

```
type row struct{
  TS int64 `ch:"ts"`
}```

**Comment by roccia** [comment]
> 

Thank you very much!   the example code did not use `ch` tag, should I submit a pr for this?

**Comment by kshvakov** [comment]
Yes, it will be good)
