### ISSUE TITLE
What is the correct way to use the load balancer of clickhouse-go driver?

### ISSUE THREAD

**Issue by yandongl** [ClickHouse/clickhouse-go#515]
## description

Hi, I recently use clickhouse-go v2 driver to insert tables in clickhouse cluster and want it can be load-balanced. However, I found all data send to one server that didn‘t work as I expected. My experiment steps are as follows. 

### setup clickhouse-cluster

I follow the repos of [tetafro/clickhouse-cluster](https://github.com/tetafro/clickhouse-cluster) to set up my clickhouse-cluster and create the database `company_db`, local table `events` and distributed table `events_distr` on cluster `company_cluster`.

Besides, I make all 4 clickhouse servers can be connected from the host.

|  Container | Host  |  Port |
|---|---|---|
|  clickhouse01 |  127.0.0.1 | 9001  |
|  clickhouse02  |  127.0.0.1 | 9002  |
|  clickhouse03 |  127.0.0.1| 9003  |
|  clickhouse04 |  127.0.0.1 | 9004  |

### insert data

I insert data to the local table per second as many suggestions, like follows:
https://github.com/ClickHouse/ClickHouse/issues/1854#issuecomment-363197252
https://clickhouse.com/docs/en/introduction/performance/#performance-when-inserting-data

The code I used:
```go
package main

import (
	"context"
	"fmt"
	"log"
	"math/rand"
	"sync"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
)

var hosts = []string{"127.0.0.1:9001", "127.0.0.1:9002", "127.0.0.1:9003", "127.0.0.1:9004"}

func randtype() string {
	num := rand.Int31n(100)
	return fmt.Sprintf("type%d", num)
}

func main() {
	conn, err := clickhouse.Open(&clickhouse.Options{
		Addr:             hosts,
		DialTimeout:      time.Second,
		MaxOpenConns:     10,
		MaxIdleConns:     5,
		ConnOpenStrategy: clickhouse.ConnOpenRoundRobin,
	})

	if err != nil {
		log.Fatal(err)
	}

	var wg sync.WaitGroup
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			var batch driver.Batch
			var err error
			if batch, err = conn.PrepareBatch(context.TODO(), "INSERT INTO company_db.events"); err != nil {
				log.Fatal(err)
			}
			for i := 0; i < 50_000; i++ {
				if err = batch.Append(
					time.Now(),
					rand.Int63(),
					randtype(),
				); err != nil {
					log.Fatal(err)
				}
			}
			if err = batch.Send(); err != nil {
				log.Fatal(err)
			}
		}()
		time.Sleep(time.Second)
	}
	wg.Wait()
}
```
## problem

After the program finishes running, I check the number of rows in each clickhouse server.
All data send to clickhouse01 and clickhouse02 (they are replicas of each other).
```
clickhouse01 :) select count() from company_db.events

SELECT count()
FROM company_db.events

┌─count()─┐
│ 5000000 │
└─────────┘

1 rows in set. Elapsed: 0.005 sec.
```

and no data in clickhouse03 and clickhouse04.
```
clickhouse04 :) select count() from company_db.events

SELECT count()
FROM company_db.events

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.005 sec.
```

## analysis

I found a conn will be cached as idle conn when this batch.Send() of this conn is finished. and if a batch wants to prepare, and there is also an idle conn, it will reuse this idle conn instead of dial a new as ConnOpenStrategy.

So, for example, in my experiment, the first time I want to batch insert data, the conn which connects to clickhouse01 will be created, and used to send data  (to clickhouse01). After the first inserting finished, the conn will be cached, and all the subsequent ops of batch will reused this conn (also send data to clickhouse01), unless this conn is broken or in busy (unlucky, it not happened).

## question

So, my question is 
1. what is the correct way to use the clickhouse-go driver to insert the local table in cluster and load-balanced as the README.me said (or I understand wrong). 
2. Need we do something at the application layer?

**Comment by kshvakov** [comment]
If you have queries to the database constantly, and there are also parallel queries, balancing will work. If there are enough open connections, it is assumed that there is no need to balance. To improve the distribution of requests in a cluster with a small number of requests, you can reduce the connection lifetime to, for example, 30 seconds

**Comment by hattonl** [comment]
But It hard to make each server have same rows when insert local table per second and the ops takes less than 1 second. Or does load balancing not refer to this?
> If there are enough open connections, it is assumed that there is no need to balance.

**Comment by genzgd** [comment]
Currently load balancing within the driver is not specifically designed to balance inserts, it's designed to utilize multiple hosts if the one host (cached connection) is not sufficient for the overall query load.  You might consider using multiple connections (perhaps one per set of shard replicas) in your application to "manually" balance inserts, or depending on the use case, inserting into a ClickHouse distributed table.  If there is a strong demand for insert balancing in the driver, we would consider adding that feature, but given the number of other options, it seems unnecessary to do at this level.
