### ISSUE TITLE
The brackets are missing when inserting with array v2.0.12

### ISSUE THREAD

**Issue by dkishere** [ClickHouse/clickhouse-go#516]
It's obverse in bind.go:163 no bracket is wrapped.
Is there any reason to omit that?

**Comment by kshvakov** [comment]
You have several options for how you can use an array of parameters, so there are no brackets in bind. 

Example 

`IN($1)`, `AND = [$1]` etc

**Comment by dkishere** [comment]
Could it be automatic in the insert statement just like v1?
or prevent an official wrapper struct for that like lib/pq?

**Comment by kshvakov** [comment]
What do you mean? Can you give an example?

**Comment by gingerwizard** [comment]
@dkishere can you provide an example of how you would like the INSERT to behave with arrays? Happy to consider all requests but we need a little more detail.

**Comment by dkishere** [comment]
https://stackoverflow.com/questions/26707553/inserting-an-array-into-a-postgresql-database

Sorry for replying late. I think this is good.

**Comment by gingerwizard** [comment]
Interpreting that as we can close this issue.
