### ISSUE TITLE
Experimental Watch Query does not work with limit.

### ISSUE THREAD

**Issue by effusion** [ClickHouse/clickhouse-go#517]
### Issue description
I created a table and live view(experimental) to watch for updates on the table. It seems that the client does not adhere to the "Limit" clause. This causes the following queries to return all the previous updates to be returned as well.  Over the HTTP Interface of the Clickhouse server, the query works.

### Example code
SQL for creating the database
```sql
SET allow_experimental_live_view = 1;
create table sensor_data ( name varchar(100), time datetime, value Float32)engine=Log;
create live view lv_endplate with refresh 5 as select * from sensor_data sd where sd.name = 'Endplate' order by sd.time desc limit 1;
```

Query with limit
```sql
watch lv_endplate limit 1"
```

Clickhouse client code
```go
package clickhouse

/*
	Example Code for driver
	https://github.com/ClickHouse/clickhouse-go/blob/v2/examples/native/scan_struct/main.go
*/
import (
	"context"
	"eatplanted.com/dashboard-backend/config"
	"fmt"
	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
	"io/ioutil"
	"net/http"
	"strings"
	"time"
)

type DbConfig struct {
	UserName string
	Password string
	Url      string
	Database string
}

type Clickhouse struct {
	context.Context
	driver.Conn
}

func Init(config config.AppConfig) *Clickhouse {
	var dbConfig DbConfig
	err := config.LoadConfigByPath("server.clickhouse", &dbConfig)

	if err != nil {
		panic(fmt.Errorf("unable to load clickhouse config: %s", err))
	}
	conn, err := clickhouse.Open(&clickhouse.Options{
		Addr: []string{dbConfig.Url},
		Auth: clickhouse.Auth{
			Database: dbConfig.Database,
			Username: dbConfig.UserName,
			Password: dbConfig.Password,
		},
		Debug:           false,
		DialTimeout:     time.Second,
		MaxOpenConns:    10,
		MaxIdleConns:    5,
		ConnMaxLifetime: time.Hour,
		Compression: &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		},
	})

	if err != nil {
		panic(fmt.Errorf("Unable to get connection to clickhouse %s\n", err))
	}

	ctx := clickhouse.Context(context.Background(), clickhouse.WithSettings(clickhouse.Settings{
		"max_block_size":               10,
		"allow_experimental_live_view": 1,
	}))
	if err := conn.Ping(ctx); err != nil {
		if exception, ok := err.(*clickhouse.Exception); ok {
			panic(fmt.Errorf("Catch exception [%d] %s \n%s\n", exception.Code, exception.Message, exception.StackTrace))
		}
	} else {
		fmt.Println("Clickhouse connection successful!")
	}

	return &Clickhouse{
		Context: ctx,
		Conn:    conn,
	}
}

func (client *Clickhouse) Query(query string, data interface{}) error {
	err := client.Conn.Select(client.Context, data, query)
	if err != nil {
		fmt.Printf("unable to execute query: %s\n", err)
		return err
	}
	return nil
}
```
 Test
```go
package Clickhouse

import (
	"testing"
	"time"
)

type MockConfig struct{}

func (mc *MockConfig) LoadConfigByPath(_ string, c interface{}) (err error) {
	config := c.(*DbConfig)
	config.Url = "127.0.0.1:9000"
	config.Database = "default"
	config.UserName = "user1"
	config.Password = "secret"
	return nil
}

func TestClickhouseConnection(t *testing.T) {
	t.Skip("local test to check clickhouse connection")
	client := Init(&MockConfig{})
	var result []struct {
		Name    string    `ch:"name"`
		Time    time.Time `ch:"time"`
		Value   float32   `ch:"value"`
		Version uint64    `ch:"_version"`
	}

	err := client.Query("watch lv_endplate limit 1", &result)

	if err != nil && len(result) <= 1 {
		t.Fatalf("No results found: %s", err.Error())
	}
}
```

### Console Output
With every subsequent query, I get more results

Execute the query: watch lv_endplate limit 1
[{Endplate 2022-01-19 23:19:10 +0100 CET %!s(float32=0.25) %!s(uint64=15)}
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)}]
Execute query: watch lv_endplate limit 1

[{Endplate 2022-01-19 23:19:10 +0100 CET %!s(float32=0.25) %!s(uint64=15)} 
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)} 
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)} 
{Endplate 2022-01-19 23:19:20 +0100 CET %!s(float32=0.25) %!s(uint64=17)}]
Execute query: watch lv_endplate limit 1

[{Endplate 2022-01-19 23:19:10 +0100 CET %!s(float32=0.25) %!s(uint64=15)}
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)} 
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)} 
{Endplate 2022-01-19 23:19:20 +0100 CET %!s(float32=0.25) %!s(uint64=17)} 
{Endplate 2022-01-19 23:19:20 +0100 CET %!s(float32=0.25) %!s(uint64=17)} 
{Endplate 2022-01-19 23:19:25 +0100 CET %!s(float32=0.25) %!s(uint64=18)}]

### Configuration
*OS:*
Windows 11

*Interface:* E.g. `native`,

*Driver version:*
2.0.12

*Go version:* run `go version` in your console
go1.17.5 windows/amd64

*ClickHouse Server version:*
ClickHouse server version 22.1.3 revision 54455

**Comment by gingerwizard** [comment]
Its not clear if this will continue to be supported in ClickHouse. I'll confirm the direction of this feature and address if needed.

**Comment by gingerwizard** [comment]
We will address this if the Watch query comes out of experimental.

**Comment by MatthiasGrandl** [comment]
Just want to say that this is also something we are looking forward to using in production. HTTP it works great.

**Comment by fiftin** [comment]
Hi @MatthiasGrandl, @effusion 

I tested HTTP, CLI and go clients with ClickHouse server version 22.5.1.2079. 

All works the same. If `live view` has limit 1 and `watch` has limit 1, I get 2 records each time.

Please try again. Does the issue actual to you?

**Comment by ortyomka** [comment]
My understanding is that there are incorrect results due to repeated queries with same `result` slice. 

To reproduce the problem, we need to write the following:
```
var result []struct{...}

for ... {
    err := client.Query("watch lv_endplate limit 1", &result)

    if err != nil  {
	...
    }
    
   // print result
}
```

Then we got the same result

> [{Endplate 2022-01-19 23:19:10 +0100 CET %!s(float32=0.25) %!s(uint64=15)}
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)}]

>[{Endplate 2022-01-19 23:19:10 +0100 CET %!s(float32=0.25) %!s(uint64=15)}
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)}
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)}
{Endplate 2022-01-19 23:19:20 +0100 CET %!s(float32=0.25) %!s(uint64=17)}]

>[{Endplate 2022-01-19 23:19:10 +0100 CET %!s(float32=0.25) %!s(uint64=15)}
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)}
{Endplate 2022-01-19 23:19:15 +0100 CET %!s(float32=0.25) %!s(uint64=16)}
{Endplate 2022-01-19 23:19:20 +0100 CET %!s(float32=0.25) %!s(uint64=17)}
{Endplate 2022-01-19 23:19:20 +0100 CET %!s(float32=0.25) %!s(uint64=17)}
{Endplate 2022-01-19 23:19:25 +0100 CET %!s(float32=0.25) %!s(uint64=18)}]

**Comment by ortyomka** [comment]
@gingerwizard, closed?

**Comment by gingerwizard** [comment]
Yep!
