### ISSUE TITLE
bulk write

### ISSUE THREAD

**Issue by tutu-zhujing** [ClickHouse/clickhouse-go#523]
when i receive data one by one on web(gin, beego) , what is the best way to bulk write data(cache in memory?)

**Comment by Dominux** [comment]
@tutu-zhujing, yes, you can use some things like in memory cache ([redis](https://redis.io/), [memcached](https://memcached.org/)), or queue brokers (like [RabbitMQ](https://www.rabbitmq.com/))

**Comment by tutu-zhujing** [comment]
> @tutu-zhujing, yes, you can use some things like in memory cache ([redis](https://redis.io/), [memcached](https://memcached.org/)), or queue brokers (like [RabbitMQ](https://www.rabbitmq.com/))

ok，thanks
