### ISSUE TITLE
How to use SSL?

### ISSUE THREAD

**Issue by marwan-nwh** [ClickHouse/clickhouse-go#524]
Hi,

The readme file and the docs are not clear about how to use SSL.

It says:

**SSL/TLS parameters:**

- **secure** - establish secure connection (default is false)
- **skip_verify** - skip certificate verification (default is false)

Example:

`clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60`

So should I pass `secure=true` as a query parameter?

What if I am connecting this way?:
```
conn := clickhouse.Open(&clickhouse.Options{
	Addr: []string{"127.0.0.1:9999"},
	Auth: clickhouse.Auth{
		Database: "default",
		Username: "default",
		Password: "",
	},
	TLS: &tls.Config{
		InsecureSkipVerify: true,
	},
	Settings: clickhouse.Settings{
		"max_execution_time": 60,
	},
	DialTimeout: 5 * time.Second,
	Compression: &clickhouse.Compression{
		clickhouse.CompressionLZ4,
	},
	Debug: true,
})
```

Does the `InsecureSkipVerify` do just that? So what does `secure` parameter that the docs is referring to? `tls.Config` doesn't have `secure` parameter.

Should I provide SSL certificates, PEM keys? That would be painful.

**Comment by gingerwizard** [comment]
@genzgd has experience here and will document.

**Comment by genzgd** [comment]
At a low level all driver connect methods (DSN/OpenDB/Open) will use the Go tls package to establish a secure connection.  The driver knows to use TLS if the Options struct contains a non-nil tls.Config pointer.

Setting `secure` in the DSN creates a minimal tls.Config struct with only the InsecureSkipVerify field set (either true or false).  It is identical to the configuration in your initial question using the clickhouse.Open function.

That minimal tls.Config is normally all that is necessary if you are connecting to a secure port (normally 9440) on your ClickHouse server.  If the ClickHouse server does not have a valid certificate (expired, wrong host name, not signed by a recognized "root" Certificate Authority), you can set InsecureSkipVerify to `true`, but that is strongly discouraged.

If you need additional TLS parameters your code should include the required fields in the tls.Config struct.  That can include specific cipher suites, forcing a specific TLS version (like 1.2 or 1.3), adding your own internal CA certificate chain, adding a client certificate (and private key) if your server requires it, and most of the other options that come with more specialized security configuration.  It's indeed painful but in most cases not necessary.
