### ISSUE TITLE
DSN from driver V1 is not compatible with V2

### ISSUE THREAD

**Issue by ritbl** [ClickHouse/clickhouse-go#525]
### Issue description
We have an application that uses V1. At the moment I am preparing an update that uses V2.
I see that DSN of V1 is not compatible with V2.

DSN that I use: `tcp://clickhouse:9000?database=telemetryd&block_size=1000&pool_size=1`

I can provide to major diferences:
 - application is crashing because `block_size` is no longer supported (the same issue with `pool_size`)
 - `database` option is also not supported, so it fallbacks to `default` DB

### Error log
```
2022-03-23T15:25:38.240+0100    FATAL   *****     *****   Failed to migrate ClickHouse: failed to setup driver: code: 115, message: Unknown setting block_size.
main.main
        *****
runtime.main
        /Users/am/.gvm/gos/go1.17.8/src/runtime/proc.go:255

```

### Configuration
*OS: * `macOS 12.3`

*Interface:*  `database/sql`

*Driver version:* `v2.0.12`

*Go version:* `go1.17.8 darwin/amd64`

*ClickHouse Server version:* `clickhouse/clickhouse-server:21.8.14.5`

**Comment by gingerwizard** [comment]
Thanks @ritbl for the issue. Firstly apologies for not documenting this breaking change. I do think the new database structure is more consistent with other formats i.e.

`clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60` 

v2 has no notion of pool_size - you can set the following which simulates similar behaviour.
```
conn.SetMaxIdleConns(5)
conn.SetMaxOpenConns(10)
```

Memory management is different in v1 so block_size isn't available.
