### ISSUE TITLE
Support for uint128 

### ISSUE THREAD

**Issue by mosajjal** [ClickHouse/clickhouse-go#526]
**Is your feature request related to a problem? Please describe.**
currently, uint128 is supported by ClickHouse, but not by `clickhouse-go`. Would be nice to add it since I'm planning to use it to store `ipv6` as an integer.

**Comment by x1unix** [comment]
@mosajjal there is a nice package https://github.com/lukechampine/uint128 that allows manipulating 128-bit numbers.

But still there is a problem with implementing a glue code to read/write `uint128` values

**Comment by x1unix** [comment]
@mosajjal I think that `UInt128`, `UInt256` and other big values can be stored in `[big.Int](https://pkg.go.dev/math/big)` (or `big.Float`), but the driver don't support it unfortunately.

Support can be added by modifying column decoder at [/lib/column/column.go:22](/ClickHouse/clickhouse-go/lib/column/column.go) and registering type at [/lib/column/common.go](/ClickHouse/clickhouse-go/lib/column/common.go) in `columnBaseTypes`

```diff
func Factory(name, chType string, timezone *time.Location) (Column, error) {  
   switch chType {  
   case "Int8":
	...
+   case "UInt128", "Int128", "UInt256", "Int256":
+     // decode value into big.Int
   }
   return nil, fmt.Errorf("column: unhandled type %v", chType)
}
```

**Comment by mosajjal** [comment]
I think if this is to be done properly, some of the limitation on the decoder needs to be re-written as well. I remember seeing the "max number of bytes" in the default decoder pointing to 10 which doesn't cover `uint128` obviously. not even sure if this project is keen to scale that support for higher bits (256 512) either.

**Comment by x1unix** [comment]
@mosajjal I recommend you to take a look at other CH library - https://github.com/uptrace/go-clickhouse.

They have some nice stuff like query builder, so maybe better types support is also included.

**Comment by mosajjal** [comment]
thanks @x1unix, just took a look there and `DateTime64` is not supported. I recently moved my time columns to `DateTime64` to include packet precision. Looks like I'm stuck :D

**Comment by gingerwizard** [comment]
@mosajjal we support DateTime64.I'll look at adding uint128 support.

**Comment by gingerwizard** [comment]
@mosajjal i think this might be partially supported e.g. https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/bigint_test.go#L45-L63 there are some gaps but they don't look too tricky to close.

**Comment by mosajjal** [comment]
Thanks a lot for this. I'd be upgrading my dependency as soon as this rolled into the next release :)
