### ISSUE TITLE
Bulk write looks like it does not commit changes

### ISSUE THREAD

**Issue by Dominux** [ClickHouse/clickhouse-go#528]
### Issue description
I use bulk write (from [docs example](https://github.com/ClickHouse/clickhouse-go/blob/v2.0.12/examples/native/batch/main.go)), but my table remains empty

Even tho I use a debug mode in clickhouse options, with that I see that everything is fine with inserting transaction

*Interface:* `native`

*Driver version:* 2.0.12

*Go version:* 1.17

*ClickHouse Server version:* latest

**Comment by gingerwizard** [comment]
Yes this is doing what a Null engine should do. I'll update the example, its not ideal.

**Comment by gingerwizard** [comment]
The more i consider this, the more I think the authors intention was for examples to not leave data in a cluster. On balance, however, i can see this being confusing for new users so will move to Memory engines for all.

**Comment by gingerwizard** [comment]
Closed by https://github.com/ClickHouse/clickhouse-go/pull/558
