### ISSUE TITLE
New type Object('JSON') is not supported

### ISSUE THREAD

**Issue by Astlol** [ClickHouse/clickhouse-go#531]
Hi,

New type Object('JSON') has appeared recently in ClickHouse 22.3.2.1. It would be super cool to add it in clickhouse-go. New feature allows you to significantly speed up a request(search) for json data type.

https://clickhouse.com/docs/en/whats-new/changelog/#223
Experimental Feature

New data type Object(<schema_format>), which supports storing of semi-structured data (for now JSON only). Data is written to such types as string. Then all paths are extracted according to format of semi-structured data and written as separate columns in most optimal types, that can store all their values. Those columns can be queried by names that match paths in source data. E.g data.key1.key2 or with cast operator data.key1.key2::Int64.

Support of dynamic subcolumns (JSON data type) #23932 
https://github.com/ClickHouse/ClickHouse/pull/23932

**Comment by sundarv85** [comment]
Hi @Astlol One question for clarification is - we can write into the dynamic object(JSON) using the clickhouse go driver, as it is written only as a string, but we need the update in the drive for reading it back... Is the understanding correct?

**Comment by Astlol** [comment]
Hey @sundarv85, Yes.
As I understand the point of an object (JSON) is an efficient get operation (search). Once we store json in object gets it immutable.

**Comment by gingerwizard** [comment]
What is the expectation as to how this should behave?

We can provide a type allowing users to pass structs at insert time which we would in turn marshal to JSON string for insertion. 

At query time a JSON object will be returned as tuples. We could map this to the target struct but ideally CH would return the column as a JSON string making marhsalling easier.

**Comment by franchb** [comment]
As for insert time there could be several ways: to pass a struct, JSON bytes.

As for query time JSON string/bytes seems enough.

**Comment by Astlol** [comment]
(insert time) to pass a map as well

**Comment by gingerwizard** [comment]
I'll have a stab at supporting this and will provide usage instructions here for feedback.

**Comment by gingerwizard** [comment]
This is tricky as the JSON type is implemented as tuples. There is no way of knowing the field names in the response to a query. e.g.

```
SET allow_experimental_object_type=1;
CREATE table github_tmp (event JSON) ENGINE = MergeTree ORDER BY tuple();

INSERT INTO github_tmp FORMAT JSONAsObject
{"type":"PushEvent","actor":{"id":93110249},"repo":{"id":429298592,
"name":"revacprogramming/pps-test1-Lakshmipatil2021",
"url":"https://api.github.com/repos/revacprogramming/pps-test1-Lakshmipatil2021"}}
SELECT * FROM github_tmp;

+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
|event                                                                                                                                                        |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
|((93110249),(429298592,'revacprogramming/pps-test1-Lakshmipatil2021','https://api.github.com/repos/revacprogramming/pps-test1-Lakshmipatil2021'),'PushEvent')|
+-------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

ClickHouse does support returning the data with the keys if you are responding with a JSON Format  - something the driver isn't likely to support. It would also require the user to specify the format or the driver to somehow detect and modify the statement (or a move to JSON formats just for this field). Ultimately we need CH to return the field names by default - ideally, JSON fields would be returned as a JSON string.

Until then we could ask the user to pass a struct which we marshall the tuples into. This feels a little fragile and defeats the whole purpose of a semi-structured field. It would rely on the user knowing the tuple order and ensuring the struct was aligned perfectly in terms of field order. Any changes to the data structure would immediately break the marshaling.

We could return the tuple data as-is and leave the user to marshall this into a struct. They would still need to perform the above logic though and likely also write fragile code. It is possible this is useful to a subset of users who have a fixed schema and want to insert JSON. We'll implement this for now and enhance once we have key information.

**Comment by Astlol** [comment]
Yes. You are right!
To make sure. 
Is the problem to unmarshal json_object field (tuple)?
Solution is strict schema of data. 
need to know for unmarshaling
	field?
	order?
	type?
	
about map (order problem)

**Comment by gingerwizard** [comment]
So we need to marshall any struct to tuples - this is how the data should be sent to the server. It seems we can either include types on our tuples or not. If no types, the server does schema inference. 
I think this is a little counter-intuitive if the types are defined i.e. a struct is strongly typed. If sending a struct id therefore probably maps the types to click house types. The same for maps.
If the user sends a JSON string, we will need to parse and send with no type information -allowing the server to perform inference. This is probably the trickiest to do efficiently and I think represents a v2 enhancement - its potentially very powerful.

**Comment by Astlol** [comment]
I see. sound reasonable!

**Comment by Astlol** [comment]
As I can see, you have not checked a response in map (with insert map) yet. 
Could you please, consider next assumption ->  as I understand we need to fix the order of tuple  (know order of fields). hence orderedMap is needed. ?

**Comment by gingerwizard** [comment]
@Astlol we support inserting a map, struct or string.

You wont need to know the order of the fields - this is encoded into the data in the order we recurse the structure. Arrays will be recursed in order, maps - it doesn't matter as we encode the name with the value.

Same on responses - we know the name for the value.

**Comment by gingerwizard** [comment]
Also note support requires https://github.com/ClickHouse/ClickHouse/pull/37482. As part of this effort the encoding format for JSON was changed CH server side.

**Comment by gingerwizard** [comment]
Note https://github.com/ClickHouse/clickhouse-go/pull/590 for specific behaviors.
