### ISSUE TITLE
support mysql placeholder

### ISSUE THREAD

**Issue by tsingsun** [ClickHouse/clickhouse-go#542]
The clickhouse statement supports mysql protocol, but v2 go driver placeholder only supports $,@, while mysql uses '? 'As placeholder.  

I hope to support the mysql placeholder

**Comment by gingerwizard** [comment]
I assume you are referring to ClickHouse's ability to communicate via the [MySql protocol](https://clickhouse.com/docs/en/interfaces/mysql/).

This is not something a dedicated ClickHouse driver is likely to support.

**Comment by tsingsun** [comment]
@gingerwizard as @itzikiusa said, V1 supported.backwards compatibility would be great

**Comment by gingerwizard** [comment]
k seems reasonable. It looks like a trivial change if its limited to this.

**Comment by gingerwizard** [comment]
Closed by https://github.com/ClickHouse/clickhouse-go/pull/577
