### ISSUE TITLE
ClickHouse can produce blocks bigger than 1 mil rows.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/clickhouse-go#546]
ClickHouse can produce blocks bigger than 1 mil rows, in case you have GROUP BY in your query.

https://github.com/ClickHouse/clickhouse-go/blob/e9d187591f80acb3da4d24adf8ff61c2231d39ee/lib/proto/block.go#L144

**Comment by alexey-milovidov** [comment]
ClickHouse itself has 64 bit block size, it allows blocks with more than 4 billion records, although it is a rare case.
Every client library should not have any artificial limitations on block size.

**Comment by UnamedRus** [comment]
But imo, it make sense to limit possible max_block_size outside of ClickHouse, because it will allow to lower max memory usage for client library when it will parse columnar block.

**Comment by variantf** [comment]
@alexey-milovidov @UnamedRus  Same here! Is there any workaround for now? Looks like the connection will broken after server returning block large than 1 million rows.

My query doesn't have groub by clause but have order by

**Comment by alexey-milovidov** [comment]
The library maintainer stopped to respond. No workaround for now, we are going to address it.

**Comment by variantf** [comment]
I vendor-ed this project and just remove the lines for errors after 1m rows. it works fine for me now.

**Comment by alexey-milovidov** [comment]
Ok from my side, but we can also set it by default to some large value (like 1 billion) if it is only a protection and does not affect memory consumption in regular cases.

**Comment by alexey-milovidov** [comment]
And if we do, don't need to add any configuration (no one will use it).

**Comment by variantf** [comment]
I prefer to set some client side settings to force a small chunk size, but I have no idea if these kind of settings exists? @alexey-milovidov any ideas?

I don't think we will have this large-chunk-detection anywhere. since if we have ever encounter this error, we have nothing to do with. We will never do a success query especially when the client doesn't have permission to modify server configurations.

**Comment by gingerwizard** [comment]
@variantf you can set `max_block_size` e.g.
```
ctx := clickhouse.Context(context.Background(), clickhouse.WithSettings(clickhouse.Settings{
"max_block_size": 10000,
}),
```
While this will force a smaller block size on most queries, there are circumstances where it cannot be enforced - resulting in large blocks. Think of it as a largely obeyed hint. that we plan to adhere to more strictly in the future.

I will increase this to 1b - 1m seems a little low.

**Comment by den-crane** [comment]
Everything will be much easier if Native protocol allowed to use RowBinary or other row (or any) formats for queries.

**Comment by gingerwizard** [comment]
Yes its guidance only @variantf its not enforced unfortunately.
