### ISSUE TITLE
converting string to Datetime64 is unsupported

### ISSUE THREAD

**Issue by ryanrolds** [ClickHouse/clickhouse-go#547]
### Issue description

Updated from v1.5.4 to 2.0.12 and started seeing `converting string to Datetime64 is unsupported` errors. It appears that [v2 does not have](https://github.com/ClickHouse/clickhouse-go/blob/137f8b6308cc35108008aef6b3584fc42b8a1775/lib/column/datetime64.go#L141-L163) the same conversion support that [v1 has](https://github.com/ClickHouse/clickhouse-go/blob/v1.5.4/lib/column/datetime64.go#L50).

Expected behavior:  That v2 support the same common conversions that v1 supports or a migration documents covering what will need to be changed when upgrading to v2.

### Error log
```
[AppendRow]: converting string to Datetime64 is unsupported
```

### Configuration

*OS: Don't know what OS Google Cloud Build is using under the hood.
*Interface: `database/sql`
*Driver version: 2.0.12
*Go version: 1.17
*ClickHouse Server version: 21.5.6.6 (official build)

**Comment by fletcherist** [comment]
Same thing with `[AppendRow]: converting int to Enum8 is unsupported`

**Comment by gingerwizard** [comment]
So i think moving forward we will be lenient on types and allow these to be passed - however not at the expense of possible loss of precision so int to Enum8 will not be possible. int8 to Enum8 :+1:

**Comment by gingerwizard** [comment]
I'll do a full audit and raise an issue with a compatibility matrix. :+1:

**Comment by ryanrolds** [comment]
You're amazing. Thank you.

**Comment by gingerwizard** [comment]
datetime64 supported in #571 We will raise a separate issue to track deltas with v1 on conversions.
