### ISSUE TITLE
Is there a way to increase max_query_size through this package

### ISSUE THREAD

**Issue by mesc08** [ClickHouse/clickhouse-go#549]
Getting issue in querying from clickhouse getting errror. In one go I am passing more than 200 thousand information but getting error from clickhouse

*Syntax error: failed at position 262140 (''suleuha.net''): 'suleuha.net', 'diagonsys.com', 'scala.com', 'omegahns.com', 'jagrannewmedia.com', '7ty7.com', 'bitseducampus.ac.in', 'creationspo.com', 'mafoirandstod.com', 'c. Max query size exceeded: ''suleuha.net''

import (
	"database/sql"
	"fmt"
	"log"
	_ "github.com/ClickHouse/clickhouse-go"
	_ "github.com/go-sql-driver/mysql"
)
func errorLog(err error){
 log.Errorf(err)
}

func connect(host, port) (*sql.DB, error){
connect, err := sql.Open("clickhouse", "tcp://"+host+":"+port+ "?debug=false")
    connect.SetMaxOpenConns(5)
    connect.SetMaxIdleConns(5)
    return connect, err
}

func query() *sql.Rows{
query := fmt.Sprint("SELECT entry FROM db.table WHERE entry IN ('" + domains + "') and scat != 'ignore'")
    result, err := clickdb.Query(query)
    errorLog(err)
    return result
}

**Comment by gingerwizard** [comment]
You should be able to pass in the SELECT i.e.
`query := fmt.Sprint("SELECT entry FROM db.table WHERE entry IN ('" + domains + "') and scat != 'ignore SETTINGS max_query_size=x'")`

**Comment by gingerwizard** [comment]
also

```
	ctx := clickhouse.Context(context.Background(), clickhouse.WithSettings(clickhouse.Settings{
		"max_query_size": 10,
	}), clickhouse.WithProgress(func(p *clickhouse.Progress) {
		fmt.Println("progress: ", p)
	}), clickhouse.WithProfileInfo(func(p *clickhouse.ProfileInfo) {
		fmt.Println("profile info: ", p)
	}))
```

**Comment by Sri0810** [comment]
for v1 version the above query is will help resolve the issue query := fmt.Sprint("SELECT entry FROM db.table WHERE entry IN ('" + domains + "') and scat != 'ignore' SETTINGS max_query_size=x'") ?
