### ISSUE TITLE
converting float64 to Float32 is unsupported

### ISSUE THREAD

**Issue by ferdyzhang** [ClickHouse/clickhouse-go#566]
### Issue description
First,I used to std database/sql interface,but slowly for me,I want more faste when insert data to clickhouse . so i switch to v2.
Now, I got problem with error log
I also check some issue which similar my problem。shoud i revert std database/sql interface or there some fix?
forgive my english is too bad. you get me ,right?
thanks a lot 
### Example code
```go
		err := batch.Append(res...)
					if err != nil {
						fmt.Println("batch error", err)
						log.Errorf("batch error,%s", err)
						panic("batch error")
					}
```
-- res type is []interface{},there is some float32 data
### Error log
```
clickhouse [AppendRow]: reason clickhouse [AppendRow]: converting float64 to Float32 is unsupported
```

### Configuration
*OS: macOS Monterey 12.2.1

*Interface: native
*Driver version:v2.0.14

*Go version: go1.18 darwin/arm64
*ClickHouse Server version:21.11.6.7

**Comment by gingerwizard** [comment]
We will not support this conversion due to possible loss of precision. You need to explicitly lower your precision and accept this loss before passing to the driver.
