### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by itzikiusa** [ClickHouse/clickhouse-go#598]
Hi, i'm using the latest version of the driver (v2.0.14)
having issues with memory that keeps on going(a lot of small inserts)

this is the output from pprof:
https://github.com/itzikiusa/gists/blob/master/heap.pprof

how we should do this small inserts?

**Comment by gingerwizard** [comment]
Can you show how you're currently using the library? It seems like you're using the std interface. Are you reusing a connection for example?
Looking at your pprof memory is quite moderate at 189mb and I don't see any obvious improvements. Possibly the compression implementation could be more efficient regards memory. I'll see if I can simulate your use case and monitor memory growth - any example code which demonstrates memory growth (or leakage) apreciated.

**Comment by itzikiusa** [comment]
@gingerwizard 
this is the connection: (for query we just use exec or batch)
```
                dsn, err := neturl.Parse(url)
		if err != nil {
			logger.Error("can't connect clickhouse, error = ", err)
			return
		}
		chDB := "default"
		queryParams := dsn.Query()

		chDbConn, ok := queryParams["database"]
		if ok {
			chDB = chDbConn[0]
		}

		chOptions := clickhouse.Options{
			Addr: []string{dsn.Host},
			Auth: clickhouse.Auth{
				Database: chDB,
				Username: userName,
				Password: password,
			},
			DialTimeout:     5 * time.Second,
			MaxIdleConns:    utils.GetOrDefaultInt(viper.GetString("CLICKHOUSE_MAX_CONNECTIONS"), 10),
			MaxOpenConns:    utils.GetOrDefaultInt(viper.GetString("CLICKHOUSE_MAX_CONNECTIONS"), 10),
			ConnMaxLifetime: time.Hour,
		}

		tlsConfig, ok := queryParams["secure"]
		if ok {
			if utils.ParseBoolean(tlsConfig[0]) {
				chOptions.TLS = &tls.Config{
					InsecureSkipVerify: true,
				}
			}
		}

		conn, err := clickhouse.Open(&chOptions)`

**Comment by gingerwizard** [comment]
So you reuse the connection and call PrepareBatch each time?

**Comment by itzikiusa** [comment]
@gingerwizard yes
the memory is not high because i stopped the benchmark when i saw it is just getting higher and higher

i can do some bulk processing in code

**Comment by stevenkitter** [comment]
@itzikiusa this is the memory usage.
<img width="1352" alt="企业微信截图_94e5c037-9b14-40ff-b056-81417032adf0" src="https://user-images.githubusercontent.com/12658782/223584958-cce536fa-5343-484b-8bad-bc9bfad0e125.png">
<img width="675" alt="企业微信截图_5dc9ae2c-e3bd-4425-908c-1b154af65854" src="https://user-images.githubusercontent.com/12658782/223585307-30f1f0a3-b1a4-46a4-882f-90dda8eacad9.png">
