### ISSUE TITLE
'INTO OUTFILE' option for SELECT queries does not write to outfile. 

### ISSUE THREAD

**Issue by GavinClarke0** [ClickHouse/clickhouse-go#607]
### Issue description

When executing a query with 'INTO OUTFILE', instead of writing to outfile query returns rows (no error) as if 'INTO OUTFILE' was never present in query when running the query with the `conn.Exec(....)` function.  I=

Expected Behaviour: file is created and written or error is returned if file cannot be written. 

Actual Behaviour: Rows queried are returned and file is not created/written. 

### Example code
```go
conn, err := clickhouse.Open(&clickhouse.Options{
Addr: []string{"127.0.0.1:9000"},
Auth: clickhouse.Auth{
	Database: "default",
	Username: "default",
	Password: "",
},
Compression: &clickhouse.Compression{
	Method: clickhouse.CompressionLZ4,
},
Settings: clickhouse.Settings{
	"max_execution_time": 60,
},
MaxIdleConns: 5,
MaxOpenConns: 10,
/Debug: true,
})

if err != nil {
return nil, err
}


conn.Exec(context.Background, "SELECT * FROM table INTO OUTFILE 'outfile.avro' FORMAT Avro;")
```

### Configuration
*OS:*

*Interface:* E.g. `native`, `database/sql`

native

*Driver version:*

github.com/ClickHouse/clickhouse-go/v2 v2.0.14

*Go version:* run `go version` in your console

go version go1.18.1 darwin/arm64

*ClickHouse Server version:*

┌─version()───┐
│ 22.6.1.1494 │
└─────────────┘

**Comment by gingerwizard** [comment]
Unlikely we will support this. Its [implemented](https://clickhouse.com/docs/en/sql-reference/statements/select/into-outfile/#implementation-details) in clickhouse-client and clickhouse-local as these share the code with the main clickhouse code base. To implement this we would need an AST and would move from being a driver to a full-blown client.

**Comment by GavinClarke0** [comment]
Ok, thank you for taking a look.

**Comment by Cryingmouse** [comment]
I saw it still mentioned that only support in [command-line client] and [clickhouse-local]
Any outlook to implemented in http interface?

> Unlikely we will support this. Its [implemented](https://clickhouse.com/docs/en/sql-reference/statements/select/into-outfile/#implementation-details) in clickhouse-client and clickhouse-local as these share the code with the main clickhouse code base. To implement this we would need an AST and would move from being a driver to a full-blown client.
