### ISSUE TITLE
getting issue in querying from clickhouse using golang script for max_query_size exceeded

### ISSUE THREAD

**Issue by Sri0810** [ClickHouse/clickhouse-go#611]
Getting issue in querying from clickhouse getting errror. In one go I am passing more than 200 thousand information but getting error from clickhouse

*Syntax error: failed at position 262140 (''suleuha.net''): 'suleuha.net', 'diagonsys.com', 'scala.com', 'omegahns.com', 'jagrannewmedia.com', '7ty7.com', 'bitseducampus.ac.in', 'creationspo.com', 'mafoirandstod.com', 'c. Max query size exceeded: ''suleuha.net''

func errorLog(err error){
 log.Errorf(err)
}
func connect(host, port) (*sql.DB, error){
connect, err := sql.Open("clickhouse", "tcp://"+host+":"+port+ "?debug=false")
    connect.SetMaxOpenConns(5)
    connect.SetMaxIdleConns(5)
    return connect, err
}

func query(domain []string) *sql.Rows{
domains := strings.Join(domain[:], ",")
query := fmt.Sprint("SELECT entry FROM db.table WHERE entry IN ('" + domains + "'))
    result, err := clickdb.Query(query)
    errorLog(err)
    return result
}

**Comment by gingerwizard** [comment]
Clickhouse core issue not a driveer problem. See https://clickhouse.com/docs/en/operations/settings/settings/#settings-max_query_size
