### ISSUE TITLE
DateTime64(9) comparison precision lost

### ISSUE THREAD

**Issue by pomo-mondreganto** [ClickHouse/clickhouse-go#615]
### Issue description
I try to filter some rows by timestamp, which is a nanosecond-precision DateTime64 in Clickhouse. However, it seems that this driver loses the precision when converting time.Time. I expect that the code below returns only the third row (with `ts3 > ts2`), but now it returns rows 2 and 3. The output of the code below:

```
All rows:
id: first, ts: 2022-06-16 19:11:33 +0000 UTC
id: second, ts: 2022-06-16 19:11:33.001 +0000 UTC
id: third, ts: 2022-06-16 19:11:34.001 +0000 UTC

rows with ts > 2022-06-16 19:11:33.001 +0000 UTC
id: second, ts: 2022-06-16 19:11:33.001 +0000 UTC
id: third, ts: 2022-06-16 19:11:34.001 +0000 UTC
```

### Example code
```go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
)

func main() {
	c, err := clickhouse.Open(&clickhouse.Options{
		Addr: []string{"127.0.0.1:9000"},
		Auth: clickhouse.Auth{
			Database: "local",
			Username: "local",
			Password: "local",
		},
	})
	if err != nil {
		panic(err)
	}
	if err := c.Exec(
		context.Background(),
		`
			CREATE TABLE IF NOT EXISTS playground1
			(id String, ts DateTime64(9))
			ENGINE = MergeTree
			ORDER BY (ts)
			`,
	); err != nil {
		panic(err)
	}

	ts1 := time.Now().Round(time.Second)
	ts2 := ts1.Add(time.Millisecond)
	ts3 := ts1.Add(time.Second + time.Millisecond)

	batch, err := c.PrepareBatch(context.Background(), "INSERT INTO playground1 (id, ts)")
	if err != nil {
		panic(err)
	}
	if err := batch.Append("first", ts1); err != nil {
		panic(err)
	}
	if err := batch.Append("second", ts2); err != nil {
		panic(err)
	}
	if err := batch.Append("third", ts3); err != nil {
		panic(err)
	}
	if err := batch.Send(); err != nil {
		panic(err)
	}

	showRows := func(query string, args ...interface{}) {
		rows, err := c.Query(context.Background(), query, args...)
		if err != nil {
			panic(err)
		}
		for rows.Next() {
			var (
				id string
				ts time.Time
			)
			if err := rows.Scan(&id, &ts); err != nil {
				panic(err)
			}
			fmt.Printf("id: %s, ts: %v\n", id, ts.UTC())
		}
	}

	fmt.Println("All rows:")
	showRows("SELECT id, ts from playground1")
	fmt.Printf("\nrows with ts > %v\n", ts2.UTC())
	showRows("SELECT id, ts from playground1 where ts > @TS", clickhouse.Named("TS", ts2))
}
```

### Configuration
*OS:* Darwin

*Interface:* `native`

*Driver version:* v2.0.15

*Go version:* 1.18.3

*ClickHouse Server version:* 21.8.10 revision 54449

**Comment by pomo-mondreganto** [comment]
For anyone with the same problem -- you can hack the driver to pass the time as-is using the following:

```go
c.Query(
    "SELECT id, ts from playground1 where ts > toDateTime64(@TS, 9)", 
    clickhouse.Named("TS", ts.UTC().Format("2006-01-02 15:04:05.999999999")),
)
```

Notice the `toDateTime64(x, 9)` to convert the formatted string to datetime. The verbose time format is not a default one (Clickhouse can't parse the Z at the end of the `time.RFC3339Nano`).

**Comment by gingerwizard** [comment]
Indeed looks like a bug in the argument code @genzgd We inherited this feature, and it's proved problematic/flaky and something we'd like to overload to ClickHouse in v3.
Will try to patch this week @pomo-mondreganto, and thanks for reporting.

**Comment by pomo-mondreganto** [comment]
While you're at it, there's also a bug here: https://github.com/ClickHouse/clickhouse-go/blob/0ab57f1106bb93ffecd1be15d72591d6a9cc2504/bind.go#L220

**Comment by gingerwizard** [comment]
@pomo-mondreganto resolved via https://github.com/ClickHouse/clickhouse-go/pull/620 

Note you will need to use a new parameter type - NamedDateValue

**Comment by pomo-mondreganto** [comment]
I like the proposed solution, nice interface!

When are you planning to release this?

**Comment by 0xrelapse** [comment]
Just fyi, ran into this issue and `NamedDateValue` doesn't quite work for all use cases - for example if I'm not using named args (like $1, $2, etc). So I'm stuck with manually converting the time to a string
