### ISSUE TITLE
AppendRow for Array.go not working with  {}interface|[]interface{} in v2. 

### ISSUE THREAD

**Issue by abhishek-buragadda** [ClickHouse/clickhouse-go#617]
### Issue description
We are using v1 clickhouse-go  and we are trying to move from  v2 recently. But we are seeing `ColumnConvertError` for a case which is working fine in v1.  Can someone please help.
```
AppendRow]: converting []interface {} to Array(String) is unsupported. try using []string
```

### Example code
```go

	values := []interface{}{}
	cols := []string{"one", "two", "three"}

	mymap := make(map[string]interface{})
	mymap["one"] = "two"
	mymap["two"] = []string{"one", "two", "three"}
	mymap["three"] = []interface{}{"one", "two", "theree"}
	mymap["four"] = []interface{}{1, 2, 3}

	for _, col := range cols {
		values = append(values, mymap[col])
	}

       stmt.ExecContext(ctx, values...); 
    
```

### Error log
```
[AppendRow]: converting []interface {} to Array(String) is unsupported. try using []string
```

### Configuration
*macOS  BigSur*

*Interface:* : `database/sql`

*Driver version:*  v2 
*Go version:* 1.17

*ClickHouse Server version:* 21.8.3.44

cc: @nikhresna

**Comment by abhishek-buragadda** [comment]
@gingerwizard  This is breaking backward compatibility . Can you help us suggest alternatives to come out of this ?

**Comment by gingerwizard** [comment]
We have no plans to introduce array casting for now. If enough users +1 this we will reconsider and we'll reopen.
