### ISSUE TITLE
Reliably measure rows and bytes consumed from a query

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/clickhouse-go#639]
**Is your feature request related to a problem? Please describe.**
I want to be able to reliably and consistently measure the number of rows and bytes processed for a given query, and ideally the resulting rows and bytes.

**Describe the solution you'd like**
A final set of variables in the query response, reliable results from `WithProgress()`

**Describe alternatives you've considered**
Using the latest update from `WithProgress()`

**Additional context**
Through discussing with the CH team, `WithProgress()` is not a widely used feature, and might have bugs. I've also noticed in testing that it seems to give inconsistent results for the same query, heavily dependant on the max blocks used in the client settings.

**Comment by gingerwizard** [comment]
Thanks, @danthegoodman1, and apologies for the belated response.
I would expect the block size to impact behavior here as it will directly impact the frequency of updates to the progress- I would still expect consistent final numbers. I will investigate and see if we can at least document behavior and provide some recommendations.

**Comment by danthegoodman1** [comment]
I wonder if perhaps I was not always getting a “final response”? For example with really high max blocks I’d only get one, but with a small max blocks I’d get many, and the final output wouldn’t be the same as the single large max block response. But I can test again to verify.

**Comment by gingerwizard** [comment]
I would expect an update per block @danthegoodman1

**Comment by gingerwizard** [comment]
@danthegoodman1 finally got around to investigating this.

A few things:

1. total_rows is not always populated - I'm looking at why.
2. rows is always reported. This isn't precise (I'll update here why) unless you lower the block size to a multiple of the target rows. I'm exploring why this is the case but its ClickHouse - not the client.
3. If yo uneed total statistics use the `WithProfileInfo` option.

 ```
	totalRows := uint64(0)
	ctx := clickhouse.Context(context.Background(), clickhouse.WithProgress(func(p *clickhouse.Progress) {
		fmt.Println("progress: ", p)
		totalRows += p.Rows
	}), clickhouse.WithProfileInfo(func(p *clickhouse.ProfileInfo) {
		fmt.Println("profile info: ", p)
	}))

	rows, err := conn.Query(ctx, "SELECT number FROM system.numbers LIMIT 10000000")
	if err != nil {
		return err
	}
	for rows.Next() {
		var (
			col1 uint64
		)
		if err := rows.Scan(&col1); err != nil {
			return err
		}
	}

	fmt.Printf("Total Rows: %d", totalRows)

```

```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/dalemcdiarmid/go #gosetup
/usr/local/go/bin/go test -c -o /private/var/folders/9r/6rgj52gd4hs7xzrjj1hzvvgm0000gn/T/GoLand/___TestProgress_in_github_com_ClickHouse_clickhouse_go_v2_examples_native.test github.com/ClickHouse/clickhouse-go/v2/examples/native #gosetup
/usr/local/go/bin/go tool test2json -t /private/var/folders/9r/6rgj52gd4hs7xzrjj1hzvvgm0000gn/T/GoLand/___TestProgress_in_github_com_ClickHouse_clickhouse_go_v2_examples_native.test -test.v -test.paniconexit0 -test.run ^\QTestProgress\E$
=== RUN   TestProgress
progress:  rows=2386428, bytes=19091424, total rows=0, wrote rows=0 wrote bytes=0
progress:  rows=1149885, bytes=9199080, total rows=0, wrote rows=0 wrote bytes=0
progress:  rows=993234, bytes=7945872, total rows=0, wrote rows=0 wrote bytes=0
progress:  rows=939906, bytes=7519248, total rows=0, wrote rows=0 wrote bytes=0
progress:  rows=1019898, bytes=8159184, total rows=0, wrote rows=0 wrote bytes=0
progress:  rows=906576, bytes=7252608, total rows=0, wrote rows=0 wrote bytes=0
progress:  rows=969903, bytes=7759224, total rows=0, wrote rows=0 wrote bytes=0
progress:  rows=919908, bytes=7359264, total rows=0, wrote rows=0 wrote bytes=0
profile info:  rows=10000000, bytes=80096192, blocks=3001, rows before limit=10002333, applied limit=true, calculated rows before limit=true
progress:  rows=716595, bytes=5732760, total rows=0, wrote rows=0 wrote bytes=0
progress:  rows=0, bytes=0, total rows=0, wrote rows=0 wrote bytes=0
Total Rows: 10002333--- PASS: TestProgress (1.07s)
PASS
```

**Comment by danthegoodman1** [comment]
@gingerwizard thanks for this update. I'm definitely interested in (relatively) precise total consumed rows and bytes, rather then the returned.

**Comment by gingerwizard** [comment]
@danthegoodman1 so the reason row count is off Progress is because we read the data in chunks - we will sometimes as a result read more rows than the LIMIT. It is accurate, however, so be prepared for it to be higher than the LIMIT in some occasions (or even less). 

The rows in progress are connected to the  max_block_size - ClickHouse will try use such size for chunks. But it is easier to ignore this. From MergeTree table we can read any number of rows in chunk if adaptive granularity is enabled.

total rows is an estimation - how many rows we are going to read. In some cases we can't calculate it properly - in this case,  because table system.numbers in infinite. Replacing system.numbers LIMIT 50000000 to numbers(50000000)  will give an accurate count of total rows. Generally, summing the `rows` is going to give you an accurate number.

**Comment by danthegoodman1** [comment]
Thanks, honestly <1% error is fine, but maybe just that example is

**Comment by gingerwizard** [comment]
To emphasize the difference isn't an error - CH needed to read these rows. Its just a byproduct of reading in chunks. I'm closing but any other problems please feel free to open @danthegoodman1 
Thanks for raising btw, the meaning of this info wasn't clear - I will add to the new docs we're working on.

**Comment by yusufozturk** [comment]
Is this implemented @gingerwizard?

We would like to get client statistics with query results like:

"statistics":
{
"elapsed": 0.000256913,
"rows_read": 0,
"bytes_read": 0
}

so we can show query details like how much time it took on Clickhouse, how much GB of data it processed etc.
It will be a perfect details for the end users so they can realize how much impact their query creates.

Thanks.

**Comment by calebeaires** [comment]
@yusufozturk, did you get it done? Statistics?
