### ISSUE TITLE
Connection query: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rtkaratekid** [ClickHouse/clickhouse-go#641]
### Issue description

When running queries to clickhouse in a loop, very rarely a panic occurs. It seems to me, being unfamiliar with the codebase, that this occurs when the decoder is trying to decode a null byte during the connection process of a query? I'm not sure that's completely right but it's my best guess with a quick look over the source code.
It would be nice to not have these panics, but for now I'm going to handle them with `recover()`.

### Error Log
```
INFO[3641] Starting Task
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x50cad9]
goroutine 1973 [running]:
github.com/ClickHouse/clickhouse-go/v2/lib/binary.(*Decoder).ReadByte(0x0)
        C:/Users/me/go/pkg/mod/bitbucket.org/darkbytesengineering/clickhouse-go/v2@v2.0.14/lib/binary/decoder.go:171 +0x19
github.com/ClickHouse/clickhouse-go/v2.(*connect).process(0xc0002aa1e0, {0xaa3aa8, 0xc0000a8000}, 0x0?)
        C:/Users/me/go/pkg/mod/bitbucket.org/darkbytesengineering/clickhouse-go/v2@v2.0.14/conn_process.go:72 +0x95
github.com/ClickHouse/clickhouse-go/v2.(*connect).query.func1()
        C:/Users/me/go/pkg/mod/bitbucket.org/darkbytesengineering/clickhouse-go/v2@v2.0.14/conn_query.go:62 +0xb9
created by github.com/ClickHouse/clickhouse-go/v2.(*connect).query
        C:/Users/me/go/pkg/mod/bitbucket.org/darkbytesengineering/clickhouse-go/v2@v2.0.14/conn_query.go:58 +0x4be
```

I have a hard time reproducing this error, so I'm reluctant to include code beyond a simple query repeated over and over. But, for the sake of thoroughness I'll include the code that I _think_ the error is coming from. If I were to try and simplify it to reproduce the error I'd probably just be throwing one of the examples in a loop and waiting for a panic.

```golang
func FetchClusters(conn *clickhouse.Conn,
	ctx context.Context,
	flowTable string,
	startTime time.Time,
	endTime time.Time,
	flowLimit int) (<-chan dfdata.Cluster, error) {

	if startTime.After(endTime) {
		return nil, fmt.Errorf("query start time must be earlier than end time")
	}

	ts := "toUnixTimestamp64Milli(Timestamp)" // for ease of typing :)
	outC := make(chan dfdata.Cluster)

	query := fmt.Sprintf("SELECT DISTINCT ON (ClusterId) ClusterId FROM %s WHERE %s >= %d AND %s < %d",
		flowTable, ts, startTime.UnixMilli(), ts, endTime.UnixMilli())

	type ClusterId struct{ ClusterId string } // just to use in query
	var clusterIds []ClusterId
	if err := (*conn).Select(ctx, &clusterIds, query); err != nil {
		log.Fatal(err)
	}

	log.Println("ClusterIds: ", clusterIds)

	go func() {
		var (
			err           error
			flow          networkflow_pb.NetworkFlow
			cluster       ClusterId
			batchStart    = startTime
			numFlows      = 0
			queryTemplate = "SELECT * FROM %s WHERE  %s >= %d AND %s < %d AND ClusterId = '%s' ORDER BY Timestamp LIMIT %d"
		)

		for _, cluster = range clusterIds {
			for {
				cQuery := fmt.Sprintf(
					queryTemplate, flowTable,
					ts, batchStart.UnixMilli(),
					ts, endTime.UnixMilli(),
					cluster.ClusterId, flowLimit,
				)

				var flows []networkflow_pb.NetworkFlow
				if err = (*conn).Select(ctx, &flows, cQuery); err != nil {
					log.Fatal(err)
				}
				numFlows = len(flows)

				var cluster dfdata.Cluster
				for _, flow = range flows {
					cluster.Flows = append(cluster.Flows, &flow)
				}
				outC <- cluster

				if numFlows < flowLimit {
					break
				} else {
					// there are more flows in this cluster that we need to fetch.
					// query for the next batch using the last timestamp in the previous
					batchStart = time.UnixMilli(*flows[numFlows-1].Timestamp)
				}
			}
		}
		close(outC)
	}()

	return outC, nil
}
```

### Configuration
*OS:*
The trace is from Windows 11 (hence the C:/), but this issue has mainly been observed on Ubuntu 20.04

*Interface:* `native`

*Driver version:* V2? Not sure what this is asking for

*Go version:*
```
$ go version
go version go1.18.3 linux/amd64
```

*ClickHouse Server version:*
```
$ clickhouse-server --version
ClickHouse server version 22.2.2.1.
```

Hopefully I can find a more consistent way to reproduce this error. It took running a program for about three hours today to get it to panic.

**Comment by rtkaratekid** [comment]
@gingerwizard yeah I think it's tricky as well. Between going on holiday and being slammed with work I probably won't get to do more debugging and fiddling till after next week. But I'm happy to help where I can after that.

**Comment by gingerwizard** [comment]
@rtkaratekid https://github.com/ClickHouse/clickhouse-go/pull/646 is worth testing if you can. Curious if it still happens.

**Comment by gingerwizard** [comment]
@rtkaratekid we will release 2.3.0 on monday. I suggest you upgrade and try - since this uses a new encoding layer. We can leave this open but close please if the issue resolves itself.

**Comment by rtkaratekid** [comment]
Got back from holiday, I'll give it a run today and see if it'll panic. Fingers crossed.

**Comment by rtkaratekid** [comment]
@gingerwizard it looks like my issue is resolved with that beta release! I have a few small fixes/suggestions that I'll make a PR for soon.

**Comment by gingerwizard** [comment]
Awesome. An immediate win from moving to ch-go for encoding.
