### ISSUE TITLE
OpenDB/Open mutate the Options struct, preventing reuse

### ISSUE THREAD

**Issue by rolinh** [ClickHouse/clickhouse-go#647]
### Issue description

The [Open](https://github.com/ClickHouse/clickhouse-go/blob/b100034624aa6c2110d01e8cf43307017a62e1f2/clickhouse.go#L74-L81) and [OpenDB](https://github.com/ClickHouse/clickhouse-go/blob/b100034624aa6c2110d01e8cf43307017a62e1f2/clickhouse_std.go#L88) functions mutate the [Options](https://github.com/ClickHouse/clickhouse-go/blob/b100034624aa6c2110d01e8cf43307017a62e1f2/clickhouse_options.go#L67) struct that is passed as a parameter (see [here](https://github.com/ClickHouse/clickhouse-go/blob/b100034624aa6c2110d01e8cf43307017a62e1f2/clickhouse.go#L75) and [here](https://github.com/ClickHouse/clickhouse-go/blob/b100034624aa6c2110d01e8cf43307017a62e1f2/clickhouse_std.go#L104) respectively, via [setDefaults](https://github.com/ClickHouse/clickhouse-go/blob/b100034624aa6c2110d01e8cf43307017a62e1f2/clickhouse_options.go#L177-L196)). This prevents reusing the options struct instance as shown in the code below.

This issue was initially discussed [here](https://github.com/ClickHouse/clickhouse-go/issues/570#issuecomment-1123350032). A potential non-breaking fix would consist of making a deep copy of the options struct but this is rather ugly. A better fix could be to, e.g., have a function returning default values when unset and user provided values if set.

### Example code

```go
package main

import (
        "log"

        "github.com/ClickHouse/clickhouse-go/v2"
)

func main() {
        options := &clickhouse.Options{}
        db := clickhouse.OpenDB(options)
        err := db.Ping()
        if err != nil {
                log.Fatal("db ", err)
        }
        db2 := clickhouse.OpenDB(options)
        err = db2.Ping()
        if err != nil {
                log.Fatal("db2 ", err)
        }
}
```

### Error log

```
2022/07/05 15:38:06 db2 cannot connect. invalid settings. use SetMaxIdleConns,SetMaxOpenConns,SetConnMaxLifetime (see https://pkg.go.dev/database/sql)
exit status 1
```

### Configuration
*OS:* Arch Linux

*Interface:* `native` and `database/sql`

*Driver version:* `v2.2.0`

*Go version:* `go version go1.18.3 linux/amd64`

*ClickHouse Server version:* `ClickHouse server version 22.3.7.28 (official build).`

**Comment by gingerwizard** [comment]
I'll address this for the next release.

**Comment by gingerwizard** [comment]
This is only an issue on `OpenDB`. First test below passes, second fails.

```

func Test647(t *testing.T) {
	options := &clickhouse.Options{
		Addr: []string{"127.0.0.1:9000"},
	}
	conn, err := clickhouse.Open(options)
	require.NoError(t, err)
	ctx := context.Background()
	require.NoError(t, conn.Ping(ctx))
	//reuse options
	conn2, err := clickhouse.Open(options)
	require.NoError(t, err)
	require.NoError(t, conn2.Ping(ctx))
}

func Test647_OpenDB(t *testing.T) {
	options := &clickhouse.Options{
		Addr: []string{"127.0.0.1:9000"},
	}
	conn := clickhouse.OpenDB(options)
	require.NoError(t, conn.Ping())
	//reuse options
	conn2 := clickhouse.OpenDB(options)
	require.NoError(t, conn2.Ping())
}
```

**Comment by gingerwizard** [comment]
@rolinh https://github.com/ClickHouse/clickhouse-go/pull/675 to address. I would appreciate your thoughts.
