### ISSUE TITLE
Object_json - error by field_name with ('.')

### ISSUE THREAD

**Issue by Astlol** [ClickHouse/clickhouse-go#662]
### Issue description

I can not use dot at key of map.
```
val := map[string]interface{}{"Lol.Kek": "text" }
batch.Append(val)
err = batch.Send() // nil
// actual
err = batch.Send() // err
```
### Error log
```
code: 62, message: Syntax error (data type): failed at position 10 ('.'): .Kek String). Expected one of: data type, nested table, identifier, token, Comma
```

### Configuration
*OS:* linux

*Interface:* `native`,

*Driver version:* v2

*Go version:* 1.18

*ClickHouse Server version:* 22.6.1

**Comment by gingerwizard** [comment]
Can you try main?   [https://github.com/ClickHouse/clickhouse-go/pull/660](https://github.com/ClickHouse/clickhouse-go/pull/660) merged to address i think

**Comment by Astlol** [comment]
yes. it got worked. thanks!
