### ISSUE TITLE
Extended Support for Datatypes from Protobuf Objects

### ISSUE THREAD

**Issue by rtkaratekid** [ClickHouse/clickhouse-go#663]
**Is your feature request related to a problem? Please describe.**
When generating protobuf data structures from schema/templates, the data structures usually end up as structs of pointers. e.g.
```
syntax = "proto2";

package person;
option go_package = "person/";

message Person {
  required int64 birthday = 1;
  required string name = 2;
  optional int32 id = 3;
  optional string email = 4;
  optional uint64 foo = 5;
  repeated float float_list = 6;
}
```
is compiled to this
```golang
type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Birthday  *int64    `protobuf:"varint,1,req,name=birthday" json:"birthday,omitempty"`
	Name      *string   `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Id        *int32    `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Email     *string   `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Foo       *uint64   `protobuf:"varint,5,opt,name=foo" json:"foo,omitempty"`
	FloatList []float32 `protobuf:"fixed32,6,rep,name=float_list,json=floatList" json:"float_list,omitempty"`
}
```

This create an issue when you're trying to insert or query from clickhouse using these protobuf structs as your data structure to send/accept data. To work around this for my own use case I've forked the repo and added specific changes to `datetime64.go`. However I think this could be a useful feature for all relevant datatypes and not just my own use case. 

**Describe the solution you'd like**
I think it would be good for the `./lib/column/` files to support serialization and deserialization to and from protobuf structs and clickhouse types. This usually is just a matter of including additional cases in if/else chains. For example, in `datetime64.go`
From:
```golang
func (col *DateTime64) ScanRow(dest interface{}, row int) error {
	switch d := dest.(type) {
	case *time.Time:
		*d = col.row(row)
	case **time.Time:
		*d = new(time.Time)
		**d = col.row(row)
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "Datetime64",
		}
	}
	return nil
}
```
To:
```golang
func (col *DateTime64) ScanRow(dest interface{}, row int) error {
	switch d := dest.(type) {
	case *time.Time:
		*d = col.row(row)
	case **time.Time:
		*d = new(time.Time)
		**d = col.row(row)
	case **int64:
		*d = new(int64)
		**d = int64(col.col.Data[row])
	default:
		return &ColumnConverterError{
			Op:   "ScanRow",
			To:   fmt.Sprintf("%T", dest),
			From: "Datetime64",
		}
	}
	return nil
}
```

I'm happy to do this if it doesn't conflict with other plans or I'm not duplicating work that is already in progress. It's not hard work, it will just need to be thorough if the library wants to support protobuf.

**Comment by gingerwizard** [comment]
Thanks @rtkaratekid this looks like https://github.com/ClickHouse/clickhouse-go/issues/574

We are always happy to consider conversions for types provided there is no risk of precision loss. Feel free to raise PRs for gaps on scanrow and append as required and I will aim to promptly review. Currently we're chipping away at this bit by bit and any help is always appreciated.

**Comment by gingerwizard** [comment]
@rtkaratekid current support now in this branch - https://github.com/ClickHouse/clickhouse-go/blob/examples/TYPES.md. Will PR with new examples.
