### ISSUE TITLE
V2 support for SetLogOutput or equivalent

### ISSUE THREAD

**Issue by nickbenzoni** [ClickHouse/clickhouse-go#679]
During upgrade from V1 to V2 : getting `undefined: clickhouse.SetLogOutput` error

Would like to, on our local env, print out the queries and _ideally_ timing information to the std logger to aid debugging.
We were able to achieve this in V1 with `SetLogOutput`

**Comment by gingerwizard** [comment]
`Debug` and `Debugf` should help.

```
	var (
		conn, err = clickhouse.Open(&clickhouse.Options{
			Addr: []string{"127.0.0.1:9000"},
			Debug: true,
			Debugf: func(format string, v ...interface{}) {
				fmt.Printf(format, v)
			},
			Settings: clickhouse.Settings{
				"max_execution_time": 60,
			},
		})
	)
```

Profiling and progress info also available e.g.

```
clickhouse.WithProgress(func(p *clickhouse.Progress) {
			fmt.Println("progress: ", p)
		}), clickhouse.WithProfileInfo(func(p *clickhouse.ProfileInfo) {
			fmt.Println("profile info: ", p)
		}))
```

**Comment by gingerwizard** [comment]
Full example https://github.com/ClickHouse/clickhouse-go/blob/examples/examples/native/progress_test.go inc. information on how to get log info back from server.

**Comment by gingerwizard** [comment]
@nickbenzoni does this satisfy your needs? Can we close?

**Comment by gingerwizard** [comment]
@nickbenzoni closing as answered. Follow up if you need more help.

**Comment by nickbenzoni** [comment]
thank you. will test out tomorrow
