### ISSUE TITLE
[question] Streaming batch

### ISSUE THREAD

**Issue by yuvalgut** [ClickHouse/clickhouse-go#681]
Hi everyone,
as far as I can tell when using a batch insert with the driver, the batch actually gets accumulated on the client side and only when we call commit/send(for native) the data is compressed and flushed to cclickhouse server.
Is there a way to stream chunks of a batch to clickhouse? right now to support the single insert into clickhouse rule it means that the clients that pushes to click has to store the entire batch in memory.

thanks

**Comment by gingerwizard** [comment]
No, this isn't supported since the protocol requires the data be encoded in a column-orientated fashion the standard API provides row-oriented semantics - this requires us to build a batch in memory.  The column-orientated API could allow this potentially - id need to check this is viable, though. 

ch-go, whilst faster also has the same memory requirement for the batch. If we were to add a true "streaming" approach where the user encodes a column at a time, this is probably where we'd add it. Discussing with @ernado not entirely sure if this is  possible and we'd need to assess the value.

**Comment by yuvalgut** [comment]
By the documentation there you can stream block by block, see the onInput callback

**Comment by gingerwizard** [comment]
yes block by block, but it still resides in memory

**Comment by yuvalgut** [comment]
But only the block size is in memory so we can write 1 millions of rows with memory allocation of a block size, instead of memory for 1 million rows

**Comment by gingerwizard** [comment]
Correct, but you could also align your batches in this driver to be approx to the size of a block i.e. approx 65,536. Depending on the data this might have some impact on insert performance, given the need to prepare a batch each time - one of the reasons we expose ch-go.

Maybe there is room for a `flush` method on a batch, which writes the existing rows but doesn't release the connection. Would this help?

**Comment by yuvalgut** [comment]
> yes block by block, but it still resides in memory. A lazy consumption column by column or even column value by column value - in a generator style pattern, is not supported.

Currently clickhouse-go do support sort of generqtor pattern, where we start a batch and append to it we can flush blocks after x rows, I think this would be great feature/improvement  for this lib

**Comment by yuvalgut** [comment]
> Correct, but you could also align your batches in this driver to be approx to the size of a block i.e. approx 65,536. Depending on the data this might have some impact on insert performance, given the need to prepare a batch each time - one of the reasons we expose ch-go.
> 
> Maybe there is room for a `flush` method on a batch, which writes the existing rows but doesn't release the connection. Would this help?
> 
> Would still need to call Send() at the end to finish the batch but current memory would be released at least (in theory).

Yes, if we can controll when to flush and then append more data and flush again until we choose to "commit" the part, it would be great

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-go/issues/684 thanks for the useful feedback @yuvalgut

**Comment by gingerwizard** [comment]
@yuvalgut https://github.com/ClickHouse/clickhouse-go/pull/704
