### ISSUE TITLE
Support sql.Null* types

### ISSUE THREAD

**Issue by nickbenzoni** [ClickHouse/clickhouse-go#682]
Converting from V1 to V2 - we currently use several `sql.Null*` types throughout our stack and are now receiving errors.

Example using `sql.NullFloat64`:
``` sql: Scan error on column index 2, name "max_value": converting driver.Value type *float64 ("0x140001ec190") to a float64: invalid syntax```

Solution I would like: Support for `sql.Null*` types as in V1 driver  :)

**Comment by gingerwizard** [comment]
Seems like a good addition. Will aim for next release.

**Comment by gingerwizard** [comment]
First pass on strings https://github.com/ClickHouse/clickhouse-go/pull/686
If we're good with the approach rest should be trivial.

**Comment by gingerwizard** [comment]
Closed by #686 

Will cover all sql.Null* except sql.NullBytes - no obvious need for this yet. Also each sql.Null* just aligned with its obvious equivalent e.g. we don't support sql.NullInt16 for Int64 - sql.NullInt16 works with Int16.
