### ISSUE TITLE
Can't insert a slice of bytes into a String

### ISSUE THREAD

**Issue by a-dot** [ClickHouse/clickhouse-go#687]
### Issue description
When trying to insert a byte slice into a String ClickHouse data type I get an error. This used to be possible in v1 and I'm trying really hard to understand why this would not be allowed in v2.

From the ClickHouse documentation for the String type: "Strings of an arbitrary length. The length is not limited. **The value can contain an arbitrary set of bytes, including null bytes.** The String type replaces the types VARCHAR, BLOB, CLOB, and others from other DBMSs."

Given that the String data type is used to store "any bytes". Why would you restrict v2 to only insert "strings" into String types?

Thanks!

### Example code
```go
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
)

const ddl = `
CREATE TABLE benchmark (
	  Col1 String
) Engine Null
`

func benchmark(conn clickhouse.Conn) error {
	batch, err := conn.PrepareBatch(context.Background(), "INSERT INTO benchmark")
	if err != nil {
		return err
	}
	for i := 0; i < 1_000_000; i++ {
		err := batch.Append(
			[]byte("Golang SQL database driver"),
		)
		if err != nil {
			return err
		}
	}
	return batch.Send()
}

func main() {
	var (
		ctx       = context.Background()
		conn, err = clickhouse.Open(&clickhouse.Options{
			Addr: []string{"127.0.0.1:9000"},
			Auth: clickhouse.Auth{
				Database: "default",
				Username: "default",
				Password: "",
			},
			//Debug:           true,
			DialTimeout:     time.Second,
			MaxOpenConns:    10,
			MaxIdleConns:    5,
			ConnMaxLifetime: time.Hour,
		})
	)
	if err != nil {
		log.Fatal(err)
	}
	if err := conn.Exec(ctx, "DROP TABLE IF EXISTS benchmark"); err != nil {
		log.Fatal(err)
	}
	if err := conn.Exec(ctx, ddl); err != nil {
		log.Fatal(err)
	}
	start := time.Now()
	if err := benchmark(conn); err != nil {
		log.Fatal(err)
	}
	fmt.Println(time.Since(start))
}

```

### Error log
```
2022/07/22 14:29:50 clickhouse [AppendRow]: Col1 clickhouse [AppendRow]: converting []uint8 to String is unsupported
```

**Comment by gingerwizard** [comment]
See [815758](https://github.com/ClickHouse/clickhouse-go/issues/574)
Currently not supported. Feel free to PR. Feels like a reasonable addition.

**Comment by a-dot** [comment]
> See [815758](https://github.com/ClickHouse/clickhouse-go/issues/574) Currently not supported. Feel free to PR. Feels like a reasonable addition.

https://github.com/ClickHouse/clickhouse-go/pull/688
