### ISSUE TITLE
List of breaking changes made going from v1 to v2 of this library?

### ISSUE THREAD

**Issue by veqryn** [ClickHouse/clickhouse-go#696]
I'd like to upgrade from v1 to v2.
Could you all release a list of the breaking changes made to the library?
Is there anything that needs to be done by users to update their codebase when migrating to v2?

**Comment by veqryn** [comment]
Also, is there a minimum clickhouse server version for the various versions of your api?

**Comment by veqryn** [comment]
Example: It looks like `Date` and `DateTime` disappeared from `github.com/ClickHouse/clickhouse-go/lib/types`.  I assume I can just use `time.Time` for both of these now?  Do I need to truncate `time.Time` to the day before using it as a `Date` type?

**Comment by gingerwizard** [comment]
> Example: It looks like Date and DateTime disappeared from github.com/ClickHouse/clickhouse-go/lib/types. I assume I can just use time.Time for both of these now? 

yes and no need to truncate.

> Also, is there a minimum clickhouse server version for the various versions of your API?

We are actively working on a support policy. Currently main supports the currently supported versions of ClickHouse - https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md. We need a policy that will be consistent across clients, however, and more nuanced. We will document this asap.
Min clickhouse version currently would be oldest support LTS - 21.8.


> Could you all release a list of the breaking changes made to the library?
> Is there anything that needs to be done by users to update their codebase when migrating to v2?

We took this library on when the maintainer (community) stepped away. v2 had already been released and there was no documented v1 migration path or list of breaking changes - we continue to find these. 

This client is now officially supported by ClickHouse and we invest resources to ensure bugs and features are continuously added. If there are gaps between v1 and v2, we will endeavor to close and be highly responsive on such issues. The API is largely dropped and replace, but be aware certain type conversions are no longer supported - mainly those which hide precision loss. Any future major releases will be more cognizant of breaking changes - these will be documented.

**Comment by gingerwizard** [comment]
We are preparing docs detailing supported conversions - https://github.com/ClickHouse/clickhouse-go/blob/examples/TYPES.md will be merged soon. See also `examples` branch for comprehensive examples.

**Comment by veqryn** [comment]
Thank you.
@gingerwizard can you please also provide examples on how to do nullable versions of all of these types?

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-go/blob/examples/examples/clickhouse_api/nullable.go - ill add a int example here for you as well now.

**Comment by gingerwizard** [comment]
Going to keep this thread open and link tickets where breaking changes are detected. I'll start a md file in the root, collating them for future readers.

**Comment by gingerwizard** [comment]
Closing in favor of https://github.com/ClickHouse/clickhouse-go/pull/700

Any issues raised or I discover I'll add to this md doc. README now references.

@veqryn thank you for raising this

**Comment by veqryn** [comment]
Thx!

**Comment by veqryn** [comment]
> We are actively working on a support policy. Currently main supports the currently supported versions of ClickHouse - https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md. We need a policy that will be consistent across clients, however, and more nuanced. We will document this asap.
> Min clickhouse version currently would be oldest support LTS - 21.8.

@gingerwizard btw, it would be great if that link listed when support will expire for each version.  If support expires based on when the next version is released instead of a date, then it should mention which that and which version would expire it.

**Comment by gingerwizard** [comment]
@veqryn noted. We'll include this in any official policy. Apologies for this, some pain as we move the library to a properly supported state.
