### ISSUE TITLE
Nullable(UInt8) can't be inserted: clickhouse [AppendRow]: converting sql.NullInt32 to UInt8 is unsupported

### ISSUE THREAD

**Issue by veqryn** [ClickHouse/clickhouse-go#697]
### Issue description
I have a field in my schema like so:
`myfield Nullable(UInt8)`

I used to be able to insert to it successfully using the v1 of this library using `sql.NullInt32`
(We make sure the value inside is a valid uint8. The reason we use sql.NullInt32, is because sql.NullUInt8 doesn't exist.  We likewise use sql.NullInt32 for nullable uint16, and sql.NullInt64 for nullable uint32 and also nullable uint64.)
Now I get an error back.

I don't see any custom wrapper types that I can use in this library, so I'm not sure how to solve this.

### Error log
```
clickhouse [AppendRow]: converting sql.NullInt32 to UInt8 is unsupported
```

### Configuration
*OS:* Linux

*Interface:* `database/sql`

*Driver version:* 2.2.0

*Go version:* 1.18.3

*ClickHouse Server version:* 22.3.2.2

**Comment by gingerwizard** [comment]
sql.Null*'s are added in https://github.com/ClickHouse/clickhouse-go/pull/686 and will be in the next release. This won't support your case, however as sql.NullInt32 isn't supported for UInt8. Its not likely we will support this conversion in v2 - same reason we don't support int32 to Int8 - there is a potential precision loss.
This is a breaking change for v1 to v2 - we no longer support conversions which transparently potentially loose precision. The user has to do this in their app and ack the risk of it explictly.

**Comment by veqryn** [comment]
Ok, so what is your proposed way for me to insert a nullable uint8 or a nullable uint64 or a nullable int8, etc, into clickhouse?

**Comment by gingerwizard** [comment]
Section from new docs, which we aim to release soon:

> The go value of Nil represents null. This can be used if a field is declared as Nullable. At insert time Nil can be passed for both the normal and Nullable version of a column. For the former, the default value for the type will be persisted e.g. empty string for string. For the nullable version a NULL value will be stored in ClickHouse. 
> At Scan time, the user must pass a pointer to pointer inorder to represent the nil value for a Nullable field. In the example below, col1 which is a Nullable(String) thus receives a **string. This allows nil to be represented.
> 
> [https://github.com/ClickHouse/clickhouse-go/blob/examples/examples/clickhouse_api/nullable.go](https://github.com/ClickHouse/clickhouse-go/blob/examples/examples/clickhouse_api/nullable.go)

**Comment by veqryn** [comment]
Thank you.
Am I reading this correctly in understanding that a Nullable(UInt8) would be represented by a golang **uint8, with a double pointer?  That is going to get extremely awkward...

**Comment by gingerwizard** [comment]
represent a null int as *int8. When you Scan, you always pass an address to all variables.

**Comment by gingerwizard** [comment]
Yes just reading ,pass nil for insert time.

**Comment by gingerwizard** [comment]
docs clearly need review.
In summary,
Insert time - just pass a nil. If you have a *int8 it supports nil.
Scan time - pass the address to your variable (which is an *int8) like any other scan.

**Comment by gingerwizard** [comment]
@veqryn includes int8 example https://github.com/ClickHouse/clickhouse-go/blob/examples/examples/clickhouse_api/nullable.go

**Comment by gingerwizard** [comment]
Closing this, behavior will be documented in new docs and examples now exist for others reading.
Thanks @veqryn for raising this and prompting clarification.

**Comment by veqryn** [comment]
Thx!
