### ISSUE TITLE
Documentation: the README description of conn_open_strategy is not correct

### ISSUE THREAD

**Issue by ns-gzhang** [ClickHouse/clickhouse-go#702]
### Issue description - documentation
the description says conn_open_strategy is random by default, in fact it was in_order.

###  DSN description includes the following
- connection_open_strategy - random/in_order (default random).
  - round-robin - choose a round-robin server from the set
  - in_order - first live server is chosen in specified order

But in the real code, the default is in_order:
```
const (
	ConnOpenInOrder ConnOpenStrategy = iota
	ConnOpenRoundRobin
)
```

### Error
This has caused the default behavior change from v1 to v2, and all query traffic went to the first replica, causing performance problems.

### Question
What was the reason to do this switch for the default?

It would be nice if there is a list of incompatible changes from v1 to v2. Thanks.

**Comment by gingerwizard** [comment]
I noticed this when writing the new docs as well. Meant to update the docs. Will PR asap. Apologies for any the pain this caused @ns-gzhang

**Comment by gingerwizard** [comment]
Updated thanks for the report @ns-gzhang
