### ISSUE TITLE
another UUID support

### ISSUE THREAD

**Issue by Laotree** [ClickHouse/clickhouse-go#713]
**Is your feature request related to a problem? Please describe.**

when I define a struct use https://github.com/satori/go.uuid 
there is a column.ColumnConverterError

**Describe the solution you'd like**

https://github.com/satori/go.uuid support 

**Describe alternatives you've considered**

uuid is not a single package, please think about those uuids not in [https://github.com/google/uuid](https://github.com/google/uuid)

**Additional context**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16837634/183373879-a9bc987c-75d6-4af2-ac4f-625f1fd940b0.png">

**Comment by DGuang21** [comment]
I don't think go mods should be introduced too much for compatibility with a certain type.

satori.uuid implements the String() method

https://github.com/satori/go.uuid/blob/b2ce2384e17bbe0c6d34077efa39dbab3e09123b/uuid.go#L115

```type iString interface```
Therefore, a judgment should be added at default here, and the value of interface should be asserted as iString.


code e.g
```
if s, ok := v.(iString); ok {
  col.col.Append(s.String())
}
```

**Comment by DGuang21** [comment]
Or I can make iString a public method in https://github.com/ClickHouse/clickhouse-go/pull/707

**Comment by DGuang21** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> when I define a struct use https://github.com/satori/go.uuid there is a column.ColumnConverterError
> 
> **Describe the solution you'd like**
> 
> https://github.com/satori/go.uuid support
> 
> **Describe alternatives you've considered**
> 
> uuid is not a single package, please think about those uuids not in https://github.com/google/uuid
> 
> **Additional context** Add any other context or screenshots about the feature request here. <img alt="image" width="1440" src="https://user-images.githubusercontent.com/16837634/183373879-a9bc987c-75d6-4af2-ac4f-625f1fd940b0.png">

This interface can also use the ```fmt.Stringer``` provided by the Golang fmt package

**Comment by gingerwizard** [comment]
I see you raised https://github.com/ClickHouse/clickhouse-go/pull/714. Similar sentiments to @DGuang21  - we could support parsing anything which implements fmt.Stringer for the uuid column. This would work but not in column mode.

**Comment by gingerwizard** [comment]
Addressed by https://github.com/ClickHouse/clickhouse-go/pull/720

uuids now need to just implement stringer and scan.
