### ISSUE TITLE
Invalid number of arguments 

### ISSUE THREAD

**Issue by pahanini** [ClickHouse/clickhouse-go#72]
Trying to run this code
```go
	_, err = tx.Exec(
		"INSERT INTO event (id, created_at, url_path) VALUES (?, ?, ?), (?, ?, ?)", 
		1, now, "a",
		2, now, "b",
	)
```
got error,  
```
Received unexpected error "sql: expected 3 arguments, got 6"
```

The only solution I have found is to use statement with 3 arguments and do insert twice(

**Comment by kshvakov** [comment]
You must use prepared statements 

Example: 

```go 
tx,_=connect.Begin()
stmt,_:=tx.Prepare("INSERT INTO event (id, created_at, url_path) VALUES (?, ?, ?)")
stmt.Exec(1,now,"a")
stmt.Exec(1,now,"b")
tx.Commit()
```

**Comment by pahanini** [comment]
Yes, statements works fine. But current kind of behaviour are little bit confusing. Because usually exec takes a lot of arguments. May be it's better to return special kind of error (like "use statement") or allow to use the common way of exec usage or at at last mark this odd in the docs.

**Comment by kshvakov** [comment]
Fixed in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
