### ISSUE TITLE
batch send err:compress: buf size 607047244 > 134217728 max size

### ISSUE THREAD

**Issue by hanjm** [ClickHouse/clickhouse-go#721]
### Issue description
Hi, i am using natvie batch with compress, i found if batch size greater 128MB, will produce a error message when invoke `batch.send()`.
it seems has a hard limit for size of compress data, what should i do.
https://github.com/ClickHouse/ch-go/blob/main/compress/writer.go#L22
https://github.com/ClickHouse/ch-go/blob/main/compress/compress.go#L31
### Example code

```
	batch, err := db.PrepareBatch(ctx, insertSQL)
	if err != nil {
		return fmt.Errorf("prepare batch err:%w", err)
	}
        // vs is 200k length array, total size execeed 128MB 
        for v:=range vs {
            err:=batch.Append(v)
             if err != nil {
			return fmt.Errorf("batch append err:%w", err)
		}
       }
      	if err = batch.Send(); err != nil {
		return fmt.Errorf("batch send err:%w", err)
	}
```
### Error log

```
batch send err:compress: buf size 607047244 > 134217728 max size
```
### Configuration
*OS:*
Linux
*Interface:* E.g. `native`, `database/sql`
native
*Driver version:*
2.23-bata2
*Go version:* run `go version` in your console
1.18.2
*ClickHouse Server version:*
21.8.12

**Comment by gingerwizard** [comment]
This is a ch-go limitation @ernado can we make this configurable?

**Comment by ernado** [comment]
Yes, we can do it. It was introduced to prevent user from accidental OOM.

**Comment by gingerwizard** [comment]
If you expose in ch-go (maybe an env variable or settings passed to the encoder init?) we can document in clickhouse-go.

**Comment by ernado** [comment]
Lol, now we can close issues with cross-repo references? :thinking: 

It should be fixed in `ch-go@v0.47.3`, I've removed this check entirely, we don't need it on data block write.

**Comment by gingerwizard** [comment]
@hanjm next release. Probably Friday or latest next monday.

**Comment by hanjm** [comment]
thank you.
