### ISSUE TITLE
Fix copylock in clickhouse.Pool

### ISSUE THREAD

**Issue by fengberlin** [ClickHouse/clickhouse-go#725]
### Issue description
In conn_http.go, [line 48](https://github.com/ClickHouse/clickhouse-go/blob/65abd39572ada7026adb1e4c6ea8093ae1c39e3b/conn_http.go#L48), the `clickhouse.Pool` contains a `sync.Pool`. To avoid the `copylock`, we should use `*sync.Pool` in `clickhouse.Pool`

That is because `sync.Pool` contains `noCopy`, and its doc said:

> A Pool must not be copied after first use

Plz cc @gingerwizard, and here is my PR [#724](https://github.com/ClickHouse/clickhouse-go/pull/724). 

### Example code
```go
type Pool[T any] struct {
    pool *sync.Pool
}
```

### Error log
```
Not have.
```

### Configuration
*OS:* `Linux rmb 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

*Interface:* `native`

*Driver version:* `main branch code`

*Go version:* `go1.19`

*ClickHouse Server version:* `21.12.3`

**Comment by gingerwizard** [comment]
Closed by https://github.com/ClickHouse/clickhouse-go/pull/724
