### ISSUE TITLE
[handshake] unexpected packet [21] from server

### ISSUE THREAD

**Issue by Kugelschieber** [ClickHouse/clickhouse-go#730]
### Issue description

Our app server and my machine can't connect to our CH server. It runs version 22.2.2 and I've tested it with clickhouse-go version 2.2.0 and 2.3.0. In all cases, I receive a `[handshake] unexpected packet [21] from server` error. The CH server logs show no related errors.

Any idea what might cause this? Is it a bug? I can connect using DBeaver and the Java CH client.

### Example code

```
db := clickhouse.OpenDB(&clickhouse.Options{
	Addr: []string{fmt.Sprintf("%s:%d", config.Hostname, config.Port)},
	Auth: clickhouse.Auth{
		Database: config.Database,
		Username: config.Username,
		Password: config.Password,
	},
	TLS: &tls.Config{
		InsecureSkipVerify: false,
	},
	DialTimeout: time.Second * 30,
	Debug:       true,
})
db.SetMaxOpenConns(1)
db.SetConnMaxLifetime(time.Duration(config.MaxConnectionLifetimeSeconds) * time.Second) // 1800
db.SetMaxIdleConns(config.MaxIdleConnections) // 5
db.SetConnMaxIdleTime(time.Duration(config.MaxConnectionIdleTimeSeconds) * time.Second) // 300
```

### Error log
```
[clickhouse][conn=1][<ip>:9440][handshake] -> Golang SQLDriver 1.1.54453
[clickhouse][conn=1][<ip>:9440][handshake] <- ClickHouse (Ubuntu-2004-focal-64-minimal) server version 22.2.2 revision 54455 (timezone UTC)
[clickhouse][conn=1][<ip>:9440][ping] -> ping
[clickhouse][conn=1][<ip>:9440][ping] <- pong
[clickhouse][conn=2][<ip>:9440][handshake] -> Golang SQLDriver 1.1.54453
2022-08-22T20:11:34 [ERROR] Error connecting to ClickHouse       err=[handshake] unexpected packet [21] from server
```

### Configuration
*OS:* Ubuntu

*Driver version:* 2.2.0 and 2.3.0

*Go version:* go version go1.18.2 linux/amd64

*ClickHouse Server version:* 22.2.2

**Comment by gingerwizard** [comment]
I noticed we aren't logging the correct version. 

All tests pass against 22.2 - we even have a simple `ping` test that replicates your example almost exactly.

Is there any proxy or eqv. between the client and your CH instance? In what format are you specifying the host?

**Comment by Kugelschieber** [comment]
> I noticed we aren't logging the correct version.

Ah okay. I'm running 22.2.2.1.

> Is there any proxy or eqv. between the client and your CH instance?

No, I directly connect to the server.

> In what format are you specifying the host?

`sub.domain.io:9440` The domain is configured for IPv4 and IPv6 if that makes any difference.

**Comment by Kugelschieber** [comment]
Okay, I've found the issue. I didn't really know what to do with the error message, but it turned out that the client connected twice and that messed up the handshake I think. After removing the superfluous connection it now works.

**Comment by willis-yang** [comment]
I have same problem too, my clickhouse version is 23.3.2.1 ,  go connect return error "[handshake] unexpected packet [21] from server"
here is my connect code 
### Example code
```package clickhouse

import (
	"fmt"
	"github.com/zeromicro/go-zero/core/logx"
	"gorm.io/driver/clickhouse"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
	"gorm.io/gorm/schema"
	"log"
	"os"
	"time"
)

type ClickHouseConfig struct {
	Dsn             string
	Tracing         bool
	MaxIdle         int
	MaxOpen         int
	ConnMaxIdleTime int
}

func NewClickHouse(clickHouseConfig ClickHouseConfig, config logx.LogConf) *gorm.DB {
	var (
		filePath  string
		newLogger logger.Interface
	)
	if config.Path == "" {
		newLogger = logger.New(
			log.New(os.Stdout, "\r\n", log.LstdFlags),
			logger.Config{
				SlowThreshold:             time.Second,
				LogLevel:                  logger.Info,
				IgnoreRecordNotFoundError: false,
				Colorful:                  false,
			},
		)
	} else {
		filePath = fmt.Sprintf("%v/sql-%v.log", config.Path, time.Now().Format("2006-01-02"))
		file, _ := os.OpenFile(filePath, os.O_RDWR|os.O_CREATE|os.O_APPEND, os.ModePerm)
		newLogger = logger.New(
			log.New(file, "\r\n", log.LstdFlags),
			logger.Config{
				SlowThreshold:             time.Second,
				LogLevel:                  logger.Info,
				IgnoreRecordNotFoundError: false,
				Colorful:                  false,
			},
		)
	}

	db, err := gorm.Open(clickhouse.New(clickhouse.Config{
		DSN:                          clickHouseConfig.Dsn,
		DisableDatetimePrecision:     true,
		DontSupportRenameColumn:      true,
		DontSupportEmptyDefaultValue: false,
		SkipInitializeWithVersion:    false,
		DefaultGranularity:           3,
		DefaultCompression:           "LZ4",
		DefaultIndexType:             "minmax",
		DefaultTableEngineOpts:       "ENGINE=MergeTree() ORDER BY tuple()",
	}), &gorm.Config{
		NamingStrategy: schema.NamingStrategy{
			SingularTable: true,
		},
		Logger: newLogger,
	})
	if err != nil {
		panic(err)
	}

	sqlDB, err := db.DB()
	if err != nil {
		panic(err)
	}

	sqlDB.SetMaxIdleConns(clickHouseConfig.MaxIdle)
	sqlDB.SetMaxOpenConns(clickHouseConfig.MaxOpen)
	sqlDB.SetConnMaxIdleTime(time.Duration(int64(clickHouseConfig.ConnMaxIdleTime)) * time.Second)

	return db
}
```
### Dsn
```
clickhouse://user:password@xxx.com:9000,xxxx:9220/test?dial_timeout=200ms&max_execution_time=60
```

**Comment by jkaflik** [comment]
@willis-yang what is `9220` port used in your DSN?

**Comment by willis-yang** [comment]
这里是k先生的邮箱，已经收到你的来信，稍后，我会回复你

**Comment by willis-yang** [comment]
> @willis-yang what is `9220` port used in your DSN?

it just demo, i use 9440

**Comment by jkaflik** [comment]
@willis-yang, it's pretty tricky to help debug the issue without enough data. 
So your DNS is assuming port `9440`? I assume it's native with TLS: https://clickhouse.com/docs/en/guides/sre/network-ports
Did you configure the client to use TLS? This is not `gorm` repository. Please take a look on this example: https://github.com/go-gorm/clickhouse?tab=readme-ov-file#advanced-configuration

**Comment by willis-yang** [comment]
@jkaflik  excellent, i see, it works,  thanks !

**Comment by willis-yang** [comment]
> @willis-yang, it's pretty tricky to help debug the issue without enough data. So your DSN is port `9440`? I assume it's native with TLS: https://clickhouse.com/docs/en/guides/sre/network-ports Did you configure the client to use TLS? I am not aware how that works with `gorm` and this is not `gorm` repository where you raise your issue. Please take a look on this example: https://github.com/go-gorm/clickhouse?tab=readme-ov-file#advanced-configuration or try adding `secure` query param to your DSN

excellent, i see, it works, thanks !
