### ISSUE TITLE
Breaking change in v2.3.0

### ISSUE THREAD

**Issue by fengberlin** [ClickHouse/clickhouse-go#731]
Before `v2.3.0`, `clickhouse.Options` contains a `Interface` field, but in `v2.3.0`, it changes to `Protocol`. Code can not be compiled successfully after upgrading `clickhouse-go` to `v2.3.0`.

Before:
```go
type Options struct {
    Interface InterfaceType
}
```

After:
```go
type Options struct {
    Protocol Protocol
}
```

And exported type `InterfaceType`, exported value `NativeInterface`, `HttpInterface` are also removed in `v2.3.0`. It's seems a bad choice to do that.

/cc @gingerwizard

**Comment by gingerwizard** [comment]
These were added for http support in 2.3.0 and  marked as experimental/beta as weren't sure of the interface. 2.3.0 finalized this. https://github.com/ClickHouse/clickhouse-go/releases/tag/v2.3.0-beta.1

**Comment by gingerwizard** [comment]
@fengberlin apologies we could of done a better job of marking this as experimental and therefore subject to change. Noted and we'll be more clear in future.
