### ISSUE TITLE
Problem with long-time executed insert queries

### ISSUE THREAD

**Issue by Android76** [ClickHouse/clickhouse-go#74]
I noticed some strange behaviour with long-time executed insert queries.
For example, query INSERT INTO Table2 SELECT * FROM Table1
Table2's engine is ReplicatedCollapsingMergeTree, Table1's engine is MergeTree.
If Table1 is not large, everything is ok.
If Table1 (as in my real case) is large enough (over 20 millions rows), I've got multiple insert (some rows have been inserted multiple times).
I found out that the problem is timeouts.
When I set timeouts (both for read and write) 3600 seconds, query works fine.
Maybe, it will be a good idea not use timeouts for queries like 'INSERT INTO... SELECT FROM...', because execution time may take a long time.
Also I noticed that, if I set parameters write_timeout=0 and read_timeout=0 query doesn't work at all.
So, it is impossible to set unlimited timeouts.

**Comment by kshvakov** [comment]
Oh, I know, I use timeout=3600 too ) I'll try to fix this problem in the near future

**Comment by kshvakov** [comment]
Fixed in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
