### ISSUE TITLE
Native Driver support for Custom Time type in struct

### ISSUE THREAD

**Issue by bzon** [ClickHouse/clickhouse-go#742]
**Is your feature request related to a problem? Please describe.**

I have a struct with a custom time type `CustomDateTime`. I use it over `time.Time` because I change the way how it is stringified in json.

```go
type CustomDateTime time.Time

type Log struct {
  Timestamp CustomDateTime `json:"timestamp" ch:"timestamp"`
  Field1 string `json:"field1" ch:"field1"`
  Field2 string `json:"field2" ch:"field2"`
}
```

However, I get an error with this code:

```go
var vv Log
_ = conn.Select(ctx, &vv, dest, args...)
```

```
query error: clickhouse [ScanRow]: (timestamp) converting DateTime to *CustomDateTime is unsupported
```

When the using `sql` driver, I have no problem using `DateTime` column type to a struct field with type `CustomDateTime`. 

**Describe the solution you'd like**

I want the same usage when I was using the `sql` driver.

```go
var vv Log
_ = conn.Select(ctx, &vv, dest)
```

I think https://github.com/ClickHouse/clickhouse-go/pull/720 is a good reference for the solution.

**Describe alternatives you've considered**
My alternative solution is to create a temporary alias struct and use row scan.

```go
type logTmp struct {
  Log
  Timestamp `ch:"timestamp"`
}

rows, _ := db.conn.Query(....)

var vv []Log
for rows.Next() {
		var res postbackLogs
		if err := rows.ScanStruct(&res); err != nil {
			return nil, errors.WrapT(span, err, "scan error")
		}
		v := res.PostbackResult

		// unsupported types by the native driver must be converted by hand.
		v.Timestsamp = parseTimeToCustomDateTimeFunc(res.Timestamp)
		vv = append(vv, v)
}
```

**Additional context**

**Comment by gingerwizard** [comment]
Makes sense to me. Will PR.

**Comment by gingerwizard** [comment]
support for sql.Scanner on DateTime should do it.

**Comment by gingerwizard** [comment]
@bzon addressed by https://github.com/ClickHouse/clickhouse-go/pull/767


Requires your type to implement sql.Scanner
e.g.

```
type CustomDateTime time.Time

func (ct *CustomDateTime) Scan(src any) error {
	if t, ok := src.(time.Time); ok {
		*ct = CustomDateTime(t)
		return nil
	}
	return fmt.Errorf("cannot scan %T into CustomDateTime", src)
}

```
