### ISSUE TITLE
Can not import module for clickhouse

### ISSUE THREAD

**Issue by selmi2** [ClickHouse/clickhouse-go#743]
### Issue description
Can not import module for clickhouse.
### Error log
```
imports github.com/ClickHouse/clickhouse-go/v2: import cycle not allowed
```

### Configuration
*OS:*

*Interface:* 

*Driver version: v2

*Go version:* 1.19

**Comment by gingerwizard** [comment]
@selmi2 what version are you using? please show your go.mod here

**Comment by gingerwizard** [comment]
Can't reproduce. This feels like an issue - can't reproduce on main. @selmi2 if you still have this issue please reopen and ping me with go.mod details.
