### ISSUE TITLE
Which Release support for clickhouse-server 21.8 LTS

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/clickhouse-go#750]
Which Release support for clickhouse-server 21.8.14.5 ?
Is there some support list?

**Comment by gingerwizard** [comment]
No this is not supported by the client - current release.  Identify when 21.8 was supported by ClickHouse -  on the release of 22.8 it was no longer supported. Thus client releases up to July 2022 would of supported this client (we test against those clickhouse versions currently supported).

Therefore, latest client supporting this was v2.2.0
