### ISSUE TITLE
Unknown setting database (Breaking change?)

### ISSUE THREAD

**Issue by nickbenzoni** [ClickHouse/clickhouse-go#757]
During update from `clickhouse-go/v1` to `v2` : instantiation of test clickhouse db get the error `code: 115, message: Unknown setting database`

The setup code so far is as follows (works with `v1`):
```
s.host = "localhost"
s.port = "9000"
dataSource = fmt.Sprintf("tcp://" + s.host + ":" + s.port + "?database=default") <-- likely error source

s.dbname = "test_db"
s.cluster="cluster_name"
conn, err := sql.Open("clickhouse", dataSource)
s.FatalOnError(conn.Ping(), "Error pinging ch")

_, err = conn.Exec(fmt.Sprintf("CREATE DATABASE %s ON CLUSTER %s", s.dbname, s.cluster))
s.FatalOnError(err, fmt.Sprintf("could not: CREATE DATABASE %s ON CLUSTER %s", s.dbname, s.cluster)) <--- ERROR HERE
```

OS: MacOS Monterey
Interface: `database/sql`
Driver version: 2.3.0
Go Version: 1.19
Ch Server Vers: 21.5.6

Thank you!!

PS I saw in the readme that this method of instantiating the connection is not listed, however it is also not listed in the breaking change section, so I thought it was a valid issue.

**Comment by gingerwizard** [comment]
Yes the format of the connection string has changed - this is a breaking change. 

Pass database like

```
clickhouse://username:password@host:port/database
```

Thanks for raising - useful for others searching for same issue.
