### ISSUE TITLE
Ensure map keys are ordered prior to insert

### ISSUE THREAD

**Issue by alanhe** [ClickHouse/clickhouse-go#758]
### Issue description
(It maybe not the best example).

Suppose I've a table,
```sql
CREATE TABLE mytest
(
    `id` Map(String, String)
)
ENGINE = ReplacingMergeTree
ORDER BY id;
```

Add few rows,
```sql
insert into mytest2 (id) values ({'k1': 'v1', 'k2': 'v2'}) ({'k1': 'v1', 'k2': 'v2'}) ({'k2': 'v2', 'k1': 'v1'});
```

Call optimize to trigger a merge. Then, the rows in the tables are:
```plain
┌─id────────────────────┐
│ {'k1':'v1','k2':'v2'} │
│ {'k2':'v2','k1':'v1'} │
└───────────────────────┘
```

With the clickhouse-client, I'm able to control the order of the keys to make sure the ids are correctly deduplicated.

But with the clickhouse-go, I'm not able to control the order of the keys because the map iterating order is non-deterministic in Golang. 

I try to insert a `proto.ColMap`, but the code does not work.
```go
keys := new(proto.ColStr)
keys.Append("k1")
keys.Append("k2")
vals := new(proto.ColStr)
vals.Append("v1")
vals.Append("v2")
m := proto.NewMap[string, string](keys, vals)
cMap := []*proto.ColMap[string, string]{m}
if err = batch.Column(0).Append(cMap); err != nil {
    panic(err)
}
``` 

The error message:
```plain
panic: clickhouse [AppendRow]: converting *proto.ColMap[string,string] to Map(String, String) is unsupported. try using map[string]string
```

Could you please teach me how to achieve what I want?

### Configuration

*Driver version:*
github.com/ClickHouse/clickhouse-go/v2 v2.3.0
*Go version:* run `go version` in your console

*ClickHouse Server version:*
go1.19

**Comment by gingerwizard** [comment]
supporting proto.ColMap[string,string] seems like a simple way to solve this use case - its advanced but proto.ColMap should be trival to support.

**Comment by gingerwizard** [comment]
We could alternatively ensure we sort our keys and use these to iterate a standard map. This will slow inserts but ensure performance is deterministic.

**Comment by gingerwizard** [comment]
Reconsidering this, im not sure having a map as a sorting key even makes sense in CLickHouse - see https://github.com/ClickHouse/ClickHouse/issues/35022

If we did support this using proto.ColMap is tricky as Append accepts an interface and ColMap is a generic type - testing for this type against interface I don't think is possible.

We could support a sorted map that doesn't use generics maybe but I'm still not convinced this is something we need to support.

To achieve this you could use the `Exec` method - albeit this will be inefficient.

**Comment by alanhe** [comment]
Thanks for checking my problem.
I understand it's a non standard usage. I will try `Exec`.

**Comment by alanhe** [comment]
I leave some questions to https://github.com/ClickHouse/ClickHouse/issues/35022#issuecomment-1256872196.

**Comment by gingerwizard** [comment]
Thanks @alanhe i'm hesitant to add the sorting code, due to the potential for a perf hit, so I think a separate ordered map makes sense.

**Comment by alanhe** [comment]
I suggest to have something like this:

```go
var cMap []proto.ColMap[string, string]
...
batch.Column(0).Append(cMap)
```

* For most scenarios, appending a Golang native map is good enough.
* If order is needed somehow, then users have to sort the keys themself and then append the keys and values in the form of two slices (though I'm not sure if it's a good idea to expose the `proto.ColMap` from the lower level API).

**Comment by gingerwizard** [comment]
Yes this is unfortunately a big API change - which will have wide reaching
probably breaking changes. A generic append interface is the best way
forward but we would need to assess if it's even compatible with
dependencies elsewhere e.g SQL golang interface. Column is not strongly
typed also so we would need to modify Interface. I'll see if w can do but
it feels like 3.0 change. We can probably support a non generic ordered map
in 2.x though.

**Comment by gingerwizard** [comment]
We could support https://github.com/wk8/go-ordered-map/tree/v1
would prefer given the size of the lib to just use the code and offer a `clickhouse.OrderedMap`.

**Comment by gingerwizard** [comment]
@alanhe proposed interface

```
type OrderedMap interface {
	Get(key interface{}) (interface{}, bool)
	Keys() <- chan interface{}
}
```

**Comment by alanhe** [comment]
By the SQL,
```sql
insert into mytest2 (id) values (CAST((['k1', 'k2'], ['v1', 'v2']), 'Map(String, String)'));
```

I prefer to have a Go interface like:
```go
var colMap [][2]any

// Add the first row
colMap = append(colMap, [2]any{
  []string{"k1", "k2"},
  []string{"v1", "v2"},
})

// Add the second row
// I have full control of the orders
colMap = append(colMap, [2]any{
  []string{"k2", "k1"},
  []string{"v2", "v1"},
})

if err = batch.Column(0).Append(colMap); err != nil {
 ...
}
```

I still consider myself new to Golang so ignore me if this does not make sense to you.

**Comment by gingerwizard** [comment]
Given ClickHouse permits duplicate keys this is maybe an acceptable pattern.

**Comment by gingerwizard** [comment]
See https://github.com/ClickHouse/clickhouse-go/blob/main/tests/map_test.go#L251 for example
