### ISSUE TITLE
formatTime sends empty timezone

### ISSUE THREAD

**Issue by mayamika** [ClickHouse/clickhouse-go#759]
### Issue description
[formatTime](https://github.com/ClickHouse/clickhouse-go/blob/85c136949364570295e32f033205e4227210f07b/bind.go#L206)
[toDateTime doc](https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions/#todatetime64)

Can't we just send Unix time for all cases?

When i use time.Parse with RFC3339Nano format with explicit timezone, the time.Location's String method returns empty string, then clickhouse-go uses this empty string and sends to clickhouse server empty timezone parameter. As a result i got wrong time in query parameter.

### Example code
```go
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
)

func main() {
	// Parse time where +04:00 is not local time.
	timeWant, err := time.Parse(time.RFC3339Nano, "2022-09-15T17:06:31.81718722+04:00")
	if err != nil {
		panic(err)
	}
	// You must get time difference, because clickhouse-server parses this as UTC time.
	fmt.Println("With timezone:")
	testWith(timeWant)

	// Now test with t.Local()
	// No time difference, because clickhouse-go sends unix time.
	fmt.Println("With local time:")
	testWith(timeWant.Local())
}

func testWith(timeWant time.Time) {
	fmt.Printf("Location string: %v\n",
		timeWant.Location().String(),
	)

	conn, err := clickhouse.Open(&clickhouse.Options{
		Addr: []string{os.Getenv("CLICKHOUSE_ADDR")},
		Auth: clickhouse.Auth{
			Database: os.Getenv("CLICKHOUSE_DATABASE"),
			Username: os.Getenv("CLICKHOUSE_USERNAME"),
			Password: os.Getenv("CLICKHOUSE_PASSWORD"),
		},
	})
	if err != nil {
		panic(err)
	}
	defer func() { _ = conn.Close() }()

	date := clickhouse.DateNamed("Time", timeWant, clickhouse.NanoSeconds)
	r := conn.QueryRow(context.TODO(), "SELECT @Time", date)

	var timeGot time.Time
	if err := r.Scan(&timeGot); err != nil {
		panic(fmt.Errorf("scan: %w", err))
	}

	if timeGot.Unix() != timeWant.Unix() {
		fmt.Printf("wrong: got = %v, want = %v\n", timeGot.Local(), timeWant.Local())
	} else {
		fmt.Println("ok")
	}
}
```

### Configuration
*OS:*

*Interface:* `native`

*Driver version:* latest

*Go version:* 1.19

*ClickHouse Server version:* 22.3

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-go/issues/719

**Comment by gingerwizard** [comment]
Couple of things here @mayamika 

- We should consider the tz if its in the string see https://github.com/ClickHouse/clickhouse-go/issues/719 item 2. We need to fix.
- If no tz is set for a time.Time{} (which in your case it isn't because you've parsed with time.RFC3339Nano) we will use the tz of the client. Not sure this addresses your problem but we wont just assume its UTC if that's what you hoped for.

**Comment by gingerwizard** [comment]
Trival fix will include in PR 

```
func formatTime(tz *time.Location, scale TimeUnit, value time.Time) (string, error) {
	switch value.Location().String() {
	case "Local", "":
```
