### ISSUE TITLE
Support for nested structures in tables

### ISSUE THREAD

**Issue by joanbalaguero** [ClickHouse/clickhouse-go#77]
I have a table with a nested structure:
 
CREATE TABLE DM_AVAIL
( 
ID UInt64, 
REQUEST_DATE Date,
CLIENT_ID UInt32,
REQUEST_ELEMENTS Nested
(
   ELEM_ID UInt32, " +
   ELEM_TYPE Enum8 ('C'=0,'A'=1,'Z'=2,'P'=3,'T'=4,H'=5,'R'=6)
  )
) ENGINE = MergeTree PARTITION BY REQUEST_DATE ORDER BY CLIENT_ID
 
 I want to insert data into this table by using a prepared statement:
 
st1, err1 := tx.Prepare("INSERT INTO DM_AVAIL VALUES (?,?,?, [????????])")
 
And then:
params := ………
if _, err := stmt[1].Exec(params); err != nil { return err }

Also we need to get nested data in queries.

**Comment by kshvakov** [comment]
Copy of email conversation 

> You can use Nested data structures like this https://gist.github.com/kshvakov/7ff31ff923ed2c717621c0599efedae0 . I'll add more convenient type for Nested structures in near future

**Comment by derekperkins** [comment]
I'd be interested in an easier way to do this

**Comment by kshvakov** [comment]
@derekperkins I think it will be in the v2 of the driver.

**Comment by Enach** [comment]
Hello, @kshvakov do you have some update on this issue?

**Comment by wozuo** [comment]
> Copy of email conversation
> 
> > You can use Nested data structures like this https://gist.github.com/kshvakov/7ff31ff923ed2c717621c0599efedae0 . I'll add more convenient type for Nested structures in near future

Thanks, nice code snippet! However this approach works for non-nullable columns in nested data structures only. The following SQL:
```
CREATE TABLE test.ntest
(
    somecol LowCardinality(Nullable(String)),
    nestedcol Nested (
        a LowCardinality(Nullable(String)),
        b LowCardinality(Nullable(String))
    )
)
ENGINE = MergeTree()
ORDER BY (somecol);

INSERT INTO test.ntest VALUES (NULL, ['a', 'a2'], ['b', NULL]);
```
creates this simple table and inserts successfully. When trying to insert in Go however:
```
tx, err = dbconn.Begin()
if err != nil {
    return
}

stmt, err := tx.Prepare("INSERT INTO test.ntest (somecol, nestedcol.a, nestedcol.b) VALUES (?, ?, ?)")
if err != nil {
    return
}

args := make([]interface{}, 3)
args[0] = "somevalue"
args[1] = []interface{}{"val_a"}
args[2] = []interface{}{"val_b"}

if _, err := stmt.Exec(args...); err != nil {
fmt.Println("exec error: " + err.Error())
    return err
}

if err := tx.Commit(); err != nil {
    fmt.Println("commit error 1: " + err.Error())
    return err
}
stmt.Close()
```
The Go client hangs and fails with an `i/o timeout`. Clickhouse itself logs the following error: `DB::Exception: Cannot read all data. Bytes read: 54. Bytes expected: 110`.

**Comment by kshvakov** [comment]
We have a better types support in [V2](https://github.com/ClickHouse/clickhouse-go/tree/v2)
