### ISSUE TITLE
Scanning null into sql.NullFloat64 fails

### ISSUE THREAD

**Issue by eqinox76** [ClickHouse/clickhouse-go#775]
### Issue description
As of #682 sql null types are supported. But when scanning a null value into them i see
``` 
sql: Scan error on column index 1, name "open": converting driver.Value type *float64 ("0xc00126ecb0") to a float64: invalid syntax
```

### Example code
Table definition:
```
DESCRIBE TABLE marketdata.daily

Query id: b50c6c2c-4c7a-433c-acc2-b902598b3b63

┌─name────────┬─type──────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ id          │ UInt32            │              │                    │         │                  │                │
│ date        │ Date              │              │                    │         │                  │                │
│ open        │ Nullable(Float64) │              │                    │         │                  │                │
└─────────────┴───────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```

```go
for rows.Next() {
	var date time.Time
	var open sql.NullFloat64

	err = rows.Scan(
		&date,
		&open,
	)

	if err != nil {
		return err
	}
}
```

This works fine as long as the dataset has a open value which is not null. If the open is null the error is thrown.

### Error log
```
[If you have an error log, please paste it here.](sql: Scan error on column index 1, name "open": converting driver.Value type *float64 ("0xc00126ecb0") to a float64: invalid syntax)
```

### Configuration
*OS:* Ubuntu 22.04.1 LTS

*Interface:* `database/sql`

*Driver version:* 2.3.0

*Go version:* go version go1.19 linux/amd64

*ClickHouse Server version:* Connected to ClickHouse server version 22.3.2 revision 54455.

### Comment

I will try the native interface next. Great work with the v2 interface so far! We see great speed improvements.

**Comment by gingerwizard** [comment]
Same as https://github.com/ClickHouse/clickhouse-go/issues/754

**Comment by gingerwizard** [comment]
@eqinox76 i think the challenge is the same as #754 https://github.com/ClickHouse/clickhouse-go/issues/754#issuecomment-1256437674 I need to think about this but I think it needs a breaking change. Null* should work with native interface
