### ISSUE TITLE
use function timezone instead of timeZone to readTimeZone in http-conn dialHttp func 

### ISSUE THREAD

**Issue by YaHuiSong** [ClickHouse/clickhouse-go#780]
### Issue description
for clickhouse with version lower than 21.4, the function timeZone does not supported, while for all clickhouse versions, function timezone could be recognized 

### Example code
```go
[If possible, please enter some example code here to reproduce the issue.](https://github.com/ClickHouse/clickhouse-go/blob/main/conn_http.go#L242)

replace SELECT timeZone() with SELECT timezone()
```

### Error log
<img width="352" alt="image" src="https://user-images.githubusercontent.com/24310039/194701399-36fa18d2-f2a1-46e7-bdb8-40836ac23a86.png">

### Configuration
*OS:*

*Interface:* E.g. `native`, `database/sql`
database/sql

*Driver version:*
2.3.0

*Go version:* run `go version` in your console
1.19

*ClickHouse Server version:*
21.3.10.1

**Comment by derN3rd** [comment]
Just created a PR for this to hopefully get this fixed sooner. Having the same issue on a CH server with version 20.12.5.14

**Comment by gingerwizard** [comment]
21.3 isnt strictly a supported version for this client nor a supported version of ClickHouse. I'm happy to consider this change, but I'm concerned that long term `timezone` will be removed in ClickHouse - `timeZone` is the standard moving forward. Will check with core as to the plans to support this backwards compatibility and when it will be removed.

**Comment by gingerwizard** [comment]
yes im not keen to have this sort of logic just to support unsupported versions of ClickHouse.

**Comment by derN3rd** [comment]
Got your point. 

But if the information for the if/else check are already in hand, this fix only seems to bring benefits, as this CH version is not that old and probably a few people will run into this error

**Comment by gingerwizard** [comment]
@derN3rd core team have confirmed this is to stay. Will merge your PR. Thanks for your patience.
