### ISSUE TITLE
[Question] How to dynamic discover schema?

### ISSUE THREAD

**Issue by alanhe** [ClickHouse/clickhouse-go#795]
I'm writing a service to insert data to multiple ClickHouse tables. Some of the schemas are unknown to me, so I need to dynamic discover the schema to build the insertion payloads, that is, with a given table name, find the:
1. The number of columns.
2. Column names.
3. Column types.

I find two solutions might work:

**Solution1**
Reference from the `dynamic_scan_types.go`,
https://github.com/ClickHouse/clickhouse-go/blob/b92bc86861690ce4eb90be4f6c1918e31701bb40/examples/clickhouse_api/dynamic_scan_types.go#L41

Before insertion, run a select query, `select * from <TABLE_NAME> limit 0`, to retrieve the schema and construct the insertion payload accordingly.

Even I can cache the result, it amplifies read.

<br/>

**Solution2**
If I run `PrepareBatch` not specifying the columns, the batch object has the schema info I want, but it is not public.
So I try this:
```go
batch, _ := db.PrepareBatch(ctx, "insert into <TABLE_NAME>")

// Get the schema
rf := reflect.ValueOf(batch).Elem().FieldByName("block")
rf = reflect.NewAt(rf.Type(), unsafe.Pointer(rf.UnsafeAddr())).Elem()
cols := rf.Interface().(*proto.Block).Columns

// loop over `cols` to get the `Name()` and `ScanType()` of the columns.
// build the insertion payload and finish the batch. 
```

<hr/>
 
Both solutions might work. Could you tech me what's the recommended way?

**Comment by gingerwizard** [comment]
Currently, (1) is the best option - if you can cache this information, the read amplification should be minimal.

We have a new column-orienated API coming for faster reads - I'll see if can make (2) possible as a byproduct of this as will expose the Columns on rows so it may make sense to do so on a batch also.

**Comment by alanhe** [comment]
Thank you very much!
