### ISSUE TITLE
Flush batch cause panic

### ISSUE THREAD

**Issue by Qjawko** [ClickHouse/clickhouse-go#798]
### Issue description
Using Flush() method in clickhouse.Batch causes panic

### Error log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x895d0b]

goroutine 12 [running]:
github.com/ClickHouse/ch-go/proto.(*Buffer).PutUInt8(...)
	/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:97
github.com/ClickHouse/ch-go/proto.(*Buffer).PutByte(...)
	/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:82
github.com/ClickHouse/clickhouse-go/v2.(*connect).sendData(0xc000146270, 0xc00011e1c0?, {0x0, 0x0})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn.go:171 +0xcb
github.com/ClickHouse/clickhouse-go/v2.(*batch).Flush(0xc00014e280)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn_batch.go:165 +0x79
```

### Configuration
*OS:* `Alpine Linux 3.16`

*Interface:* `native`

*Go version:* 1.19

*ClickHouse Server version:* 22.9.3.18

**Comment by gingerwizard** [comment]
Are you attempting to reuse a batch after send? Can you share some Sample code?

**Comment by gingerwizard** [comment]
Reusing batches after send isn’t supported - see https://github.com/ClickHouse/clickhouse-go/issues/728

**Comment by Qjawko** [comment]
> Are you attempting to reuse a batch after send? Can you share some Sample code?

Here is my sample code
`	if err := c.batch.Append(
		/* some data */
	); err != nil {
		return fmt.Errorf("append to batch: %w", err)
	}

	c.leftRows--

	if c.leftRows == 0 {
		if err = c.batch.Flush(); err != nil {
			return fmt.Errorf("send batch: %w", err)
		}

		c.logger.Debug("send batch")
		c.leftRows = c.BatchCount
	}

	return nil
`

**Comment by Qjawko** [comment]
I think it's because of Flush() method, Flush doesn't close a batch but resets a buffer

**Comment by gingerwizard** [comment]
yes its not supposed to, you still need to issue a Send().

I should update examples but this [simple test](https://github.com/ClickHouse/clickhouse-go/blob/main/tests/flush_test.go#L76-L103) is a good usage

**Comment by Qjawko** [comment]
Still panicking with Send() method. 

Sample code 
```
if err := c.batch.Append(/* some data */); err != nil {
	return fmt.Errorf("append to batch: %w", err)
}

c.leftRows--
if c.leftRows == 0 {
	if err = c.batch.Send(); err != nil {
		return fmt.Errorf("send batch: %w", err)
	}

	c.batch, err = c.conn.PrepareBatch(context.Background(), batchQuery)
	if err != nil {
		return fmt.Errorf("reinit batch: %w", err)
	}

	c.logger.Debug("send batch")
	c.leftRows = c.BatchCount
}

return nil
```

Trace log 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x895d0b]

goroutine 66 [running]:
github.com/ClickHouse/ch-go/proto.(*Buffer).PutUInt8(...)
	/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:97
github.com/ClickHouse/ch-go/proto.(*Buffer).PutByte(...)
	/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:82
github.com/ClickHouse/clickhouse-go/v2.(*connect).sendData(0xc000406a90, 0xc0?, {0x0, 0x0})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn.go:171 +0xcb
github.com/ClickHouse/clickhouse-go/v2.(*batch).Send(0xc0003b0000)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn_batch.go:144 +0xe5
```

**Comment by gingerwizard** [comment]
Can you reproduce this with a test? we have a lot of tests that check flush for every type - ill add one now for uint8 but I doubt this is the issue.

To be clear, you can't call Send more than once.

Call flush each time and Send once you've finished with the batch. Once you've called Send you can't reuse the batch. See the example I linked.

**Comment by gingerwizard** [comment]
Note how we issue a flush in the loop and send at end.

```
func TestIntFlush(t *testing.T) {
	conn, err := GetNativeConnection(nil, nil, &clickhouse.Compression{
		Method: clickhouse.CompressionLZ4,
	})
	ctx := context.Background()
	require.NoError(t, err)
	defer func() {
		conn.Exec(ctx, "DROP TABLE IF EXISTS int_flush")
	}()
	const ddl = `
		CREATE TABLE int_flush (
			  Col1 UInt8
		) Engine MergeTree() ORDER BY tuple()
		`
	require.NoError(t, conn.Exec(ctx, ddl))
	batch, err := conn.PrepareBatch(ctx, "INSERT INTO int_flush")
	require.NoError(t, err)
	vals := [1000]uint8{}

	for i := 0; i < 1000; i++ {
		vals[i] = uint8(i)
		require.NoError(t, batch.Append(vals[i]))
		if i%100 == 0 {
			require.NoError(t, batch.Flush())
		}
	}
	batch.Send()
	rows, err := conn.Query(ctx, "SELECT * FROM int_flush")
	require.NoError(t, err)
	i := 0
	for rows.Next() {
		var col1 uint8
		require.NoError(t, rows.Scan(&col1))
		assert.Equal(t, vals[i], col1)
		i += 1
	}
}
```

**Comment by Qjawko** [comment]
> Can you reproduce this with a test? we have a lot of tests that check flush for every type - ill add one now for uint8 but I doubt this is the issue.
Will do it tomorrow

**Comment by gingerwizard** [comment]
@Qjawko were you able to get this reproducible with a test?

**Comment by gingerwizard** [comment]
reported in #815 also

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xed7aab]

github.com/ClickHouse/ch-go/proto.(*Buffer).PutUInt8(...)
        /root/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:97
github.com/ClickHouse/ch-go/proto.(*Buffer).PutByte(...)
        /root/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:82
github.com/ClickHouse/clickhouse-go/v2.(*connect).sendData(0xe000890750, 0xdb8832f320?, {0x0, 0x0})
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn.go:171 +0xcb
github.com/ClickHouse/clickhouse-go/v2.(*connect).sendQuery(0xe000890750, {0xc0a4931040, 0xca}, 0xc3945b1550)
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn_send_query.go:46 +0x6b8
github.com/ClickHouse/clickhouse-go/v2.(*connect).prepareBatch(0xe000890750, {0x1454ba0?, 0xc0000460c8}, {0xc0b5e26270?, 0xa17087e66cba3d49?}, 0xde06cc2860)
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn_batch.go:45 +0x2c5
github.com/ClickHouse/clickhouse-go/v2.(*clickhouse).PrepareBatch(0xdd41bec4a0, {0x1454ba0, 0xc0000460c8}, {0xc0b5e26270, 0xc3})
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/clickhouse.go:150 +0x99
```

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-go/issues/812 might be related.

**Comment by moming00** [comment]
> reported in #815 also by @moming00
> 
> ```
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xed7aab]
> 
> github.com/ClickHouse/ch-go/proto.(*Buffer).PutUInt8(...)
>         /root/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:97
> github.com/ClickHouse/ch-go/proto.(*Buffer).PutByte(...)
>         /root/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:82
> github.com/ClickHouse/clickhouse-go/v2.(*connect).sendData(0xe000890750, 0xdb8832f320?, {0x0, 0x0})
>         /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn.go:171 +0xcb
> github.com/ClickHouse/clickhouse-go/v2.(*connect).sendQuery(0xe000890750, {0xc0a4931040, 0xca}, 0xc3945b1550)
>         /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn_send_query.go:46 +0x6b8
> github.com/ClickHouse/clickhouse-go/v2.(*connect).prepareBatch(0xe000890750, {0x1454ba0?, 0xc0000460c8}, {0xc0b5e26270?, 0xa17087e66cba3d49?}, 0xde06cc2860)
>         /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn_batch.go:45 +0x2c5
> github.com/ClickHouse/clickhouse-go/v2.(*clickhouse).PrepareBatch(0xdd41bec4a0, {0x1454ba0, 0xc0000460c8}, {0xc0b5e26270, 0xc3})
>         /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/clickhouse.go:150 +0x99
> ```

the issue randomly happens when doing a massive concurent test, will try to collect more info. But panic at PrepareBatch is little bit confusing.

**Comment by vnazarenko** [comment]
I'm getting the same during `.Send()`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14a260b]

goroutine 1 [running]:
github.com/ClickHouse/ch-go/proto.(*Buffer).PutUInt8(...)
	/Users/vnazarenko/code/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:97
github.com/ClickHouse/ch-go/proto.(*Buffer).PutByte(...)
	/Users/vnazarenko/code/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:82
github.com/ClickHouse/clickhouse-go/v2.(*connect).sendData(0xc0004f15f0, 0x17c27e0?, {0x0, 0x0})
	/Users/vnazarenko/code/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn.go:171 +0xcb
github.com/ClickHouse/clickhouse-go/v2.(*batch).Send(0xc0006a6550)
	/Users/vnazarenko/code/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn_batch.go:148 +0x12d
main.(*CassandraUsersIterator).IterateUsersInBatchesCh(0xc00030fd50, 0xc0001a2008?, 0xc00063fdf8?, 0x8000000000000000)
	/Users/vnazarenko/code/go/src/gitlab.com/ipl/cacheinfo/cmd/cache_users_iterator/clickhouse_saver.go:306 +0x72d
main.main()
	/Users/vnazarenko/code/go/src/gitlab.com/ipl/cacheinfo/cmd/cache_users_iterator/main.go:188 +0x986
```

**Comment by gingerwizard** [comment]
@vnazarenko version?

**Comment by gingerwizard** [comment]
@Qjawko, @moming00 also version please of client

**Comment by gingerwizard** [comment]
nvm i see in exception path v2.3.0 for all.

**Comment by gingerwizard** [comment]
@vnazarenko any chance you could be calling `Send` twice? are you using `flush`? any test case?

**Comment by gingerwizard** [comment]
Ok i can see potentially how this happens. I'm going to PR and release 2.4.0. If all effected could upgrade and report back.

**Comment by gingerwizard** [comment]
Released v2.4.0 please test and report back. I still can't see how this can occur, provided the user:

1. Doesn't try to reuse a batch after `Send`
2. Doesn't share batches across multiple go routines.
3. Calls `Send` only once.

If someone has a test case that would be hugely appreciated. Changes in 2.4.0 may inadvertently fix so please test.

**Comment by vnazarenko** [comment]
I found my problem, due to my logging( to separate file) i missed that i got type conversion errors for all appended batch rows. So it was kinda empty, and that's why there was panic with `nil pointer dereference` but i think there should be some error notifying that batch is empty ...

**Comment by gingerwizard** [comment]
hmm, good catch. I think there is some other trappy behavior here - 

1. empty batch causes panic - this should just do nothing. Null op. 
2. Calling `Send` twice or after an error on `Send` shouldn't panic
3. Reuse of batch after `Send` shouldn't panic.

Protecting against these will probably help a lot of the reports here.

**Comment by scottix** [comment]
I am new to this library and ran into this error as well.

It turns out I had the wrong data types in append.

I feel we should avoid the panic and give an error when something is not right, I just checked 2.4.1 and still get a panic if the wrong datatype is sent.

**Comment by gingerwizard** [comment]
Ok this reproduces, as @scottix points out its not the empty batch that is the issue but more a failed append curropts the batch entirely.

```
func Test798(t *testing.T) {
	var (
		conn, err = clickhouse_tests.GetConnection("issues", clickhouse.Settings{
			"max_execution_time": 60,
		}, nil, &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		})
	)
	ctx := context.Background()
	require.NoError(t, err)
	const ddl = `
			CREATE TABLE test_issue_798 (
				  Col1 Bool
				, Col2 Bool
				, Col3 Array(Bool)
			) Engine MergeTree() ORDER BY tuple()
		`
	defer func() {
		conn.Exec(ctx, "DROP TABLE IF EXISTS test_issue_798")
	}()
	require.NoError(t, conn.Exec(ctx, ddl))
	batch, err := conn.PrepareBatch(ctx, "INSERT INTO test_issue_798")
	require.NoError(t, err)
	require.NoError(t, batch.Append(true, false, []bool{true, false, true}))
	require.NoError(t, batch.Send())
	// test resend
	require.ErrorIs(t, batch.Send(), clickhouse.ErrBatchAlreadySent)
	batch, err = conn.PrepareBatch(ctx, "INSERT INTO test_issue_798")
	require.NoError(t, err)
	// test empty batch
	require.NoError(t, batch.Send())
	batch, err = conn.PrepareBatch(ctx, "INSERT INTO test_issue_798")
	// append invalid batch
	require.Error(t, batch.Append("true", false, []bool{true, false, true}))
	// send invalid batch
	require.NoError(t, batch.Send())
}
```

**Comment by gingerwizard** [comment]
Two possible approaches here:

1. The Append of invalid data invalidates the batch and `Send()` returns an error. This is easy and would be better than a panic.
2. The Append of invalid data fails but the batch is still valid - `Send()` will this succeed. This is trickier as columns are added one by one. If the error occurs due to a column other than the first, we have to undo the previous changes. I suspect this isn't trivial as it will mean reversing the changes to the buffer. We could check to see all values are valid beforehand - this will incur an overhead though.

**Comment by gingerwizard** [comment]
Will release 2.4.2 this week to address this. Thanks for everyone's patience.

**Comment by moming00** [comment]
@gingerwizard, is clickhouse connection a concurrent safe object?

we are using ch-go in the following pattern, and is frequently seeing  segmentation violation error with latest release.
`
func writeRows(prepareSQL string, rows model.Rows, conn clickhouse.Conn) (err error) {
	var batch driver.Batch
	if batch, err = conn.PrepareBatch(context.Background(), prepareSQL)
	defer func() {
		_ = batch.Abort()
	}()
	for _, row := range rows {
		batch.Append((*row)...)
	}
	return err = batch.Send()
}

func Run() {
	...
	conn = clickhouse.Open(&sc.opts)
	todo, done := int64(len(items)), int64(-1)
	var wg sync.WaitGroup
	wg.Add(10)
	for i := 0; i < 10; i++ {
		go func() {
			for {
				index := atomic.AddInt64(&done, 1)
				if index >= todo {
					wg.Done()
					break
				}
				writeRows(items[index].sql, items[index].rows, conn)
				items[index] = nil
			}
		}()
	}
	wg.Wait()
	...
}
`

**Comment by moming00** [comment]
> @gingerwizard, is clickhouse connection a concurrent safe object?
> 
> we are using ch-go in the following pattern, and is frequently seeing segmentation violation error with latest release.
> 
> ```
> func writeRows(prepareSQL string, rows model.Rows, conn clickhouse.Conn) (err error) {
> 	var batch driver.Batch
> 	if batch, err = conn.PrepareBatch(context.Background(), prepareSQL)
> 	defer func() {
> 		_ = batch.Abort()
> 	}()
> 	for _, row := range rows {
> 		batch.Append((*row)...)
> 	}
> 	return err = batch.Send()
> }
> 
> func Run() {
> 	...
> 	conn = clickhouse.Open(&sc.opts)
> 	todo, done := int64(len(items)), int64(-1)
> 	var wg sync.WaitGroup
> 	wg.Add(10)
> 	for i := 0; i < 10; i++ {
> 		go func() {
> 			for {
> 				index := atomic.AddInt64(&done, 1)
> 				if index >= todo {
> 					wg.Done()
> 					break
> 				}
> 				writeRows(items[index].sql, items[index].rows, conn)
> 				items[index] = nil
> 			}
> 		}()
> 	}
> 	wg.Wait()
> 	...
> }
> ```

Attaching some of the panic log for your reference:
```
goroutine 242 [running]:
github.com/ClickHouse/ch-go/proto.(*Buffer).PutUVarInt(...)
        /root/go/pkg/mod/github.com/!click!house/ch-go@v0.50.0/proto/buffer.go:72
github.com/ClickHouse/ch-go/proto.(*Buffer).PutLen(...)
        /root/go/pkg/mod/github.com/!click!house/ch-go@v0.50.0/proto/buffer.go:87
github.com/ClickHouse/ch-go/proto.(*Buffer).PutString(...)
        /root/go/pkg/mod/github.com/!click!house/ch-go@v0.50.0/proto/buffer.go:92
github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Query).Encode(0xc8b1f876c0?, 0x0?, 0xd4b5?)
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.4.2/lib/proto/query.go:45 +0xb6
github.com/ClickHouse/clickhouse-go/v2.(*connect).sendQuery(0xc8b5dfd6c0, {0xccc644c750, 0xca}, 0xc6d4cfe420)
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.4.2/conn_send_query.go:38 +0x5eb
github.com/ClickHouse/clickhouse-go/v2.(*connect).prepareBatch(0xc8b5dfd6c0, {0x14fd3a0?, 0xc0000460d8}, {0xc000033c70?, 0x0?}, 0xc9a8448d20)
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.4.2/conn_batch.go:55 +0x325
github.com/ClickHouse/clickhouse-go/v2.(*clickhouse).PrepareBatch(0xc5c29fe8c0, {0x14fd3a0, 0xc0000460d8}, {0xc000033c70, 0xc3})
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.4.2/clickhouse.go:152 +0x99
github.com/housepower/clickhouse_sinker/output.writeRows({0xc000033c70, 0xc3}, {0xcad8100000, 0x10001, 0x6e65757165735f39?}, 0x0, 0xf, {0x1509830, 0xc5c29fe8c0})
        /usr/local/src/sinker/clickhouse_sinker/output/clickhouse_util.go:36 +0xb6
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf202c4]

goroutine 187 [running]:
github.com/ClickHouse/ch-go/proto.(*Buffer).PutUInt8(...)
        /root/go/pkg/mod/github.com/!click!house/ch-go@v0.50.0/proto/buffer.go:97
github.com/ClickHouse/ch-go/proto.(*Buffer).PutByte(...)
        /root/go/pkg/mod/github.com/!click!house/ch-go@v0.50.0/proto/buffer.go:82
github.com/ClickHouse/clickhouse-go/v2.(*connect).sendQuery(0xc536af1a00, {0xc49c2be8f0, 0xca}, 0xc96edaa160)
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.4.2/conn_send_query.go:28 +0x104
github.com/ClickHouse/clickhouse-go/v2.(*connect).prepareBatch(0xc536af1a00, {0x14fd3a0?, 0xc000198000}, {0xc0002e2d00?, 0x0?}, 0xc96fffebf0)
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.4.2/conn_batch.go:55 +0x325
github.com/ClickHouse/clickhouse-go/v2.(*clickhouse).PrepareBatch(0xc4445f6f80, {0x14fd3a0, 0xc000198000}, {0xc0002e2d00, 0xc3})
        /root/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.4.2/clickhouse.go:152 +0x99
github.com/housepower/clickhouse_sinker/output.writeRows({0xc0002e2d00, 0xc3}, {0xcab78cc000, 0x10001, 0x363?}, 0x0, 0xf, {0x1509830, 0xc4445f6f80})
        /usr/local/src/sinker/clickhouse_sinker/output/clickhouse_util.go:36 +0xb6
```

**Comment by gingerwizard** [comment]
Yes it should be safe to use in different threads....this reproduces your issue..


```
func writeRows(prepareSQL string, rows [][]interface{}, conn clickhouse.Conn) (err error) {
	batch, err := conn.PrepareBatch(context.Background(), prepareSQL)
	defer func() {
		_ = batch.Abort()
	}()
	for _, row := range rows {
		batch.Append(row...)
	}
	return batch.Send()
}

func Test798Concurrent(t *testing.T) {

	var (
		conn, err = clickhouse_tests.GetConnection("issues", clickhouse.Settings{
			"max_execution_time": 60,
		}, nil, &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		})
	)
	ctx := context.Background()
	const ddl = `
			CREATE TABLE test_issue_798 (
				  Col1 Bool
				, Col2 Bool
			) Engine MergeTree() ORDER BY tuple()
		`
	defer func() {
		conn.Exec(ctx, "DROP TABLE IF EXISTS test_issue_798")
	}()
	require.NoError(t, conn.Exec(ctx, ddl))

	require.NoError(t, err)
	todo, done := int64(10000), int64(-1)
	var wg sync.WaitGroup
	wg.Add(10)
	for i := 0; i < 10; i++ {
		go func() {
			for {
				index := atomic.AddInt64(&done, 1)
				if index >= todo {
					wg.Done()
					break
				}
				writeRows("INSERT INTO test_issue_798", [][]interface{}{{true, false}, {false, true}}, conn)
			}
		}()
	}
	wg.Wait()

}
```

**Comment by gingerwizard** [comment]
This is a different issue to the others reported I think - the fact it occurs on prepareBatch not when a batch is reused after an error. I think this happens if the connection to ClickHouse errors on any single go routine - this is causing a segmentation fault on other routines. trying to figure out how this happens.

**Comment by gingerwizard** [comment]
Ok can see a few places this could happen:

1. Calling append after an error on the batch - ill add a guard
2. the issue here - a race condition with `Abort` and `Send`. If I remove the `Abort` call above it succeeds.
_I think_ this is happening:
 - `Send()` executes. and returns. Either the connection is released by `Abort` or `Send`.

i.e.

```
func (b *batch) Send() (err error) {
	defer func() {
		b.sent = true
		b.release(err)
	}()
```
or

```
func (b *batch) Abort() error {
	defer func() {
		b.sent = true
		b.release(os.ErrProcessDone)
	}()
```

- A release has been called and a new batch picks up the connection and calls acquire setting `conn.released` to false.
- The connections is released again by the defer of the `Abort` or `Send`. This is bad. bad stuff happens.

**Comment by moming00** [comment]
good catch, I'll try to refine the abort() part and test if this is the problem =)

**Comment by gingerwizard** [comment]
Its ok ill do a PR and release shortly. Please test.

**Comment by gingerwizard** [comment]
@moming00 https://github.com/ClickHouse/clickhouse-go/pull/833

**Comment by gingerwizard** [comment]
Done v.2.4.3 is out. Let me know if this doesn't resolve the issue @moming00
