### ISSUE TITLE
Speed-up methods with context

### ISSUE THREAD

**Issue by AlekSi** [ClickHouse/clickhouse-go#80]
`Query` is slower than `QueryContext` because the former one converts arguments: https://github.com/kshvakov/clickhouse/blob/81a24df15f5b96db6bd2558a7894dd7647dcd67d/stmt.go#L69-L75

I propose to make it a general rule. Then some other places should be changed, for example, `Exec` should convert arguments, not `ExecContext`.
https://github.com/kshvakov/clickhouse/blob/81a24df15f5b96db6bd2558a7894dd7647dcd67d/stmt.go#L31-L41

**Comment by kshvakov** [comment]
Done
