### ISSUE TITLE
tx.Prepare: 202: Too many concurrent requests. Max: 200

### ISSUE THREAD

**Issue by ParvizBoymurodov** [ClickHouse/clickhouse-go#819]
### Issue description
Tell us what should happen and what happens instead
Hello!

I'm working with Click House v1 and I'm about to do a batch insert, but I'm getting the error 
tx.Prepare: 202: Too many concurrent requests. Max: 200

There was such a mistake before.
tx.Prepare code: 202, message: Too many concurrent requests. Max: 100

Then in the ClickHouse settings
did
max_concurrent_queries = 200

But again the same error.

What could be the problem?
### Example code
```go
If possible, please enter some example code here to reproduce the issue.
```

### Error log
```
If you have an error log, please paste it here.
```

### Configuration
*OS:*

*Interface:* E.g. `native`, `database/sql`

*Driver version:*
v1
*Go version:* run `go version` in your console
1.17
*ClickHouse Server version:*

**Comment by gingerwizard** [comment]
Hi, v1 is no longer supported but we'll try to help.

Can you reproduce this issue with a simple script? Are you sure other user limits are not applied? How are you seeing this setting - can you share you clickhouse config?

**Comment by gingerwizard** [comment]
Closing. This is a clickhouse/clickhouse issue. Raise there and/or upgrade to a supported client.
