### ISSUE TITLE
An element with a value of nil in the map will have an error

### ISSUE THREAD

**Issue by ACV-er** [ClickHouse/clickhouse-go#823]
### Issue description
when I insert multiple rows, and have a field is nil in json, maybe get error

### Example code
```go
If possible, please enter some example code here to reproduce the issue.
```

### Error log
```
clickhouse [Encode]:  mismatched len of columns and  various random errors
```

### Configuration
*OS:* linux & macos

*Driver version: v2.20

*Go version: go1.19.1

*ClickHouse Server version: 22.9.3.18

**Comment by gingerwizard** [comment]
Fixed in 2.4.2
