### ISSUE TITLE
Date column parsing withZone error for date 1970-01-01

### ISSUE THREAD

**Issue by schorsch** [ClickHouse/clickhouse-go#832]
### Issue description
I am setting the default value for date cols to the string "1970-01-01", to prevent NULL values, since the doc state that NULLs may not be the best to have. After the withZone update i get an error about the date being out of bounds probably because my local TZ is used (CET)

I could simply add a zone info to the date and be done with it, but i do have a couple of other questions and reflections of the code.

1. Why does one need to have a zone info for a date? (Besides golang time.parse offering that feature)
2. I am using the [Append method with a slice of strings](https://github.com/ClickHouse/clickhouse-go/blob/main/lib/column/date.go#L129) and have no chance to add an ""empty string, letting the columns default value kick in. But for a slice of string pointers or other value types such is supported.
3. I am parsing CSV values and use strings for date columns to prevent extensive parsing and gain speed. I wonder why there is no way to prevent date/datetime parsing at all. I mean if someone deliberately chooses to use strings for dates he should know what he is doing. Aren't Dates transferred as strings anyway? In [AppendRow](https://github.com/ClickHouse/clickhouse-go/blob/main/lib/column/date.go#L211) there is at least a way to add a custom format, but still forces me to invent a new DateAsSting Type and also does not allow empty strings.
4. I dont really know how to deal with it atm. Would it make sense to implement costom date/datetime column types based on the column.Interface?

**Comment by gingerwizard** [comment]
What type is your column? If its `date` then you shouldn't need to specify a timezone. If no tz is specified we assume the local tz.

Dates are sent as uint16 clickhouse so they must be offset based on their tz.

Some context https://github.com/ClickHouse/clickhouse-go/issues/693

**Comment by gingerwizard** [comment]
You can just implement a custom date struct and implement fmt.Stringer. We will then use this.

**Comment by schorsch** [comment]
The column type i am using is: Date with a DEFAULT of '1970-01-01' . 

In my go code i am now using a default value of "1970-01-01 -00:00" to prevent out-of bounds warnings from[ func dateOverflow](https://github.com/ClickHouse/clickhouse-go/blob/main/lib/column/date.go#L228) receiving a date value with my local TZ ( e.g "1970-01-01 -02:00" ).

I may switch to use a custom struct or a time based slice, wich allows me to prevent some string parsing.

Dates are sent as uint16 -> OK, I was looking at the [native protocol columns](https://clickhouse.com/docs/en/native-protocol/columns) and did not find a date col info, but i found it in the [data-types spec](https://clickhouse.com/docs/en/sql-reference/data-types/date)

Closing the ticket, as i found a way around
