### ISSUE TITLE
insert into table (`field1`,`field2`) VALUES ('a', 'b') -> "column `field1` is not present"

### ISSUE THREAD

**Issue by wizzard0** [ClickHouse/clickhouse-go#848]
### Issue description
Expected: 1 row inserted
What happens: 
https://github.com/ClickHouse/clickhouse-go/blob/main/conn_http_batch.go#L92 `column %s is not present in the table %s`

Looks like it's the cousin of #715 and can be fixed by patching line 48 to
```
rColumns[i] = strings.TrimSuffix(strings.TrimPrefix(strings.TrimSpace(rColumns[i]),"`"),"`")
```
if we're to continue with this crazy approach to parsing %)

### Example code
```go
stmt := tx.PrepareContext(context.TODO(), "insert into table (`field1`,`field2`) VALUES ('a', 'b')")
```

### Configuration
*OS:* macOS

*Interface:* `database/sql`

*Driver version:* 2.4.3

*Go version:* go1.19.4 darwin/arm64

*ClickHouse Server version:* 22.8.1.1316

**Comment by jkaflik** [comment]
My bad. This was already fixed in #829 and already reported in #828. Closing it.

**Comment by wl506** [comment]
@jkaflik   v2.6.2   This error still exists

**Comment by jkaflik** [comment]
@wl506 can you post a minmalistic code snippet that reproduces this error?
