### ISSUE TITLE
Problem with dates

### ISSUE THREAD

**Issue by joanbalaguero** [ClickHouse/clickhouse-go#87]
I have a table with a field named REQUEST_DATE, that it’s a Date.

When I query this table using clickhouse client:

SELECT REQUEST_DATE, COUNT() 
FROM WBEDS_AVAIL_VIEW 
GROUP BY REQUEST_DATE

┌─REQUEST_DATE─┬──COUNT()─┐
│   2018-01-07 │ 76178366 │
│   2018-01-08 │ 25202906 │
└──────────────┴──────────┘

When I try to get this data from go:

var data time.Time
var count int

rows, err := db.Query("SELECT REQUEST_DATE, COUNT() FROM DM_TRPLAN.WBEDS_AVAIL_VIEW GROUP BY REQUEST_DATE")
if err != nil { return err }
defer rows.Close() }

for rows.Next() {
   rows.Scan(&data, &count)
   log.Printf("data: %v, count: %v", data, count)
}

This is the output:
2018/01/05 00:55:13 data: 2018-01-06 16:00:00 -0800 PST, count: 76178366
2018/01/05 00:55:13 data: 2018-01-07 16:00:00 -0800 PST, count: 25202906 

Since this server is located nearby San Francisco, it’s taking the date and converting it to pacific time (PST).

Is there anyway to get the date as it is in the DDBB?

**Comment by kshvakov** [comment]
At the moment, the work with dates is not implemented well, in the near future I will redesign it

**Comment by crzmshrmffs** [comment]
It would be great also to separate types Date and DateTime from each other. I select dates from db and want to read it to string instead of time.Time. Db returns string "2006-01-02" but I got "2006-01-02T00:00:00Z" instead.

**Comment by kshvakov** [comment]
Database doesn't return String, database returns Int16 (count of days since 1970)

**Comment by kshvakov** [comment]
Right now you can use DateTime with Timesone types
