### ISSUE TITLE
Parameter for column not supported / wrong query response

### ISSUE THREAD

**Issue by makeavish** [ClickHouse/clickhouse-go#870]
I want to set parameters on column names in a select query but it is not supported.
Example Query: `SELECT toStartOfInterval(timestamp, INTERVAL 50 minute) as time, responseStatusCode as groupBy,  count(*) as value  FROM signoz_traces.distributed_signoz_index_v2 GROUP BY time, responseStatusCode as groupBy ORDER BY time`

Here I want to replace responseStatusCode column with a parameter as it can be any column like serviceName or any other user input. I tried using bind parameters using `$1, $2...` and also `@param` and also clickhouse query parameters `{name:type}` introduced in v2.5.0. But none of them work.

Sample code on query formation:
```
query = fmt.Sprintf("SELECT toStartOfInterval(timestamp, INTERVAL %d minute) as time, {groupByVar:String} as groupBy, %s FROM %s.%s WHERE timestamp >= {timestampL:String} AND timestamp <= {timestampU:String}  GROUP BY time, {groupByVar:String} as groupBy ORDER BY time", queryParams.StepSeconds/60, aggregation_query, r.TraceDB, r.indexTable)

args := []interface{}{clickhouse.Named("timestampL", strconv.FormatInt(queryParams.Start.UnixNano(), 10)), clickhouse.Named("timestampU", strconv.FormatInt(queryParams.End.UnixNano(), 10))}
args = append(args, clickhouse.Named("groupByVar", queryParams.GroupBy))

err := r.db.Select(ctx, &SpanAggregatesDBResponseItems, query, args...)
```

Expected correct response:

```
┌────────────────time─┬─groupBy─┬─value─┐
│ 2023-01-04 09:50:00 │ 500     │     8 │
│ 2023-01-04 09:50:00 │         │     5 │
│ 2023-01-04 09:50:00 │ 200     │     2 │
│ 2023-01-11 08:30:00 │ 404     │     2 │
│ 2023-01-11 08:30:00 │         │     2 │
│ 2023-01-11 08:30:00 │ 200     │     2 │
│ 2023-01-11 09:20:00 │         │   105 │
│ 2023-01-11 09:20:00 │ 500     │     2 │
│ 2023-01-11 09:20:00 │ 404     │     1 │
│ 2023-01-11 09:20:00 │ 304     │    17 │
│ 2023-01-11 09:20:00 │ 200     │    30 │
│ 2023-01-11 20:10:00 │         │    11 │
│ 2023-01-11 20:10:00 │ 500     │     2 │
│ 2023-01-11 20:10:00 │ 200     │    20 │
│ 2023-01-11 21:00:00 │ 200     │     8 │
│ 2023-01-11 21:00:00 │         │     4 │
└─────────────────────┴─────────┴───────┘
```

Current response:

```
┌────────────────time─┬─────groupBy───────────┬─value─┐
│ 2023-01-11 09:50:00 │ responseStatusCode    │     6 │
│ 2023-01-11 09:50:00 │responseStatusCode     |   155 │
│ 2023-01-11 20:10:00 │ responseStatusCode    │    33 │
│ 2023-01-11 21:30:00 │ responseStatusCode    │    12 │
└─────────────────────┴───────────────────────┴───────┘
```

**Comment by jkaflik** [comment]
Hi @makeavish 

Thanks for raising this issue.
If you look here: https://clickhouse.com/docs/en/interfaces/cli/#cli-queries-with-parameters It's expected column, database, or any other identifiers has to be mapped with an `Identifier` type:
> It's also possible to pass table, database, column names as a parameter, in that case you would need to use Identifier as a data type.

Indeed, I can confirm there is an issue mapping query parameter values to `Identifier` type. I need to follow up on this by more extensive debugging.

**Comment by jkaflik** [comment]
@makeavish sorry for the delay, but I found Identifier type in query parameters is working as expected. The problem is with my test case implemented it wrongly.
Please have a look at this MR: https://github.com/ClickHouse/clickhouse-go/pull/875
There is a test case with the expected way of providing identifiers via query parameters. I will add some example/documentation to this later.
