### ISSUE TITLE
Can't acquire new connection once MaxOpenConns is reached

### ISSUE THREAD

**Issue by lazywei** [ClickHouse/clickhouse-go#873]
### Issue description
After finishing `MaxOpenConns` connections (all succeeded), we're unable to acquire new connection nor any connection got released or created. All we get is below error msg for *every single new query*
```
clickhouse: acquire conn timeout. you can increase the number of max open conn or the dial timeout
```

### Example code
```go
	conn, err = clickhouse.Open(&clickhouse.Options{
		Addr: []string{"foo.bar:9000"},
		Auth: clickhouse.Auth{
			...
		},
		DialTimeout:     time.Second,
		MaxOpenConns:    50,
		ConnMaxLifetime: 10 * time.Minute,
	})
// ...
	loadChan := make(chan LoadSpec, 1119)
	go genLoad(ctx, loadChan)
	go consumeLoad(ctx, loadChan)
// ...
```

and inside the `consumeLoad` we have something like
```go
        // with some proper goroutine concurrency limiting
	for {
		select {
		case <-ctx.Done():
			break loop
		case load := <-loadChan:
                       go func() {
                           conn.Query(ctxWithDeadline, getQueryFrom(load))
                       }()
                 }
         }
```

### Error log
```
clickhouse: acquire conn timeout. you can increase the number of max open conn or the dial timeout
```

Also querying our own counters shows that the succeeded requests are exactly the same number as `MaxOpenConns`
```
$ curl localhost:8087/metrics
ch_query_benchmark_req_total{name="case-1-top-100-1h",status="nok"} 156
ch_query_benchmark_req_total{name="case-1-top-100-1h",status="ok"} 50
```

### Configuration
*OS:* MacOS on my laptop, `clickhouse-server` docker image on AWS as server

*Interface:* `native`

*Driver version:* 2.5.1

*Go version:* `go version go1.19.3 darwin/arm64`

*ClickHouse Server version:* `22.11.2 revision 54460`

**Comment by jkaflik** [comment]
Hi @lazywei 

I attempt to reproduce this issue with this code:
```go
package issues

import (
	"context"
	"github.com/ClickHouse/clickhouse-go/v2"
	clickhouse_tests "github.com/ClickHouse/clickhouse-go/v2/tests"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"sync"
	"testing"
	"time"
)

func Test873(t *testing.T) {
	ctx := context.Background()

	env, err := clickhouse_tests.GetTestEnvironment(testSet)
	require.NoError(t, err)

	opts := clickhouse_tests.ClientOptionsFromEnv(env, clickhouse.Settings{})
	opts.MaxOpenConns = 1
	opts.DialTimeout = time.Second
	conn, err := clickhouse.Open(&opts)
	require.NoError(t, err)

	var wg sync.WaitGroup
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func(num int) {
			defer wg.Done()

			_, err := conn.Query(ctx, "SELECT 1")
			assert.NoError(t, err, "conn num %d", num)
		}(i)
	}

	wg.Wait()
}
```

(initialize functions are part of client test framework: https://github.com/ClickHouse/clickhouse-go/blob/0c79b0fd50ee848198dde5a3392850820974ee6f/tests)

This code run just fine. Once the query finishes the connection is released.
When I change line 32 to `_, err := conn.Query(ctx, "SELECT sleep(3)")` and make every query sleep for 3 seconds, then in fact I am not able to acquire any new connection:
```
clickhouse: acquire conn timeout. you can increase the number of max open conn or the dial timeout
```

Can you check if your query does not take longer than the connection pool is able to pick up? What is your use case?

**Comment by jkaflik** [comment]
@lazywei thanks for providing me with more details.

I don't know how far your code example is accurate, but what I see is:
```
                       go func() {
                           conn.Query(ctxWithDeadline, getQueryFrom(load))
                       }()
```
the problem here is `conn.Query` does not block until the query is done and the connection is released.
For an expected behavior, you should make sure your implementation goes over the rows results.

```
                       go func() {
                           rows, err := conn.Query(ctxWithDeadline, getQueryFrom(load))
                           if err != nil {
                               handleErr(err)
                           }
                           defer rows.Close()
                           
                           for rows.Next() {
                               // ...
                           }
                       }()
```

CH protocol operates on the block and until you read all blocks returned by the server followed with EOF, the connection is not released.

However, I believe your use case is not reading data out of CH, but data ingestion. In that case, you might be interested with [.Exec](https://github.com/ClickHouse/clickhouse-go/blob/0c79b0fd50ee848198dde5a3392850820974ee6f/examples/std/exec.go) function or [batch ingestion](https://github.com/ClickHouse/clickhouse-go/blob/0c79b0fd50ee848198dde5a3392850820974ee6f/examples/std/batch.go).

**Comment by jkaflik** [comment]
> the next call to conn.Query will be blocked by 1 second and then it will get dial timeout correct?

Yes, exactly. It's a client-side thing (not a socket timeout) and there is no attempt to open a conn. Timeout duration is set with `DialTimeout` option.

>  If we're having a lot of such dial timeout is that gonna create pressure on CH server? or these "pending" dialings will be handled on the client and will not go out to server at all?

Yes.

Hope this clarifies it a bit!
