### ISSUE TITLE
Options method for Conn

### ISSUE THREAD

**Issue by mayamika** [ClickHouse/clickhouse-go#877]
**Is your feature request related to a problem? Please describe.**
I want the ability to get Conn's Options that were passed to `clickhouse.Open`. Sometimes i need some information like Auth.Database to build queries. I can store that Options by myself, but i think it would be nice if i could retrieve that Options from some `Conn` method. 

**Describe the solution you'd like**
A method for `Conn` for retrieving `*Options`.

**Comment by jkaflik** [comment]
Hi @mayamika 
I am open to such change. Would you like to send your contribution?

**Comment by mayamika** [comment]
Ok, will send later.
