### ISSUE TITLE
The 2.6.0 release lacks the "v" prefix

### ISSUE THREAD

**Issue by rolinh** [ClickHouse/clickhouse-go#885]
### Issue description

The [v2.6.0 release](https://github.com/ClickHouse/clickhouse-go/releases/tag/2.6.0) was tagged as `2.6.0` instead of `v2.6.0`. As [documented](https://go.dev/ref/mod#versions):

> Each version starts with the letter v, followed by a semantic version.

Without the `v` prefix, Go tooling won't update to 2.6.0.

### Error log
```
$ go get github.com/ClickHouse/clickhouse-go/v2@latest
$ grep clickhouse-go go.mod
        github.com/ClickHouse/clickhouse-go/v2 v2.5.1
```

**Comment by jkaflik** [comment]
hi @rolinh 
Yeah, didn't play that well. Sorry! fixed

**Comment by rolinh** [comment]
Thanks!
