### ISSUE TITLE
Timeout on querying idle ClickHouse cloud instance

### ISSUE THREAD

**Issue by CamiloSierraH** [ClickHouse/clickhouse-go#890]
### Issue description
When you try to run queries and the ClickHouse instance is idling the code will not handle the error as expected. This will produce issues in integration as grafana.

### Error log
```
Jan 30 10:53:28 ERROR graph/schema.resolvers.go:2799 Could not get analytics summary {"error": "read: EOF", "errorVerbose": "read:
github.com/ClickHouse/ch-go/proto.(*Reader).ReadFulln /home/starptech/go/pkg/mod/github.com/!click!house/ch-go@v0.51.0/proto/reader.go:63
- EOF", "organizationSlug": "starptech", "environmentSlug": "cf9e95769kfbe49r5mjg", "actorID": "88638923-9601-4712-bb44-83c472e3c819", "resolver": "AnalyticsOverview"}
github.com/wundergraph/cloud/pkg/graph.(*queryResolver).AnalyticsOverview
```

### Configuration
You can reproduce this issue with the current version.

**Comment by jkaflik** [comment]
@CamiloSierraH, the solution for this will be to set dial timeout to a value that matches cloud instance activation time:

> Services usually take 20-30 seconds to restart after pausing.

Depending on the connection method, it's described in the client README.

We should default dial timeout to 30s (confirmed it's working on idle service). I will PR.

**Comment by StarpTech** [comment]
Hi, I'm the original author of the issue. Increasing the dial timeout is indeed a solution but it hides the real issue. Cold starts of 30s are super annoying, especially if you can't configure the threshold of inactivity. I know such instances are for development purposes but you only need to wait a few seconds until someone has to wait again 20 or more seconds to continue debugging the application. Cold starts of less than 10s would be ideal.

**Comment by jkaflik** [comment]
@StarpTech, that's the issue you face, which we should be addressing soon. My mitigation solution is only from a CH Cloud client's perspective. @CamiloSierraH, can you please help forward this issue to the respective team? Thank you
