### ISSUE TITLE
version 2.6.1 numeric bind conflict with column named like "$360_name"

### ISSUE THREAD

**Issue by WillMeng** [ClickHouse/clickhouse-go#905]
### Issue description
We have table_schema like this:

### Example code
```
CREATE TABLE default.text_local
(
    `chan_pub_id` Int64,

    `$360_name` Int64,

    `$360_call_num` Int64
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(data_date)
PRIMARY KEY chan_pub_id
ORDER BY chan_pub_id;

insert into default.text_local (chan_pub_id, `$360_name`,  `$360_call_num`) value (
1, 1,1)
```

### Error log
```
have no arg for $360 param
```

### Configuration
*OS: centos 7.9

*Interface:* clickhouse interface (formally native interface)

*Driver version: 2.6.1

*Go version:* 1.20

*ClickHouse Server version: 22.3

**Comment by jkaflik** [comment]
Hi @WillMeng 
The binding mechanism is not really supported since we have a CH native query parameters support.
Would you like to give it a try? Here is an example: https://github.com/ClickHouse/clickhouse-go/blob/main/examples/clickhouse_api/query_parameters.go

**Comment by jkaflik** [comment]
That's an interesting case. The binding mechanism has depreciated since we introduced CH native query parameters support.

 It gets disabled if you use native query parameters, but in your case, you are not interested in doing that.
 We can introduce an additional query/client option that forces disable binding. WDYT?

**Comment by WillMeng** [comment]
> Thank you.
1. What would you mean about "CH native query parameters support"?
2. "introduce an additional query/client option that forces disable binding", that is a good idea. 



> That's an interesting case. The binding mechanism has depreciated since we introduced CH native query parameters support.
> 
> It gets disabled if you use native query parameters, but in your case, you are not interested in doing that. We can introduce an additional query/client option that forces disable binding. WDYT?

**Comment by WillMeng** [comment]
@jkaflik

**Comment by jkaflik** [comment]
@WillMeng, there is a mechanism called query parameters natively supported by CH: https://clickhouse.com/docs/en/interfaces/cli#cli-queries-with-parameters

This doc is explaining how to use it with a CH CLI client. For a `clickhouse-go`, there is an example in repo: https://github.com/ClickHouse/clickhouse-go/blob/669fda2413a4d2233688a949ec9d5ebbb818c2b2/examples/std/query_parameters.go#L31-L30 

---

Actually, I found this issue unreproducable. Can you post a code snippet if possible? Here is how I reproduce it with a test:
```go
package issues

import (
	"context"
	"fmt"
	"github.com/ClickHouse/clickhouse-go/v2"
	clickhouse_tests "github.com/ClickHouse/clickhouse-go/v2/tests"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test905(t *testing.T) {
	var (
		conn, err = clickhouse_tests.GetConnection("issues", clickhouse.Settings{
			"max_execution_time": 60,
			"flatten_nested":     0,
		}, nil, &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		})
	)

	ctx := context.Background()
	require.NoError(t, err)
	env, err := clickhouse_tests.GetTestEnvironment(testSet)
	require.NoError(t, err)

	ddl := fmt.Sprintf("CREATE TABLE `%s`.`test_905` (`$360_name` String, `$360_call_num` Int32) Engine MergeTree() ORDER BY tuple()", env.Database)
	defer func() {
		conn.Exec(ctx, fmt.Sprintf("DROP TABLE IF EXISTS `%s`.`test_905`", env.Database))
	}()
	require.NoError(t, conn.Exec(ctx, ddl))

	err = conn.Exec(ctx, fmt.Sprintf("INSERT INTO `%s`.`test_905` (`$360_name`, `$360_call_num`) VALUES ('foo', 5)", env.Database))
	require.NoError(t, err)
}

```

**Comment by WillMeng** [comment]
You can change this code to `err = conn.Exec(ctx, fmt.Sprintf("INSERT INTO `%s`.`test_905` (`$360_name`, `$360_call_num`) VALUES ('foo', 5)", env.Database), 1)`, it alaways reproduce.

There is another way reproduce it.

`
err = exec(conn, "insert into default.text_local (chan_pub_id, `$360_name`,  `$360_call_num`) select chan_pub_id, `$360_name`,  `$360_call_num` from default.text_local")

func exec(conn driver.Conn, sql string, args ...interface{}) error {
	ctx := clickhouse.Context(context.Background(), clickhouse.WithSettings(clickhouse.Settings{
		// "max_block_size": 10,
	}), clickhouse.WithProgress(func(p *clickhouse.Progress) {
		// fmt.Println("progress: ", p.TotalRows)
	}))

	err := conn.Exec(ctx, sql, args)
	return err
}
`

**Comment by WillMeng** [comment]
@jkaflik Thank you

**Comment by WillMeng** [comment]
`err = conn.Exec(ctx, fmt.Sprintf("INSERT INTO `%s`.`test_905` (`$360_name`, `$360_call_num`) VALUES ($1, $2)", env.Database), 'foo', 5)`

**Comment by jkaflik** [comment]
@WillMeng thanks. I see what's the deal here.

This is only reproducible if you provide an args and have a positional bind. What I can suggest you to do, is to adapt your code to use [native query parameters](https://github.com/ClickHouse/clickhouse-go/pull/854):

```go
	execCtx := clickhouse.Context(ctx, clickhouse.WithParameters(clickhouse.Parameters{
		"name":    "foo",
		"callNum": "5",
	}))

	err = conn.Exec(execCtx, fmt.Sprintf("INSERT INTO `%s`.`test_905` (`$360_name`, `$360_call_num`) VALUES ({name:String}, {callNum:Int32})", env.Database))
```

or by using NamedArg:

```go
	err = conn.Exec(
		ctx,
		fmt.Sprintf("INSERT INTO `%s`.`test_905` (`$360_name`, `$360_call_num`) VALUES ({name:String}, {callNum:Int32})", env.Database),
		clickhouse.Named("name", "foo"),
		clickhouse.Named("callNum", "5"),
	)
```

---

Like I said, binding mechanism is no longer supported, so no further improvements are planned.

**Comment by WillMeng** [comment]
> @WillMeng thanks. I see what's the deal here.
> 
> This is only reproducible if you provide an args and have a positional bind. What I can suggest you to do, is to adapt your code to use [native query parameters](https://github.com/ClickHouse/clickhouse-go/pull/854):
> 
> ```go
> 	execCtx := clickhouse.Context(ctx, clickhouse.WithParameters(clickhouse.Parameters{
> 		"name":    "foo",
> 		"callNum": "5",
> 	}))
> 
> 	err = conn.Exec(execCtx, fmt.Sprintf("INSERT INTO `%s`.`test_905` (`$360_name`, `$360_call_num`) VALUES ({name:String}, {callNum:Int32})", env.Database))
> ```
> 
> or by using NamedArg:
> 
> ```go
> 	err = conn.Exec(
> 		ctx,
> 		fmt.Sprintf("INSERT INTO `%s`.`test_905` (`$360_name`, `$360_call_num`) VALUES ({name:String}, {callNum:Int32})", env.Database),
> 		clickhouse.Named("name", "foo"),
> 		clickhouse.Named("callNum", "5"),
> 	)
> ```
> 
> Also, you can consider using `conn.PrepareBatch` for ingestion. There is no need for binding/query parameters in that case.
> 
> Like I said, binding mechanism is no longer supported, so no further improvements are planned.

Thanks very much, I got it

**Comment by jkaflik** [comment]
@WillMeng, you are welcome. Feel free to reach out to me in case of any questions.
