### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [ClickHouse/clickhouse-go#907]
Hey folks!

I'm the founder of [CloudQuery](https://github.com/cloudquery/cloudquery) - open source high performance ELT framework in Go.

We recently shipped a ClickHouse destination to [CloudQuery](https://www.cloudquery.io/docs/plugins/destinations/clickhouse/overview). And have a few questions/ideas:

1) We would love to do a shared blog on how to ingest data with our open source framework to ClickHouse!
2) Are you interested (or heard users ask for it) for a ClickHouse source plugin? i.e syncing data from ClickHouse to other destinations/databases? If yes, We would love to help bootstrapping such a plugin as long as you can help us maintain it (as we usually maintain destinations ourselves but for sources we defer to the official vendors).

Cheers!
Yevgeny

**Comment by Ryado** [comment]
Hello Yevgeny 👋 ,
I'm part of the integrations team at ClickHouse, thank you for your message! 

It's great to see that CloudQuery supports ClickHouse as a destination now! we will definitely try it and share if we have feedback.
We will  also be happy to explore a shared blog together and coordinate this messaging , just ping me on ryadh[at]clickhouse.com and I'll make the relevant introductions cc. @gingerwizard .

Also, if you have some content already, it will be great if you can add CloudQuery to ClickHouse docs:
https://clickhouse.com/docs/en/integrations/
https://clickhouse.com/docs/en/integrations/data-ingestion/etl-tools

We can also help list it in the Cloud UI under:
https://clickhouse.cloud/integrations

Below the template used by the Cloud UI catalog + an example:
[template.md](https://github.com/ClickHouse/clickhouse-go/files/10767168/template.md)
[superset.md](https://github.com/ClickHouse/clickhouse-go/files/10767169/superset.md)

Thanks!

**Comment by yevgenypats** [comment]
Thanks @jkaflik ! Opened a PR here - https://github.com/ClickHouse/clickhouse-docs/pull/791

Would love to provide the template shortly as well for the Cloud UI catalog.

**Comment by jkaflik** [comment]
Thanks @Ryado, for engaging here. @yevgenypats, if anything else is needed from my side (clickhouse-go), I am happy to help you. Let me close this issue for now.
