### ISSUE TITLE
Expose progress metadata

### ISSUE THREAD

**Issue by arctica** [ClickHouse/clickhouse-go#92]
It would be very nice if your driver somehow could expose the progress metadata of a query. I saw in the code that it already handles the necessary part of the ClickHouse protocol (and logs the data when run in debug mode).

I am not sure how the API can expose the data but my first thought was to use a context.WithValue() to provide an unbuffered channel of progress structs to the query executing functions. The driver can then check if the context specified such a channel and attempt to send the progress update to it (but not block) whenever it receives an update from the server.

Example:

```
progressChan := make(chan clickhouse.Progress)

go func() {
    for progress := range progressChan {
        fmt.Printf("Progress: %v / %v rows, %v bytes.\n", progress.Rows, progress.TotalRows, progress.Bytes)
    }
}()

ctx := context.WithValue(context.Background(), clickhouse.ProgressKey, progressChan)
conn.QueryContext(ctx, "SELECT foo FROM bar")
```

**Comment by kshvakov** [comment]
It's a good idea, I'll investigate and implement this feature

**Comment by arctica** [comment]
Happy to hear that the idea was accepted, thanks :)

**Comment by mikelovato** [comment]
@kshvakov excuse me, Is this feature ready to use?

**Comment by kshvakov** [comment]
Added in [V2](https://github.com/ClickHouse/clickhouse-go/blob/v2/examples/native/simple.go#L34)
