### ISSUE TITLE
Possible to allow `Auth`.`Database` to be empty?

### ISSUE THREAD

**Issue by v4run** [ClickHouse/clickhouse-go#925]
Currently, if the Database is not set, it is set to "default" in the `setDefaults` method. I am facing a scenario where the `default` database may not exist. Is there any possibility to allow `Auth`.`Database` to be empty?

**Comment by jkaflik** [comment]
Hi @v4run 
It's possibly supported by native protocol. Contributions are welcome.

**Comment by v4run** [comment]
I would be happy to work on this

**Comment by v4run** [comment]
Hi @jkaflik, I have created a PR for this. I tested it with using native and http interface. It was working. The tests were also passing. Could you please take a look? 
Thanks 😃

**Comment by v4run** [comment]
#926
