### ISSUE TITLE
Support customized "url path" in http connection

### ISSUE THREAD

**Issue by crisismaple** [ClickHouse/clickhouse-go#937]
We are hosting our Clickhouse clusters behind a nginx gateway and routing request by url path instead of different host, since we are supporting customize http headers via `Options.HttpHeaders` and there is no other entry we could inject the url path before sending request, it would be good to support customized url path from Options.HttpPath while constructing the URL in `dialHttp`:

```go
type Options struct {
//...
	HttpHeaders      map[string]string // set additional headers on HTTP requests
	HttpPath         string            // HTTP request url additional path if any
//...
}

func dialHttp(ctx context.Context, addr string, num int, opt *Options) (*httpConnect, error) {
	if opt.scheme == "" {
		switch opt.Protocol {
		case HTTP:
			opt.scheme = opt.Protocol.String()
			if opt.TLS != nil {
				opt.scheme = fmt.Sprintf("%ss", opt.scheme)
			}
		default:
			return nil, errors.New("invalid interface type for http")
		}
	}
	u := &url.URL{
		Scheme: opt.scheme,
		Host:   addr,
		Path:   opt.HttpPath,
	}
   
}
```

**Comment by jkaflik** [comment]
Hi @crisismaple 

Would you like to submit a PR with such a change?

**Comment by crisismaple** [comment]
> 
Hi @jkaflik,

Sure, I already prepared a local branch for this and just waiting for a contributor role XD

**Comment by jkaflik** [comment]
@crisismaple you can fork the project and then submit PR

**Comment by crisismaple** [comment]
#938
