### ISSUE TITLE
Can't insert FixedString column using GORM serializer

### ISSUE THREAD

**Issue by OscBacon** [ClickHouse/clickhouse-go#939]
### Describe the bug
Inserting into a table using GORM with a FixedString fails when using a serializer.

```
clickhouse [AppendRow]: address clickhouse [AppendRow]: converting *schema.serializer to FixedString is unsupported
```

The serializer seems to output a *schema.serializer struct, with the string value contained in its value field. 

https://github.com/go-gorm/gorm/blob/532e9cf4ccce927249bcb102c09e4a9093aae4fe/schema/serializer.go#L46

Note: ideally there would be an easy way to write a byte slice to a fixed string

### Expected behaviour

Clickhouse-go should properly extract the string value from the serializer in AppendRow: https://github.com/ClickHouse/clickhouse-go/blob/ca9c1f0265cec9aeb5cd54cabec31136adc2c9b3/lib/column/fixed_string.go#L140

Suggestion: handle schema.serializer type in the switch

### Error log
clickhouse [AppendRow]: address clickhouse [AppendRow]: converting *schema.serializer to FixedString is unsupported

#### Environment
* Client version:
* Language version:
* OS:
* Interface: ClickHouse API / database/sql compatible driver

#### ClickHouse server
* ClickHouse Server version: latest
* `CREATE TABLE` statements for tables involved:
```sql
CREATE TABLE IF NOT EXISTS user_with_hexes (
    address FixedString(20),
    name String
)
ENGINE = Memory
```

* Sample data for all these tables:
```sql
insert into user_with_hexes (name, address) values ('a', '\xbc\x4c\xa0\xed\xa7\x64\x7a\x8a\xb7\xc2\x06\x1c\x2e\x11\x8a\x18\xa9\x36\xf1\x3d');
insert into user_with_hexes (name, address) values ('b', '\xcc\x4c\xa0\xed\xa7\x64\x7a\x8a\xb7\xc2\x06\x1c\x2e\x11\x8a\x18\xa9\x36\xf1\x3d')
```

**Comment by jkaflik** [comment]
@OscBacon thanks for submitting this.

It makes sense for `FixedString` to implement the same behavior as `String` type does. It didn't implement type casting check against `sql.Scanner` interface, which would solve the issue. 

https://github.com/ClickHouse/clickhouse-go/blob/28833a6c586d37b3e60d49d0be5203413dd3a8ee/lib/column/string.go#L76

I will have a look on this, but it's not on top of my priority list. Contributions are welcome :)

**Comment by jkaflik** [comment]
@OscBacon basically, we should have the same `if scan, ok := dest.(sql.Scanner); ok { ` statement in `fixed_string.go` for FixedString column type.

**Comment by jkaflik** [comment]
@OscBacon My apologies. I confused ingestion with the scanning rows. For ingestion, we need to implement `driver.Valuer`, which is also implemented by GORM `schema.serializer`. Thats nice.

Please see: https://github.com/ClickHouse/clickhouse-go/pull/946

**Comment by OscBacon** [comment]
Update, I used `dlv` and set a break point at the `AppendRow` call:
```
break github.com/ClickHouse/clickhouse-go/v2/lib/column.(*FixedString).AppendRow
```

Here is the value of `v` when I print it:
```go
interface {}(*gorm.io/gorm/schema.serializer) *{
        Field: *gorm.io/gorm/schema.Field {
                Name: "Address",
                DBName: "address",
                BindNames: []string len: 1, cap: 1, ["Address"],
                DataType: "string",
                GORMDataType: "string",
                PrimaryKey: true,
                AutoIncrement: false,
                AutoIncrementIncrement: 1,
                Creatable: true,
                Updatable: true,
                Readable: true,
                AutoCreateTime: 0,
                AutoUpdateTime: 0,
                HasDefaultValue: false,
                DefaultValue: "",
                DefaultValueInterface: interface {} nil,
                NotNull: false,
                Unique: false,
                Comment: "",
                Size: 20,
                Precision: 0,
                Scale: 0,
                IgnoreMigration: false,
                FieldType: reflect.Type(*reflect.rtype) ...,
                IndirectFieldType: reflect.Type(*reflect.rtype) ...,
                StructField: (*reflect.StructField)(0xc0004726a0),
                Tag: "gorm:\"primaryKey;size:20;serializer:hex\"",
                TagSettings: map[string]string [...],
                Schema: *(*"gorm.io/gorm/schema.Schema")(0xc000472000),
                EmbeddedSchema: *gorm.io/gorm/schema.Schema nil,
                OwnerSchema: *gorm.io/gorm/schema.Schema nil,
                ReflectValueOf: gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func4,
                ValueOf: gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func3,
                Set: gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func17,
                Serializer: gorm.io/gorm/schema.SerializerInterface(github.com/vulcanlink/eth-sql-ingestion/pkg/models.HexSerializer) *(*"gorm.io/gorm/schema.SerializerInterface")(0xc000472750),
                NewValuePool: gorm.io/gorm/schema.FieldNewValuePool(*sync.Pool) ...,},
        Serializer: gorm.io/gorm/schema.SerializerInterface nil,
        SerializeValuer: gorm.io/gorm/schema.SerializerValuerInterface(github.com/vulcanlink/eth-sql-ingestion/pkg/models.HexSerializer) {},
        Destination: reflect.Value {
                typ: *(*reflect.rtype)(0xf45720),
                ptr: unsafe.Pointer(0xc0000f4100),
                flag: 409,},
        Context: context.Context(*context.emptyCtx) *0,
        value: interface {} nil,
        fieldValue: interface {}(github.com/ethereum/go-ethereum/common.Address) [188,76,160,237,167,100,122,138,183,194,6,28,46,17,138,24,169,54,241,61],}
```

Therefore, when `AppendRow` is called, `v` is a `*schema.Serializer`.
The easiest solution, in my eyes, would be to have a case `*schema.Serializer` in AppendRow, with:
```go
case *schema.Serializer:
    return col.AppendRow(v.fieldValue)
```

That way, all possibile values of the field will be handled by the existing logic.
Thoughts?

**Comment by OscBacon** [comment]
Also, note that only serializing *to* the DB is the issue, not scanning from the DB, as the following test passes:
```

**Comment by jkaflik** [comment]
@OscBacon did you had a chance to have a look on PR I mentioned above?

**Comment by OscBacon** [comment]
Hi @jkaflik haven't had the chance to try it yet, but looks promising!
