### ISSUE TITLE
Broken semver tag v.2.8.1

### ISSUE THREAD

**Issue by obalunenko** [ClickHouse/clickhouse-go#954]
Hi @jkaflik 
The last release https://github.com/ClickHouse/clickhouse-go/releases/tag/v.2.8.1
Contains broken semver tag v`.`2.8.1 - should be v2.8.1

**Comment by jkaflik** [comment]
@obalunenko thanks! I will fix it within an hour.

**Comment by jkaflik** [comment]
Fixed. My apologies.
