### ISSUE TITLE
[v2] Prepare Statement does not work with statements others than INSERT

### ISSUE THREAD

**Issue by vfoucault** [ClickHouse/clickhouse-go#960]
### Describe the bug

When using Clickhouse-go v2, we are unable to use the `PrepareContext` with a query that does not accept `VALUES`

This comes from line 37 in `conn_batch.go` 

```go
func (c *connect) prepareBatch(ctx context.Context, query string, release func(*connect, error)) (driver.Batch, error) {
	//defer func() {
	//	if err := recover(); err != nil {
	//		fmt.Printf("panic occurred on %d:\n", c.num)
	//	}
	//}()
	query = splitInsertRe.Split(query, -1)[0]
	colMatch := columnMatch.FindStringSubmatch(query)
	var columns []string
	if len(colMatch) == 2 {
		columns = strings.Split(colMatch[1], ",")
		for i := range columns {
			columns[i] = strings.Trim(strings.TrimSpace(columns[i]), "`")
		}
	}
	if !strings.HasSuffix(strings.TrimSpace(strings.ToUpper(query)), "VALUES") {
		query += " VALUES" <---- Here we force not matter what to add `VALUES` to the query.

	}
	...
}

### Steps to reproduce
1. use v2 clickhouse-go
2. use the example code

### Expected behaviour

### Code example

```go
ctx := context.TODO()
query := `CREATE USER bob IDENTIFIED BY 'bladibla'`
stmt, err := tx.PrepareContext(ctx, query) <-- Issue here
if err != nil {
    log.Errorf("unable to create stmt. err=%v", err.Error())
return err
}
```

### Error log
logger will log somwthing like `unable to create stmt. err=code: 62, message: Syntax error: failed at position 79 ('VALUES'): VALUES. Expected one of: HOST, SETTINGS, DEFAULT ROLE, ON, GRANTEES, DEFAULT DATABASE, end of query"`
#### Environment
* Client version: v2

github.com/ClickHouse/clickhouse-go/v2 v2.8.3 h1:R6na3RNq/4vEEwfwkxQYrWOf21T9HMhGmE8mhkhq7TI=
github.com/ClickHouse/clickhouse-go/v2 v2.8.3/go.mod h1:teXfZNM90iQ99Jnuht+dxQXCuhDZ8nvvMoTJOFrcmcg=

* Language version:
* OS: 1.20
* Interface: sql compatible driver

**Comment by jkaflik** [comment]
@vfoucault, thanks for reporting this. A prepared statement has its purpose in this driver. (bulk ingestion)
Wouldn't be a `conn.ExecContext` a solution for you? OR it's about database/sql compatibility.

**Comment by vfoucault** [comment]
Hi there, thanks for the reply. 
I would say that this is about database/sql compatibility. 

Let's take the example of user creation, I want to create a sequence of users of a user linked to its role.
Also, what about statement such as Alter when you want to change a schema, wouldn't it be nice as well ?

So far, this is working with the v1 driver, and I guess I can surely drop the prepare stuff for a simple exec with checks

**Comment by jkaflik** [comment]
`database/sql` compatibility layer almost 1-1 corresponds to a driver's API.  In that case, it was decided prepared statement is just a batch ingestion operation.

> Let's take the example of user creation, I want to create a sequence of users of a user linked to its role.
> Also, what about statement such as Alter when you want to change a schema, wouldn't it be nice as well ?

Technically, all those sequence queries will have to be sent individually. Given that fact, we could improve it only for a SQL driver compatibility.

 > So far, this is working with the v1 driver, and I guess I can surely drop the prepare stuff for a simple exec with checks
 
 Given what I mentioned above, it completely makes sense to run your queries with exec function.
