### ISSUE TITLE
What is the difference between the Send and Flush methods when inserting in batches?

### ISSUE THREAD

**Issue by may11544** [ClickHouse/clickhouse-go#967]
I noticed that the batch insert example on the official website uses the send method, but the batch object cannot be reused after calling the send method. The difference is the Flush method, I can always take the batch object. But I don't know what effect this will have on my code. I tried to look at the concrete implementation of both, but couldn't fully understand because of the lack of comments.

I am very eager to get an answer, thank you very much.

**Comment by jkaflik** [comment]
Hi @may11544 
It would be good to understand your use case for batch object reuse. Batch is usually a chunk of your data for a client side batching. It shouldn't be reused.

**Comment by may11544** [comment]
> Hi @may11544 It would be good to understand your use case for batch object reuse. Batch is usually a chunk of your data for a client side batching. It shouldn't be reused.
Thanks for your reply, I think I got it
