### ISSUE TITLE
how to use clickhouse-go/v2 v2.9.0

### ISSUE THREAD

**Issue by tiamoliu** [ClickHouse/clickhouse-go#972]
i want to use **github.com/ClickHouse/clickhouse-go/v2 v2.9.0** sdk, but it contains **github.com/ClickHouse/clickhouse-go v1.5.4**, They each have init methods to generate drivers, which caused my project to fail to start，throw panic.

**Comment by tiamoliu** [comment]
bootstrap.go => init()

**Comment by tiamoliu** [comment]
clickhouse_std.go => init()

**Comment by tiamoliu** [comment]
![image](https://user-images.githubusercontent.com/33012561/232442771-0c5b7d6f-7a04-4f41-b6e3-fd2089da5284.png)
it has **github.com/ClickHouse/clickhouse-go v1.4.8 // indirece**, so i go mod tidy.  i don’t know how to exclude it. it has init methods to generate drivers too.

**Comment by tiamoliu** [comment]
so i annotate Go source code to start my project
![image](https://user-images.githubusercontent.com/33012561/232444724-53e52e3f-d248-410e-ba75-a50dd7a310de.png)

**Comment by notmahsa** [comment]
I am seeing the same issue, the import is called only once, but other packages in my code import the package that imports the clickhouse package and that tries to register again.
