### ISSUE TITLE
Best practices of using batch.Flush()

### ISSUE THREAD

**Issue by cergxx** [ClickHouse/clickhouse-go#973]
What is a reasonable frequency of using Flush (in terms of numbers of rows/bytes)?
Does it have a negative impact on the insertion efficiency/compression/disk usage?

For context: we currently don't use Flush and write batches of up to 100k rows, the underlying ch-go buffer grows up to 50MB

**Comment by jkaflik** [comment]
There are two perspectives here: client-side and server-side. The batch interface in the client driver is a client-side batching. (there is also a server-side one using `async_insert=1`: [doc](https://clickhouse.com/docs/en/optimize/asynchronous-inserts#enabling-asynchronous-inserts))

From a client-side perspective, memory is your limit. Compression is done in chunks defined as `MaxCompressionBuffer` option. 

From CH perspective, larger batches are better than smaller chunks of data. Ideally, you shouldn't have insert query ratio above one query per second: https://clickhouse.com/docs/en/optimize/bulk-inserts

**Comment by cergxx** [comment]
It seems it would be helpful if Batch interface had a method providing current buffer size

**Comment by jkaflik** [comment]
@cergxx `MaxCompressionBuffer` option is available in v2.
