### ISSUE TITLE
Is v2 support Clickhouse-server 21.8LTS?

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/clickhouse-go#978]
Is v2 support Clickhouse-server 21.8LTS?

**Comment by jkaflik** [comment]
We don't test against version 21.8, since it's not supported anymore: https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions

However, the client driver should work since we keep backward compatibility as long as possible.
