### ISSUE TITLE
Do not support select * from table FORMAT JSON

### ISSUE THREAD

**Issue by muzi939375821** [ClickHouse/clickhouse-go#979]
### Steps to reproduce
1.
2.
3.

### Code example
```go
```
#### Environment
* Client version:2.9.1
* Language version:1.20.2
* OS:
* Interface: ClickHouse API / database/sql compatible driver

#### ClickHouse server
* ClickHouse Server version:22.7.1.2484
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by muzi939375821** [comment]
Code example
func New() *sql.DB {
	db := clickhouse.OpenDB(&clickhouse.Options{
		Addr: []string{"192.168.xx.xx:9000"},
		Auth: clickhouse.Auth{
			Username: "xxx",
			Password: "xxx",
		},
		Settings: clickhouse.Settings{
			"max_execution_time":             60,
			"allow_experimental_object_type": 1,
			"format":                         "JSON",
		},
		DialTimeout: 5 * time.Second,
		Compression: &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		},
		Debug: true,
	})
	err := db.Ping()
	if err != nil {
		println(err.Error())
		return nil
	}
	return db
}

rows, err := db.Query("select * from table FORMAT JSON")

**Comment by jkaflik** [comment]
@muzi939375821 I overlooked this issue since it was closed after creation.

Currently, only the native format is supported in clickhouse-go. Please see https://github.com/ClickHouse/clickhouse-go/issues/638
