### ISSUE TITLE
Cannot provide custom settings using Native protocol

### ISSUE THREAD

**Issue by aramperes** [ClickHouse/clickhouse-go#983]
### Describe the bug

ClickHouse Server can be [configured to accept custom settings](https://clickhouse.com/docs/en/operations/settings#custom_settings), by defining a custom prefix list. These settings can be read from queries and UDFs using `getSetting('custom_xyz')`. This is a useful way to modify the behavior of UDFs at query time, instead of providing explicit parameters.

The Native protocol expects the Settings `flags` to have the `0x02` bit set to mark a setting as `CUSTOM`: https://github.com/ClickHouse/ClickHouse/blob/c873560fe7185f45eed56520ec7d033a7beb1551/src/Core/BaseSettings.h#L508-L530

Currently, the `clickhouse-go` client is hard-coding the `flags` to just `0x01` (`is_important`): https://github.com/ClickHouse/clickhouse-go/blob/1812cf442fa81f2dbeae6d62a18c018fb721f178/lib/proto/query.go#L175

Hard-coding all settings as `is_custom (0x02)` does not seem to be an appropriate solution, as ClickHouse will [only decode custom settings as strings](https://github.com/ClickHouse/ClickHouse/blob/c873560fe7185f45eed56520ec7d033a7beb1551/src/Core/BaseSettings.h#L516-L521) (instead of binary like other settings).

This does not affect the HTTP protocol, as all settings are simply passed as query parameters and accepted by the ClickHouse server (as long as the prefix is valid). The client would need a way to mark a setting as `CUSTOM`, or otherwise have a separate collection of `Settings` for custom settings.

### Steps to reproduce
1. Configure ClickHouse to accept custom settings with a prefix, such as:

```xml
<custom_settings_prefixes>ls_</custom_settings_prefixes>
```
2. In `clickhouse.Options`, pass a custom setting such as `ls_profile`
3. An error is thrown by the server: `error querying the database: code: 115, message: Unknown setting ls_profile`

### Expected behaviour

The custom settings are accepted by ClickHouse, or a separate `clickhouse.Options` field allows the client to do so.

### Code example
```go
customSettings := make(clickhouse.Settings)
customSettings["ls_profile"] = "example"

db := clickhouse.OpenDB(&clickhouse.Options{
	// - Snip -
	Settings:    customSettings,
})

// Run query with db ...
```
### Error log

```
error querying the database: code: 115, message: Unknown setting ls_profile
```

#### Environment
* Client version: `2.8.1`
* Language version: `1.19`
* OS: Linux
* Interface: database/sql compatible driver

#### ClickHouse server
* ClickHouse Server version: `23.2 +`
* ClickHouse Server non-default settings, if any:

```xml
<custom_settings_prefixes>ls_</custom_settings_prefixes>
```

**Comment by jkaflik** [comment]
Thanks for reporting this @aramperes.

Definitely, we could support it in a driver, and ideally, it could be passed all together with a standard settings map. This would require to driver understand what is `custom_settings_prefixes` on the server side. Otherwise, we have to provide a custom map. (which is still fine)
Any Ideas?

**Comment by aramperes** [comment]
I'll have to test if `custom_settings_prefexes` can be read by the client. If so, that would require this driver to make a `SELECT getSetting` query on startup, so future queries have the proper flags set.

**Comment by aramperes** [comment]
`custom_settings_prefixes` does not get returned in either:

```sql
SELECT getSetting('custom_settings_prefixes');

SELECT * FROM system.server_settings WHERE name='custom_settings_prefixes';
```

So at this point, unless a work-around can be done in ClickHouse Server I think the only way is to have a separate map in the driver.

It seems like a design gap that the `Native` protocol requires setting this flag, but no way for drivers to know whether to set it or not (except by letting the user configure it explicitely) unlike `HTTP`.

**Comment by jkaflik** [comment]
@aramperes, it's not likely we will have this changed in the protocol or in the system table as of now. I will have a look on this week.

**Comment by aramperes** [comment]
I think the custom prefix list idea makes sense. I can also open a PR tomorrow if you'd like.

**Comment by jkaflik** [comment]
@aramperes I come up with a different proposal: https://github.com/ClickHouse/clickhouse-go/pull/993.
Please let me know what you think about it. Ideally, in v3 we could refactor `clickhouse.Settings` so it's a slice of `Setting` struct type not a simple key-value map.
